### ISSUE TITLE
redirect_url doesn't work with URL with fragment

### ISSUE THREAD

**Issue by caiych** [greenpau/caddy-auth-portal#101]
**Describe the issue**

Imagined user is visiting https://example.com/#/path/in/fragment. 
It's redirected to https://login.example.com?redirect_url=https://example.com/#/path/in/fragment
Then the second hop goes to https://login.example.com#/path/in/fragment and setting https://example.com in AUTH_PORTAL_REDIRECT_URL cookie.

**Configuration**

Paste full `Caddyfile` below:

```
n/a
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.3.0
http.authentication.hashes.scrypt v2.3.0
http.authentication.providers.http_basic v2.3.0
http.authentication.providers.jwt v1.2.7
http.handlers.auth_portal v1.4.5
http.handlers.authentication v2.3.0
```

**Expected behavior**

The second redirect should goes to https://login.example.com and setting https://example.com/#/path/in/fragment in cookie.

**Additional context**

I briefly skimmed the code and I think we can do this by setting the redirect_url to a url.PathEscaped value of RequestURI in here: https://github.com/greenpau/caddy-auth-portal/blob/7665ed8de6d6f3a2d934e96c56e088da62653c76/pkg/handlers/redirect.go#L42

Then do url.PathUnescape in here: https://github.com/greenpau/caddy-auth-portal/blob/1d42614c6a75b6a03fbcc7738500a3f06292ed55/pkg/core/portal.go#L174

A untested commit here: https://github.com/caiych/caddy-auth-portal/commit/4ef832d2fab41e11a5bfd8706bd2e49eb9274251

Another option would be setting the escaped value into cookie as well and do Unescape when reading from the cookie though I think it's a better idea to do Unescaping earlier than later.

Thanks for this great plugin. Let me know what you think:)

**Comment by greenpau** [comment]
@caiych , i think automated redirect should just work. How do you set redirect in ‘jwt’ plugin?

**Comment by caiych** [comment]
I'm not setting it explicitly. Mostly coping from the instruction.

```
jwt {
        primary yes
        trusted_tokens {
            static_secret {
                token_name access_token_caiych
                token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
            }
        }
        auth_url //login.caiych.top
        allow roles root
    }
```

**Comment by greenpau** [comment]
@caiych , where is https in the auth_url?

**Comment by caiych** [comment]
I didn't set that but making it https://login.caiych.top didn't make a difference.

I think the problem is that when the server receives the http request of  https://login.example.com?redirect_url=https://example.com/#/path/in/fragment , it's interpreting the url fragment("#/path/in/fragment") as the fragment of the whole URL so it's not passed into redirect_url arg.
