### ISSUE TITLE
Support for Elliptic Curve JWKs

### ISSUE THREAD

**Issue by alucryd** [greenpau/caddy-auth-portal#102]
**Describe the issue**

Trying to use the generic oauth2 backend with an auth server using elliptic curve keys fails with the following error message:

`failed to fetch jwt keys for OAuth 2.0 authorization server: invalid jwks key: unsupported key type EC for ec`

It works fine if I stick to RSA.

**Configuration**

```
sub.domain.tld {

  route /auth* {
    auth_portal {
      backends {
        generic_oauth2_backend {
          method oauth2
          realm generic
          provider generic
          base_auth_url https://auth.domain.tld/
          metadata_url https://auth.domain.tld/.well-known/openid-configuration
          client_id XXXXXXXXXXXX
          client_secret YYYYYYYYYYYYYYYYY
          scopes openid
        }
      }
    }
  }

  route /sso/oauth2/generic* {
    jwt {
      auth_url /auth/oauth2/generic
    }
    respond * "generic oauth2 sso" 200
  }

  reverse_proxy 127.0.0.1:8080
}
```

**Version Information**

```
http.authentication.hashes.bcrypt v2.3.0
http.authentication.hashes.scrypt v2.3.0
http.authentication.providers.http_basic v2.3.0
http.authentication.providers.jwt v1.2.7
http.handlers.auth_portal v1.4.6
http.handlers.authentication v2.3.0
```

**Expected behavior**

The plugin should load the EC keys just as well as traditional RSA keys.

**Comment by greenpau** [comment]
@alucryd , currently, not supported. Could look into it over the weekend.

**Comment by alucryd** [comment]
Not really urgent, but it would be nice to have, thanks!

**Comment by greenpau** [comment]
@alucryd , it is now supported. Please see docs at https://github.com/greenpau/caddy-auth-jwt#generate-ecdsa-public-key
