### ISSUE TITLE
Generic Oauth2 backend won't start if the identity server is hosted on the same caddy instance

### ISSUE THREAD

**Issue by alucryd** [greenpau/caddy-auth-portal#103]
**Describe the issue**

I have a local identity server which I use for all my OpenID Connect purposes. Up until now I was using OpenResty to host all my services, including the OIDC server, and I would like to switch to Caddy. However, trying to use the Oauth2 backend fails if the OIDC server is also exposed on the same domain via the same Caddy instance, because it tries to validate the backend before it is actually exposed by Caddy.

Is it possible to delay this validation until after caddy is actually running and exposing the OIDC endpoints?

**Comment by greenpau** [comment]
@alucryd , not at the moment. However, I can add the delayed start option over the weekend.

**Comment by alucryd** [comment]
Thanks for the quick answer, that would be grand!

**Comment by IzeQube** [comment]
Oh yes, it would be great if something like a delyed start could be added.

**Comment by michaelhthomas** [comment]
@greenpau Any update on this? It would make selfhosted OIDC without the need to run two separate reverse proxies.

**Comment by greenpau** [comment]
@michaelhthomas , will try making it a priority.

**Comment by greenpau** [comment]
@alucryd , @IzeQube, @michaelhthomas , the delayed start is available in [v1.4.19](https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.4.19).

Please contribute to the development of Caddy auth plugins by:

1. Giving Github stars to github.com/greenpau/caddy-auth-portal and github.com/greenpau/caddy-auth-jwt
2. Promoting the plugins on Twitter by referencing the above repos and mentioning @caddyserver
3. Participating in https://caddy.community/
4. Blogging about your Caddy setup with auth plugins

**Comment by michaelhthomas** [comment]
Unfortunately @greenpau, though this new feature does work, the wait seems to be blocking the main thread and preventing Caddy from starting, which means the same errors occur. Because Caddy waits for the plugin to finish initializing, the proxy never starts and therefore the auth-portal plugin can never reach the oidc endpoint and fails to load. Please feel free to correct me if there's something I'm misunderstanding!

Relevant logs:

```
{"level":"debug","ts":1628709310.0207937,"logger":"http.handlers.authp","msg":"Configured connection retries for OAuth 2.0 backend","backend_name":"generic_oauth2_backend","retry_attempts":3,"retry_interval":10}
{"level":"debug","ts":1628709310.0268338,"logger":"http.handlers.authp","msg":"fetchMetadataURL failed","backend_name":"generic_oauth2_backend","attempt_id":0,"error":"failed to fetch metadata for OAuth 2.0 authorization server: Get \"$SERVER_NAME/.well-known/openid-configuration\": dial tcp $IP:443: connect: connection refused"}
```

**Comment by greenpau** [comment]
> the proxy never starts 

@michaelhthomas , lol! this is new :-) what is that proxy? how is it related to "OIDC server"? Is it another plugin? Please show your Caddyfile and explain the "plumbing."

**Comment by greenpau** [comment]
@michaelhthomas, I will add `async` options. This way the fetching of keys happens after the provisioning.

**Comment by michaelhthomas** [comment]
@greenpau Awesome, thanks so much!

**Comment by greenpau** [comment]
@michaelhthomas , the change is now in [v1.4.21](https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.4.21). Please test and report back. You need to add `delay_start <seconds>` to your config.

**Comment by michaelhthomas** [comment]
@greenpau, Just tested with the new version with a 30 second delay and that worked perfectly, thanks so much for your work!

**Comment by greenpau** [comment]
> Just tested with the new version with a 30 second delay and that worked perfectly, thanks so much for your work!

@michaelhthomas , glad that it worked out! 👍 


Please contribute to the development of Caddy auth plugins by:

1. Giving Github stars to github.com/greenpau/caddy-auth-portal and github.com/greenpau/caddy-auth-jwt
2. Promoting the plugins on Twitter by referencing the above repos and mentioning @caddyserver
3. Participating in https://caddy.community/
4. Blogging about your Caddy setup with auth plugins
