### ISSUE TITLE
Would like to explore setting up caddy-auth-portal using PortalGuard IdP Product

### ISSUE THREAD

**Issue by orware** [greenpau/caddy-auth-portal#104]
Hi @greenpau!

I was excited to see this module available for Caddy v2 when I was looking through the list of modules on the download page over the past weekend, specifically because I'd like to explore using it to help create "intranet" type sites (protected by authentication before being able to access the page) using Caddy's built-in file_server / templates directives.

I know the examples in the README specifically seem to cover some more advanced use cases (e.g. using caddy-auth-portal to protect Prometheus for example), but I'm not sure if there's an example that covers the scenario above (I'm sure it's probably not too complicated and I can figure it out, but might be helpful to have an example of that use case if it's possible).

Additionally, my organization uses the PortalGuard IdP product which supports multiple protocol options (CAS, SAML, and OpenID Connect). At the moment it seems like OpenID Connect might be the simplest one to use with caddy-auth-portal, but I'm happy to try out SAML as well (I don't think CAS is a current option from what I saw).

I'm not sure if you have any extra starting tips aside from what's in the README (I only have time to read through it at the moment but won't get to get in depth and run some tests until later today or over the weekend), but if you do please let me know and perhaps once I have a working solution I can share any tips I learn back to have notes for that specific IdP if it's of interest to include in the README.

If you do have a quick yes/no answer related to whether I can use caddy-auth-portal to secure a simple Caddy-powered static site using the file_server / templates directives though that would be helpful just to make sure I don't work through this and then find out that use case isn't supported.

Thank you!

**Comment by greenpau** [comment]
@orware , the examples are here https://github.com/greenpau/caddy-auth-portal#usage-examples
