### ISSUE TITLE
If my browser is already logged in with a different MSA I cannot switch the MSA for use with Caddy

### ISSUE THREAD

**Issue by richardpowellus** [greenpau/caddy-auth-portal#105]
**Describe the issue**

Let's say I happen to already be logged into Microsoft's services using MSA a@outlook.com. My Caddy web portal is configured to only permit connections from b@outlook.com. When I browse to my Caddy web portal instead of being given an option to "logout" I just get "Forbidden".

Further, if I then browse directly to the Caddy auth page and click the "Logout" button and then try again, I'm immediately logged back in (behind the scenes, I guess) into a@outlook.com and so, once again, I can't login and get the "Forbidden" message.

Usually with any other Microsoft properties I visit there is a popup that lets me select which MSA I want to use to login to that website. Caddy doesn't seem to present that popup and just uses the already logged in MSA by default with no option to change it.

The only way I can access my web portal now is by creating an In Private session.

**Configuration**

Paste full `Caddyfile` below:

```
{
  https_port 443
}

(tls-dns-azure) {
  tls {
    dns azure {
      tenant_id [REDACTED]
      client_id [REDACTED]
      client_secret [REDACTED]
      subscription_id [REDACTED]
      resource_group_name [REDACTED]
    }
  }
}

(auth-trusted-tokens) {
  token_name access_token
  token_secret [REDACTED]
}

(auth) {
  jwt {
    primary yes
    auth_url https://auth.myhome.net/auth/oauth2/azure
    allow roles anonymous guest
    allow roles admin
    allow roles everyone Everyone
    trusted_tokens {
      static_secret {
        import auth-trusted-tokens
      }
    }
  }
}

(auth-admin-required) {
  jwt {
    primary no
    auth_url https://auth.myhome.net/auth/oauth2/azure
    allow roles admin
    trusted_tokens {
      static_secret {
        import auth-trusted-tokens
      }
    }
  }
}

auth.myhome.net {
  route /auth* {
    auth_portal {
      path /auth
      cookie_domain myhome.net
      backends {
        azure_oauth2_backend {
          method oauth2
          realm azure
          provider azure
          client_id [REDACTED]
          client_secret [REDACTED]
          scopes openid email profile
          user [REDACTED] add role admin
        }
      }
      jwt {
        import auth-trusted-tokens
      }
      ui {
        links {
          "Radarr" https://radarr.myhome.net
        }
      }
    }
  }

  route /* {
    import auth
    redir https://auth.myhome.net/auth/oauth2/azure 302
  }
 
  import tls-dns-azure

}

radarr.myhome.net {

  route {
    import auth-admin-required

    reverse_proxy radarr:7878
  }

  import tls-dns-azure

}```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
/srv # caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.3.0
http.authentication.hashes.scrypt v2.3.0
http.authentication.providers.http_basic v2.3.0
http.authentication.providers.jwt v1.2.7
http.handlers.auth_portal v1.4.6
http.handlers.authentication v2.3.0
```

**Expected behavior**

When I browse to a Caddy website I should be presented with a prompt asking me which MSA I would like to proceed with. Or, at the very least, when I "logout" I should be properly logged out so that the next time I log in I have to actually log in again (thereby allowing me to login with the intended MSA).

**Additional context**

Add any other context about the problem here.

**Comment by greenpau** [comment]
@richardpowellus , the latest release has all of this fixed. The plugin would auto-guess the original authentication endpoint. A user would not even know the redirect to Azure happened.
