### ISSUE TITLE
feature: add auto push of new docker image on release

### ISSUE THREAD

**Issue by danielfrankcom** [greenpau/caddy-auth-portal#106]
**Describe the issue**

I would like to use Caddy with this authentication plugin on an Unraid system, in such a way that the Docker container image can be auto-updated from Docker Hub.

**Expected behavior**

Docker Hub contains a predefined Caddy image that includes this plugin. It is available for download in a similar manner to https://hub.docker.com/_/caddy. When the Caddy image or the plugin is updated, the Docker Hub image is also updated.

**Additional context**

The only way that I can find to use this authentication plugin with Docker is to define my own Docker image using the `caddy:<version>-builder` tag. This would mean that for every update of either the plugin or the original Caddy image I would need to rebuild the container.

Since precompiled binaries are offered for download, would it be possible to offer a Docker container too? This represents a barrier to entry for me, as I'm looking for something that I can integrate conveniently with my Unraid system. I can use the existing Caddy system just fine because Unraid will pull updates from Docker Hub, but I am currently unable to use this plugin without breaking that workflow.

**Comment by greenpau** [comment]
@danielfrankcom , sure. Will add it to the build.

**Comment by danielfrankcom** [comment]
Great, thank you!

**Comment by greenpau** [comment]
Finally, I am ready to implement this.

**Comment by greenpau** [comment]
Years ago I've created https://github.com/greenpau/vanilla
Will mimic it.

**Comment by oscrx** [comment]
I also build this (with Github actions), maybe it'll be helpful for anyone.
https://github.com/oscrx/caddy

**Comment by danielfrankcom** [comment]
Any news on this? Would love to be able to use this project with my setup, as it just keeps getting better.

**Comment by greenpau** [comment]
> Any news on this? Would love to be able to use this project with my setup, as it just keeps getting better.

@danielfrankcom , reading up on https://ghcr.io

Once I figure out how to do it, I will add an image.

**Comment by greenpau** [comment]
> I also build this (with Github actions), maybe it'll be helpful for anyone.

@oscrx , thank you for the pointer! 👍

**Comment by greenpau** [comment]
@danielfrankcom , @oscrx , just published the container image.

https://github.com/greenpau?tab=packages&repo_name=caddy-auth-portal

Please see if you can use it or improve it.

**Comment by greenpau** [comment]
> The real test will be when a change is made to this repo. Hopefully Unraid will be able to pull the change from your hosted docker image. I'm optimistic, but I'll let you know when there's an update here that I can test with.

@danielfrankcom , I did not set up the image build and labeling upon a new release. Want to test whether the image is working, but don't have much time to test 😞 been busy at work.

**Comment by greenpau** [comment]
> Is there a benefit that you see to building it outside of caddy:builder?

@danielfrankcom , it could be that the image would have more layers when necessary when using `caddy:builder`. Idk, perhaps things changes and that stuff is optimized.

FYI, I am testing the automated image push right now.

**Comment by greenpau** [comment]
@danielfrankcom , this is not completed. I will be triggering a new build with each release.

https://github.com/greenpau/caddy-auth-portal/pkgs/container/caddy-auth-portal

**Comment by danielfrankcom** [comment]
Sounds good. Please let me know when you get around to it and I'll test out the pull behavior in Unraid. I'll probably have to wait for another release after you finish it to test it properly though since the auto-updating to the newest image part is the important bit for my use case.

**Comment by greenpau** [comment]
> Sounds good. Please let me know when you get around to it and I'll test out the pull behavior in Unraid. I'll probably have to wait for another release after you finish it to test it properly though since the auto-updating to the newest image part is the important bit for my use case.

@danielfrankcom , just triggered the latest build. Try it in 30 mins.
