### ISSUE TITLE
Question: Increasing token lifetime?

### ISSUE THREAD

**Issue by cakoose** [greenpau/caddy-auth-portal#107]
**Describe the issue**

I'm running a website on an Internet-accessible IP.  I only want people at my company to have access, so I'm using Caddy 2 with `auth_portal`+`jwt` in front to "protect" it.  The website doesn't actually use the auth information itself.

I'm seeing this error in the Caddy log every ~15 minutes:

```
2021/03/22 23:19:55.675 ERROR   http.handlers.authentication    auth provider returned error    {"provider": "jwt",
 "error": "[Token is expired]"}   
```

This is fine for normal HTTP GETs of top-level pages.  But for AJAX requests, this makes the website appear broken, with no indication to the user.

Is there a way to make this occur less frequently?  For example, can I extend the token's lifetime to something like 24 hours?

**Configuration**

Paste full `Caddyfile` below:

```
subdomain.blah-internal.com {
    route /_auth/* {
        auth_portal {
            path /_auth
            jwt_token_secret XXXXXXX
            backends {
                google_oauth2_backend {
                    method oauth2
                    realm google
                    provider google
                    client_id XXXXXXX
                    client_secret XXXXXXX
                    scopes openid email
                }
            }
        }
    }
    route /* {
        jwt {
            primary yes
            trusted_tokens {
                static_secret {
                    token_name access_token
                    token_secret XXXXXXX
                    # token_lifetime 86400000000000 # 24 hours in nanoseconds
                }
            }
            auth_url /_auth/oauth2/google
            allow roles everyone
        }
        reverse_proxy localhost:3000
    }
}
```

I saw the identifier `TokenLifetime` in the code (next to `TokenName` and `TokenSecret`), so I tried adding `token_lifetime` to the config (see commented-out line above).  That didn't work:

```
2021/03/23 00:10:23.571 INFO    using provided configuration    {"config_file": "Caddyfile", "config_adapter": ""}
run: adapting config using caddyfile: parsing caddyfile tokens for 'route': Caddyfile:33 - Error during parsing: pa
rsing caddyfile tokens for 'jwt': Caddyfile:27 - Error during parsing: auth backend static_secret subdirective fail
ed to compile to JSON: json: cannot unmarshal string into Go struct field CommonTokenConfig.token_lifetime of type 
int
```

**Version Information**

```
http.authentication.hashes.bcrypt v2.3.0
http.authentication.hashes.scrypt v2.3.0
http.authentication.providers.http_basic v2.3.0
http.authentication.providers.jwt v1.2.7
http.handlers.auth_portal v1.4.5
http.handlers.authentication v2.3.0
```

**Expected behavior**

**Additional context**

**Comment by tgelite** [comment]
I used this in our config for 12 hour timeout in seconds and it worked for extending the timeout.

```
   jwt {
           token_name access_token
           token_secret AnExampleSecretString123
           token_lifetime 43200
    }
```

You can see examples of our full config file example that is working for us at: 
https://caddy.community/t/new-feature-caddy-trust-with-support-for-config-switch/11606

Note in our config /* routes to /auth* for authentication if no token is present (as does /ui/* and /gr/* routes) and we set the token_lifetime in the jwt assertion under the /auth section.

**Comment by greenpau** [comment]
@cakoose , the token lifetime needs to be set on portal, because it issues tokens. The token lifetime is in seconds.

You are setting lifetime on ‘jwt’ plugin. That looks incorrect.

regarding AJAX scripts. They need to recognize 403/404 errors and redirect to login.

hope this helps!

**Comment by cakoose** [comment]
Ah, that makes sense.  I moved `token_lifetime` up to the `auth_portal` section and it seems to work now.

When I added `token_lifetime` in the wrong place, the error message made it seem like it was just a type mismatch (int vs string): "json: cannot unmarshal string into Go struct field CommonTokenConfig.token_lifetime of type int".  Is that easy to improve?
