### ISSUE TITLE
Is there a way to get caddy to re-read the local user_db.json without restarting the server?

### ISSUE THREAD

**Issue by tgelite** [greenpau/caddy-auth-portal#109]
**Describe the issue**

One of our team members has created an [external user management tool for the caddy_auth_portal user registration & user db](https://github.com/dczysz/caddy-auth-user-manager).  (For anyone who needs it, its MIT license so please, check out).

One thing we have found is that the caddy reload command does not seem to trigger re-reading the user_db.json.

```
caddy reload --config /etc/caddy/Caddyfile 
```

Is there any kind of call or something we can trigger via API or otherwise to get Caddy server to trigger the auth_portal to reread the user_db.json file after changes?

**Configuration**

Paste full `Caddyfile` below:

```
{
        local_certs
        http_port 80
        https_port 443
}
https://host.example.com, https://10.252.252.10 {
        log {
                level INFO
                format console
                output file /var/log/caddy/caddy.log
        }
        route /auth* {
                auth_portal {
                        path /auth
                        backends {
                                local_backend {
                                        method local
                                        path /opt/caddy/auth/user_db.json
                                        realm local
                                }
                        }
                        jwt {
                                token_name access_token
                                token_secret AnExampleSecretString123
                                token_lifetime 43200
                        }
                        ui {
                                theme basic
                                generic_template "/opt/caddy/templates/em20-tmpl/generic.template"
                                login_template "/opt/caddy/templates/em20-tmpl/login.template"
                                portal_template "/opt/caddy/templates/em20-tmpl/portal.template"
                                register_template "/opt/caddy/templates/em20-tmpl/register.template"
                                whoami_template "/opt/caddy/templates/em20-tmpl/whoami.template"
                                settings_template "/opt/caddy/templates/em20-tmpl/settings.template"
                                custom_css_path "/opt/caddy/css/custom.css"
                                static_asset "assets/logo.png" "image/png" "/opt/caddy/templates/em20-tmpl/logo.png"
                                logo_url "assets/logo.png"
                                links {
                                        "Elite Manager" /
                                        "Auth Portal Settings" /auth/settings
                                        "who am i check" /auth/whoami
                                }
                        }
                }
        }
        route /gr/* {
                jwt {
                        enable claim headers
                }
                reverse_proxy http://localhost:3000
        }
         route /version* {
                respond * "2.0.0-a" 200
        }
        route /ui/* {
                jwt {
                        enable claim headers
                }
                reverse_proxy http://localhost:1880
        }
        # caddy_auth_portal user manager running on port #5555
        route /user-mgr/* {
               jwt {
                        allow roles superuser,manager
                        enable claim headers
                }
                reverse_proxy http://localhost:5555
        }
        route /* {
                jwt {
                        primary yes
                        trusted_tokens {
                                static_secret {
                                        token_name access_token
                                        token_secret AnExampleSecretString123
                                }
                        }
                        enable claim headers
                }
                reverse_proxy http://localhost:1081
        }
}

```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.4.0-beta.1
http.authentication.hashes.scrypt v2.4.0-beta.1
http.authentication.providers.http_basic v2.4.0-beta.1
http.handlers.authentication v2.4.0-beta.1
http.authentication.providers.jwt v1.2.7
http.handlers.auth_portal v1.4.6
```

**Expected behavior**

Hoping to find a way to trigger re-read of the user_db.json without having to restart the caddy binary.

**Additional context**

**Comment by tgelite** [comment]
Oof, we figured it out!  

we needed to add `--force` probably because caddy was looking at an unchanged caddyfile, and not reloading anything.  We're updating now!

**Comment by tgelite** [comment]
So further testing has found that the caddy reload even with --force does not seem to trigger re-reading the user file.  So the question stands is there a way short of restarting caddy server to get the caddy_auth_plugin to update from the user_db.json.

**Comment by greenpau** [comment]
@tgelite , the issue here is that you took a shortcut of modifying underlying files and not using API from go-identity. That is the issues here.

**Comment by tgelite** [comment]
Ok we will go back to the drawing board and examine that, thanks for the pointer!

**Comment by greenpau** [comment]
@tgelite , in short, there are functions you could trigger to operate the local identity database.

See here: https://github.com/greenpau/caddy-auth-portal/blob/d8ef9f687eca4fc80cf39ac385f23374b1e2b8d4/pkg/backends/local/backend.go#L417-L460

**Comment by tgelite** [comment]
ooh nice thanks for the pointer!

**Comment by tgelite** [comment]
Ok so reading through this (go is a very readable language, nice) it looks like we would need to expand this module to be able to have a backend1 and backend2 opened and then build functional calls for the move and set role (and whatever other things like demote, delete, etc).  Learning the go-identity API will be first step (noticing there is a node.js one too..) 

We're going to go ahead and back our little project out of public github before we cause someone to injure their users in an unintentional way. ( @dczysz sorry I asked you to post it... :D )

For any kind of scenario where its beyond a small set of users that are set up by a superuser only, what we are doing is exactly that, a hack...    Paul thanks for your pointers to the right way to approach this.
