### ISSUE TITLE
Disable Auth Portal + Links to unauthorized Users

### ISSUE THREAD

**Issue by sandstormkeshav** [greenpau/caddy-auth-portal#114]
**Describe the issue**
I have setup google oauth on my auth portal, when logging in as any google user they have access to see my links available in the portal, as well the /auth/whoami endpoint, as well as the /auth/settings endpoint. It would be nice if users could have a role called self_service which gives them access to those endpoints as stated before.
Here is a caddyfile I am using to fix that behavior, is this okay? Is there a better way to accomplish this or am I missing something? Thank You!

```
	@securesite path /auth/portal* /auth/whoami* /auth/settings*
	auth.domain.com {
		route @securesite {
			jwt {
				allow roles superadmin
			}
		}
}
route /auth* {
			auth_portal {
				path /auth
				backends {
...
```

**Comment by greenpau** [comment]
@sandstormkeshav . thank you for opening the issue.

Your snippet doe not look correct. Please reformat and paste your complete configuration with the reduction of sensitive data.

The following does not look correct:

```
@securesite path /auth/portal* /auth/whoami* /auth/settings*
```

Also, please explain "user journey" a bit better. I don't understand the ask.

**Comment by sandstormkeshav** [comment]
```
	@securesite path /auth/portal* /auth/whoami* /auth/settings*
	@authportal host authenticate.domain.com
	handle @authportal {
		route @securesite {
			jwt {
				allow roles superadmin
			}
		}

		route /auth* {
			auth_portal {
				path /auth
				backends {
					# local_backend {
					# 	method local
					# 	path /auth/users.json
					# 	realm local
					# 	#require mfa
					# }
					google_oauth2_backend {
						method oauth2
						realm google
						provider google
						client_id REDACTED
						client_secret REDACTED
						scopes openid email profile
						
					}
				}
				cookie_domain .domain.com
				cookie_lifetime 3600
				jwt {
					token_name access_token
					token_secret REDACTED
					#token_lifetime 10
				}

				ui {
					links {
						"Who Am I" /auth/whoami icon "las la-smile"
						"Settings" /auth/settings icon "las la-cog"
						"Private App" https://myprivateapp.domain.com target_blank icon "las la-cog"
					}
				}
				# registration {
				# 	dropbox /auth/registrations_db.json
				# 	title "User Registration"
				# 	code "NY2020"
				# }
			}
		}
		route {
			redir https://{hostport}/auth 302
		}
	}
```
Here is my Caddyfile, I have created the @securesite matcher to allow me to prevent access to the /auth/portal* /auth/whoami* /auth/settings* endpoints for users that do not have the superadmin role. Would there be a different way to implement this? If I remove this matcher, and login using google oauth -- I am able to have access to the portal (as well as see what links are available), even though I may not have access to actually visit them. I think this happens because any user by default has the guest, anonymous roles. 

So in essence, it would be nice to not let guest,anonymous have access to the portal UI and the settings UI.

**Comment by greenpau** [comment]
@sandstormkeshav , are you saying you don't want to let Google OAuth authenticated user in, unless the user is superadmin?

**Comment by sandstormkeshav** [comment]
@greenpau That is correct, I would not want an authenticated oauth user that does not receive any role other than the default guest, anonymous role to be able to access the whoami, portal, and settings page. The portal page with the links could be especially sensitive as it may show others what services the user is running, even if he/she cannot actually access them.

**Comment by sandstormkeshav** [comment]
@greenpau Thank you so much! 😀

**Comment by sandstormkeshav** [comment]
@greenpau Do you have any updates on this? It would also be cool to dynamically show the links based on what roles the user has. But I understand this may not be feasible.

**Comment by mueslimak3r** [comment]
It would be great to have links/portal access denied too if user doesn't have sufficient privileges, specifically I'm using Google Oath. Bare minimum it would be nice to get the same "Forbidden" page if user signs in and isn't privileged. Just having an easy to access list of all of my services is a little worrying

**Comment by greenpau** [comment]
> It would be great to have links/portal access denied if user doesn't have sufficient privileges, specifically I'm using Google Oath. Bare minimum it would be nice to get the same "Forbidden" page if user signs in and isn't privileged. Just having an easy to access list of all of my services is a little worrying

@mueslimak3r , the latest release works as follows. https://github.com/greenpau/caddy-auth-portal#jwt-tokens

By default, in addition to the roles configured by an authentication provider,
the plugin issues one of the three roles to a user.

* `authp/admin`: this is the admin user. It must be granted by authentication
  provider or added to a user via `transform user` directive
* `authp/user`: the user can access `/settings` endpoint. It must be granted
  by authentication provider or added to a user via `transform user` directive
* `authp/guest`: can access portal only. This is the default role assigned by
  the portal to a user when neither `authp/admin` nor `authp/user` are being
  assigned

**Comment by sandstormkeshav** [comment]
@greenpau just to confirm, so users that do not have an assigned role will still be able to reach the portal? Is there a way to only allow valid authenticated users to reach the portal. This would prevent random users authenticating with Google oauth from seeing the services available in the portal.
