### ISSUE TITLE
Only authenticate specific parts

### ISSUE THREAD

**Issue by Whizzzer** [greenpau/caddy-auth-portal#115]
**Describe the issue**

I'm experiencing an issue where I can't login to Kibana (running within a container) with a username/password for Kibana because Caddy with this authentication plugin is interfering. Probably a misconfiguration on my end, yet I don't know how to fix it.

To be more specific: I have a setup with three containers (besides caddy) all running on one FQDN:
- portainer
- whoami
- kibana

Authentication to access portainer & whoami is done by Caddy (OAuth with Azure). Access to Kibana should go without any authentication/authorization by Caddy. Kibana itself shows a login prompt to which I need to a form-based authentication (local username/password, not yet with OAuth at this time)

Yet when logging in to Kibana with the correct username/password, it shows "failed" in its webpage and funny enough Caddy shows in te logging: `{"level":"warn","ts":1617367708.6953683,"logger":"http.handlers.auth_portal","msg":"Authentication failed","request_id":"e8ebc3a4-51ae-4a9d-a890-77d2b0884815","error":"Request content type is not application/x-www-form-urlencoded"}`

But if I log in first by using the auth portal (so within Caddy itself) and afterwards go to Kibana, authentication passes sucessfully (again: with local user/pass). So based on that I have the impression caddy-auth-portal is doing something it shouldn't.

**Configuration**

Paste full `Caddyfile` below:

```
fully.qualified.domain.name {

    route /auth* {
       auth_portal {
         ui {
           theme basic
           links {
             "Portainer" /portainer/
             "Whoami" /whoami/
             "Kibana" /
           }
         }
         backends {
           azure_oauth2_backend {
             method oauth2
             realm azure
             provider azure
             tenant_id my-tenant.onmicrosoft.com
             client_id <client_id>
             client_secret <client_secret>
             scopes openid email profile
             user "@fully.qualified.domain.name$" regex add role admin
           }
         }
         cookie_domain fully.qualified.domain.name
         jwt {
           token_name access_token
           token_secret <token_secret>
           token_lifetime 3600
         }
       }
    }

    route /portainer/* {
      jwt {
        primary yes
        trusted_tokens {
          static_secret {
            token_name access_token
            token_secret <token_secret>
          }
        }
        auth_url /auth
#        allow roles anonymous guest admin
#        allow roles superadmin
      }
      uri strip_prefix /portainer
      reverse_proxy http://portainer:9000
      }

    route /whoami/* {
       jwt
       uri strip_prefix /whoami
       reverse_proxy http://whoami
       }

    reverse_proxy https://kibana:5601 {
      header_up X-Real-IP {remote_host}
      header_up X-Forwarded-Proto {scheme}
      header_up Access-Control-Allow-Origin *
      header_up Access-Control-Allow-Credentials true
      header_up Access-Control-Allow-Headers Cache-Control,Content-Type
#      header_up -Authorization
      transport http {
         tls
         tls_insecure_skip_verify
         read_buffer 8192
         }
      }
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
whizzer@docker:~/$ docker exec -it caddy /bin/sh
/srv # caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.4.0-beta.1
http.authentication.hashes.scrypt v2.4.0-beta.1
http.authentication.providers.http_basic v2.4.0-beta.1
http.handlers.authentication v2.4.0-beta.1
http.authentication.providers.jwt v1.2.7
http.handlers.auth_portal v1.4.6
/srv #

```

**Expected behavior**

Caddy should act as a "simple" reverse proxy for, in this case, kibana. Authentication should only be done for portainer & whoami.

**Additional context**

Chances are big I'm making a configuration mistake. Yet I don't see what it could be. Also, though Kibana is capable of doing OAuth as well, there are

**Comment by greenpau** [comment]
> So based on that I have the impression caddy-auth-portal is doing something it shouldn't.

@Whizzzer , everything is possible :-) 

What comes to mind is that "/auth" path exist in `portal`, but also in the proxied app. Please check that. if so, change `portal` to serve from different path, e.g. `/xauth`. This way it will not conflict.

**Comment by Whizzzer** [comment]
Seems we have a winner...

Changed a few things:
- `route /auth*` to `route /xauth*`
- Within that section added `path /xauth`
- `auth_url /auth` in the "portainer" section to `auth_url /xauth`

Also needed to change the redirect url in te azure app-registration of course..

Thanks for the quick response. Any other suggestions based on the configuration?

**Comment by greenpau** [comment]
> Any other suggestions based on the configuration?

@Whizzzer , still not working? or general feedback?

**Comment by Whizzzer** [comment]
It's working now... Just wanted to give some feedback for you and anyone else in a way that you can see what I've done to fix this thing.

Interesting to see kibana apparently uses something with /auth*, yet I can't find it in the documentation.
