### ISSUE TITLE
Redirect to /auth after token has expired

### ISSUE THREAD

**Issue by sandstormkeshav** [greenpau/caddy-auth-portal#116]
**Describe the issue/How to reproduce**

1. Visit Protected website (authenticate with google oauth)
2. Wait until JWT Token Expires
3. Refresh the page or open a new tab with the same website
4. Here you will see that you will be sent back to the /auth endpoint, upon logging in you will not be redirected to the page you requested.

**Configuration**

Paste full `Caddyfile` below:

```
		@myapp host myprivateapp.domain.com
	handle @myapp {
		route {
			jwt {
				primary yes
				auth_url https://authenticate.domain.com/auth/oauth2/google
				allow roles guest
				trusted_tokens {
					static_secret {
						token_name access_token
						token_secret REDACTED
					}
				}
			}
			respond "My Private App!"
		}
	}
	
	@securesite path /auth/portal* /auth/whoami* /auth/settings*
	@authportal host authenticate.domain.com
	handle @authportal {
		route @securesite {
			jwt {
				allow roles superadmin
			}
		}

		route /auth* {
			auth_portal {
				path /auth
				backends {
					# local_backend {
					# 	method local
					# 	path /auth/users.json
					# 	realm local
					# 	#require mfa
					# }
					google_oauth2_backend {
						method oauth2
						realm google
						provider google
						client_id REDACTED
						client_secret REDACTED
						scopes openid email profile
						
					}
				}
				cookie_domain .domain.com
				cookie_lifetime 3600
				jwt {
					token_name access_token
					token_secret REDACTED
					#token_lifetime 10
				}

				ui {
					links {
						"Who Am I" /auth/whoami icon "las la-smile"
						"Settings" /auth/settings icon "las la-cog"
						"Private App" https://myprivateapp.domain.com target_blank icon "las la-cog"
					}
				}
				# registration {
				# 	dropbox /auth/registrations_db.json
				# 	title "User Registration"
				# 	code "NY2020"
				# }
			}
		}
		route {
			redir https://{hostport}/auth 302
		}
	}
```

**Version Information**

```
I am running 1.4.6
```

**Expected behavior**

The expected behavior would be to when attempting to refresh or visit myprivateapp.domain.com with an expired JWT token, we should send the user to the auth_url endpoint, but also keep track of the redirect url so we can send them back after completion. We should not be returning the user back to the login portal showing the links.

 I think the reason why this is sending me direct to the /auth login page instead of the google login page is that the redirect url cookie does not exist.

**Additional context**

Here is another scenario that may shed more light on the issue:

1. Visit Protected website (authenticate with google oauth)
2. Wait until JWT Token Expires
3. Refresh the page or open a new tab with the same website
4. You will get sent to /auth like before, and never be redirected -- ignore this for the sake of step 5
5. Try opening a new tab and visiting the same page again, now everything seems to work (you get sent to the google oauth flow and returned back to the website you are trying to access)

**Comment by sandstormkeshav** [comment]
The easiest way to reproduce this would be to set your token_lifetime to something short so you can see the JWT expire in your browsing session.

**Comment by sandstormkeshav** [comment]
@greenpau I wonder if this is maybe a browser side issue that the redirect cookie isn't getting stored. Are you able to reproduce this behavior? Thank you!

**Comment by greenpau** [comment]
@sandstormkeshav , I am in a middle of rewriting jwt plugin. Once I get back to this issue, I will ping you here.

**Comment by sandstormkeshav** [comment]
@greenpau Thank you sir!

**Comment by sandstormkeshav** [comment]
@greenpau I see that you have updated for the caddy-auth-jwt plugin, is it ready for release (and should I use xcaddy to build?) or should I wait for a published release.

**Comment by greenpau** [comment]
@sandstormkeshav , please upgrade to the latest release. This feature now work. If not, please open a separate issue with new config syntax attached.
