### ISSUE TITLE
feature: Add support for specifying CAs

### ISSUE THREAD

**Issue by jprenken** [greenpau/caddy-auth-portal#12]
It would be great if I could specify a file or directory containing (a) specific CA certificate(s) to trust for validation of an LDAPS server's certificate.

**Comment by greenpau** [comment]
@jprenken , I released support for https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.1.11

See https://github.com/greenpau/caddy-auth-portal#ldap-authentication-backend

Caddyfile directive:

```
          servers {
            ldaps://ldaps.contoso.com
          }
          trusted_authority /etc/gatekeeper/tls/trusted_authority/contoso_com_root1_ca_cert.pem
          trusted_authority /etc/gatekeeper/tls/trusted_authority/contoso_com_root2_ca_cert.pem
          trusted_authority /etc/gatekeeper/tls/trusted_authority/contoso_com_root3_ca_cert.pem
```
