### ISSUE TITLE
Signing in does nothing

### ISSUE THREAD

**Issue by UndarkAido** [greenpau/caddy-auth-portal#120]
**Describe the issue**

When I sign in with the default `webadmin` credentials it just reloads the auth page. If I enter incorretc credentials it throws an error.

**Configuration**

Paste full `Caddyfile` below:

```
http://localhost, http://192.168.1.70, http://prometheus.theundarkpixel.com {
    route /auth* {
        trace tag="testing" response_debug=yes uri_filter="^/auth$"
        auth_portal {
            path /auth
            backends {
                local_backend {
                    method local
                    path /var/lib/caddy/auth/local/users.json
                    realm local
                }
            }
            jwt {
                token_name access_token
                token_secret 016733c0-9a58-11eb-a8b3-0242ac130003
                token_lifetime 3600
                token_sign_method HS256
            }
            ui {
                theme basic
            }
            registration {
                dropbox /var/lib/caddy/auth/local/users.json
                title "User Registration"
                code "TN2021"
                #require accept_terms
                #require domain_mx
            }
        }
    }

    route {
        jwt {
            primary yes
            trusted_tokens {
                static_secret {
                    token_name access_token
                    token_secret 016733c0-9a58-11eb-a8b3-0242ac130003
                    token_issuer 86f7df80-9a58-11eb-a8b3-0242ac130003
                }
            }
            auth_url /auth
            allow roles anonymous guest admin
            allow roles superadmin
        }
        root * /usr/share/caddy/heimdall/public
        php_fastcgi unix//run/php/php7.4-fpm.sock
        file_server
    }
}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.3.0
http.authentication.hashes.scrypt v2.3.0
http.authentication.providers.http_basic v2.3.0
http.authentication.providers.jwt v1.2.7
http.handlers.auth_portal v1.4.6
http.handlers.authentication v2.3.0
```

**Expected behavior**

It should load the services panel

**Additional context**

I got it to work once but I'm not sure what I've changed since then lol :P

**Comment by greenpau** [comment]
> I got it to work once but I'm not sure what I've changed since then lol :P

@UndarkAido , this happens to me too from time to time 😃 

Couple things here.

1. Use HTTPS ... I don't think it will allow you to get a cookie on HTTP connection. However, that depends on a security of your browser.

2. You should not use the same file for authentication and registration. If you want a registration, put it in a different file. See https://github.com/greenpau/caddy-auth-portal#user-registration

Remove:

```
            registration {
                dropbox /var/lib/caddy/auth/local/users.json
                title "User Registration"
                code "TN2021"
                #require accept_terms
                #require domain_mx
            }
```

3. no need to define default theme. However, there is a need to setup links.

Remove:

```
            ui {
                theme basic
            }
```

Add: 

```
            ui {
              links {
                "My Identity" "/auth/whoami" icon "las la-star"
                "My Settings" /auth/settings icon "las la-cog"
                "My App" / icon "las la-cog"
              }
            }
```

4. Auth portal JWT should use [shortcuts](https://github.com/greenpau/caddy-auth-portal#caddyfile-shortcuts):

Remove:

```
            jwt {
                token_name access_token
                token_secret 016733c0-9a58-11eb-a8b3-0242ac130003
                token_lifetime 3600
                token_sign_method HS256
            }
```

Add. Try not adding `HS256`:

```
            jwt_token_secret 016733c0-9a58-11eb-a8b3-0242ac130003
            jwt_token_lifetime 3600
```


Please change the config and paste the new to this issue. I think this is related to you not having UI links.

**Comment by UndarkAido** [comment]
Ah! I doesn't work when I access it via IP but it does work when I access it via HTTPS. So I guess this won't work for LAN stuff? I could probably just not enable JWT on LAN.

There is actually HTTPS, it's just on a different machine right now. This is a server I'm setting up for a friend as a wedding present so it's proxied from mine.

Is there an example anywhere for how to set up authentication as a subdomain instead of a path? I couldn't get that to load.

**Comment by greenpau** [comment]
> Is there an example anywhere for how to set up authentication as a subdomain instead of a path? I couldn't get that to load.

@UndarkAido , for an example try looking at https://github.com/greenpau/caddy-auth-portal/issues/99

also, look for “cookie_domain” in the documentation.

> Edit: And is there a reason for disabling registration?

no need to disable. Just don’t use the same file. The reason not using the same file is potential attack vector.

**Comment by UndarkAido** [comment]
Is there UI for approving new users yet?

**Comment by greenpau** [comment]
> Is there UI for approving new users yet?

@UndarkAido , not yet. I did not get to it yet. Probably in the next couple of months.

**Comment by greenpau** [comment]
FYI, starting working on this feature.

**Comment by greenpau** [comment]
@dczysz , please read about “transform user” directive. It is probably worth deleting you comment here and opening a separate issue. So not to confuse readers.

**Comment by dczysz** [comment]
Will do, sorry about that. I thought it was close enough to fit in the same issue. I'll check out "transform user" and open a new issue if I still can't get it working. Thanks!
