### ISSUE TITLE
Documentation clarification: OAuth 2.0 full example using Google

### ISSUE THREAD

**Issue by cceyda** [greenpau/caddy-auth-portal#121]
Firstly I absolutely love this plugin 😍 It is everything I have been searching for~
But I'm a bit confused about how to correctly configure OAuth 2.0 backends (Google in my case).
I understand the `backends` configuration, but in the OAuth 2.0 examples  there is no `jwt` settings. But I found it necessary for it to function correctly. As far as I understand it works like; auth backend-> google says okay -> caddy jwt creates/sets token...?

In the prometheus example `jwt` is configured like below (for a local backend) 
I'm not clear on what `primary` means? and `static_secret ` Is this setting exclusive to a local backend?
```
jwt {
      primary yes
      trusted_tokens {
      static_secret {
          token_name access_token
          token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
        }
      }
```
I found the below configuration to work, but I feel like I might be missing something important.
```
test.example.org {
  route /auth/* {
		auth_portal {
                cookie_domain example.org 
		  backends {
			google_oauth2_backend {
			  method oauth2
			  realm google
			  provider google
			  client_id SECRET
			  client_secret SECRET
			  scopes openid email profile
			}
		  }
		  # I don't understand which fields in jwt are necessary here?
		  jwt {
			token_name access_token
			token_secret SECRET
		  }
	    }
	}
	
  route /api* {
    jwt {
    #I think this is necessary too?
      primary yes 
    #Is this the correct way to pass token info for oauth2 too?
      trusted_tokens {
        static_secret { 
          token_name access_token
          token_secret SECRET
        }
      }
      auth_url /auth/oauth2/google
    }
	uri strip_prefix /api
	reverse_proxy localhost:8000
  }   
}
```
I saw `token_issuer` in a couple of old examples is it deprecated?

Thanks

**Comment by greenpau** [comment]
>  I'm not clear on what primary means? and static_secret Is this setting exclusive to a local backend?

@cceyda , you can read about `primary` over [here](https://github.com/greenpau/caddy-auth-jwt#overview). I really want to create Youtube video explaining it :-)

Regarding your configuration.  Here is what you need. Note `#user "^greenpau" regex add role superuser` and change it to your email.

The `0c9d8d51-aed0-4769-9315-44f5a8ddf548` is the shared key between `portal` and `jwt` plugins.

```
test.example.org {
  route /auth* {
    auth_portal {
      path /auth
      backends {
        google_oauth2_backend {
          disabled
          method oauth2
          realm google
          provider google
          client_id SECRET
          client_secret SECRET
          scopes openid email profile
          #user "^greenpau" regex add role superuser
        }
      jwt {
        token_secret 0c9d8d51-aed0-4769-9315-44f5a8ddf548
        token_sign_method HS512
        token_lifetime 3600
      }
      ui {
        links {
          "My API" /api/
          "My Identity" "/auth/whoami" icon "las la-star"
          "My Settings" /auth/settings icon "las la-cog"
        }
      }
    }
  }
  route /api* {
    jwt {
      primary yes
      trusted_tokens {
        static_secret {
          token_secret 0c9d8d51-aed0-4769-9315-44f5a8ddf548
        }
      }
      auth_url /auth/oauth2/google
      allow roles superuser
      allow roles anonymous guest
    }
    uri strip_prefix /api
    reverse_proxy http://127.0.0.1:8000
  }
  route {
    # trace tag="default"
    redir https://{hostport}/auth 302
  }
}
```

>  and static_secret Is this setting exclusive to a local backend?

It is just a label to identify a secret. There could be many secrets.

> Firstly I absolutely love this plugin 😍 It is everything I have been searching for~

Enjoy! Please ask follow up questions! :-)

**Comment by cceyda** [comment]
I guess the static in `static_secret` was throwing me off, like it wouldn't change or something.
I would love an example of `context` directive. Would this be the thing to use to have different allowed roles for different routes?

**Comment by mueslimak3r** [comment]
@greenpau thanks for your example. When I use it ,with only minimal changes like using my google api client ID and secret, using my domain, and pointing the "/api" reverse proxy to one of my services, I get the error: 

`May 26 02:47:46 DietPi4 caddy[8039]: run: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'auth_portal': provision http.handlers.auth_portal: authentication provider registration error, instance portal-1, error: portal-1: no valid backend found
May 26 02:47:46 DietPi4 systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
May 26 02:47:46 DietPi4 systemd[1]: caddy.service: Failed with result 'exit-code'.`

**Comment by cceyda** [comment]
Leaving this here because I found it pretty useful, maybe should add this to README as reference: 
https://caddyserver.com/docs/json/apps/http/servers/routes/handle/auth_portal/
