### ISSUE TITLE
Mutliple subdomains /w a snippet possible?

### ISSUE THREAD

**Issue by Dulanic** [greenpau/caddy-auth-portal#122]
I am not super familar /w http routing etc.. so I am having trouble grasping this as easily as some others. EX: I have maybe 10 subdomains, do you have any config examples for use /w multiple subdomains? Like /w the jwt etc... in a snippet? I was thinking something like this, but I am stuck and I know I am missing some jwt commands. I am just trying to add like import secure for any subdomain and have it handle it /w the one snippet. Is that possible? 

I've found examples online for caddyv1, but not caddyv2. https://kamal.io/blog/securing-internal-services-behind-oauth2-with-caddy

Sorry for being a newb with this stuff, I just am having trouble grasping a lot of this part. Also, I had issues /w it complaining about order, is there anything that would need to change? I kind of guessed. Basically trying to move all my basicauth over to oauth. The full file is here: https://dulanic.com/files/Caddyfile

```
{
	default_sni dulanic.com
	acme_ca https://acme-v02.api.letsencrypt.org/directory
	email {$ACMEEMAIL}
	order jwt before basicauth
	order auth_portal before jwt
}
(secure) {
	jwt {
		auth_url https://auth.dulanic.com/login?backTo=https://{host}{uri}
	}
}
https://auth.dulanic.com {
	auth_portal {
		backends {
			google_oauth2_backend {
				method oauth2
				realm google
				provider google
				client_id {$google_client_id}
				client_secret {$google_client_secret}
				scopes openid email profile
				user dulanic@gmail.com add role verified
			}
		}
	}
}
```

**Comment by greenpau** [comment]
@Dulanic , the config you have is not from this plugin family.

First, thank you for opening the issue 👍 

Second, write down what you want the users to experience and I will help drafting your config. Yes, you can have multiple subdomain.

**Comment by Dulanic** [comment]
Im not sure what you mean its not from this plugin family? It is Caddyv2 using github.com/greenpau/caddy-auth-portal and github.com/greenpau/caddy-auth-jwt. Appreciate you dealing with my newbness. I am trying my best to pick this up, but some of the http routing stuff is still over my head. This is my docker file to build my caddy container. https://github.com/Dulanic/docker-caddy/blob/master/Dockerfile

My caddyfile is https://dulanic.com/files/Caddyfile

Also, what I am looking to do it just have the subdomains go to google oauth if not already logged in.  That is, If i import the snipped for that subdomain. The plan was to replace import DAUTH /w the google auth snippet instead. I am manually setting user for now, but will convert to a json file long term based on what rights a user has. Default is no access.

**Comment by greenpau** [comment]
@Dulanic , let discuss this part of your config. 

```
(secure) {
	jwt {
		auth_url https://auth.dulanic.com/login?backTo=https://{host}{uri}
	}
}
https://auth.dulanic.com {
	auth_portal {
		backends {
			google_oauth2_backend {
				method oauth2
				realm google
				provider google
				client_id {$google_client_id}
				client_secret {$google_client_secret}
				scopes openid email profile
				user dulanic@gmail.com add role verified
			}
		}
	}
}

https://protected.dulanic.com {
	import main
	import secure
	file_server
	root * /www/websites/fuckoff.dulanic.com
	handle_path /img/* {
		root * /www/websites/fuckoff.dulanic.com/images
		file_server
	}
}
```

The use of `import secure` without `route` is invalid. Here is what you likely need.

1. Only, one of the `jwt` references is the "primary" instance in a "context". More info on this [here](/www/websites/protected.dulanic.com). The rest of `jwt` reference would inherit setting from it. If you want many different configuration for `jwt`, separate them using `context` directive, e.g. `context domain1`, `context domain2`, etc.
2. The `order auth_portal before jwt` is not necessary.
3. When using `portal` and `jwt` plugins you need a key to encrypt tokens. That's the token secret. You could also use RSA (see [here](https://github.com/greenpau/caddy-auth-jwt#verification-with-rsa-keys))
4. You also want to allow `verified` role in.
5. As to the redirect. You don't need to specify `backTo`. It is not auto-discovered. You just need to point to Google OAuth2.0 endpoint.

```
(jwt_protected) {
  jwt {
    primary yes
    trusted_tokens {
      token_secret {$token_shared_secret}
    }
    allow roles verified
    auth_url https://auth.dulanic.com/auth/oauth2/google
  }
}

# The portal is being served from / root.
https://auth.dulanic.com {
  route /auth* {
    auth_portal {
      path /auth
      backends {
        google_oauth2_backend {
          method oauth2
          realm google
          provider google
          client_id {$google_client_id}
          client_secret {$google_client_secret}
          scopes openid email profile
          user dulanic@gmail.com add role verified
        }
      }
      jwt {
        token_sign_method HS512
        token_secret {$token_shared_secret}
      }
      ui {
        links {
          "My Identity" "/auth/whoami" icon "las la-star"
        }
      }
    }
  }

  route {
    # automatically redirects to Google OAuth 2.0
    redir https://{hostport}/auth/oauth2/google 302
  }
}

https://protected.dulanic.com {
  import main
  route /img/* {
    import jwt_protected
    file_server {
      root /www/websites/protected.dulanic.com/images
    }
  }
  route {
    jwt
    file_server {
      root /www/websites/protected.dulanic.com
    }
  }
}
```

Please ask follow up questions.

**Comment by Dulanic** [comment]
OK let me work on it that way. The order by was put in because it was saying my caddyfile was invalid without a order. I'll try this out now.

**Comment by greenpau** [comment]
@Dulanic , please do not hesitate to reach out right away.

**Comment by Dulanic** [comment]
Something doesnt seem right, it errors out and im not sure why. That env variable is deff set too, i verified. I created it at https://www.javainuse.com/jwtgenerator key shouldnt matter right? I used H256 and changed it to H256. 
```
dulanic@mediaserver:~/docker/envs$ caddyrl
2021/04/17 18:57:40.336 INFO    using provided configuration    {"config_file": "/etc/caddy/Caddyfile", "config_adapter": "caddyfile"}
reload: adapting config using caddyfile: parsing caddyfile tokens for 'route': /etc/caddy/Caddyfile:118 - Error during parsing: parsing caddyfile tokens for 'auth_portal': /etc/caddy/Caddyfile:110 - Error during parsing: jwt token_secret subdirective has no value
```

**Comment by greenpau** [comment]
@Dulanic , you did not set secret. It is done the same way how you set google client id.

**Comment by greenpau** [comment]
Search token_shared_secret

**Comment by Dulanic** [comment]
I did didn't I? 
![Screenshot 2021-04-17 2 07 40 PM](https://user-images.githubusercontent.com/2948206/115124228-cab18e00-9f86-11eb-9c5a-637c2e679aa5.png)

**Comment by greenpau** [comment]
@Dulanic , you have the key that looks like JWT token. Just do uuidgen to generate a shorter string for now.

it might be that the double import in jwt_protected is not working. For now, don’t use that import and paste directly into the config.

**Comment by greenpau** [comment]
@Dulanic , the secret is “symmetric” key. It can be used to both sign and validate JWT tokens.

**Comment by Dulanic** [comment]
Still doesnt seem to be working, I switched to using uuidgen too.
I updated https://dulanic.com/files/Caddyfile
```

dulanic@mediaserver:~/docker/caddy$ caddyrl
2021/04/17 19:38:01.036 INFO    using provided configuration    {"config_file": "/etc/caddy/Caddyfile", "config_adapter": "caddyfile"}
reload: adapting config using caddyfile: parsing caddyfile tokens for 'route': /etc/caddy/Caddyfile:107 - Error during parsing: parsing caddyfile tokens for 'auth_portal': /etc/caddy/Caddyfile:99 - Error during parsing: jwt token_secret subdirective has no value
```

**Comment by greenpau** [comment]
@Dulanic , the `{$token_shared_secret}` is not being taken in. Try changing it to environment variable with something like `{env.CLOUDFLARE_API_TOKEN}`

**Comment by greenpau** [comment]
@Dulanic , additionally, change:

```
        route {
                jwt {
                        primary yes
                        trusted_tokens {
                                token_secret {$token_shared_secret}
                        }
                        allow roles verified
                        auth_url https://auth.dulanic.com/auth/oauth2/google
                }
                file_server {
                        root /www/websites/protected.dulanic.com
                }
        }
```

to:

```
        route {
                jwt {
                        primary yes
                        trusted_tokens {
                           static_secret {
                                token_secret {$token_shared_secret}
                           }
                        }
                        allow roles verified
                        auth_url https://auth.dulanic.com/auth/oauth2/google
                }
                file_server {
                        root /www/websites/protected.dulanic.com
                }
        }
```

**Comment by Dulanic** [comment]
OK, the env. fixed that part. Odd how it works sometimes but not others. But the redir seems wrong.

![image](https://user-images.githubusercontent.com/2948206/115125904-e7eb5a00-9f90-11eb-9b4d-e34129b54557.png)

**Comment by greenpau** [comment]
Notecthe “protected” in my example. I did not use f word.

**Comment by Dulanic** [comment]
Oh I know, I switched it as I should have and it gave me the same error. Thats also why I moved it to my pgadmin subdomain to make discussing easier.

**Comment by greenpau** [comment]
@Dulanic , at the top of you config enable debugging and try seeing what is happening:

```
{
  http_port     8080
  https_port    8443
  debug
}
```

**Comment by Dulanic** [comment]
So once I did that, it started getting further. So I didnt see much there. But now if i go to pgadmin.dulanic.com it routes me to google, i pick my account, it errors /w too many redirects screen for a 1/4 second goes to Authentication Failed screen /w the portal. Then I can go to my identity.

Quick video example:



https://user-images.githubusercontent.com/2948206/115127411-e4110500-9f9b-11eb-971f-dc04300efec6.mp4

**Comment by greenpau** [comment]
Change the  redir https://{hostport}/auth/oauth2/google 302

to  redir https://{hostport}/auth/ 302

**Comment by greenpau** [comment]
It could be that the below does not work. watch the logs for clues.

user dulanic@gmail.com add role verified

**Comment by Dulanic** [comment]
So the change to redir didnt change anything. Im watching the log but I am so lost. I dont see anything that stands out to me or anything specific i can use grep to narrow down to. I changed it to superuser, and no change, and I can see it is properly clasifying me as a superuser. It says authentication succeeded. I used jq to make it more readable and still really dont know what I am looking for. I see successful and failed, so not sure?

Not sure which parts are things i shouldnt share so anything that looked like a key i replaced random sections /w redacted.

```
  "log": "{\"level\":\"debug\",\"ts\":1618703563.0686939,\"logger\":\"http.handlers.auth_portal\",\"msg\":\"Authentication succeeded\",\"request_id\":\"redacted-a191-4321-a0c1-341fc3a240d4\",\"auth_method\":\"oauth2\",\"auth_realm\":\"google\",\"user\":{\"exp\":1618704463,\"jti\":\"redacted-a191-4321-a0c1-341fc3a240d4\",\"iat\":1618703563,\"iss\":\"https://auth.dulanic.com/auth/oauth2/google/authorization-code-callback\",\"nbf\":1618702963,\"sub\":\"101721796260108068070\",\"name\":\"Dulanic\",\"email\":\"dulanic@gmail.com\",\"roles\":[\"anonymous\",\"guest\",\"everyone\",\"superuser\"],\"origin\":\"https://accounts.google.com\",\"picture\":\"https://lh3.googleusercontent.com/a-/redacted-03MWrkxyQVUgE=s96-c\"}}\n",
```
```
"log": "{\"level\":\"warn\",\"ts\":1618703564.3726544,\"logger\":\"http.handlers.auth_portal\",\"msg\":\"Authentication failed\",\"request_id\":\"9c3fc694-73e5-4e58-9661-993d1e03b0e2\",\"auth_method\":\"oauth2\",\"auth_realm\":\"google\",\"error\":\"failed fetching OAuth 2.0 access token: failed obtaining OAuth 2.0 access token, error: invalid_grant, description: Bad Request\"}\n"
```

```
 "log": "{\"level\":\"debug\",\"ts\":1618703564.3726811,\"logger\":\"http.handlers.auth_portal\",\"msg\":\"serve generic page\",\"request_id\":\"9c3fc694-73e5-4e58-9661-993d1e03b0e2\",\"title\":\"Authentication Failed\",\"status_code\":401}\n",
```

**Comment by cceyda** [comment]
@Dulanic It is possible that you are missing the `cookie_domain dulanic.com` inside `auth_portal` at the same level as `backends`.
I was trying this code and that line made it work

**Comment by cceyda** [comment]
@greenpau In a kind of relevant question:
Is it possible to have multiple subdomains on different machines use the same auth?
Would this work as long as they are using the same `token_secret`?

Senario: 
```
Machine A:
static.example.org-> protected with auth 

Machine B:
auth.example.org -> auth backend
api.example.org-> protected with auth 
```
Where user signs in once; lets say being redirected through `api.example.org` and they wouldn't have to also sign in for `static.example.org`

**Comment by Dulanic** [comment]
@cceyda Thanks! That did correct that problem.

Quick question as a follow up, how can I avoid auth on /api for example? If using basic auth, i would use handle. I tried to use route not /api* but it doesn't seem to like that even though not says it takes any other matcher, it doesnt.
```
	route not path /api* {
		jwt {
			trusted_tokens {
				static_secret {
					token_secret {env.token_shared_secret}
				}
			}
			allow roles verified
			auth_url https://auth.dulanic.com/auth/
		}
	}
```

```
reload: adapting config using caddyfile: parsing caddyfile tokens for 'route': /etc/caddy/Caddyfile:181 - Error during parsing: Wrong argument count or unexpected line ending after 'not'
```
This was the method I would use for basic auth:
ex:

```
	handle /api* {
	}
	handle {
		basicauth {
			{$DAUTH}
		}
	}
```

**Comment by greenpau** [comment]
> Is it possible to have multiple subdomains on different machines use the same auth?
Would this work as long as they are using the same token_secret?

@cceyda , yes. Importantly, with your questions, I realized I made a mistake calling there properties `token_...`. It is really encryption or decryption keys. In the case of `token_secret`, it can be used for encryption and decryption of tokens.

I suggest you consider using public-private key cryptography with RS512.

Also, I am the process of rewriting JWT plugin and will change the names to make more sense.

**Comment by greenpau** [comment]
> Quick question as a follow up, how can I avoid auth on /api for example? If using basic auth, i would use handle. I tried to use route not /api* but it doesn't seem to like that even though not says it takes any other matcher, it doesnt.

@Dulanic , please clarify your question and provide a short config snippet for it.

**Comment by greenpau** [comment]
> > Is it possible to have multiple subdomains on different machines use the same auth?
Would this work as long as they are using the same token_secret?

@cceyda , additionally, the `portal` plugin needs both encryption and decryption functions, i.e. private key (although it is called private key, it contains both private and public keys). The `jwt` only needs the decryption function, e.g. public key only.

**Comment by Dulanic** [comment]
> > Quick question as a follow up, how can I avoid auth on /api for example? If using basic auth, i would use handle. I tried to use route not /api* but it doesn't seem to like that even though not says it takes any other matcher, it doesnt.
> 
> @Dulanic , please clarify your question and provide a short config snippet for it.

@greenpau OK so I have subdomain .dulanic.com I want it to require authorization on subdomain.dulanic.com and any subfolder except /api. So if I am accessing subdomain.dulanic.com/api I do not want authentication required as it requires a API key already.

I attempted to use this which according to https://caddyserver.com/docs/caddyfile/matchers#not should work bescause path is another matcher. But it errors out.

```
	route not path /api* {
		jwt {
			trusted_tokens {
				static_secret {
					token_secret {env.token_shared_secret}
				}
			}
			allow roles verified
			auth_url https://auth.dulanic.com/auth/
		}
	}
```

```
reload: adapting config using caddyfile: parsing caddyfile tokens for 'route': /etc/caddy/Caddyfile:181 - Error during parsing: Wrong argument count or unexpected line ending after 'not'
```

I used to use this /w basic auth, so I tried using handle, but that errors out.
```

(DAUTH) {
	handle /api* {
	}
	handle {
		basicauth {
			{$DAUTH}
		}
	}
}
```

So I tried that with route but got this: This seems more like a caddy thing that a portal thing, but trying to think of alternatives.

```
	handle /api* {
	}
	handle {
		jwt {
			trusted_tokens {
				static_secret {
					token_secret {env.token_shared_secret}
				}
			}
			allow roles verified
			auth_url https://auth.dulanic.com/auth/
		}
	}
```
```
reload: adapting config using caddyfile: parsing caddyfile tokens for 'handle': directive 'jwt' is not ordered, so it cannot be used here
```

**Comment by greenpau** [comment]
> except /api. 

@Dulanic , now I get it. Currently it is not possible to bypass when you have `jwt` plugin in between the entry point to the route and reverse proxy. I added https://github.com/greenpau/caddy-auth-jwt/issues/61.

Also, compare the config in the https://github.com/greenpau/caddy-auth-jwt/issues/61 with the part of the config in https://dulanic.com/files/Caddyfile, i.e. the below.

```
https://subdomain.dulanic.com {
	import main
	route {
		jwt {
			trusted_tokens {
				static_secret {
					token_secret {env.token_shared_secret}
				}
			}
			allow roles verified
			auth_url https://auth.dulanic.com/auth/
		}
	}
	reverse_proxy test:80 {
		import proxyheaders
	}
}
```

**Comment by Dulanic** [comment]
@greenpau Thanks, yes that is what I was looking to do.  You are spot on.  

Also as a FYI, I was able to throw the route back into the snippet to try to keep it consolidated /w these updates, and it errors out in the log .  For now, Ill just repeat that same route in every subdomain, just not sure why it wont take it as a snippet.


```
(jwt_protected) {
	route {
		jwt {
			trusted_tokens {
				token_secret {$token_shared_secret}
			}
			allow roles verified
			auth_url https://auth.dulanic.com/auth/oauth2/google
		}
	}
}
```

```
{"level":"error","ts":1619101882.4429889,"logger":"http.handlers.authentication","msg":"auth provider returned error","provider":"jwt","error":"jwt-87: token keys and secrets must be defined either via environment variables or via token_ configuration element"}
```

**Comment by greenpau** [comment]
> For now, Ill just repeat that same route in every subdomain, just not sure why it wont take it as a snippet.

@Dulanic , I suggest you ask in https://caddy.community/ because I am not proficient with inclusions. My guess is that `{$token_shared_secret}` is not being resolved when passed via `(jwt_protected) {` inclusion.

**Comment by Dulanic** [comment]
Not sure yet, I use docker and that hasn't made it downstream yet but thinking how I can test it.

**Comment by Dulanic** [comment]
@greenpau I think he was implying you needed to reload the values? The value is left as env and not updated? Not sure.

```
"trusted_tokens": [
                                                                                    {
                                                                                        "token_secret": "{env.token_shared_secret}"
                                                                                    }
```

**Comment by greenpau** [comment]
@Dulanic , please upgrade to the latest. I believe placeholders work. Look for `repl.ReplaceAll` in `caddyfile.go`, e.g.:

https://github.com/greenpau/caddy-auth-portal/blob/65e7d665214ad77a736159460b8d932e5cdd0c39/caddyfile.go#L194-L197
