### ISSUE TITLE
feature request: MFA for LDAP backend

### ISSUE THREAD

**Issue by erichiller** [greenpau/caddy-auth-portal#123]
It would be great if LDAP supported MFA / TOTP (as the _local_ backend does).

**Comment by greenpau** [comment]
@erichiller, that's easily doable. However, I don't have access to AD domain where I can test. Feel free connecting with me over LinkedIn and discussing it there.

In short, one can add shared or asymmetric key as part of a custom attribute and that info could be available in when logging in a user.

https://social.technet.microsoft.com/wiki/contents/articles/51121.active-directory-how-to-add-custom-attribute-to-schema.aspx

**Comment by greenpau** [comment]
Unfortunately, I don't have a way to pilot this.
