### ISSUE TITLE
Question: route vs handle directive

### ISSUE THREAD

**Issue by cceyda** [greenpau/caddy-auth-portal#124]
I was wondering if there is a specific reason for using [route](https://caddyserver.com/docs/caddyfile/directives/route) directive as opposed to [handle](https://caddyserver.com/docs/caddyfile/directives/handle) / [handle_path](https://caddyserver.com/docs/caddyfile/directives/handle_path), can we use also use these?
I know they both group directives;
 - route "Directives contained in a route block will **not be reordered** internally", is this critical for this plugin?
 - "Evaluates a group of directives **mutually exclusively** from other handle blocks" would this mean every jwt defined would need to be primary (since mutually exclusive implies no inheritence?)?

I guess this is a bit of a caddy related question...

**Comment by greenpau** [comment]
@cceyda , that’s a very good question! 👍 at the moment, idk the answer to it, because as you’ve said, it is about how caddyserver works.

**Comment by greenpau** [comment]
@cceyda , one thing to point out is that portal and jwt are different plugin types. The portal is a regular http handler, while jwt is “authorizer” plugin. Each of them have their own dynamic.

**Comment by greenpau** [comment]
@cceyda , when you read handle docs, see “Only HTTP handler directives can be used inside handle blocks.”

It could be that “jwt” plugin is not http handler (not supposed to serve any content) and therefore should not be used inside “handle” directive.

**Comment by cceyda** [comment]
Hmm that makes sense. Thanks for explaining~
