### ISSUE TITLE
Protecting a subdomain with proxy_pass to a service rather than portal

### ISSUE THREAD

**Issue by samcro1967** [greenpau/caddy-auth-portal#129]
I would like for a user to be able to go to auth.mydomain.net/auth, login, and get the UI.  When they go to main.mydomian.net, they are redirected to auth.mydomain.net/auth for login, returned to main.mydomian.net, and then follow the proxy_pass to the service.

With the config below, when I go to main.mydomian.net, I am sent to auth.mydomain.net/auth to login.  Once logged in, I am taken to auth.mydomain.net/auth/portal rather than returned to main.mydomian.net and then onto the proxy_pass directive.

Not sure if I am missing something or if what I am trying to accomplish is not possible.

**Caddyfile**
```
{
	https_port	443
	http_port	80
	debug
	email user@mydomain.net
}
(geofilter) {
		@mygeofilter {
			  maxmind_geolocation {
			  db_path "/data/GeoLite2-Country.mmdb"
			  allow_countries US
			}
		}
}
auth.mydomain.net {
	import geofilter
    log {
        output file /data/access.log
    }
	route /auth* {
		auth_portal {
			path /auth
#			cookie_domain mydomain.net
			backends {
				local_backend {
					method local
					path /config/caddy/users.json
					realm local
					require mfa
				}
			}
			jwt {
				token_name access_token
				token_secret <redacted>
				token_lifetime 86400
			}
			registration {
				dropbox /config/caddy/registrations_db.json
				title "User Registration"
				code "<redacted>"
				require accept_terms
				require domain_mx
			}
			ui {
				links {
					"My Identity" "/auth/whoami" icon "las la-star"
					"My Settings" "/auth/settings" icon "las la-cog"
					}
				}
		}
	}
}
main.mydomain.net {
	import geofilter
	route / {
		jwt {
			primary yes
			trusted_tokens {
				static_secret {
					token_name access_token
					token_secret <redacted>
				}
			}
			auth_url https://auth.mydomain.net/auth
			allow roles anonymous guest admin
			allow roles superadmin
		}
		reverse_proxy @mygeofilter 192.168.1.157:80
	}
}
```

**Comment by greenpau** [comment]
@samcro1967 did you add cookie_domain directive?

**Comment by samcro1967** [comment]
I did have "cookie_domain mydomain.net" in there, but removed it since it had no impact.

**Comment by greenpau** [comment]
@samcro1967 , where does `https://main.mydomain.net/login?loginRedirect=%2F` come from? I don't remember "loginRedirect"

**Comment by greenpau** [comment]
@samcro1967 , have you tried changing 

```
route /auth* {
		auth_portal {
			path /auth
```

for:

```
route {
		auth_portal {
			path /
```

**Comment by samcro1967** [comment]
Did not seem to have any effect.  Still working the same way.  I can authenticate and get redirected properly, but then it loads a blank page.  I tried it with another service on a second subdomain and get the same results.  Wanted to rule out something with the services I picked to test with.

**Comment by samcro1967** [comment]
Below is what I see in the browser console with and without caddy-auth-portal.  Looks like a Jquery is not being loaded/executed when caddy-auth-portal is enabled for that subdomain?

**Browser console without caddy-auth-portal**
```
[Deprecation] ::-webkit-details-marker pseudo element selector is deprecated. Please use ::marker instead. See https://chromestatus.com/feature/6730096436051968 for more details.
login?loginRedirect=%2F:72 Jquery Loaded
login?loginRedirect=%2F:1 Denying load of chrome-extension://cdhdonkamhccabhlohocejghpgklhimn/assets/fonts/GT-Walsheim-Bold.otf.otf. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
invalid/:1 Failed to load resource: net::ERR_FAILED
```
****Browser console witht caddy-auth-portal****
```
extension://cdhdonkamhccabhlohocejghpgklhimn/assets/fonts/GT-Walsheim-Bold.otf.otf. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
invalid/:1 Failed to load resource: net::ERR_FAILED
```

**Comment by samcro1967** [comment]
@greenpau So it sounds like subdomains should work and I have the correct config?  Either I have something environmental going on or have stumbled across a potential issue?  Since it works with just caddy and no caddy-auth-portal, is there anything environmental you can think of to check or try at this point or any other info I can provide to further troubleshoot?

**Comment by greenpau** [comment]
@samcro1967 , have you tried it without `@mygeofilter`?

**Comment by samcro1967** [comment]
@greenpau I did, but just retested for my own sanity and still get the same results.

**Comment by greenpau** [comment]
@samcro1967 , please paste your latest config.

**Comment by samcro1967** [comment]
Here are the changes I made:
uncommented cookie
route /auth* --> route /
path /auth --> path /
auth_url https://auth.mydomain.net/auth --> auth_url https://auth.mydomain.net

```
{
	https_port	443
	http_port	80
	debug
	email user@mydomain.net
}
(geofilter) {
		@mygeofilter {
			  maxmind_geolocation {
			  db_path "/data/GeoLite2-Country.mmdb"
			  allow_countries US
			}
		}
}
auth.mydomain.net {
	import geofilter
    log {
        output file /data/access.log
    }
	route  {
		auth_portal {
			path /
			cookie_domain mydomain.net
			backends {
				local_backend {
					method local
					path /config/caddy/users.json
					realm local
					require mfa
				}
			}
			jwt {
				token_name access_token
				token_secret <redacted>
				token_lifetime 86400
			}
			registration {
				dropbox /config/caddy/registrations_db.json
				title "User Registration"
				code "<redacted>"
				require accept_terms
				require domain_mx
			}
			ui {
				links {
					"My Identity" "/auth/whoami" icon "las la-star"
					"My Settings" "/auth/settings" icon "las la-cog"
					}
				}
		}
	}
}
main.mydomain.net {
	import geofilter
	route / {
		jwt {
			primary yes
			trusted_tokens {
				static_secret {
					token_name access_token
					token_secret <redacted>
				}
			}
			auth_url https://auth.mydomain.net
			allow roles anonymous guest admin
			allow roles superadmin
		}
		reverse_proxy @mygeofilter 192.168.1.157:80
	}
}
```

**Comment by samcro1967** [comment]
@greenpau Not sure what this tells me (other than it is not an issue with subdomains), but I tried to serve a static web page, and I get the same behavior.   There are no errors present in caddy logs or browser consoles (Chrome or Firefox).  Tried clearing browser cache.  Also tried both browsers from 2 different clients (Windows 10 and Ubuntu).  The only pattern I seem to be able to get working is reverse_proxy to services that support a base URL.

**Outside of caddy-auth-proxy works fine**
```
http://local.goaccess {
	root * /srv/report
	file_server
        tls internal
}
```

**Inside of caddy-auth-proxy loads blank page (with or without jwt)**
```
/goaccess* {
	route {
		jwt
		file_server {
			root /srv/report
		}
	}
}
```

**Comment by samcro1967** [comment]
@greenpau I followed the article below and got further.  Adding the sso snippet and putting the order lines in my global block now has jwt for non primary subdomains working correctly.

[Single Sign On (SSO) with subdomains using Caddy v2](https://dev.to/shu8/single-sign-on-sso-with-subdomains-using-caddy-v2-l2i)

The service where jwt is primary still does not work.  The only line different between the sso snippet and the service where jwt is primary is the line "primary yes".  I even copied the sso snippet to the primary instance and added that line to make sure I did not have a typo somewhere I was not seeing.

Not sure why the primary instance is not working, but is seems one of 2 things fixed it for non primary subdomains:
1.  Adding adding order to the global block 
2.  Specifying the entire jwt config less "primary yes" for the non primary subdomain rather than just jwt.

**Comment by samcro1967** [comment]
@greenpau I got the primary JWT instance working.  I had jwt and the reverse_proxy in a route block.  Removing them from the route block solved it.  Not sure why, but it did.  Probably something I missed in the docs or just did not understand properly.  Appreciate your help and loving the SSO.

**Comment by greenpau** [comment]
> @greenpau I got the primary JWT instance working. I had jwt and the reverse_proxy in a route block. Removing them from the route block solved it. Not sure why, but it did. Probably something I missed in the docs or just did not understand properly. Appreciate your help and loving the SSO.

@samcro1967 , the most important thing here is that you get a chance to learn and experiment. You did really well by not giving up on it! 👍 

> Removing them from the route block solved it.

I think getting to "why" is important! Join https://caddy.community/
