### ISSUE TITLE
feature: add microsoft authentication MFA to local auth

### ISSUE THREAD

**Issue by greenpau** [greenpau/caddy-auth-portal#13]
Microsoft Authenticator: https://www.microsoft.com/en-us/account/authenticator

<img src="https://raw.githubusercontent.com/greenpau/caddy-auth-portal/main/assets/docs/images/mfa_ms_auth_add_account.png">

<img src="https://raw.githubusercontent.com/greenpau/caddy-auth-portal/main/assets/docs/images/mfa_ms_auth_scan_qrcode.png">

<img src="https://raw.githubusercontent.com/greenpau/caddy-auth-portal/main/assets/docs/images/mfa_ms_auth_add_manually.png">

**Comment by jumanjiman** [comment]
@greenpau 

https://www.w3.org/TR/webauthn/ may be of interest for this.

PyPI uses it for a seamless experience.

1. I registered for a PyPI account and elected to add MFA
1. It showed me a QR code
1. I scanned the QR code with my preferred MFA app
1. PyPI magically recognized my MFA provider and associated it to my account

PyPI uses https://www.w3.org/TR/webauthn/

**Comment by greenpau** [comment]
Future MFA prompt for UI.

![image](https://user-images.githubusercontent.com/3826416/83800434-6c810280-a675-11ea-9f77-5badfda9285f.png)

**Comment by greenpau** [comment]
Additionally, FIDO2: https://fidoalliance.org/specifications/

The FIDO Alliance has published three sets of specifications for simpler, stronger authentication:

* FIDO Universal Second Factor (FIDO U2F)
* FIDO Universal Authentication Framework (FIDO UAF) and
* the Client to Authenticator Protocols (CTAP). It is complementary to the W3C’s Web Authentication (WebAuthn) specification; together, they are known as FIDO2.

**Comment by greenpau** [comment]
Opened #36 . Currently working on QR code for the registration.

![image](https://user-images.githubusercontent.com/3826416/93720852-e02e1900-fb59-11ea-962d-03b7058b15da.png)

**Comment by greenpau** [comment]
The registration code is working: 

![image](https://user-images.githubusercontent.com/3826416/97456737-83b7d980-190f-11eb-8fdf-d4b22ece2e64.png)

**Comment by xombiemp** [comment]
@greenpau I have attempted to configure MFA out of curiosity to see if it would work.  When I enter the codes from my auth app and then click Add Token, the page seems to refresh and MFA is not enabled.  Is this feature a work in progress still? Or should this be working?

**Comment by greenpau** [comment]
@xombiemp , it is still WIP. I am trying to find some time to implement it. Will ping you when it is ready.

**Comment by greenpau** [comment]
@xombiemp , at the moment, you will be able to add a token to Authentication App on your phone. However, the backend of the auth portal is not wired. Perhaps, your note here is the push for me to deliver it :-)

**Comment by xombiemp** [comment]
@greenpau ok, no problem. Was just curious. No rush. :)

**Comment by greenpau** [comment]
... back to making this work :-)

**Comment by greenpau** [comment]
Able adding app tokens. Next step is adding token test screen.

![image](https://user-images.githubusercontent.com/3826416/101271041-366c2a80-374d-11eb-81d4-e7a18296cfcc.png)

**Comment by greenpau** [comment]
I added a materialize CSS card to hold the contents of a token. The "Delete" button works. In progress - "Test" button.

![image](https://user-images.githubusercontent.com/3826416/101289981-99050b00-37cd-11eb-94c9-cc1e5e75c2ff.png)

**Comment by greenpau** [comment]
@jumanjiman , @xombiemp , if you have a moment, I just released [v1.3.4](https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.3.4). It has the functionality to add a token and test it.

Once you add a token, please click "TEST":

![image](https://user-images.githubusercontent.com/3826416/101298161-a2f13300-37fa-11eb-96a2-f0d2516c0260.png)

After a successful validation, you should see a message.

![image](https://user-images.githubusercontent.com/3826416/101298218-e2b81a80-37fa-11eb-9318-45ff464826f3.png)

Please report the application that worked for you.

If all goes well, I will be integrating MFA auth next week.

**Comment by xombiemp** [comment]
@greenpau 
I just tested it and it worked! I was able to add the MFA device and then successfully validate the code.

**Comment by greenpau** [comment]
>  I just tested it and it worked! I was able to add the MFA device and then successfully validate the code.

@xombiemp , thank you for testing! We are one step closer to having MFA protected logins :-)

**Comment by greenpau** [comment]
@xombiemp , which app or apps did you use?

**Comment by xombiemp** [comment]
@greenpau I used OTP Auth on iOS.

**Comment by greenpau** [comment]
currently, I am working on U2F Registration ... a bit delayed in terms of progress.

**Comment by pemontto** [comment]
Adding comment here for interest. I've added and tested tokens with Google authenticator and 1Password. Hoping to be able to enforce the use/registration of MFA for users.

**Comment by greenpau** [comment]
> Adding comment here for interest. I've added and tested tokens with Google authenticator and 1Password. Hoping to be able to enforce the use/registration of MFA for users.

@pemontto , I am working on webauthn at the moment. Once finished, I would move to the creation of UI interface for token prompting. In sum, will keep you posted!

**Comment by eliaharm** [comment]
Hello, thank you for that very nice plugin and all the features.
Will you also add some method for resetting MFA if a user looses his device or etc?

**Comment by greenpau** [comment]
>  Will you also add some method for resetting MFA if a user looses his device or etc?

@eliaharm , yes. Currently, I am working to get the WebAuthn going. It is my priority.

**Comment by pohlt** [comment]
@greenpau Thanks for your hard work! MFA handling works for me (using Bitwarden).

Two comments / questions:
* Currently, the login portal does not ask for the MFA. This is still WIP, right?
* You decided to use a very long secret. In some corner cases, it might be necessary for the user to type in the secret (because the app on the phone does not support copying or scanning QR codes or ...). A random string of about ten characters is virtually impossible to guess or brute-force attack, so I would prefer a much shorter secret. What are your thoughts?

**Comment by greenpau** [comment]
> Currently, the login portal does not ask for the MFA. This is still WIP, right?

Yes, it is. I need to finish webauthn prior to building MFA prompts.

> You decided to use a very long secret. In some corner cases, it might be necessary for the user to type in the secret (because the app on the phone does not support copying or scanning QR codes or ...). A random string of about ten characters is virtually impossible to guess or brute-force attack, so I would prefer a much shorter secret. What are your thoughts?

I will think about adding an option on a page to allow for shorter shared key. There will be some toggle to do it.

**Comment by tgelite** [comment]
(Note that setup test with google authenticator worked too)

**Comment by bigbydesign** [comment]
I am wondering if it is possible to just setup your plugin to do MFA. The setup constraint would be that I want to have users use the Microsoft o365 authenticator code for their account to allow the proxies requests to complete. If this is not possible, can one authentication allow the JWT token for multiple sites? i.e. I authenticate to the portal and now I have access to 5 sites on caddy? Forgive me for my ignorance.

**Comment by greenpau** [comment]
@bigbydesign , great question! Please open a separate issue for that and delete your comment from here. I will answer your question in a separate issue.

**Comment by greenpau** [comment]
fyi, working through UI design.

## Users **with** 2nd factor configured

Upon successful authentication of a user with MFA-enabled, the plugin will not issue JWT token. Rather, it will create one time `sandbox_id` and store it in Sandbox cache. The cache store maps the `sandbox_id` with a user identity. The `sandbox_id` can only be used once. Next, the plugin redirects the user to a sandbox page `/auth/sandbox/<sandbox_id>`.

The plugin detects the landing to the page and the use of the `sandbox_id`. The plugin locks the `<sandbox_id>` entry in the cache and prevents serving the page with that `<sandbox_id>` again. The plugin considers the `<sandbox_id>` being **inUse**.

The user gets presented with the following screen. Purposefully want the two choices so not to let a clue as to which method being configured to a potential attacker.

![image](https://user-images.githubusercontent.com/3826416/107875258-d8ff0300-6e8c-11eb-89fb-2ca33457f445.png)

The two links redirect to different pages:
* Authenticator App: `/auth/sandbox/<sandbox_id>/app`
* Hardware Token: `/auth/sandbox/<sandbox_id>/u2f`

There links are also one time use. Each link presents a form with an appropriate authentication method.
* Authenticator App: web form with digit input
* Hardware Token: webauthn javascript 

## Users **without** 2nd factor configured

In this case, a user get presented with slightly different screen. It will say:

"Your session requires multi-factor authentication. However, you don't have second factor authentication method configured. Please configure one of the authentication methods below"

The two links redirect to different pages:
* Authenticator App: `/auth/sandbox/<sandbox_id>/add-app`
* Hardware Token: `/auth/sandbox/<sandbox_id>/add-u2f`

... to be continued ...

**Comment by bigbydesign** [comment]
Paul,

This is really great. I like this concept.

-Andy

**Comment by greenpau** [comment]
The App Authenticator screen follows. Will try adding U2F authentication screen by EOW.

![image](https://user-images.githubusercontent.com/3826416/108171772-04bafc80-70ca-11eb-9647-f6137539db19.png)

**Comment by akvadrako** [comment]
I tested the MFA login on main branch with Bitwarden and it seems to be working well.

**Comment by greenpau** [comment]
> I tested the MFA login on main branch with Bitwarden and it seems to be working well.

@akvadrako , It is incomplete yet :-) it works in a limiting fashion :-)

**Comment by greenpau** [comment]
> You decided to use a very long secret. In some corner cases, it might be necessary for the user to type in the secret (because the app on the phone does not support copying or scanning QR codes or ...). A random string of about ten characters is virtually impossible to guess or brute-force attack, so I would prefer a much shorter secret. What are your thoughts?

@pohlt , here is what I implemented. A user may click "here" and change the default token secret.

![image](https://user-images.githubusercontent.com/3826416/110384396-9368cc80-802b-11eb-804e-f6e8414bf7f8.png)


![image](https://user-images.githubusercontent.com/3826416/110384325-76cc9480-802b-11eb-92a1-0fa6fbbef4fd.png)

**Comment by pohlt** [comment]
Awesome! Thanks for considering my comment. 🙏
________________________________

**Comment by greenpau** [comment]
This is complete.
