### ISSUE TITLE
MFA login failure after switching DNS providers

### ISSUE THREAD

**Issue by samcro1967** [greenpau/caddy-auth-portal#132]
**Describe the issue**
Unable to lgoin with MFA after switching DNS providers

**A clear and concise description of what the issue is.**
I switched from using Godaddy as my DNS provider to DuckDNS.  When require MFA is enabled, I receive a login failure.  Everything works as expected when it disabled.

**Configuration**

Paste full `Caddyfile` below:

```
{
	https_port	443
	http_port	80
	order jwt before reverse_proxy
    order auth_portal before jwt
	email samcro1967@mydomain.net
	debug
	log {
		output file /data/access.log
        format json
    }
}
(geofilter) {
		@mygeofilter {
			  maxmind_geolocation {
			  db_path "/data/GeoLite2-Country.mmdb"
			  allow_countries US
			}
		}
}
(sso) {
	jwt {
        trusted_tokens {
            status_secret {
                token_name access_token
                token_secret <redacted>
            }
        }
        auth_url https://auth.samcro1967.duckdns.org
		allow roles anonymous guest admin
		allow roles superadmin
    }
}
auth.samcro1967.duckdns.org {
	import geofilter
	route {
		auth_portal {
			path /
			cookie_domain samcro1967.duckdns.org
			backends {
				local_backend {
					method local
					path /config/caddy/users.json
					realm local
				}
			}
			jwt {
				token_name access_token
				token_secret <redacted>
				token_lifetime 86400
			}
			registration {
				dropbox /config/caddy/registrations_db.json
				title "User Registration"
				code <redacted>
				require accept_terms
				require domain_mx
			}
			ui {
				links {
					"My Identity" "/whoami" icon "las la-star"
					"My Settings" "/settings" icon "las la-cog"
				}
			}
		}
	}
	route {
		redir https://{hostport}/login/ 302
	}
}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
/srv # caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.4.0
http.authentication.hashes.scrypt v2.4.0
http.authentication.providers.http_basic v2.4.0
http.handlers.authentication v2.4.0
http.authentication.providers.jwt v1.2.7
http.handlers.auth_portal v1.4.6
/srv #
```

**Expected behavior**

Able to login with MFA enabled.

**Additional context**

I am able to login via Firefox, but not Chrome or Safari.  Tried clearing browser cache and Delete domain security policies.  Also removed users.json and recreated from scratch.  Tried removing the MFA from the user and re-adding it.  Chrome works in in incognito mode.  I am also able to test the MFA in the Settings page and it works fine.

I see the cookie in the browser with this error message.
```
auth:1 POST https://auth.samcro1967.duckdns.org/sandbox/l5b904prnu2m6kx9scxnm3x2wfdsrlb59xwyg5ll8ku1sv9z2pmjsqzbt3lohyn5qqw78sjhvssv5w6ttforayrapy7k5w/app/auth 401
```

Seems like a browser thing, but clearing the cache did not resolve it.  Not sure where else to look.

**Comment by samcro1967** [comment]
I am now able to login with Edge, Firefox and Safari.  Seems like once the token expired after 24 hours those started working.  Not sure why clearing the browser cache did not make them work right away.  Chrome is still not working unless I am in Incognito mode.  When I compare the browser consoles in normal mode vs. incognito, I see the access_token cookie in incognito mode, but not normal mode.

I tried removing the container and recreating to rule out the access_token cookie being stored locally in the container.  I looked through the caddy volume mounts and I do not see anything that looks like it is the cookie file.  Also cleared the local temp directory.  Not sure where it is being stored, but it does not appear to be in the browser cache, temp folder, the container, or any of the volume mounts.  Also rebooted just to rule out it being stored in memory somewhere.

There seems to be 2 issues.  One is where the access_token is being stored.  It does not appear to be in the browser cache as clearing Chrome, Edge, Firefox, or Safari solved it.  Only time for the cookie to expire solved it for Edge, FireFox, and Safari.

The other issues seems to be Chrome specific.  I think when I first logged in that I did not have a cookie lifetime set so it is not expiring.

@greenpau Is there a way to force the cookie to be stored say in the caddy config directory so that it will create new one?

**Comment by samcro1967** [comment]
Interestingly enough, removing Chrome and reinstalling it allows it to work once.  After logout and attempting to log back in the problem happens again.  Perhaps a bug with Chrome Version 91.0.4472.101 (Official Build) (64-bit).  Everything is working with Firefox, Edge, and Safari.

**Comment by samcro1967** [comment]
I turned on Chrome logging.  It appears Google Safebrowsing is blocking mfa from working.  I see it in the logs in normal mode, but not incognito mode.  If I disable it, it works fine in normal mode.  My site does shows up as safe in the Google
Transparency Report so not sure why it is being blocked, but appears to have started after I switched to DuckDNS.  Perhaps Google has some blanket rule to block all DuckDNS traffic for certain things???

Have not found a way yet to add my site as a safe site in Chrome so I do not need to disable safebrowsing or run in incognito mode all the time.

**Comment by samcro1967** [comment]
Closing this issue.  Had to submit a request to Google to be removed from Safe Browsing and it is working now.

2 things I might suggest:
1.  If possible, capture Chrome/Google Safe Browsing stopping the login and post a message other than failed login.
2.  Provide a way to delete previously issued tokens so as to not have to wait for them to expire.

**Comment by greenpau** [comment]
> Provide a way to delete previously issued tokens so as to not have to wait for them to expire

@samcro1967 , will have it in the next release.
