### ISSUE TITLE
route /auth* mess up if a hash sign is used in url

### ISSUE THREAD

**Issue by akzkak** [greenpau/caddy-auth-portal#133]
A PrivateBin url looks like this and always have a # sign in the url
https://privatebin.net/?8132015d33f2dcac#EqRtDrbmAr1zYAagpXz5Muz5bs7rzPd7wVemGXWGKDAT

I have it self-hosted and setup auth login page, but results in:

original url: example.com/?7cc67fc6c545fe8e#Cf3dcZgvYWwqapcvPTZ6Xmyggt1PeiT1GMoiLJFUuLnC
on login page: example.com/auth#Cf3dcZgvYWwqapcvPTZ6Xmyggt1PeiT1GMoiLJFUuLnC
after login: example.com/?7cc67fc6c545fe8e

No idea if regex magic can solve this problem, or its a caddy-auth-portal thing.

**Comment by greenpau** [comment]
@akzkak , did you look into “js redirect”? It is used in the cases of pound sign in url path.

**Comment by akzkak** [comment]
Ah i see. Just found on caddy-auth-jwt front page.  Followed setup guide from here:
https://lucaci32u4.xyz/blog/2021/mainsail-gateway.html

edited in enable js redirect.

    jwt {
      primary yes
      enable js redirect
...

but no matter where i put the line it errors on Caddy reload.  "Error during parsing: unsupported directive for enable: js redirect"

**Comment by greenpau** [comment]
@akzkak , please wait until next week. I am going to release new versions of plugins. The reason  you are getting errors is because this feature will be  available only in the new release.
