### ISSUE TITLE
Proper JSON configuration for 2fa in local authentication configuration.

### ISSUE THREAD

**Issue by tgelite** [greenpau/caddy-auth-portal#134]
**Describe the issue**

I have a question on documenting the proper JSON configuration format for 2fa under the parent "backends": {} entry

**Configuration**

Paste full `Caddyfile` below:
Sorry the full json file is _massive_, I believe this is the specific section below is what we SHOULD be targeting to configure from our already working config (will attach full config as zip if needed)

After looking at the "caddy validate --config /path/to/our/config.json" appears that "require_mfa": is the proper key to be providing a `true` value to like so (note realm is unique as well due to collisions across multiple instances in google authenticator)

```
  "backends": [
    {
      "method": "local",
      "name": "local_backend",
      "path": "/opt/caddy/auth/user_db.json",
      "realm": "local-[uniquename]",
      "require_mfa": true 
     }
                                            ],
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
 $ caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.4.1
http.authentication.hashes.scrypt v2.4.1
http.authentication.providers.http_basic v2.4.1
http.handlers.authentication v2.4.1
http.authentication.providers.jwt v1.2.7
http.handlers.auth_portal v1.4.6
```

**Expected behavior**

I'm just verifying how to document proper configuration json form and propose submitting a documentation update! (do branch/pull and update of docs after testing to help if needed.

**Additional context**

Great Toolset, thanks for building and improving this awesome plugin!

**Comment by tgelite** [comment]
Hmm, I have some config checking to do and customized template and possibly CSS updating.  Testing with my proposed config ends up in a weird place on new registration and re-enforcing 2fa on login flows, even tho the config seems to be correct.   I'll open again when I've got this working to talk about docs contrib.

**Comment by greenpau** [comment]
@tgelite , exactly for that reason, in the upcoming release, I have separated configs from actual backends. Wait to digging into the code, because lots of changes coming very soon.

https://github.com/greenpau/caddy-auth-portal/blob/1db7d209abeb0ef2dd71e085ebf64b15fe29f342/pkg/backends/backend.go#L48
