### ISSUE TITLE
Please consider create a new release so it's compatible with newer caddy-auth-jwt

### ISSUE THREAD

**Issue by caiych** [greenpau/caddy-auth-portal#138]
**Describe the issue**

xcaddy failed to build with default versions.

```
xcaddy build     --with github.com/greenpau/caddy-auth-jwt     --with github.com/greenpau/caddy-auth-portal     --with github.com/caddy-dns/cloudflare
```

**Configuration**

Paste full `Caddyfile` below:

```
N/A
this is a build issue
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
github.com/greenpau/caddy-auth-portal v1.4.6
github.com/greenpau/caddy-auth-jwt v1.3.2
```

**Expected behavior**

xcaddy should build successfully w/ default versioning.

**Additional context**

You can check the xcaddy build log in this CI run:

https://github.com/caiych/caiych-caddy/runs/2847981323?check_suite_focus=true#step:9:282

**Comment by caiych** [comment]
Sorry I didn't find issue related to this(with keyword xcaddy) in this repository.

I know I can specify version in xcaddy(and I'm doing that), but IMO that's a work around but not something permanent.

The situation is worse on caddy download page where (I think) people don't normally specify a version(and the error message isn't telling them they should be setting a version and the error will go away)

![image](https://user-images.githubusercontent.com/2850650/122675382-afbffc00-d20b-11eb-9fab-ed344e2c8874.png)


Thanks.

**Comment by animosity22** [comment]
I've been looking for the last few days to figure out to build and I've tried a few things with no success. If you find a version combo that allows you to build, please share.

**Comment by caiych** [comment]
@animosity22 

github.com/greenpau/caddy-auth-portal@1.4.6   # <- current latest
github.com/greenpau/caddy-auth-jwt@v1.2.7

Worked for me.

**Comment by animosity22** [comment]
I get this unless I'm doing something incorrectly (which very well could be)

![image](https://user-images.githubusercontent.com/5088712/122681514-9fcffa00-d1c2-11eb-8c80-d41f05fe810c.png)

**Comment by caiych** [comment]
@animosity22 You have to specify the version as v1.2.7 -- note the "v"

**Comment by animosity22** [comment]
Same thing with the v:

![image](https://user-images.githubusercontent.com/5088712/122692421-ecd3c080-d202-11eb-89cf-95f800b2135e.png)

**Comment by caiych** [comment]
@animosity22 Sorry I couldn't spot anything different between your setup with mine -- I just tested again and it still works.

**Comment by animosity22** [comment]
No worries. Just for insanity, I tried again and it worked so if I didn't actually take a screenshot, I wouldn't believe myself. Thanks for the help.

**Comment by greenpau** [comment]
@caiych , it is in works.

**Comment by greenpau** [comment]
@caiych , the new release is out.
