### ISSUE TITLE
Section "Authorization Cookie" README is not up to date

### ISSUE THREAD

**Issue by fdarveau** [greenpau/caddy-auth-portal#141]
**Describe the issue**

Due to the `caddy-auth-jwt` update, the information in the section "Authorization Cookie" of the README is now invalid.

**Configuration**

Paste full `Caddyfile` below:

Not relevant

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

By looking at the changelogs : since 1.4.9

```
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.8
http.handlers.authp v1.4.10
```

**Expected behavior**

README is up to date.

**Additional context**

None

**Comment by greenpau** [comment]
@fdarveau , will fix it! Thank you for the issue! Please paste your config file and I will convert it to the new syntax.

**Comment by fdarveau** [comment]
Thanks for the offer!

I have already updated the `jwt` part in my routes/domains, but the token lifetime and secret are causing me issues. I have commented them out for now since it works, except I have to re-authenticate much more often.

```
authp {
    cookie domain [redacted]
    backends {
	    local_backend {
		    method local
		    path [redacted]
		    realm local
	    }
    }
    jwt {
		         token_name access_token
		         token_secret [redacted]
		         token_lifetime 3600
    }
    ui {
	    links {
		    [redacted]
	    }
    }
}

route /primary {
    jwt {
        primary yes
        allow roles admin superadmin
        set auth url [redacted]
    }
}
```

I have also noticed I lost access to the settings page :
![image](https://user-images.githubusercontent.com/6851146/123559767-17c29500-d76c-11eb-8bb9-c0fe2f9f4a7f.png)

Here is the result of the `whoami` :
```
{
  "addr": "[redacted]",
  "authenticated": true,
  "exp": 1624829658,
  "expires_at_utc": "Sun Jun 27 21:34:18 UTC 2021",
  "iat": 1624828758,
  "iss": "[redacted]",
  "issued_at_utc": "Sun Jun 27 21:19:18 UTC 2021",
  "jti": "[redacted]",
  "mail": "[redacted]",
  "nbf": 1624828698,
  "not_before_utc": "Sun Jun 27 21:18:18 UTC 2021",
  "origin": "local",
  "roles": [
    "superadmin",
    "authp/guest"
  ],
  "sub": "[redacted]"
}
```

I think it might be because of the `authp/guest` role, but that role is not in my `users.json` file :
![image](https://user-images.githubusercontent.com/6851146/123559808-57897c80-d76c-11eb-84d5-42685301670f.png)

**Comment by greenpau** [comment]
@fdarveau , here is what you need to do.

Remove the following section from `authp`.

```
    jwt {
		         token_name access_token
		         token_secret [redacted]
		         token_lifetime 3600
    }
```

If you never specify token info in the config, the plugin would auto-generate ECDSA keys for you.
See how it is done here: https://github.com/greenpau/caddy-auth-portal/issues/140#issuecomment-868145150

Provided you run all on a standalone server, you should be ok!

Next, the default roles are as follows:

* `authp/admin`: no limits.
* `authp/user`: can access settings
* `authp/guest`: can access portal only

So change the roles in your database file.

**Comment by greenpau** [comment]
@fdarveau, updated [Authorization Cookie](https://github.com/greenpau/caddy-auth-portal#authorization-cookie) section.

**Comment by fdarveau** [comment]
Thanks! Everything is now working just like before I updated to the latest version.

**Comment by greenpau** [comment]
@fdarveau , awesome! 👍
