### ISSUE TITLE
User role addition on google_oauth2_backend throws an error

### ISSUE THREAD

**Issue by jaysonsantos** [greenpau/caddy-auth-portal#143]
**Describe the issue**

Hey there, first, thanks for this project :).
I was using `google_oauth2_backend` in order to authenticate to my caddy install but after upgrading from 1.4.6 to 1.4.11 it started to break saying that ` Error during pasing: auth backend google_oauth2_backend subdirective user is unsupported `

**Configuration**

Paste full `Caddyfile` below:

```
:9999 {
  log {
    output stderr
    level debug
  }
  route /login* {
    authp {
      backends {
        local_backend {
          method local
          path /users.json
          realm local
        }
        google_oauth2_backend {
          method oauth2
          realm google
          provider google
          client_id {$GOOGLE_CLIENT_ID}
          client_secret {$GOOGLE_CLIENT_SECRET}
          scopes openid email profile

          user myemail@gmail.com add role user
        }
      }
      jwt {
        token_name access_token
        token_secret {$JWT_SECRET}
      }
    }
  }

  route /grafana* {
    jwt {
      primary yes
      trusted_tokens {
        static_secret {
          token_name access_token
          token_secret {$JWT_SECRET}
        }
      }
      auth_url /login
      allow roles superadmin
      allow roles user
    }
    reverse_proxy http://grafana.monitoring.cluster.svc.local:8000
  }

  route /prometheus* {
    jwt {
      allow roles superadmin
    }
    uri strip_prefix /prometheus
    reverse_proxy http://prometheus-kube-prometheus-prometheus.monitoring.cluster.svc.local:9090
  }

  route /* {
    jwt
    file_server browse {
      root /data/
    }
  }
}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
docker run --rm -it jaysonsantos/caddy-with-auth caddy list-modules --versions | grep auth
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.10
http.handlers.authp v1.4.12
```

**Expected behavior**

Caddy should still spin up

**Additional context**
Error message:
```
{"level":"info","ts":1624955157.7229333,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
run: adapting config using caddyfile: parsing caddyfile tokens for 'route': /Caddyfile:42 - Error during parsing: parsing caddyfile tokens for 'authp': /Caddyfile:9 - Error during parsing: auth backend backends directive failed: backend config map[name:transform] error: auth method not found
```

**Comment by greenpau** [comment]
@jaysonsantos , will post a replacement config today.

**Comment by greenpau** [comment]
@jaysonsantos , try this:

```
:9999 {
  log {
    output stderr
    level debug
  }
  route /xauth* {
    authp {
      backends {
        local_backend {
          method local
          path /users.json
          realm local
        }
        google_oauth2_backend {
          method oauth2
          realm google
          provider google
          client_id {$GOOGLE_CLIENT_ID}
          client_secret {$GOOGLE_CLIENT_SECRET}
          scopes openid email profile
        }
      }
      crypto default token lifetime 3600
      crypto key sign-verify {$JWT_SECRET}
      enable source ip tracking
      transform user {
        match email myemail@gmail.com
        action add role authp/user
      }
      transform user {
        match email adminemail@gmail.com
        action add role authp/admin
      }
    }
  }

  route /grafana* {
    jwt {
      primary yes
      crypto key verify {$JWT_SECRET}
      set auth url /xauth
      allow roles authp/admin authp/user
    }
    reverse_proxy http://grafana.monitoring.cluster.svc.local:8000
  }

  route /prometheus* {
    jwt {
      allow roles authp/admin
    }
    uri strip_prefix /prometheus
    reverse_proxy http://prometheus-kube-prometheus-prometheus.monitoring.cluster.svc.local:9090
  }

  route {
    jwt
    file_server browse {
      root /data/
    }
  }
}
```

Also, attached please see config diff.
[config_diff.pdf](https://github.com/greenpau/caddy-auth-portal/files/6733505/config_diff.pdf)

**Comment by jaysonsantos** [comment]
Hey there @greenpau it seems to wokr up to a certain point but it fails with an error pointing here [1].
And the error is as follows  `run: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 2: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subro ││ ute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'authp': provis ││ ion http.handlers.authp: transformer has no matchers: &{[] [email myemail@gmail.com add role authp/admin]`
[1] https://github.com/greenpau/caddy-auth-portal/blob/b020fa44ba895cd29f36478cbe00fd98a4ff93e6/pkg/transformer/transformer.go#L54

**Comment by greenpau** [comment]
@jaysonsantos , what is the status now? yes, try `exact match email adminemail@gmail.com`.

Will have to add login to prepend `exact` when the first thing keyword is `match`.

**Comment by jaysonsantos** [comment]
it works but i had to force the auth url to `/auth*` otherwise it would try to serve `/assets` instead of `/auth/assets*` but it seems all good anyway :)

**Comment by greenpau** [comment]
> it works but i had to force the auth url to /auth* otherwise it would try to serve /assets instead of /auth/assets* but it seems all good anyway :)

@jaysonsantos, reopening it. This is a bug and I will fix it.

**Comment by greenpau** [comment]
> it works but i had to force the auth url to /auth* otherwise it would try to serve /assets instead of /auth/assets* but it seems all good anyway :)

@jaysonsantos , what is the path that had the issue with assets? Is it `https://SERVER:PORT/login`?

**Comment by jaysonsantos** [comment]
that is the one, i'll try and come up with small caddyfile to reproduce it

**Comment by greenpau** [comment]
> that is the one

@jaysonsantos , the `/login` is not a good service endpoint, because it matches the `login` endpoint.

https://github.com/greenpau/caddy-auth-portal/blob/65e7d665214ad77a736159460b8d932e5cdd0c39/pkg/authn/respond_http.go#L32-L63

That's why I suggested serving it from `/xauth` (or you could use `/authp`).

**Comment by jaysonsantos** [comment]
Hey @greenpau it is ok, I just changed to authp as you said and it worked fine
