### ISSUE TITLE
Config update

### ISSUE THREAD

**Issue by xombiemp** [greenpau/caddy-auth-portal#145]
**Describe the issue**

There have been a lot of changes! I just updated Caddy and the plugins and Caddy won't start now. Can you help me convert my config to the newer directives? I'm trying to get the most concise config possible.

**Configuration**

Paste full `Caddyfile` below:

```
  route /auth* {
    auth_portal {
      local_backend /etc/caddy/auth/local/users.json
      jwt_token_file 1 /etc/caddy/auth/jwt/jwt_privatekey.pem
      ui {
        links {
          "Tautulli" /tautulli
          "ruTorrent" /rutorrent
          "Sonarr" /sonarr
          "Radarr" /radarr
          "Lidarr" /lidarr
          "Resillio Sync" /sync
        }
      }
    }
  }

  @protected not path /favicon.ico /public* /tautulli/api*
  route @protected {
    jwt {
      primary yes
      user_identity subject
      trusted_public_key 1 /etc/caddy/auth/jwt/jwt_publickey.pem
    }
  }
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.12
http.handlers.authp v1.4.14
```

**Comment by greenpau** [comment]
@xombiemp , will post a replacement shortly.

**Comment by greenpau** [comment]
@xombiemp , are you running it all on the same server?

**Comment by greenpau** [comment]
@xombiemp , try the below and post errors if any
Also, seesing the exceptions to not protected, see “jwt” plugin for “bypass” documentation.

  route /auth* {
    authp {
     backend local /etc/caddy/auth/local/users.json local
      ui {
        links {
          "Tautulli" /tautulli
          "ruTorrent" /rutorrent
          "Sonarr" /sonarr
          "Radarr" /radarr
          "Lidarr" /lidarr
          "Resillio Sync" /sync
        }
      }
    }
  }

  @protected not path /favicon.ico /public* /tautulli/api*
  route @protected {
    jwt {
      primary yes
      set user identity subject
      allow roles authp/guest
    }
  }

**Comment by xombiemp** [comment]
@greenpau Works perfect! Thank you!

**Comment by greenpau** [comment]
@xombiemp , the keys are now autogenerated if non are specified. It is ECDSA (ES512)
