### ISSUE TITLE
Service Unavailable when going to /auth/settings

### ISSUE THREAD

**Issue by sandstormkeshav** [greenpau/caddy-auth-portal#150]
**Describe the issue**

I get a Service Unavailable message from the auth portal when visiting /auth/settings and logged in via oauth with the authp/admin role

**Configuration**

Paste full `Caddyfile` below:

```
*.secure.domain.com {
			route /auth* {
			authp {
				cookie domain .domain.com
				crypto key sign-verify REDACTED
				backends {

					google_oauth2_backend {
						method oauth2
						realm google
						provider google
						client_id REDACTED
						client_secret REDACTED
						scopes openid email profile
						
					}
				}

				transform user {
					exact match email myemail@gmail.com
					action add role authp/admin

				}

			}
		}

		route {
			redir https://{hostport}/auth 302
		}
	}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.13
http.handlers.authp v1.4.17
```

**Expected behavior**

Describe expected behavior.
I am wondering if it expected to receive a Service Unavailable from the auth portal when navigating to the /auth/settings endpoint. Is that because I am already using oauth as opposed to the form based auth?

**Additional context**

I cannot find anything in the logs that say why it is doing this. I have only experienced this after updating to the rewritten plugin. Thank you for your help!

**Comment by greenpau** [comment]
@sandstormkeshav , this is expected behavior, because OAuth2.0 backend does not support settings. The `local` backend has settings. 

Why do you need settings with OAuth2.0?

**Comment by sandstormkeshav** [comment]
Hi @greenpau, you are right, I just wanted to make sure I wasn't missing something. Thank you!
