### ISSUE TITLE
breakfix: User transforms and matches

### ISSUE THREAD

**Issue by lbreitk** [greenpau/caddy-auth-portal#152]
1. it would be nice if there was a document that indicated which fields are and are not supported for matching against, as it seems I can't just try arbitrary fields, I.E. `match authenticated yes` resulted in an error and caddy didn't start.
2. I can't seem to match against any roles. for example, I would like the following to work, and it doesn't:
```
transform user {
  match roles res-caddy-admin
  action add roles authp/admin
  ui link "whoami" /whoami target_blank
}
```
![image](https://user-images.githubusercontent.com/77999616/125710783-4af082b2-d33e-4ff4-8c99-4c8893a40346.png)

**Comment by greenpau** [comment]
@lbreitk , what are the versions of the modules you are using?

**Comment by lbreitk** [comment]
I just downloaded `@latest` yesterday, before testing and opening this issue.

![image](https://user-images.githubusercontent.com/77999616/125826424-45a53903-eb2d-420c-ae89-80671442033e.png)

**Comment by lbreitk** [comment]
@greenpau any ideas?

**Comment by greenpau** [comment]
@lbreitk , will check after work.

**Comment by lbreitk** [comment]
Thanks man! :)

**Comment by greenpau** [comment]
@lbreitk , could you please attach your full config (pastebin works too)?

Also, could you please change to “action add role authp/admin”? (role vs roles)

**Comment by lbreitk** [comment]
Sure. I'm positive I've tried both combinations. I also tried things like matching the email or other claims, some of which worked fine, with the same action item, so I'm thinking it's the matcher, not the action. I'll attach configs when I have a chance

**Comment by greenpau** [comment]
@lbreitk , what comes to mind is whether the token has both "role" and "roles" claims.
