### ISSUE TITLE
question: Microsoft Azure OAuth and send custom claims as header

### ISSUE THREAD

**Issue by joeyaben** [greenpau/caddy-auth-portal#154]
Is it possible to add custom claims to the Azure OAuth backend.

I would like to send the UPN (UserPrincipalName) and group memberships from Azure to Caddy.
Authentication is working fine with the OAuth backend.

But adding custom claims seems not to work, although they are not visible on the whoami page.
```https://auth.domain.example {
  route /auth* {
    authp {
      cookie domain "domain.example"
      backends {
        azure_oauth2_backend {
          method oauth2
          realm azure
          provider azure
          client_id xxx
          client_secret xxx
          scopes openid email profile
        }
```

I tried to add UPN to Azure and then replace email with UPN in the scopes openid command.
But this occured in an authentication error.

I'm looking for a solution to receive the user UPN by Caddy and insert this command as custom header to a backend application.

`inject headers with claims`

Is working for inserting the email address of the user, but this does not always match with external systems for authentication.

` inject header "X-UserName" from email`

Didn't insert anything.

The next step is to receive group memberships from Azure to implement an ACL.

Full Caddy file:
```
https://auth.domain.example {
  route /auth* {
    authp {
      cookie domain "domain.example"
      backends {
        azure_oauth2_backend {
          method oauth2
          realm azure
          provider azure
          client_id xxx
          client_secret xxx
          scopes openid email profile
        }
}      
	 transform user {
        regex match email ^.*@domain.example$
        exact match origin azure
        action add role user
        }

    }
  }
  route /placeholder {
	jwt {
      primary yes
      set auth url https://auth.domain.example/auth/oauth2/azure
      allow role user
        validate bearer header
inject headers with claims
    }
    respond "Nothing to see here, {http.request.header.X-Token-User-Name}!"
  }
  route {
    # Avoid a blank white page, send the user somwhere useful
    redir /auth/whoami 302
  }
}

https://app1.domain.example {
        route  {
                jwt {
                acl rule {
        match role user
        allow stop log error
#       deny log error
}
}
                reverse_proxy 192.168.1.1:80
        }

        
}
```
Is this possible with the OAuth backend, or do I need to switch to SAML backend. I need support for multi-tenant authentication.

**Comment by greenpau** [comment]
@joeyaben , I did not experiment with it. I might be possible to extend the plugin to accomplish what you need. However, I don't have access to Azure LDAP instance. If you setup one for me, then I will be able to help you.

**Comment by greenpau** [comment]
@joeyaben , please reopen in [github.com/greenpau/caddy-security](https://github.com/greenpau/caddy-security/issues/new/choose) if this is still relevant for you. Please consider sponsoring the work on the project! 👍
