### ISSUE TITLE
caddy adapt not accepting a Caddyfile with ui { custom_css_path } config present 

### ISSUE THREAD

**Issue by tgelite** [greenpau/caddy-auth-portal#155]
**Describe the issue**
The custom_css_path directive for the ui {} configuration does not appear to be "legal" when converting to config.json format.

In performing upgrade and testing; When attempting to use "caddy adapt" to modify a Caddyfile configuration to a config.json, the adapt command fails with the following:

```
$ caddy adapt -pretty -config ./Caddyfile > config.json
adapt: parsing caddyfile tokens for 'route': ./Caddyfile:45 - Error during parsing: parsing caddyfile tokens for 'authp': ./Caddyfile:31 - Error during parsing: unsupported subdirective for ui: custom_css_path
```

**Configuration**

Paste full `Caddyfile` below:

```
https://10.252.252.21, https://10.1.1.216 {
        log {
                level INFO
                format console
                output file /var/log/caddy/caddy.log
        }
        route /auth* {
                authp {
                        backends {
                                local_backend {
                                        method local
                                        path /opt/caddy/assets/conf/local/auth/user_db.json
                                        realm local
                                }
                        }
                        registration {
                                dropbox /opt/caddy/assets/conf/local/auth/registrations_db.json
                                title "User Registration"
                        }
                        crypto default token lifetime 21600
                        crypto key sign-verify AnExampleSecretKey1234!
                        crypto key token name access_token
                        ui {
                                theme basic
                                template login "/opt/caddy/templates/em20-tmpl/login.template"
                                template generic "/opt/caddy/templates/em20-tmpl/generic.template"
                                template portal "/opt/caddy/templates/em20-tmpl/portal.template"
                                template register "/opt/caddy/templates/em20-tmpl/register.template"
                                template whoami "/opt/caddy/templates/em20-tmpl/whoami.template"
                                template settings "/opt/caddy/templates/em20-tmpl/settings.template"
                                custom_css_path /opt/caddy/css/custom.css
                                static_asset "assets/logo.png" "image/png" "/opt/caddy/templates/em20-tmpl/logo.png"
                                logo_url "assets/logo.png"
                                logo description "Elite Manager"
                                links {
                                "Elite Manager" /
                                        "My Auth Portal Settings" /auth/settings icon "las la-cog" target_blank
                                        "who am i check" /auth/whoami target_blank icon "las la-star"
                                        "Add MFA Authentication App" /auth/settings/mfa/add/app
                                }

                        }
        }
        }
        route /gr/* {
                jwt {
                        inject headers with claims
                }
                reverse_proxy http://localhost:3000
        }
        route /version* {
                respond * "2.0.0-a" 200
        }
        route /ui/* {
                jwt {
                        inject headers with claims
                }
                reverse_proxy http://localhost:1880
        }
        route /* {
               jwt {
                        primary yes
                        crypto key token name access_token
                        crypto key verify AnExampleSecretKey1234!
                        set auth url /auth
                        }
               inject headers with claims
               reverse_proxy http://localhost:1081
        }
}

```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
$ caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.14
http.handlers.authp v1.4.18
```

**Expected behavior**

Given the documentation is indicating that "custom_css_path" is still a valid option ( https://github.com/greenpau/caddy-auth-portal#user-content-custom-css-styles )

**Additional context**

I've tested with both 
`custom_css_path /opt/caddy/css/custom.css`
and
`custom_css_path "/opt/caddy/css/custom.css"`
with the same result. 

Next step as a workaround is going to be where I add this custom CSS setting after performing an "adapt" without it present (as a workaround). 

 I'll also check if the schema being generated by caddy json-schema is showing it as a valid setting (probably not?).

**Comment by tgelite** [comment]
further testing seemed to provide good results: 

`custom_css_path "/opt/caddy/css/custom.css"` needed to be replaced with `custom css_path "/opt/caddy/css/custom.css"`

`logo_url` needed to be replaced with `logo url` to parse

These seemed to fix the caddy adapt processing the Caddyfile.  It might be the docs / examples just need updating, I'll continue to test.

**Comment by dczysz** [comment]
I tried `custom css_path "/opt/caddy/css/custom.css"` as well and it gets past `caddy validate` but errors on `caddy run` with `failed to load asset file css_path /opt/caddy/css/custom.css`, seems like it's trying to load the file `css_path /opt/caddy/css/custom.css`.

Switching to `custom css path "/opt/caddy/css/custom.css"` seems to work.  It's no longer throwing that error for the css file, but I have other errors so I can't get caddy started to fully test that it works.  Although it seems correct based on this:
https://github.com/greenpau/caddy-auth-portal/blob/9008586b7d6a328261a729f70adc2dfac1e25078/caddyfile.go#L464-L465

**Comment by greenpau** [comment]
@dczysz , i am on mobile and can’t type much. Your best bet is caddyfile.go

https://github.com/greenpau/caddy-auth-portal/blob/9008586b7d6a328261a729f70adc2dfac1e25078/caddyfile.go#L460

It should be “custom css path <PATH>”

I tried getting rid of underscores.

**Comment by greenpau** [comment]
@dczysz , what are the other errors?

**Comment by dczysz** [comment]
This is the one I'm stuck on now:
```
caddy[29981]: run: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 5: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'authentication': provision http.handlers.authentication: loading authentication providers: module name 'jwt': provision http.authentication.providers.jwt: jwt-default-000004: configuration error: access list rule config not found
```

**Comment by tgelite** [comment]
Should we close this out and deal with any "other" issues in separate git issue? I think the custom css path issue is resolved by your explanation of dropping _'s, @greenpau.

**Comment by greenpau** [comment]
@tgelite , you need to create a Caddyfile configuration first. Then, run it. caddyserver will create  autosave JSON file. Review the file to see what the syntax should be.

**Comment by tgelite** [comment]
Thank you, we will focus on doing that to pick up the syntax.  Thanks.

**Comment by tgelite** [comment]
Closing issue to start over based on Caddyfile configuration & testing first, then will follow what JSON config is generated, per comment from Paul.  @dczysz We should open up discrete issue after following this setup / config approach.
