### ISSUE TITLE
map[name:crypto] error: auth method not found

### ISSUE THREAD

**Issue by MurrayGroves** [greenpau/caddy-auth-portal#157]
**Describe the issue**

Caddy will not boot, with error `Error during parsing: auth backend backends directive failed: backend config map[name:crypto] error: auth method not found`

**Configuration**

https://pastebin.com/TUzxxkUX

**Version Information**
`
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.14
http.handlers.authp v1.4.18
`

**Additional context**

The problem may actually lie with jwt, as if I add a jwt directive, I get `unsupported root directive: jwt`

**Comment by greenpau** [comment]
@MurrayGroves ,

This config does not look right, because `crypto key` should be defined under `authp`.
Also, you could use [Shortcuts](https://github.com/greenpau/caddy-auth-portal#shortcuts) for the `backends`.

```
media.murraygrov.es:443 {
  route /auth* {
    authp {
      ...
      backends {
        crypto key sign-verify REDACTED
        local_backend {
          method local
          path /home/mediaserver/configs/caddy/users.json
          realm local
        }
      }
```

Try:

```
media.murraygrov.es:443 {
  route /auth* {
    authp {
      ...
      crypto key sign-verify REDACTED
      backend local /home/mediaserver/configs/caddy/users.json local
```

Next, the `jwt` setup is not up to data. 

```
admin.murraygrov.es:443 {
  route {
    jwt {
      forbidden https://hub.murraygrov.es/
      allow roles superadmin
      primary yes
      trusted_tokens {
        static_secret {
          token_name access_token
          token_secret REDACTED
        }
      }
      auth_url https://media.murraygrov.es/auth
    }
```

Try:

```
admin.murraygrov.es:443 {
  route {
    jwt {
      primary yes
      crypto key verify REDACTED
      allow roles superadmin
      set forbidden url https://hub.murraygrov.es/
      set auth url https://media.murraygrov.es/auth
    }
```

Try the above changes and let me know if you running into any issues.

**Comment by greenpau** [comment]
@MurrayGroves, also please  see `jwt` plugin syntax [here](https://github.com/greenpau/caddy-auth-jwt#plugin-syntax).

**Comment by MurrayGroves** [comment]
@greenpau I made the changes you suggested but still have the same problem. I noticed in the syntax guide you sent, it says I should remove the crypto directives for single server deployment. I tried removing them, and get `map[name:backend] error: auth method not found`, notice that crypto is replaced with backend.

**Comment by greenpau** [comment]
@MurrayGroves , please provide the full error you are getting. There will be a reference to a line number in your config.

**Comment by MurrayGroves** [comment]
Line 43.
`run: adapting config using caddyfile: parsing caddyfile tokens for 'route': /home/mediaserver/configs/caddy/Caddyfile:51 - Error during parsing: parsing caddyfile tokens for 'authp': /home/mediaserver/configs/caddy/Caddyfile:43 - Error during parsing: auth backend backends directive failed: backend config map[name:backend] error: auth method not found`

**Comment by greenpau** [comment]
@MurrayGroves , same Caddyfile?

**Comment by MurrayGroves** [comment]
@greenpau this has all been the same Caddyfile.

**Comment by MurrayGroves** [comment]
@greenpau the line numbers are different now though, since I made your changes. [Here](https://pastebin.com/ep0tfUV5) is the updated Caddyfile.

**Comment by greenpau** [comment]
Regarding line 51. You did not execute as I explained.

```
      backends {
        crypto key sign-verify REDACTED
        backend local /home/mediaserver/configs/caddy/users.json local
      }
```

should be:

```
      crypto key sign-verify REDACTED
      backend local /home/mediaserver/configs/caddy/users.json local
```

**Comment by MurrayGroves** [comment]
@greenpau that fixed it. Thanks :)
