### ISSUE TITLE
Map google groups to roles

### ISSUE THREAD

**Issue by silvajp2** [greenpau/caddy-auth-portal#158]
**Describe the issue**

Following this [issue](https://github.com/greenpau/caddy-auth-portal/issues/41) . Is it possible to map google groups to roles?

**Configuration**

Paste full `Caddyfile` below:

```
    :8080 {
      route /auth* {
        authp {

          backends {
            google_oauth2_backend {
              method oauth2
              realm google
              provider google
              client_id XXXXXXXXX
              client_secret XXXXXXXXXX
              scopes openid email profile "https://www.googleapis.com/auth/groups"
            }
          }
          ui {
            links {
              "My Identity" "/auth/whoami" icon "las la-star"
            }
          }
        }
      }
      route /sso/oauth2/google* {
        jwt {
          set auth url /auth/oauth2/google
        }
        respond * "google oauth2 sso" 200
      }
      route {
        redir https://{hostport}/auth/login 302
      }
    }
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
# caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.14
http.handlers.authp v1.4.18

```

**Comment by greenpau** [comment]
@silvajp2, I don't have a setup that provides groups. Please let me know if you can create an account for me that I would be able to test it. If not, then this goes to a backlog.

**Comment by greenpau** [comment]
When I added `groups` to requested scopes:

```
scopes openid email profile "https://www.googleapis.com/auth/groups"
```

I got the following prompt:

![image](https://user-images.githubusercontent.com/3826416/128077038-2e3302d6-d65c-483e-9db2-b56412dc887e.png)

I think it makes sense creating a shortcut for groups:

```
scopes openid email profile "https://www.googleapis.com/auth/groups"

# vs.

scopes openid email profile groups
group regex "foobar"
```

The `group regex` directive would only add the groups matching the regex expression.

**Comment by greenpau** [comment]
Adding screenshots for the creation of a google group.
![01-create-viewer-group](https://user-images.githubusercontent.com/3826416/128078069-33f232d4-7f55-440a-b30d-583ada70261d.png)
![02-viewer-group-privacy-settings](https://user-images.githubusercontent.com/3826416/128078070-b2ff89a4-089d-434c-8668-feca3511f806.png)
![03-viewer-group-subscription](https://user-images.githubusercontent.com/3826416/128078072-e2b7af03-2243-4432-8452-542e8ad99350.png)

**Comment by greenpau** [comment]
@silvajp2 , apparently, the `https://www.googleapis.com/auth/groups` scope does not function as I've hoped. There is no way known to me to enumerate the Google Groups memberships of OAuth authenticated user. There is a way to do it from directory services. However, that requires domain association. I don't have that setup and can't help here. Please consider using "transforms".

**Comment by silvajp2** [comment]
Hey @greenpau, thank you very much for looking into this!

I was able to use curl to retrieve the groups using:

```bash
curl \
  'https://cloudidentity.googleapis.com/v1/groups?parent=customers%2F[COSTUMER_ID]' \
  --header 'Authorization: Bearer [YOUR_ACCESS_TOKEN]' \
  --header 'Accept: application/json' \
  --compressed
```

And it requires the scope: `https://www.googleapis.com/auth/cloud-identity.groups.readonly` and also adding the extra parameter costumer ID. It returns :
```json
{
  "groups": [
    {
      "name": "groups/ID",
      "groupKey": {
        "id": "NAME@DOMAIN"
      },
      "displayName": "group1"
    },
    {
      "name": "groups/ID",
      "groupKey": {
        "id": "NAME@DOMAIN"
      },
      "displayName": "group2"
    }
  ]
}
```

Would this be possible to add? Could you give some pointers to where in the code this could be implemented?

**Comment by greenpau** [comment]
@silvajp2 , that curl command with “ parent=customers%2F[COSTUMER_I”, what did you put for customer id?

There are not “Google Groups” per se. Rather, they are identity groups, correct?

FYI, I have had implemented some of it here https://github.com/greenpau/caddy-auth-portal/commit/5eef9fccdb4f16597c98d3c23a0bceddb207bac8

**Comment by silvajp2** [comment]
@greenpau I used `gcloud organizations list` to get that. 
Yes the groups are based on the google cloud platform in this case, sorry about the confusion.

**Comment by greenpau** [comment]
>  Yes the groups are based on the google cloud platform in this case, sorry about the confusion.

@silvajp2 , yes, that's my understanding too.

> I used gcloud organizations list to get that.

Could you please paste the output of the above command?

> I was able to use curl to retrieve the groups using

Did you get all the groups in the domain or the ones the user is a member of?

I think you got all the groups, not only the one the user is a member of.

**Comment by silvajp2** [comment]
@greenpau you are correct and the API call above returns all groups, documentation states that :[link](https://cloud.google.com/identity/docs/reference/rest/v1/groups/list)
```
Lists the Group resources under a customer or namespace.
```
I also tested:

1. Create a new group
2. Remove myself from said group
3. Do the curl request and the new group is part of the response.

It might be needed to use or correlate with the `Method: groups.memberships.*` . Not sure yet, but look like:

1. Get all the groups
2. For each group of the list execute a `groups.memberships` lookup for the user 

The command result, in json, sorry about the redacteds. The value for the request is found at `[0].owner.directoryCustomerId` .
```json
$ gcloud organizations list --format=json
```

```json
[
  {
    "creationTime": "2018-10-11T06:33:09.923Z",
    "displayName": "REDACTED.com",
    "lifecycleState": "ACTIVE",
    "name": "organizations/REDACTED",
    "owner": {
      "directoryCustomerId": "REDACTED"
    }
  }
]
```

**Comment by silvajp2** [comment]
For the lookup we can use [link](https://cloud.google.com/identity/docs/reference/rest/v1/groups.memberships/lookup)

```
curl \
  'https://cloudidentity.googleapis.com/v1/groups/[YOUR_GROUP_ID]/memberships:lookup?memberKey.id=[YOUR_EMAIL]' \
  --header 'Authorization: Bearer [YOUR_ACCESS_TOKEN]' \
  --header 'Accept: application/json' 
```

And the response is either 200 Ok
```json
{
  "name": "groups/YOUR_GROUP_ID/memberships/MEMBERSHIP_ID"
}
```

Or 
```json
{
  "error": {
    "code": 404,
    "message": "Error(4006): Membership does not exist.",
    "status": "NOT_FOUND"
  }
}
```
