### ISSUE TITLE
feature: GitHub authentication

### ISSUE THREAD

**Issue by schu** [greenpau/caddy-auth-portal#16]
Regarding caddy-auth-forms being a successor to tarent/loginsrv with Caddy 2 (https://github.com/tarent/loginsrv/issues/167) - it would be great to have GitHub authentication support in caddy-auth-forms.

**Comment by greenpau** [comment]
@schu , Github authentication is now doable with this backend. See https://github.com/greenpau/caddy-auth-portal#oauth-20-authorization-servers-and-identity-providers

I may need to add `github` provider, but that is easy.

**Comment by greenpau** [comment]
Started documenting Github OAuth2.0 https://github.com/greenpau/caddy-auth-portal#github

**Comment by schu** [comment]
Hi @greenpau - thanks for the ping.

I was looking into this tonight but eventually hit the following error:

```
... loading module 'auth_portal': ... backend configuration error: unsupported OAuth 2.0 provider github
```

caddy and module versions:

```
$ caddy version
v2.2.0 h1:sMUFqTbVIRlmA8NkFnNt9l7s0e+0gw+7GPIrhty905A=
$ caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.2.0
http.authentication.hashes.scrypt v2.2.0
http.authentication.providers.http_basic v2.2.0h1:sMUFqTbVIRlmA8NkFnNt9l7s0e+0gw+7GPIrhty905A=
http.authentication.providers.jwt v1.0.17
http.handlers.auth_portal v1.1.7
http.handlers.authentication v2.2.0
```

It looks like the built-in `auth_portal` version is a few releases behind and doesn't actually include the GitHub OAuth support yet. Am I missing something?

**Comment by greenpau** [comment]
It looks like the built-in auth_portal version is a few releases behind and doesn't actually include the GitHub OAuth support yet. Am I missing something?

@schu , yes, you need to be at `caddy-auth-jwt v1.1.2` and `caddy-auth-portal v1.2.1`.

**Comment by schu** [comment]
> you need to be at caddy-auth-jwt v1.1.2 and caddy-auth-portal v1.2.1

Does that mean I have to build caddy myself or is there a way to "force" https://caddyserver.com/download to include particular versions of a module?

**Comment by greenpau** [comment]
@schu i think you need “xcaddy” and building it yourself. See “build” in Makefike.
