### ISSUE TITLE
Documentation Addition Request - Add Subdomain Example

### ISSUE THREAD

**Issue by samcro1967** [greenpau/caddy-auth-portal#160]
Subdomains do not work in version 1.4.18 using the same Caddyfile config as previous version.  Is it possible for you to update the Usage Example Caddyfile with an example of how the config needs to be for subdomains with the latest version?

**Comment by greenpau** [comment]
@samcro1967 , which part does not work? 
Will the below help you?

https://github.com/greenpau/caddy-auth-portal/pull/130/files

**Comment by samcro1967** [comment]
Adding JWT to a subdomain referring back to a primary JWT instance in the auth.mydomain.duckdns.org block does not work like it did in previous versions.  It is the same Caddyfile config as before upgrading.  Guessing something in the latest upgrade requires slightly different syntax.

**Comment by greenpau** [comment]
@samcro1967 , need Caddyfile format and the actual error.

**Comment by samcro1967** [comment]
I can't provide the full config in Caddyfle format.  caddy-docker-proxy no longer has that capability.  The base file I feed it is below whihc has the caddy-auth-portal config in it and one subdomain as well.

[Caddyfile](https://pastebin.com/4yVapPNx)

Here are the caddy container [logs](https://pastebin.com/qVqKkWeZ)  I do not see any errors in them.  The browser just redirects back to the portal.

**Comment by greenpau** [comment]
@samcro1967 , what is not working though? It looks like the server starts. If you are unable to authenticate, please provide browser trace to see redirects.

**Comment by samcro1967** [comment]
@greenpau Caddy starts and I am able to login and access links except those that are subdomains protected by JWT.  Chrome network logs are attached.  This was working with version 4.1.6 with the same Caddyfile syntax.

[auth.mydomain.duckdns.org.har.txt](https://github.com/greenpau/caddy-auth-portal/files/6949262/auth.mydomain.duckdns.org.har.txt)

**Comment by greenpau** [comment]
@samcro1967 , good clarity! Config is no longer in paste bin. Please repaste Caddyfile config here.

**Comment by samcro1967** [comment]
Here is the relevant config.
```
{
	https_port	443
	http_port	80
	order jwt before reverse_proxy
    order authp before jwt
	email user@ydomain.net
	debug
	log {
		output file /data/access.log
        format json
    }
}
(geofilter) {
		@mygeofilter {
			  maxmind_geolocation {
			  db_path "/data/GeoLite2-Country.mmdb"
			  allow_countries US
			}
		}
}
(sso) {
	jwt
}
auth.mydomain.duckdns.org {
	import geofilter
	route /* {
		authp {
			crypto default token lifetime 3600
			crypto key sign-verify <redacted>
			backends {
				local_backend {
					method local
					path /config/caddy/users.json
					realm local
				}
			}
			transform user {
				match origin local
				action add role authp/admin
				require mfa
			}
			ui {
				links {
					"My Identity" "/whoami" icon "las la-star"
					"My Settings" "/settings" icon "las la-cog"
					"MyService" "https://myservice.mydomain.duckdns.org" target_blank
					}
			}
		}
	}
	route /test/* {
	jwt {
		primary yes
		crypto key verify <redacted>
		set auth url https://auth.mydomain.duckdns.org/
		allow roles authp/admin authp/user authp/guest
		allow roles superadmin
	}
		uri strip_prefix /test
		encode gzip
		root * /test
		file_server browse
	}
    redir /test /test/
}
myservice.mydomain.duckdns.org {
	import geofilter
	jwt
	reverse_proxy @mygeofilter 192.168.1.157:80
}
```

**Comment by greenpau** [comment]
have you tried setting cookie domain?

cookie domain mydomain.duckdns.org

see https://github.com/greenpau/caddy-auth-portal#intra-domain-cookies

**Comment by samcro1967** [comment]
Adding it now has it working.  Thanks for the help.  Might suggest adding it as an example to the documentation.  Maybe it is there, but wasn't clear to me it was required for subdomains to work.  Really appreciate your work on this project!

**Comment by greenpau** [comment]
@samcro1967 , awesome! 👍 I've marked this issue as "config example".

Please contribute to the development of Caddy auth plugins by:

1. Giving Github stars to github.com/greenpau/caddy-auth-portal and github.com/greenpau/caddy-auth-jwt
2. Promoting the plugins on Twitter by referencing the above repos and mentioning @caddyserver
3. Participating in https://caddy.community/
4. Blogging about your Caddy setup with auth plugins
