### ISSUE TITLE
feature: API access via the portal when using external SSO

### ISSUE THREAD

**Issue by silvajp2** [greenpau/caddy-auth-portal#161]
Is it possible to have the portal issue API keys for logged in users? Or is any way to facilitate access to APIs behind the portal to cli users?

**Comment by greenpau** [comment]
@silvajp2 , please elaborate on the specific use case and authentication flow. Please describe the process in its entirety.

**Comment by silvajp2** [comment]
hey @greenpau , sorry for not being clear!I don´t have a full flow yet, just a general question / something I would like to have / exploring. 

As a starting point, having a /token endpoint that returns the token that the user can then copy paste. Would this be possible?

**Comment by greenpau** [comment]
> As a starting point, having a /token endpoint that returns the token that the user can then copy paste. Would this be possible?

@silvajp2 , I am not great at hypotheticals 😄 However, the JWT is the token you could use to get "/whoami" endpoint programmatically. See here: https://github.com/greenpau/caddy-auth-portal/issues/159#issuecomment-892076005

generally, are we talking about?
* authentication
* data access

**Comment by greenpau** [comment]
Not at the moment.

i am redesigning local auth in such a way that SSO account (“connected account”) become linked to a local account. So it will likely happen in the next couple months.

**Comment by silvajp2** [comment]
That's awesome!

This will also allow MFA for SSO then?

**Comment by greenpau** [comment]
@silvajp2 , the portal is now issuing API keys.

Please reopen in [github.com/greenpau/caddy-security](https://github.com/greenpau/caddy-security/issues/new/choose) if this is still relevant for you. Please consider sponsoring the work on the project! 👍
