### ISSUE TITLE
Possible to set a custom lifetime when using auto-generated encryption keys?

### ISSUE THREAD

**Issue by gregoryjjb** [greenpau/caddy-auth-portal#162]
**Describe the issue**

I want my sessions to last longer than 15 minutes, older answers to this question reference a `token_lifetime` directive (ex: #107) that appears to not exist anymore. If I use the `crypto default token lifetime` without manually setting an encryption key Caddy complains: `Error during parsing: crypto key config error: no key configs found`. Is there a way to do this?

**Version Information**

```
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.14
http.handlers.authp v1.4.18
```

**Comment by greenpau** [comment]
> If I use the crypto default token lifetime without manually setting an encryption key Caddy complains

@gregoryjjb , I think I would need to add a feature that would properly process `crypto default token lifetime` in the absence of key material.

**Comment by gregoryjjb** [comment]
Thanks Paul, [this right here](https://github.com/greenpau/caddy-auth-jwt/blob/main/pkg/kms/keystore.go#L69) is where it needs to be set right? If it's easier you could have a separate set of directives for the auto-generated keys (though I agree that pulling the same `crypto default token lifetime` is cleaner)

**Comment by greenpau** [comment]
@gregoryjjb , yes. The issue is how to propagate the changes across both plugins. I will try finding time this week.

**Comment by greenpau** [comment]
Notes for self.

By default, if not `crypto` configuration is found, the plugin calls `AutoGenerate`. Importantly, the `AutoGenerate` can either generate a new key or get a key from **shared** space (see https://github.com/greenpau/caddy-auth-jwt/blob/main/pkg/shared/shared.go).

https://github.com/greenpau/caddy-auth-portal/blob/213edd2a92597983771f91c4cd3acdb123774c13/pkg/authn/configure.go#L439-L452

What need to happen?
* Detect whether the `crypto` configuration contains only `crypto default` entries
* If the above is true, then let the plugin to amend the properties of the "shared" auto-generated key with the `crypto default` parameters.

**Comment by greenpau** [comment]
The `Error during parsing: crypto key config error: no key configs found` is being thrown by the following code:

https://github.com/greenpau/caddy-auth-portal/blob/d54633dea2c4b42ed8061adbb71b180ce629bd99/caddyfile.go#L593-L597

Perhaps, it makes sense to have a separate field for `CryptoDefaults`. That field would store default lifetime and token name.

**Comment by greenpau** [comment]
@gregoryjjb , I will add the change to the next release. You should be all set to specify `crypto default` without providing any `crypto key` config. Thank you for opening the issue! 👍 

```
    authp {
      crypto default token lifetime 3600
```

Please contribute to the development of Caddy auth plugins by:

1. Giving Github stars to github.com/greenpau/caddy-auth-portal and github.com/greenpau/caddy-auth-jwt
2. Promoting the plugins on Twitter by referencing the above repos and mentioning @caddyserver
3. Participating in https://caddy.community/
4. Blogging about your Caddy setup with auth plugins

**Comment by greenpau** [comment]
@gregoryjjb , released [v1.4.20](https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.4.20).

**Comment by gregoryjjb** [comment]
Thank you Paul, amazing turnaround time!

**Comment by greenpau** [comment]
> Thank you Paul, amazing turnaround time!

@gregoryjjb , at time I have time to do it 😄 You just asked your questions at the right time. I am doing dev on my own time/computer, etc.
