### ISSUE TITLE
Getting the package via wget results in the standard package, without your Auth packages

### ISSUE THREAD

**Issue by cilex-ft** [greenpau/caddy-auth-portal#163]
Just started playing with caddy, and I love it. With your package it will be perfect!

The link you provide in the doc to linux/amd64 is OK when loading via my browser - but KO when used from a server, as in 

    wget -q -O caddy https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com%2Fgreenpau%2Fcaddy-auth-portal%40v1.4.19&p=github.com%2Fgreenpau%2Fcaddy-auth-jwt%40v1.3.14&p=github.com%2Fgreenpau%2Fcaddy-trace%40v1.1.7

Do you have a trick to download from wget, instead of scp-ing the file on all my servers ?

**Comment by greenpau** [comment]
@cilex-ft , try putting the path in quotations.

```
wget -q -O caddy 'https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com%2Fgreenpau%2Fcaddy-auth-portal%40v1.4.19&p=github.com%2Fgreenpau%2Fcaddy-auth-jwt%40v1.3.14&p=github.com%2Fgreenpau%2Fcaddy-trace%40v1.1.7'
```

Then, verify the versions:

```
$ ./caddy list-modules -versions -packages | egrep "(authp|jwt)"
http.authentication.providers.jwt v1.3.14 github.com/greenpau/caddy-auth-jwt
http.handlers.authp v1.4.19 github.com/greenpau/caddy-auth-portal
```

**Comment by cilex-ft** [comment]
:facepalm: of course... this was a real noob question, perhaps I should  have some sleep!

Thank you - closed !

**Comment by greenpau** [comment]
@cilex-ft, awesome! 👍

Please contribute to the development of Caddy auth plugins by:

1. Giving Github stars to github.com/greenpau/caddy-auth-portal and github.com/greenpau/caddy-auth-jwt
2. Promoting the plugins on Twitter by referencing the above repos and mentioning @caddyserver
3. Participating in https://caddy.community/
4. Blogging about your Caddy setup with auth plugins

**Comment by cilex-ft** [comment]
- [x] Starred with :heart:
