### ISSUE TITLE
Adding an oauth2 breaks the url instead of redirecting to the auth url

### ISSUE THREAD

**Issue by DevangJ** [greenpau/caddy-auth-portal#164]
**Describe the issue**

Setting up oauth for a route makes the page not work.

**Configuration**

Paste full `Caddyfile` below:
```
http:// {
        route /auth* {
                authp {
                        backends {
                                google_oauth2_backend {
                                        method oauth2
                                        realm google
                                        provider google
                                        client_id XXXX.apps.googleusercontent.com
                                        client_secret XXXX
                                        scopes openid email profile
                                }
                        }
                        ui {
                                links {
                                        "Jellyfin" /jellyfin
                                }
                        }
                }
        }
        route /sso/oauth2/google* {
                jwt {
                        set auth url /auth/oauth2/google
                }
                respond * "google oauth sso" 200
        }
        route /jellyfin* {
                jwt {
                        set auth url /auth/oauth2/google
                }
                uri strip_prefix /jellyfin
                reverse_proxy jellyfin:8096
        }
}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.15
http.handlers.authp v1.4.21
```

**Expected behavior**

Expect to redirect to auth both for /jellyfin and for /sso/oath2/google and then redirect back after logging in.

**Additional context**

My setup is behind a CGNAT and as such I've had to employ a tunnel to access it. The tunnel connects to port 80.
I am able to access /auth as well as login using oAuth2 on /auth (but it doesn't redirect anywhere obviously).

**Comment by greenpau** [comment]
@DevangJ , try “cookie insecure on”

https://github.com/greenpau/caddy-auth-portal#intra-domain-cookies

**Comment by greenpau** [comment]
@DevangJ , the above needs to be added in “authp” plugin config.

Your JWT plugin config is incorrect. I will paste a basic example later today.

**Comment by greenpau** [comment]
@DevangJ , here is your complete config. Substitute `YOUR_EMAIL`, `CLIENT_ID`, and `CLIENT_SECRET` to the appropriate values.

Please try it and let me know if it worked for you.

```
http:// {
  route /auth* {
    authp {
      backend google CLIENT_ID.apps.googleusercontent.com CLIENT_SECRET
      ui {
        links {
          "Jellyfin" /jellyfin icon "las la-star"
        }
      }
      transform user {
        match origin google
        match email YOUR_EMAIL
        action add role authp/user
      }
      cookie insecure on
    }
  }

  route {
    jwt {
      primary yes
      allow roles authp/admin authp/user
      validate bearer header
      set auth url /auth/oauth2/google
      inject headers with claims
    }
    reverse_proxy jellyfin:8096
  }
}
```

**Comment by greenpau** [comment]
Some explanation on the Caddyfile lines here.

The is a shortcut for a multi-line config. You are using vanilla setting for the most part.
It is easier to just provide `CLIENT_ID`, and `CLIENT_SECRET`. In retrospect, I think I should see
whether `CLIENT_ID` has a domain name and, if not, append the `apps.googleusercontent.com`.
This would make that line shorter.

```
      backend google CLIENT_ID.apps.googleusercontent.com CLIENT_SECRET
```

Here, the plugin would check whether the OAuth provider is google and whether
the email matches the provided email. If it does, then the user would get `authp/user`
role (ordinarily, a user gets `authp/guest`). The `authp/user` role would allow access
to Jellyfin frontend.

```
      transform user {
        match origin google
        match email YOUR_EMAIL
        action add role authp/user
      }
```

You serve the webserver on port 80 (see `http://`). By default, the plugin
does not pass cookies over insecure connections. Thus, you need to overwrite
that behaviour.

```
      cookie insecure on
```

Finally, the `route {` is analogous to `route /* {`.

We allow roles `authp/admin` and `authp/user` accessing it.

```
  route {
    jwt {
      primary yes
      allow roles authp/admin authp/user
```

You don't have to use `uri strip_prefix`, because you are serving Jellyfin
from the root of your server.

```
    reverse_proxy jellyfin:8096
  }
}
```

**Comment by DevangJ** [comment]
@greenpau Thanks for this clean explanation. I was actually following through on the repo's Readme and testing it out which was why my Caddyfile had just one route to it. I intend to add a few more actually. Are all the extra lines inside jwt just because I'm serving through http? Because I was testing with the snippet that's [here.](https://github.com/greenpau/caddy-auth-portal#google-identity-platform)

If I wanted to serve jellyfin not on the root then would I need the `uri strip_prefix`. I presume it would then look like - 
```
route /jellyfin* {
    jwt {
      primary yes
      allow roles authp/admin authp/user
      validate bearer header
      set auth url /auth/oauth2/google
      inject headers with claims
    }
    reverse_proxy /jellyfin* jellyfin:8096 # I'm not sure if I need the '/jellyfin*' both at the route part and over here?
  }
```

I had one other question, I see that `allow roles authp/admin authp/user` has an admin role as well. How do I assign this role to someone and the user role to everyone else? Is this automatic in someway?

Thanks a ton for your response, I'll try out the Caddyfile you posted and update here with my results

**Comment by greenpau** [comment]
> If I wanted to serve jellyfin not on the root then would I need the uri strip_prefix. I presume it would then look like -

@DevangJ , the you would user the `uri strip_prefix`:

```
  route /jellyfin* {
    jwt {
      ...
    }
    uri strip_prefix /jellyfin
    reverse_proxy jellyfin:8096
  }
```

I would recommend using default route to redirect to your landing page, e.g.

```
  route {
    redir https://{hostport}/auth/login 302
  }
```

> I had one other question, I see that allow roles authp/admin authp/user has an admin role as well. How do I assign this role to someone and the user role to everyone else? Is this automatic in someway?

The assignment of roles happens with `transform` directive.

Here a user with email `greenpau@outlook.com` and authentication with Google OAuth would get `authp/admin` and `authp/user` roles. Otherwise, when the email does not match, the user would get `authp/user` only.

```
      # match any user authenticated via Google OAuth endpoint
      transform user {
        match origin google
        action add role authp/user
      }
      # match the user authenticated via Google OAuth endpoint AND
      # having email in the user's Google profile `greenpau@outlook.com`:
      transform user {
        match origin google
        match email greenpau@outlook.com
        action add role authp/admin
      }
```

> run: adapting config using caddyfile: parsing caddyfile tokens for 'route': /etc/caddy/Caddyfile:18 - Error during parsing: unrecognized directive: transform

The `Caddyfile:18` means the error is happening at that line. It is likely you misaligned enclosing brackets somewhere. Please past a Gist to your current config.

**Comment by greenpau** [comment]
@DevangJ , remember, you don't need to define `backends` when using `backend` shortcut.

**Comment by greenpau** [comment]
> Are all the extra lines inside jwt just because I'm serving through http

@DevangJ , let me quickly explain the purpose here.

This one is probably not necessary. See https://github.com/greenpau/caddy-auth-jwt#token-discovery for the explanation. 

```
      validate bearer header
```

This one is not necessary, unless you want to inform Jellyfin about the identity of the user you are proxying.

See this section for the explanation: https://github.com/greenpau/caddy-auth-jwt#pass-jwt-token-claims-in-http-request-headers

```
      inject headers with claims
```

**Comment by DevangJ** [comment]
@greenpau Thanks a ton for your help. I finally got it to work. I'm kinda excited because a CGNAT is so annoying to work through since I can't port forward anything or link to any IP.

> The Caddyfile:18 means the error is happening at that line. It is likely you misaligned enclosing brackets somewhere. Please past a Gist to your current config.

Ah I did misplace the brackets, I thought transform was outside authp. It started working when I fixed it.

> This one is probably not necessary. See https://github.com/greenpau/caddy-auth-jwt#token-discovery for the explanation.
`validate bearer header`

Is this to enable ADFS auth? It looks somewhat like what I do at work to authenticate stuff.

> See this section for the explanation: https://github.com/greenpau/caddy-auth-jwt#pass-jwt-token-claims-in-http-request-headers
  `inject headers with claims`

So this is if my downstream systems already use oauth I can daisy chain the authentication?

Thanks again man, caddy has been a new learning experience and I've been having a lot of fun. One other thing I'd like to say is it's be nice to have a plug-and-play Caddyfile in the documentation to get folks like me started on.

**Comment by greenpau** [comment]
> Is this to enable ADFS auth? It looks somewhat like what I do at work to authenticate stuff.

@DevangJ , it is primarily for Javascript based interaction. Say if you had Javascript app (that did not utilize cookies) making calls to Jellyfin.

> So this is if my downstream systems already use oauth I can daisy chain the authentication?

Not exactly. Say your downstream app does not support authentication at all. However, your app, e.g. PHP, knows to read headers your upstream (i.e. Caddy) sends. The app can say "Hello Paul Greenberg!" by inspecting the header `X-Token-User-Name` :-)

> Thanks again man, caddy has been a new learning experience and I've been having a lot of fun. One other thing I'd like to say is it's be nice to have a plug-and-play Caddyfile in the documentation to get folks like me started on.

Will try improving the docs :-)

Please contribute to the development of Caddy auth plugins by:

1. Giving Github stars ⭐ to http://github.com/greenpau/caddy-auth-portal and ⭐ http://github.com/greenpau/caddy-auth-jwt
2. Promoting the plugins on Twitter by referencing the above repos and mentioning @caddyserver and @GreenbergTech
3. Participating in https://caddy.community/
4. Blogging about your Caddy setup with auth plugins

**Comment by DevangJ** [comment]
@greenpau I see that these would be useful if I were making my own app. I'll definitely do what I can to contribute to these plugins, they're honestly a lifesaver.

I found a new issue that happens now. When I do 
```
route /jellyfin* {
                jwt {
                        primary yes
                        allow roles authp/admin authp/user
                        validate bearer header
                        set auth url /auth/oauth2/google
                        inject headers with claims
                }
                uri strip_prefix /jellyfin
                reverse_proxy jellyfin:8096
        }
```
I'm able to auth normally and this reverse proxies to my jellyfin server as well (redirects to `http://hostname/jellyfin/web/index.html` which is my landing page) but this page isn't able to load. It says `hostname redirected you too many times. Try clearing your cookies.` I'm running this in incognito so I know there aren't any cookies. I guess this is happening because both caddy-auth and jellyfin try to use /jellyfin and they keep redirecting each other? How do I stop that from taking place?

Another problem is, I'm able to remove this `/jellyfin` part on the server side (so basically `http://hostname/web/index.html`) but this is seen as default routing `/` by caddy-auth and redirects it to main landing page. How do I make caddy-auth preserve the `/jellyfin` so that when jellyfin reroutes to `hostname/web/index.html` caddy-auth still uses `hostname/jellyfin/web/index.html`

**Comment by greenpau** [comment]
@DevangJ , please create a gist with your current config. Second, capture HTTP traffic with your browser to see requests, redirects and status codes.

my guess is that you need to configure Jeff with something that tells it you are hosting it from /jellyfin and then remov uri stripping from Caddyfile config.

**Comment by greenpau** [comment]
Based on this https://www.google.com/amp/s/amp.reddit.com/r/jellyfin/comments/ecod2z/understanding_the_base_url_change/

jellyfin is already being served from /jellyfin. Just remove URI prefix stripping from your config and things should work.

**Comment by DevangJ** [comment]
@greenpau, Oh so that's what uri stripping does, I tried searching the docs but couldn't find what it does anywhere(Maybe the name is self evident haha). So if things are already served on `/appname` then I don't need to uri strip. But what if things are served on something else. 

For ex: I have an app `portainer` that serves on `localhost:port/#!/` so if I uri strip `/portainer` the `/#!` resolves to default route and goes to main landing page. Actually I'm not sure what I acheive with uri stripping since then would it not always just redirect to the root page?

Is this behavior something I configure on the app side instead of on caddy-auth?

**Comment by greenpau** [comment]
> So if things are already served on /appname then I don't need to uri strip. 

@DevangJ , yes 😃 

> But what if things are served on something else.

I think you need to sort out how “route” directive works. Say you have a route “/prometheus*” and you reverse proxy it to a server that serves data from “/“. Then you uri strip the “/prometheus” so that when it arrives to a proxied server, that server gets request without it and things just work.
