### ISSUE TITLE
Authenticating against a (mysql) database

### ISSUE THREAD

**Issue by cilex-ft** [greenpau/caddy-auth-portal#165]
Our current php SaaS application already manages users. It relies on a mysql table "User", where it stores amoung other information user's login, email and (bcrypt) password.

I couldn't find in documentation how we might declare such a database as the authentication backend for your plugin? Is is possible?

Thanks a lot for your great work!

**Comment by greenpau** [comment]
> I couldn't find in documentation how we might declare such a database as the authentication backend for your plugin?

@cilex-ft , unfortunately, there is no such feature at the moment.

> Is is possible?

Everything is possible 😃 for the right amount of sponsorship contributions and being able to have access to the setup you have. Ping me on LinkedIn if you want to discuss it.
