### ISSUE TITLE
"error: auth method not found" when trying to use google_oauth2_backend

### ISSUE THREAD

**Issue by cakoose** [greenpau/caddy-auth-portal#166]
**Describe the issue**

I have a local HTTP service.  I want to run Caddy in front of that service to (1) add TLS and (2) protect the service with Google auth.  I'm trying to piece together the correct configuration from examples in the README and on various online forums, but I can't get it working.

The error I get when running `./caddy run -config Caddyfile`:

```
2021/08/15 19:54:55.581 INFO    using provided configuration    {"config_file": "Caddyfile", "config_adapter": ""}
run: adapting config using caddyfile: parsing caddyfile tokens for 'route': Caddyfile:17 - Error during parsing: parsing caddyfile tokens for 'authp': Caddyfile:5 - Error during parsing: auth backend backends directive failed: backend config map[name:crypto] error: auth method not found
```

**Configuration**

Paste full `Caddyfile` below:

```
test.cakoose.net {
    route /_auth/* {
        authp {
            backends {
                crypto key sign-verify ZZZ
                crypto key token name auth_token
                google_oauth2_backend {
                    method oauth2
                    realm google
                    provider google
                    client_id XXX
                    client_secret YYY
                    scopes openid email
                }
            }
        }
    }

    route /* {
        jwt {
            primary yes
            crypto key verify ZZZ
            crypto key token name auth_token
            set auth url /_auth
            allow roles everyone
        }
        respond * "hello" 200
    }
}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.15
http.handlers.authp v1.4.21
```

**Expected behavior**

Describe expected behavior.

**Additional context**

**Comment by greenpau** [comment]
@cakoose , your syntax is a bit of.

read through these comment and modify your config accordingly. You don’t need to configure crypto keys if everything is hosted on one server. Also “crypto” is the top level config item, it should not be enclosed in a backend.

https://github.com/greenpau/caddy-auth-portal/issues/164#issuecomment-898906600

**Comment by greenpau** [comment]
@cakoose , please modify your config and paste it here. I will comment on its context and explain some parts, if necessary.

**Comment by greenpau** [comment]
> You don’t need to configure crypto keys if everything is hosted on one server.

The key pair will be auto-generate and shared between authp and jwt plugins.

**Comment by greenpau** [comment]
@cakoose , you would also likely need to use “cookie domain <fqdn>“. Will figure it out when you post your final config.

**Comment by cakoose** [comment]
> Also “crypto” is the top level config item, it should not be enclosed in a backend.

Thanks, that fixed it!

One of the examples in the caddy-auth-portal README has it enclosed under `backends`: https://github.com/greenpau/caddy-auth-portal#configuration-primer-1

> You don’t need to configure crypto keys if everything is hosted on one server.
>
> The key pair will be auto-generate and shared between authp and jwt plugins.

I assume a new key is regenerated every time I restart Caddy, in which case Caddy has to hit the OAuth provider API to regenerate the cookies.  Though that's not a _huge_ deal, I figure I might as well use a fixed key to avoid that.

**My latest config**

```
ccott.cakoose.net, sboot.cakoose.net, sboot2.cakoose.net {
    route /_auth/* {
        authp {
            crypto key sign-verify {$BROWSER_AUTH_TOKEN_KEY}
            crypto key token name __Host-auth_token
            #cookie samesite strict
            backends {
                google_oauth2_backend {
                    method oauth2
                    realm google
                    provider google
                    client_id {$GOOGLE_OAUTH_CLIENT_ID}
                    client_secret {$GOOGLE_OAUTH_CLIENT_SECRET}
                    scopes openid email
                }
            }
            transform user {
                match origin google
                suffix match email @cakoose.com
                action add role authp/user
            }
        }
    }

    route /* {
        jwt {
            primary yes
            set token sources cookie
            enable strip token  
            crypto key verify {$BROWSER_AUTH_TOKEN_KEY}
            crypto key token name __Host-auth_token
            set auth url /_auth/oauth2/google
            allow roles authp/user
        }
        @ccott {
            host ccott.cakoose.net
        }
        @sboot {
            host sboot.cakoose.net
        }
        @sboot2 {
            host sboot2.cakoose.net
        }
        # These will actually be reverse_proxy
        respond @ccott "hello ccott" 200
        respond @sboot "hello sboot" 200
        respond @sboot2 "hello sboot2" 200
    }
}
```

This basically works, thanks so much for your help!

There are a few minor things that I'm curious about:
1. I tried using `cookie samesite strict` but that didn't work.  I don't care _that_ much, but I was just wondering if that was a known thing.
2. If I sign in using an account on the wrong domain (i.e. not on "@cakoose.com") I get taken to a "Forbidden" page.  It would be nice if that page had the user's email, which might help them see that they're signed in with the wrong Google account.
3. If someone is signed in with the wrong account (and gets a forbidden page), is there a way to link them to sign in again?  I think they can go to "accounts.google.com" and remove the app, but I was hoping for something simpler.

**Comment by greenpau** [comment]
> I assume a new key is regenerated every time I restart Caddy, in which case Caddy has to hit the OAuth provider API to regenerate the cookies. Though that's not a huge deal, I figure I might as well use a fixed key to avoid that.

@cakoose , I would recommend not using shared keys here. Rather, follow this [doc](https://github.com/greenpau/caddy-auth-jwt#generate-ecdsa-public-key) to generate ECDSA keypair.

Then, user the following directives:

* `authp` plugin: `crypto key sign-verify from file /path/to/signkey.pem`
* `jwt` plugin: `crypto key verify from file /path/to/verifykey.pem`

> host ccott.cakoose.net

You have number of hosts here. Add the following directive under authp:

```
cookie domain cakoose.net
```

> backends in your config.

I suggest removing `backends` and using [shortcut](https://github.com/greenpau/caddy-auth-portal#shortcuts) instead.

It makes your config shorter.

```
backend google <client_id> <client_secret>
```

> transform user

The following directive grants `authp/user` roles to anyone authenticated via your Google app and that identities email is from `@cakoose.com`.

BUT, what happens when a user does not have email. The user gets granted `authp/guest` role.

```
            transform user {
                match origin google
                suffix match email @cakoose.com
                action add role authp/user
            }
```

I suggest expanding the config to include a transform that would match any user that is
not from `@cakoose.com` and block them from gaining access to the portal.

NOTE: This feature is still under development. Please watch https://github.com/greenpau/caddy-auth-jwt/issues/80
for the progress.

```
      transform user {
        match origin google
        no suffix match email @cakoose.com
        block
      }
```

> I tried using cookie samesite strict but that didn't work. I don't care that much, but I was just wondering if that was a known thing.

The `cookie samesite strict` is the top level command within `authp`. Should just work.

> If I sign in using an account on the wrong domain (i.e. not on "@cakoose.com") I get taken to a "Forbidden" page. It would be nice if that page had the user's email, which might help them see that they're signed in with the wrong Google account.

Please create a feature request issue for this. Will continue the discussion on the topic there.

> If someone is signed in with the wrong account (and gets a forbidden page), is there a way to link them to sign in again? I think they can go to "accounts.google.com" and remove the app, but I was hoping for something simpler.

Please create a separate issue on this one.

> I put the keys/secrets in "secrets.txt" and run Caddy with caddy run -config Caddyfile -envfile secrets.txt. It would be nice if I could load the secrets from files without using environment variables since they're not as secure: article.

I suggest you ask this question in https://caddy.community/

There is the concept of placeholders and some other things that could help you.

**Comment by cakoose** [comment]
Thanks you so much for the tips!  I will open new issues for the things you called out at the bottom.

> I would recommend not using shared keys here. Rather, follow this doc to generate ECDSA keypair.

The advantage of HMAC is that it's 5-10x more efficient.  And since the same process does both the signing and verification, there doesn't appear to be a benefit to using asymmetric crypto.  But maybe I'm missing something?

> The `cookie samesite strict` is the top level command within authp. Should just work.

When I added that directive, there were some issues with the Google auth flow.  When I get some time I'll try it again and provide the details of what went wrong.

**Comment by greenpau** [comment]
> When I added that directive, there were some issues with the Google auth flow. When I get some time I'll try it again and provide the details of what went wrong.

@cakoose , I think when you specify `cookie domain` things would work.

> The advantage of HMAC is that it's 5-10x more efficient

See page 7 here https://iopscience.iop.org/article/10.1088/1757-899X/550/1/012023/pdf

There is not much difference.

**Comment by cakoose** [comment]
> > The advantage of HMAC is that it's 5-10x more efficient
> 
> See page 7 here https://iopscience.iop.org/article/10.1088/1757-899X/550/1/012023/pdf
> 
> There is not much difference.

I actually ran into that PDF as well, but it seemed pretty low quality.
1. Figure 6 is useless.  Figure 7's y-axis doesn't start at zero, making it hard to visualize the relative difference.  The charts all show each test run instead of just showing the mean with confidence intervals.
2. It only  measures signing time and not verification time.
3. It wasn't clear whether the graph's "HMAC" line was HS256 or HS512.

The [golang-jwt/jwt](https://github.com/golang-jwt/jwt) library's benchmarks show HS256 to be about 5x faster than ES256 on my computer.

But even if the performance difference were smaller (e.g. 2x), we don't need the asymmetry in my setup, so HMAC seems strictly better.
