### ISSUE TITLE
Bypassing MFA for a subpath

### ISSUE THREAD

**Issue by samcro1967** [greenpau/caddy-auth-portal#167]
**Describe the issue**
I am trying to setup a service so that when a user goes to /service they are prompted for MFA (caddy-auth-portal).  The service sits at /service/app and other sub paths.  I need to be able to exclude /service/rest from MFA as the mobile app does not support it.

**Configuration**
```
    route /service* {
		jwt
		@whitelisted  {
			path /rest*
		}
		reverse_proxy @whitelisted 192.168.1.104:9999
	}
```

**Version Information**
```
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.15
http.handlers.authp v1.4.21
```

**Expected behavior**
A user is not prompted for MFA when they go to /service/rest*, but they are for all other subdirectories under /service.

**Additional context**
I thought this [article](https://caddy.community/t/v1-block-or-allow-certain-paths-to-a-backend-using-caddy-proxy/7089) would get what I needed, but I am not sure whitelisting is what I need as this example is not using jwt.

**Comment by greenpau** [comment]
@samcro1967 , have you looked at “bypass” in jwt docs?

**Comment by greenpau** [comment]
@samcro1967 , I also suggest considering setting up two portals with their own keys and endpoints. One regular, another mobile.

**Comment by samcro1967** [comment]
Thank you!  Bypass seems to be working.  That is what I needed.  Here is the config I ended up with for future reference by others.

```
    route /service* {
		jwt {
			bypass uri prefix /service/rest
			acl rule {
				match role user admin authp/admin authp/user
				allow stop log debug
			}
			acl default deny
		}
		reverse_proxy 192.168.1.104:4533
```
What would be the advantage of separating them into different portals?  Is it just to keep jwt protected URLs in one portal and non protected in another so it is easier to tell what is protected and what is not when looking at Caddyfile or is there another advantage?

**Comment by greenpau** [comment]
> What would be the advantage of separating them into different portals?

You could potentially implement different security controls for different paths. For example, if a user accesses mobile frontend check user agent, etc. This way you could protect against bots.
