### ISSUE TITLE
feature: introduce i18n to anything related to user interface

### ISSUE THREAD

**Issue by cilex-ft** [greenpau/caddy-auth-portal#168]
For my French users, I'm trying to change the title on login page from "Log in" to "Connexion".

While modifying the login.template, I saw that we can define a title:

                   <h4>{{ .Title }}</h4>

However trying to define the title in a Caddyfile 

                        ui {
                                theme basic
                                template login "/var/www/global-resources/templates/pia-now/login.template"
                                logo url "../assets/img/pia-now-low.png"
                                logo description "my Description"
                                title "Connexion"
                                links {

prevents the server from starting:

```
run: adapting config using caddyfile: parsing caddyfile tokens for 'route': /etc/caddy/Caddyfile:43 - Error during parsing: parsing caddyfile tokens for 'authp': /etc/caddy/Caddyfile:35 - Error during parsing: unsupported subdirective for ui: title
```

However "title" is valid if I add it in a caddy.json file generated from the previous caddyfile:

                                            "ui": {
                                              "auto_redirect_url": "",
                                              "logo_description": "my Description",
                                              "title": "Connexion",

and correctly displays "Connexion" on the login page.

I've read other issues about underscores with logo directives, and tried to read the code, but I couldn't figure how to define the Title in Caddyfile.

This is probably an other caddy-noob mistake... but I'd appreciate advice about using this parameter, and about "how to find the solution by myself"

**Comment by cilex-ft** [comment]
I forgot to add the versions:

```
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.14
http.handlers.authp v1.4.18

**Comment by cilex-ft** [comment]
No hurry @greenpau , enjoy your vacation!

**Comment by greenpau** [comment]
Looking for ideas to introduce i18n to the entire codebase.

**Comment by greenpau** [comment]
@cilex-ft , please reopen in [github.com/greenpau/caddy-security](https://github.com/greenpau/caddy-security/issues/new/choose) if this is still relevant for you. Please consider sponsoring the work on the project! 👍
