### ISSUE TITLE
Fetch additional claims for GitLab?

### ISSUE THREAD

**Issue by TobiX** [greenpau/caddy-auth-portal#169]
**Describe the issue**

It would be nice if auth-portal could fetch the OIDC claims from a GitLab OAuth2 backend. The [GitLab documentation](https://docs.gitlab.com/ee/integration/openid_connect_provider.html) says:

> The claims sub, sub_legacy, email and email_verified are included in the ID token, all other claims are available from the /oauth/userinfo endpoint used by OIDC clients.

**Configuration**

Paste full `Caddyfile` below:

```
some-host.example.com {
	root * /srv/files

	route /auth* {
		authp {
			backends {
				gitlab_oauth2_backend {
					method oauth2
					realm gitlab
					provider generic
					metadata_url https://git.example.com/.well-known/openid-configuration
					base_auth_url https://git.example.com/oauth/authorize
					client_id YES
					client_secret OFCOURSE
					scopes openid email
				}
			}
		}
	}

	route {
		jwt {
			primary yes
			set auth url /auth/oauth2/gitlab
			allow roles authp/guest
		}
		reverse_proxy localhost:6070
	}

	handle_errors {
		respond "{http.error.status_code} {http.error.status_text}"
	}
}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.15
http.handlers.authp v1.4.21
```

**Expected behavior**

I'd expect that I could limit user access by membership in a GitLab group, but unfortunately that information isn't available in the "default" answer from GitLab, but needs to be fetched separately.

**Additional context**

Maybe a special `gitlab` provider which defaults to `gitlab.com`, but can be pointed at other GitLab instances?

Otherwise: ❤️  this, really a pleasure to use 👍

**Comment by greenpau** [comment]
@TobiX , I don't have access to a gitlab setup. If you fancy providing me with one, I will create `gitlab` provider and make the fetching of groups work for you.

I attempted to do similar thing go Google IAM groups, but I don't have access to a set up like that.

https://github.com/greenpau/caddy-auth-portal/blob/7e1adfea46c84d7276b68ba4ffdc48beedc637b4/pkg/backends/oauth2/groups.go#L26-L54

**Comment by TobiX** [comment]
You could probably just use gitlab.com, honestly. The account page for creating "applications" is here: https://gitlab.com/-/profile/applications - You need at least the openid and email scopes AFAICS:
![grafik](https://user-images.githubusercontent.com/78534/130026201-2ecad339-deb4-456a-9442-7d7920b8738f.png)

I might be able to provide a public test instance in the future, if that's preferable to you, but that would have to wait until after my vacation 😄

**Comment by greenpau** [comment]
> I might be able to provide a public test instance in the future, if that's preferable to you, but that would have to wait until after my vacation 😄

@TobiX , vacation that is :-)

**Comment by TobiX** [comment]
I set up a test GitLab instance at https://gitlab.23.gs/ - It cannot send mails and allows unverified sign-ups for e-mails under `@example.com`, so it should be able to spam anyone, but should be all right for some simple OAuth tests. Oh, and the system is running with just 4GB RAM, so it might be slow at times :smile:

**Comment by greenpau** [comment]
@TobiX . awesome! 👍

At the moment, I've created a user. 

Next, I need your help with creating a few user groups and adding my user to them. Then, generating client id and secret. Finally, sharing it with me via email: greenpau@outlook.com 😃 

Thank you for engaging on this! 👍

**Comment by TobiX** [comment]
I think any user is allowed to create OAuth2 applications: https://gitlab.23.gs/-/profile/applications - I had to enable at least the `openid` and `email` scopes in our internal GitLab to make caddy-auth-portal work...

**Comment by greenpau** [comment]
> I think any user is allowed to create OAuth2 applications: https://gitlab.23.gs/-/profile/applications - I had to enable at least the openid and email scopes in our internal GitLab to make caddy-auth-portal work...

@TobiX , I have the application setup complete. The gitlab is integrated with my app.

![image](https://user-images.githubusercontent.com/3826416/133936165-5f280dc1-3f94-4680-8783-c1ca7ebf2433.png)

Next, what other info are you interested in bringing to the JWT token? groups?

**Comment by greenpau** [comment]
@TobiX , I think I got it:

```
{
  "sub": "4",
  "sub_legacy": "c21347f5293a2158bafae695085d3cb093812c7944c16bf010512f82593a8a47",
  "name": "Paul Greenberg",
  "nickname": "greenpau",
  "email": "greenpau@example.com",
  "email_verified": true,
  "profile": "https://gitlab.23.gs/greenpau",
  "picture": "https://secure.gravatar.com/avatar/2d158059b341813be7f99bf370b010b9?s=80&d=identicon",
  "groups": [
    "foobar",
    "barfoo",
    "public-stuff",
    "a-private-group/a-subgroup"
  ]
}
```

What is the information you would need from here?

**Comment by greenpau** [comment]
@TobiX , I integrating everything but the `groups`. Here is the token I get.

```
{
  "addr": "10.0.2.2",
  "authenticated": true,
  "exp": 1632083599,
  "expires_at_utc": "Sun Sep 19 16:33:19 EDT 2021",
  "iat": 1632082699,
  "iss": "https://localhost:8443/auth/oauth2/gitlab/authorization-code-callback",
  "issued_at_utc": "Sun Sep 19 16:18:19 EDT 2021",
  "jti": "w4FiW9ZPL0mWhzN7ey8BfrOnn6aTQC9IxN8C",
  "mail": "greenpau@example.com",
  "name": "Paul Greenberg",
  "nbf": 1632082639,
  "not_before_utc": "Sun Sep 19 16:17:19 EDT 2021",
  "origin": "gitlab",
  "picture": "https://secure.gravatar.com/avatar/2d158059b341813be7f99bf370b010b9?s=80\u0026d=identicon",
  "roles": [
    "authp/user",
    "authp/admin"
  ],
  "sub": "https://gitlab.23.gs/greenpau"
}
```

For the groups, I will convert them from

```
  "groups": [
    "foobar",
    "barfoo",
    "public-stuff",
    "a-private-group/a-subgroup"
  ]
```

To (by prefixing them with server/domain name):

```
gitlab.23.gs/foobar
gitlab.23.gs/barfoo
gitlab.23.gs/public-stuff
gitlab.23.gs/a-private-group/a-subgroup
```

Then, I will add Caddyfile directive to filter the groups received from Gitlab. For example,

```
  route /auth* {
    authp {
      backends {
        gitlab_oauth2_backend {
          method oauth2
          realm gitlab
          provider gitlab
          domain_name gitlab.23.gs
          client_id XXXX
          client_secret YYYY
          scopes openid email profile
          group filter private
          group filter ^acl_
        }
      }
```

Based on the filter, only the `gitlab.23.gs/a-private-group/a-subgroup` would be propagated to auth portal's issued token.

**Comment by TobiX** [comment]
Nice! Yeah, that group info was exactly what I was looking for!

**Comment by greenpau** [comment]
@TobiX , release the feature in [v1.4.24](https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.4.24). Enjoy Caddy!

**Comment by greenpau** [comment]
@TobiX , the docs are here: https://github.com/greenpau/caddy-auth-portal#gitlab
