### ISSUE TITLE
breakfix: auto redirect to the sub domain after authentication?

### ISSUE THREAD

**Issue by renaisun** [greenpau/caddy-auth-portal#171]
**Describe the issue**

I tried to restrict the role of visitors to `sub.example.com` and used `https://example.com/auth` as portal.
- I set the `cookie domain` to make sure both `sub.example.com ` and `example.com` can have access to the cookies.
- redirect_url is set and `caddy_auth_jwt` looks worked

BUT, after the authentication, request to `example.com/auth/portal` will be automatically redirected to `sub.example.com`. Why did it happened?
If remove the `cookie domain` in line 8 and 9, the authentication will not work properly and get messages like `too many redirects`.
Just stuck for hours and checked every issue may help but I cannot figure out the reason.

**Configuration**

Paste full `Caddyfile` below:

```

{
    debug
}

example.com {
    route /auth* {
        authp {
            cookie domain sub.example.com
            cookie domain example.com
            backends {
                github_oauth2_backend {
                    method oauth2
                    realm github
                    provider github
                    client_id Iv1.<omiited>
                    client_secret <omiited>
                    scopes user
                }
            }
            transform user {
                exact match sub github.com/renaisun
                action add role authp/admin
                ui link "Settings" /auth/settings
            }

        }
    }
}

sub.example.com {
    route {
        jwt {
            set auth url https://example.com/auth?redirect_url=https://sub.example.com
            allow roles authp/admin
        }
        respond "Hello!"
    }
}

```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.15
http.handlers.authp v1.4.21
```

**Expected behavior**

`example.com/auth/portal` would show the portal page.

**Additional context**

I have another off-topic question: what is [token-verification](https://github.com/greenpau/caddy-auth-jwt#token-verification) used for? I couldn't understand the example given, maybe there's some prerequisite knowledge I don't know?

**Comment by greenpau** [comment]
@renaisun , please browse to `example.com/auth` and login. Then, browse to `example.com/auth/whoami` and take the screenshot of the screen. I want to see how the token view from the server.

> If remove the cookie domain in line 8 and 9, the authentication will not work properly and get messages like too many redirects. Just stuck for hours and checked every issue may help but I cannot figure out the reason.

This is happening because the authorization cookie will not have the domain. Since it does not have it, it will not be forwarded to the other hosts in the domain, e.g. `sub.example.com`. Since it is not forwarded, the server treats the user as unauthenticated, and redirects the user to `https://example.com/auth`. The `https://example.com/auth` previously issued the token, it trusts it and send the user back. The process repeats and ends with `too many redirects`.

Solution: You just need a single domain related entry in your Caddyfile: `cookie domain example.com`

Next, change your JWT config to the following. The `jwt` plugin will automatically figure out where you were redirected from. Also, the has to be a `primary` directive. More on it [here](https://github.com/greenpau/caddy-auth-jwt#overview).

```
        jwt {
            primary yes
            set auth url https://example.com/auth
            allow roles authp/admin
        }
```

**Comment by renaisun** [comment]
@greenpau , thanks for your prompt reply.
The screenshot of `whoami` endpoint looks like:

![CleanShot_2021-08-30_at_21 52 55](https://user-images.githubusercontent.com/43090234/131350916-69be0e85-240c-481f-9f4e-38dcfd531a83.png)


And I followed the instruction you gave and the Caddyfile looks like this if I am not wrong.
But the problem still exist: when I tried to browse `example.com/auth/portal`, it will be redirected to `sub.example.com`
Log from the caddy is also attached below as it may helps.


```
{
    debug
}

example.com {
    route /auth* {  
        authp {
            cookie domain example.com
            backends {
                github_oauth2_backend {
                    method oauth2
                    realm github
                    provider github
                    client_id Iv1.2623b2ad209f7db6
                    client_secret 3756a5d7dc4475edee5067fcdcfcf849ac500bb5
                    scopes user
                }
            }
            transform user {
                exact match sub github.com/renaisun
                action add role authp/admin
                ui link "Identity" /auth/whoami icon "las la-wheelchair"
            }
        }
    }
}

sub.example.com {
    route {
        jwt {
            primary yes
            set auth url https://example.com/auth
            allow roles authp/admin
        }
        respond "Hello, world!"
    }
}
```






``` json
2021/08/30 13:56:00.996 INFO    http.handlers.authp     Successful login        {"session_id": "4NYVZKowxtlDcBUedW4LKfEnMQUyo1F8i0okWfvUgNkiY", "request_id": "2c661195-ec23-47cb-ba47-ff58fe418e74", "backend": {"name":"github_oauth2_backend","realm":"github","method":"oauth2"}, "user": {"addr":"103.97.200.18","exp":1630332660,"frontend_links":["Identity /auth/whoami icon \"las la-wheelchair\""],"iat":1630331760,"iss":"https://example.com/auth/oauth2/github/authorization-code-callback","jti":"4NYVZKowxtlDcBUedW4LKfEnMQUyo1F8i0okWfvUgNkiY","metadata":{"id":43090234},"name":"Aaron","nbf":1630331700,"origin":"github","picture":"https://avatars.githubusercontent.com/u/43090234?v=4","realm":"github","roles":["authp/admin"],"sub":"github.com/renaisun"}}
2021/08/30 13:56:00.997 DEBUG   http.handlers.authp     Detected cookie-based redirect  {"session_id": "4NYVZKowxtlDcBUedW4LKfEnMQUyo1F8i0okWfvUgNkiY", "request_id": "2c661195-ec23-47cb-ba47-ff58fe418e74", "redirect_url": "https://sub.example.com/"}
2021/08/30 13:56:01.665 DEBUG   http.authentication.providers.jwt       acl rule hit    {"action": "allow", "tag": "rule0", "user": {"addr":"103.97.200.18","iss":"https://example.com/auth/oauth2/github/authorization-code-callback","jti":"4NYVZKowxtlDcBUedW4LKfEnMQUyo1F8i0okWfvUgNkiY","name":"Aaron","origin":"github","roles":["authp/admin"],"sub":"github.com/renaisun"}}
2021/08/30 13:56:08.492 DEBUG   http.handlers.authp     Redirect served {"session_id": "4NYVZKowxtlDcBUedW4LKfEnMQUyo1F8i0okWfvUgNkiY", "request_id": "9f9673f5-cffe-4ad3-96e1-3fb9d9a29d39", "redirect_url": "https://example.com/auth/portal"}
2021/08/30 13:56:08.722 DEBUG   http.handlers.authp     Cookie-based redirect   {"session_id": "4NYVZKowxtlDcBUedW4LKfEnMQUyo1F8i0okWfvUgNkiY", "request_id": "f69e653b-f0b0-4338-8155-081be0cd0c0a", "redirect_url": "https://sub.example.com/"}
2021/08/30 13:56:09.101 DEBUG   http.handlers.authp     Redirect served {"session_id": "4NYVZKowxtlDcBUedW4LKfEnMQUyo1F8i0okWfvUgNkiY", "request_id": "055c5884-36e2-4a9d-bb73-08e4101bcf36", "redirect_url": "https://example.com/auth/login"}
2021/08/30 13:56:09.366 DEBUG   http.handlers.authp     Redirect served {"session_id": "4NYVZKowxtlDcBUedW4LKfEnMQUyo1F8i0okWfvUgNkiY", "request_id": "445c653c-ee87-4778-ae45-1fc82645bdd7", "redirect_url": "https://example.com/auth/portal"}
2021/08/30 13:56:09.631 DEBUG   http.handlers.authp     Cookie-based redirect   {"session_id": "4NYVZKowxtlDcBUedW4LKfEnMQUyo1F8i0okWfvUgNkiY", "request_id": "fc4c175c-33cb-49b5-89e6-14429305a254", "redirect_url": "https://sub.example.com/"}
2021/08/30 13:56:10.686 DEBUG   http.handlers.authp     Cookie-based redirect   {"session_id": "4NYVZKowxtlDcBUedW4LKfEnMQUyo1F8i0okWfvUgNkiY", "request_id": "367a45d3-b5f2-4c90-a0a5-4ccd38abad2d", "redirect_url": "https://sub.example.com/"}
```

**Comment by greenpau** [comment]
@renaisun , change the `set auth url` directive to look like this:

```
set auth url https://example.com/auth/oauth2/github
```

Next, browse to `sub.example.com` and let me know what you see.

**Comment by greenpau** [comment]
>  But the problem still exist: when I tried to browse example.com/auth/portal, it will be redirected to sub.example.com

@renaisun , i'm a bit confused. The following logs says that upon successful authentication, you were redirected to `https://sub.example.com/`. If that is not the expected behavior, where do you want to get redirected upon successful auth?

```
2021/08/30 13:56:10.686 DEBUG   http.handlers.authp     Cookie-based redirect   {"session_id": "4NYVZKowxtlDcBUedW4LKfEnMQUyo1F8i0okWfvUgNkiY", "request_id": "367a45d3-b5f2-4c90-a0a5-4ccd38abad2d", "redirect_url": "https://sub.example.com/"}
```

**Comment by renaisun** [comment]
> > But the problem still exist: when I tried to browse example.com/auth/portal, it will be redirected to sub.example.com
> 
> @renaisun , i'm a bit confused. The following logs says that upon successful authentication, you were redirected to `https://sub.example.com/`. If that is not the expected behavior, where do you want to get redirected upon successful auth?
> 
> ```
> 2021/08/30 13:56:10.686 DEBUG   http.handlers.authp     Cookie-based redirect   {"session_id": "4NYVZKowxtlDcBUedW4LKfEnMQUyo1F8i0okWfvUgNkiY", "request_id": "367a45d3-b5f2-4c90-a0a5-4ccd38abad2d", "redirect_url": "https://sub.example.com/"}
> ```

Yes, it did redirect to `sub.example.com` successfully and show the expected content which indicates that the `jwt` plugin do the authorization.
But the problem is, when I directly browse `https://example.com/auth/portal` , it will jump to `sub.example.com` rather than showing the portal page (containing the url in `ui` directive)

**Comment by renaisun** [comment]
> @renaisun , change the `set auth url` directive to look like this:
> 
> ```
> set auth url https://example.com/auth/oauth2/github
> ```
> 
> Next, browse to `sub.example.com` and let me know what you see.

![CleanShot_2021-08-30_at_22 34 14](https://user-images.githubusercontent.com/43090234/131356137-7a7a8784-3131-4348-bb25-aa6da3e39a55.png)

changed `set auth url` and the problem still exists.

**Comment by greenpau** [comment]
> Yes, it did redirect to sub.example.com successfully and show the expected content which indicates that the jwt plugin do the authorization.

@renaisun , auth and authorization works. Now, the issue is redirects.

> But the problem is, when I directly browse https://example.com/auth/portal , it will jump to sub.example.com rather than showing the portal page (containing the url in ui directive)

@renaisun , browse to `https://example.com/auth/logout` and would clear the cookies. Then, click the Github login button and see what happens.

Alternatively, you could do:

```
set auth url https://example.com/auth?redirect_url=https://example.com/auth/portal
```

**Comment by renaisun** [comment]
> @renaisun , browse to `https://example.com/auth/logout` and would clear the cookies. Then, click the Github login button and see what happens.
> 
> Alternatively, you could do:
> 
> ```
> set auth url https://example.com/auth?redirect_url=https://example.com/auth/portal
> ```

what I've done:
- browse `https://example.com/auth/logout` to clear the cookies.
- click the Github login button and login
- then I was redirected to `a.example.com`



part of caddyfile:
```
a.example.com {
    route {
        jwt {
            primary yes
            set auth url https://example.com/auth?redirect_url=https://example.com/auth/portal
            allow roles authp/admin
        }
        respond "visiting a.example"
    }
}
```

**Comment by greenpau** [comment]
> then I was redirected to a.example.com

@renaisun , you did not get to the portal UI welcome page ... hmmmm 🤔 What did you set the "User authorization callback URL" in Github apps to?

**Comment by renaisun** [comment]
> @renaisun , you did not get to the portal UI welcome page ... hmmmm 🤔 What did you set the "User authorization callback URL" in Github apps to?

Yeah that's the problem.
You mean this field? @greenpau 
![CleanShot_2021-08-30_at_22 58 04](https://user-images.githubusercontent.com/43090234/131359706-e5ab6f89-0608-42f7-b144-024ec8ddb2be.png)

**Comment by greenpau** [comment]
@renaisun , what is the latest on this?

**Comment by renaisun** [comment]
> @renaisun , what is the latest on this?

As a workaround, I use sub-domain as auth endpoint and everything just works fine.
