### ISSUE TITLE
feature: implementation of simple TOTP and HOTP without password

### ISSUE THREAD

**Issue by daiaji** [greenpau/caddy-auth-portal#173]
Other authentication methods seem too complicated. OAuth seems to require that the OAuth service provider is always online, while the implementation of TOTP and HOTP is very simple and does not rely on third-party authentication servers.

After all, I just want to use TOTP to replace the less secure basic authentication, and I don’t want to perform complicated authentication configurations.

https://github.com/andOTP/andOTP

**Comment by daiaji** [comment]
I just use TOTP instead of Caddy's native `basicauth`. I just think that `basicauth` is relatively insecure for verifying the identity of visitors.

**Comment by greenpau** [comment]
@daiaji , how do you want this plugin to change? Are you saying you want to provide username + TOTP only, without the need for a password?

**Comment by daiaji** [comment]
Yes, in fact, 2FA is not required. My SSH only uses TOTP. Moreover, if user management is not required, I don't think it is necessary to authenticate the user name.

**Comment by renaisun** [comment]
> @daiaji , how do you want this plugin to change? Are you saying you want to provide username + TOTP only, without the need for a password?

I wonder if it's possible to implement password less auth? like using hardware (Yubikey) as single-factor authentication? It seems like the plugin only support form-based auth + 2FA to use hardware like that.

**Comment by greenpau** [comment]
> @greenpau I wonder if it's possible to implement password less auth? like using hardware (Yubikey) as single-factor authentication? It seems like the plugin only support form-based auth + 2FA to use hardware like that.

@renaisun , yes. This would require redesign how the login page works today. It is worthy feature to have.

**Comment by greenpau** [comment]
@daiaji @renaisun, the next step on this is allowing a user to choose to skip password auth when HOTP/TOTP (MFA) is present. Will implement the ability to switch in UI.

**Comment by greenpau** [comment]
FYI, the next step on this is creating a knob to allow "dropping" the password security challenge when HOTP/TOTP exists. This could potentially be a user transform.

```
transform user {
  match ...
  disable password auth
}
```

The logic would reside in `injectUserChallenges` function. The function takes (1) the security challenges found in local database and reconciles them with (2) the security challenges found in user transforms.

https://github.com/greenpau/caddy-auth-portal/blob/e76a149543d821dc0f08612a14469db05acdf2fe/pkg/authn/handle_http_login.go#L178-L209

Caveat, one could potentially brute force login if the only security challenge is Authenticator App, e.g. passcode is too short. See #207 for the context.

**Comment by greenpau** [comment]
@daiaji , please reopen in [github.com/greenpau/caddy-security](https://github.com/greenpau/caddy-security/issues/new/choose) if this is still relevant for you. Please consider sponsoring the work on the project! 👍
