### ISSUE TITLE
No API reference?

### ISSUE THREAD

**Issue by sbrl** [greenpau/caddy-auth-portal#175]
**Describe the issue**

I really appreciate complete configuration examples, but I'm finding them difficult to understand without an API reference that explains each directive individually.

**Configuration**

Paste full `Caddyfile` below:

```
N/A - don't have one yet, because I'm struggling to understand use to use caddy-auth-portal for my use-case in the first place
```

**Version Information**

```http.authentication.hashes.bcrypt v2.4.5
http.authentication.hashes.scrypt v2.4.5
http.authentication.providers.http_basic v2.4.5
http.handlers.authentication v2.4.5
http.authentication.providers.jwt v0.5.0
http.handlers.authp v1.4.24
```

**Expected behavior**

I can find an official API reference.

**Additional context**

I want to have the authentication portal on a dedicated subdomain and authenticate for other subdomains, but I don't understand the individual directives being used in e.g. #94 well enough to implement it.

**Comment by greenpau** [comment]
@sbrl , the majority of it should be in README.md files in “caddy-auth-portal” and “caddy-auth-jwt” plugins.

Also, i don’t recognize the jwt version you have in your module output.

**Comment by sbrl** [comment]
@greenpau, hmmm, I see. I've read both of those extensively, but still have a number of questions.

To take just 1 example from many, where can `redir` be used and in what contexts?

Another key point on #94 is e.g. `auth.example.com`, why is there both a n `auth_portal`` definition and an `route /* { import my-auth ...` definition? Isn't the second one redundant?

> Also, I don’t recognize the jwt version you have in your module output.

Ah, thanks for that. Looks like I got the wrong github repo in my xcaddy build. Fixed:

```
http.authentication.hashes.bcrypt v2.4.5
http.authentication.hashes.scrypt v2.4.5
http.authentication.providers.http_basic v2.4.5
http.handlers.authentication v2.4.5
http.authentication.providers.jwt v1.3.16
http.handlers.authp v1.4.24
```

**Comment by greenpau** [comment]
> To take just 1 example from many, where can redir be used and in what contexts?

the “redir” is caddy directive, not auth portal specific. You could get help in Caddy community forum and reading caddy docs. This directive simply tells to redirect users to another page.

additionally, each “route” directive handles request in a certain way. Importantly, if two directives match the same requested path, the first one mentioned in the config wins. The other will be disregarded.


How about you try your best to construct caddyfile based on your current understanding of how things work and paste it here? Then, I will try helping you getting to a working config.

**Comment by sbrl** [comment]
Oh I see. I couldn't tell if it was specific to caddy-auth-portal/caddy-auth-jwt or whether it was a generic caddy directive.

Ah, ok - got it.

Sure thing. Here's my first attempt:

```caddy
(auth) {
	jwt {
		primary yes
		trusted_tokens {
			static_secret {
				token_name {$JWT_TOKEN_NAME}
				token_secret {$JWT_TOKEN_SECRET}
			}
			set auth_url https://auth.mooncarrot.space/
			allow roles superadmin authp/admin authp/user
		}
	}
}

auth.mooncarrot.space {
	auth_portal {
		cookie_domain mooncarrot.space
		ui {
			theme basic
		}
		jwt {
			token_name {$JWT_TOKEN_NAME}
			token_secret {$JWT_TOKEN_SECRET}
		}
		backend local /etc/caddy/users_db.json local
	}
}


*.mooncarrot.space {
	import auth
	
	reverse_proxy https://fabio.mooncarrot.space:443 {
		#header_down strict-transport-security	"max-age=31536000"
	}
}
```

....but I get this error:

```
run: adapting config using caddyfile: parsing caddyfile tokens for 'route': /etc/caddy/Caddyfile:54 - Error during parsing: parsing caddyfile tokens for 'jwt': /etc/caddy/Caddyfile:26 - Error during parsing: unsupported root directive: trusted_tokens
```

....yet in #94 `trusted_tokens` seems to be a thing?

What I'm trying to accomplish here is to use Caddy as a generic reverse proxy to my cluster which authenticates all users before they access any backend services. Then I can port forward to Caddy on my router instead of Fabio (which does support http basic authentication, but caddy-auth-portal is significantly more sophisticated).

**Comment by greenpau** [comment]
@sbrl , try this:

```
auth.mooncarrot.space {
  route {
    authp {
      backend local /etc/caddy/users_db.json local
      cookie domain mooncarrot.space
      ui {
        links {
          "My Website" https://www.mooncarrot.space/ icon "las la-star"
          "My Identity" "/whoami" icon "las la-star"
        }
      }
      transform user {
        match origin local
        action add role authp/user
      }
    }
  }
}

*.mooncarrot.space {
    jwt {
      primary yes
      allow roles authp/admin authp/user
      set auth url https://auth.mooncarrot.space
    }
    reverse_proxy https://fabio.mooncarrot.space:443
}
```

**Comment by greenpau** [comment]
@sbrl , updated the above example with `crypto key` directives. They are optional if you are running a single instance of your server.

**Comment by sbrl** [comment]
Hey, thanks @greenpau! I added a `route` there to avoid an error about things being unordered, and also moved the user db into a subdirectory that I've chowned to the `caddy` user & group:

```caddy
(auth) {
	jwt {
		primary yes
		allow roles authp/admin authp/user
		set auth url https://auth.mooncarrot.space
		#crypto key verify a138a4f3-830e-42f4-bb55-27fd3943c368
    }
}

auth.mooncarrot.space {
	route {
		authp {
			backend local /etc/caddy/data/users_db.json local
			cookie domain mooncarrot.space
			# crypto key sign-verify a138a4f3-830e-42f4-bb55-27fd3943c368
			ui {
				links {
					"mooncarrot.space" https://mooncarrot.space/ icon "las la-star"
					"Identity" "/whoami" icon "las la-star"
				}
			}
			transform user {
				match origin local
				action add role authp/user
			}
		}
	}
}


*.mooncarrot.space {
	import auth
	
	route {
		import auth
		reverse_proxy https://fabio.mooncarrot.space:443
	}
}
```

.....however I'm met with an error about a read-only filesystem:

```
run: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 1: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'authp': provision http.handlers.authp: backend configuration for "default" instance in "portal-default-000001" context failed: failed initializing database at "/etc/caddy/data/users_db.json": failed database commit to "/etc/caddy/data/users_db.json": open /etc/caddy/data/users_db.json: read-only file system
```

...yet I can write to the directory as the caddy user just fine:

```
$ sudo -u caddy touch /etc/caddy/data/testfile
$ ls /etc/caddy/data/testfile
-rw-rw-r-- 1 caddy caddy 0 Sep 26 14:27 testfile
```

**Comment by greenpau** [comment]
@sbrl , please use the template I posted. Avoid the “import” statement, unless you understand what it means.

**Comment by greenpau** [comment]
@sbrl regarding the error

failed database commit to "/etc/caddy/data/users_db.json": open /etc/caddy/data/users_db.json: read-only file system

It looks like the process cannot write to the provided path.

**Comment by sbrl** [comment]
Removing the import has no effect (I thought it was a way to have reusable snippets in a caddyfile? `*.mooncarrot.space` is not the only domain I want to add this for). ` /etc/caddy/data/users_db.json` does not exist, because I expected that caddy-auth-portal would create it.

I can prove that the directory is writeable by the following:

```
$ systemctl show caddy | grep -i user=
User=caddy
DynamicUser=no
$ sudo -u caddy nano  /etc/caddy/data/users_db.json
$ cat  /etc/caddy/data/users_db.json
testing
$ rm  /etc/caddy/data/users_db.json
```

**Comment by greenpau** [comment]
> expected that caddy-auth-portal would create it.

@sbrl , are you using containers/docker? What is your OS?

**Comment by sbrl** [comment]
> @sbrl , are you using containers/docker? What is your OS?

I do use containers @greenpau, but not on the host upon which Caddy is running. This is a plain old Ubuntu Server 20.04 instance on amd64 (specifically an Athlon 3000G), running Caddy with systemd with the official package - specifically I followed these instructions: https://caddyserver.com/docs/build#package-support-files-for-custom-builds-for-debianubunturaspbian

**Comment by greenpau** [comment]
@sbrl , btw, you are editing the file as root (see sudo), while running caddy server as caddy user. It could be that caddy user has no write access.

**Comment by sbrl** [comment]
@greenpau true, but I use `-u caddy` to ensure it's the caddy user, not `root`. In addition, the file does *not* exist when  start Caddy - rather it's a directory that is chowned to `caddy:caddy`. I assume that caddy-auth-portal will create an initial template user DB? Or do I need to lift one from somewhere myself?

**Comment by greenpau** [comment]
@sbrl , this look like something filesystem related. I can offer little help here.

**Comment by sbrl** [comment]
haha, found it! It was `ProtectSystem=full` in the systemd service file. Moving the data dir elsewhere fixed it.

Now I'm going to play around with the web administration panel :D
