### ISSUE TITLE
Unrecognized directive

### ISSUE THREAD

**Issue by spouradrix** [greenpau/caddy-auth-portal#176]
Hi,

I have the following config
```
(secure) {
      jwt {
        path /
        redirect https://auth.mywebsite.com/login?backTo=https://{host}{uri}
      }
    }


{
    email email@mail.com
}

 auth.mywebsite.com {
       login {
          simple username=password
          jwt_expiry 24h
          redirect_check_referer false
          redirect_host_file /root/.caddy/hosts
          cookie_expiry 2400h
          cookie_domain mywebsite.com
 }
    }

service.mywebsite.com {
    import secure
    reverse_proxy service:port
}


````

When I do docker-compose, there is no issue with the jwt block but I get:
`unrecognized directive: login`
`unrecognized directive: simple`

By the way if it is relevant I build the docker image with this:
```
RUN xcaddy build \
    --with github.com/greenpau/caddy-auth-jwt \
    --with github.com/greenpau/caddy-auth-portal
```

I found the code multiple times online and I really don't understand what I'm supposed to do to make this simple config work. If someone could help me out, that'd be great. Thanks,

**Comment by greenpau** [comment]
@spouradrix , you have a config from some other plugin.

Use the following config:

https://github.com/greenpau/caddy-auth-portal/issues/175#issuecomment-927305564

and read the README.md for both portal and jwt plugins.

**Comment by spouradrix** [comment]
Thank you. It’s really strange as It links to this repo and was written in May 2021 but your confit works. Thanks a lot for the assistance, I’ve been looking for this kind of plug-in for a long time.

**Comment by spouradrix** [comment]
I tried this on Docker and I'm getting:
```
caddy_1  | handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'authentication': provision http.handlers.authentication: loading authentication providers: module name 'jwt': provision http.authentication.providers.jwt: found more than one primaryInstance instance of the plugin for default context

My code is exactly as explained in the other issue:

```
{
    order jwt before reverse_proxy
    order authp before jwt
}



auth.mywebsite.com {
  route {
    authp {
      backend local /etc/caddy/users_db.json local
      cookie domain mywebsite.com
      ui {
        links {
          "Code-Server" https://code.mywebsite.com
          "Jupyter"  https://jupyter.mywebsite.com
        }
      }
      transform user {
        match origin local
        action add role authp/user
      }
    }

  }
}




service.mywebsite.com {
     jwt {
      primary yes
      allow roles authp/admin authp/user
      set auth url https://auth.mywebsite.com
    }
    reverse_proxy service:port
}

```

Would you know what's going on?

**Comment by greenpau** [comment]
Remove the following and retry:

{
    order jwt before reverse_proxy
    order authp before jwt
}

**Comment by greenpau** [comment]
@spouradrix , if you have many places where you specify “jwt”, please re-read jwt README.md about the meaning of “primary yes”. Hint, you should probably have a single primary instance.

**Comment by spouradrix** [comment]
It is now perfectly working, thanks. The issue was not due to the order directive or the primary yes being at multiples places, it was that when my config had a bug, each time I started my container the config file inside it didn't have time to be updated so my modifications were never applied.

**Comment by helmut72** [comment]
Hello, I don't get it. For many hours last days. I've tried so many examples, I feel like I'm in a vortex. Now started again with this example, removed `order jwt...`, but always get an `unrecognized directive: jwt`.

Building Caddy with '--with github.com/greenpau/caddy-auth-jwt' isn't possible (anymore?):

```
2022/01/01 21:01:04 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/greenpau/caddy-auth-jwt 
go: downloading github.com/greenpau/caddy-auth-jwt v1.3.22
go get: github.com/greenpau/caddy-auth-jwt@v1.3.22: parsing go.mod:
	module declares its path as: github.com/greenpau/caddy-authorize
	        but was required as: github.com/greenpau/caddy-auth-jwt
2022/01/01 21:01:06 [FATAL] exit status 1
```

Even opening the website `github.com/greenpau/caddy-auth-jwt` in a browser redirects me to `caddy-authorize`. Does the plugin still exists? Also directive `jwt`? Or was there a rename in the last weeks?

Documentation at `https://authp.github.io/docs/authorize/intro` doesn't help much. Searching for `jwt` doesn't show any single example like in the configuration above:
```
service.mywebsite.com {
     jwt {
      primary yes
      allow roles authp/admin authp/user
      set auth url https://auth.mywebsite.com
    }
    reverse_proxy service:port
}
```

But when searching for `jwt` in the issues, I get so many configuration examples. Also this one. I really feel lost. :(

**Comment by greenpau** [comment]
@helmut72 , the `jwt` was replaced by `authorize`. See https://github.com/greenpau/caddy-authorize/issues/86

**Comment by helmut72** [comment]
Thanks, this helps a lot. Now my config starts working a bit and need to figure out the details :)
