### ISSUE TITLE
breakfix: Logout not working 

### ISSUE THREAD

**Issue by basharatusman** [greenpau/caddy-auth-portal#177]
**Describe the issue**

I'm using Keycloak as the Oauth2 provider. I'm able to secure my route, login to the portal and see the ui links. The issue is that once I click logout, I come back to the login screen and if I click login, it logs me in without asking for credentials. 

The access token cookie clears but the auth session remains.

![Screen Shot 2021-10-04 at 1 29 19 PM](https://user-images.githubusercontent.com/65037474/135897546-7320278f-3e5a-442f-a75f-6aff1c0be6d2.png)

Caddy picks up the correct end_session endpoints. If I enter the end_session endpoint manually with the redirect_uri back to /auth/logout it seems to work.

**Configuration**

```
{$BASE_WEB_ADDRESS} {
  route /auth* {
     authp { 
      ui {
	links {
	  "Kibana" /kibana
	 }
	}	 
      backends {
        keycloak_backend {
          method oauth2
          realm {$OAUTH_REALM}
          provider generic
          client_id {$OAUTH_CLIENT}
	  client_secret {$OAUTH_SECRET}
          metadata_url {$OAUTH_META_URL} 
	  base_auth_url {$OAUTH_BASE_URL}
          scopes {$OAUTH_SCOPES}
          identity_token_name {$OAUTH_TOKEN}
        }
       }
      }
     }

  route /kibana* {
    jwt {
      primary yes
      allow roles authp/admin authp/user
      validate bearer header
      set auth url /auth
      inject headers with claims
    }
    uri strip_prefix /kibana
    reverse_proxy kibana:{$PORT}
  }

The expected behaviour would be for the logout button to end the session and require reauthentication.

**Comment by greenpau** [comment]
@basharatusman , please reopen in [github.com/greenpau/caddy-security](https://github.com/greenpau/caddy-security/issues/new/choose) if this is still relevant for you. Please consider sponsoring the work on the project! 👍
