### ISSUE TITLE
Request email from Facebook backend

### ISSUE THREAD

**Issue by benroy73** [greenpau/caddy-auth-portal#181]
**Describe the issue**

When using the Facebook backend it does not request permission to get the email address even when "scopes email" is set in the config.

**Configuration**

Paste full `Caddyfile` below:

```
{
    admin off
}
:8888 {

  route /auth* {
    authp {
      backends {
        facebook_oauth2_backend {
          method oauth2
          realm facebook
          provider facebook
          client_id XXX
          client_secret YYY
          scopes email
        }
      }

      transform user {
        exact match origin facebook
        exact match mail user@example.com
        action add role authp/user authp/admin
      }

      ui {
        links {
          "App" /private
          "User" /private/user
          "Admin" /private/admin
          "My Identity" /auth/portal/whoami
        }
      }
    }

  }

  route /public {
    respond * "hello" 200
  }

  route /private {
    jwt {
      primary yes
      set auth url /auth
      allow roles authp/admin authp/user
    }
    respond * "welcome authorized user" 200
  }

  route /private/user {
    jwt
    respond * "welcome authorized user" 200
  }

  route /private/admin {
    jwt {
      allow roles authp/admin
    }
    respond * "welcome admin user" 200
  }

}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.4.5
http.authentication.hashes.scrypt v2.4.5
http.authentication.providers.http_basic v2.4.5
http.handlers.authentication v2.4.5
http.authentication.providers.jwt v1.3.16
http.handlers.authp v1.4.24
```

**Expected behavior**

I would expect that setting "scopes email" in the Facebook backend config would cause the permission to be requested and if the user approve it would be available in "exact match mail" for user transforms. 

**Additional context**

When I use the explorer portal https://developers.facebook.com/tools/explorer/?method=GET&path=me%3Ffields%3Did%2Cname%2Cemail&version=v12.0
it does prompt for permission and provide the email address. 

It looks like the caddy-auth-portal uses this URL https://www.facebook.com/v8.0/dialog/oauth?client_id=&redirect_uri=&state=XXX

And the FB explorer uses this URL https://www.facebook.com/v12.0/dialog/oauth?response_type=token&display=popup&client_id= XXX&redirect_uri=XXX&auth_type=rerequest&scope=public_profile%2Cemail

When I add "&scope=public_profile%2Cemail" to my caddy URL it prompts for email permission so I think that this line might be the reason it's not including the scope for Facebook backends. It also looks like "b.disableScope = true" is only used for Facebook, so maybe there is another reason to keep this line.
https://github.com/greenpau/caddy-auth-portal/blob/13fb8dfd37a773ea1ded2cf23bcd703b3450f3b0/pkg/backends/oauth2/configure.go#L209

The discussion in https://github.com/greenpau/caddy-auth-portal/issues/136 was helpful in getting the email permission added correctly to my app.

**Comment by greenpau** [comment]
@benroy73 , working on it now.

Note: The versions are https://developers.facebook.com/docs/graph-api/changelog/versions/
Currently, the latest is v12.0

**Comment by greenpau** [comment]
@benroy73 , once I release the new version you should be fine. By default, the scopes are `public_profile`, `email`.

Also, instead of this:

```
      backends {
        facebook_oauth2_backend {
          method oauth2
          realm facebook
          provider facebook
          client_id XXX
          client_secret YYY
          scopes email
        }
      }
```

Per [Shortcuts](https://github.com/greenpau/caddy-auth-portal#shortcuts), you could do this:

```
backend facebook <client_id> <client_secret>
```

**Comment by greenpau** [comment]
@benroy73 , additionally, I suggest you match on "sub" field in your transforms. It will be more appropriate.

```
      transform user {
        match origin facebook
        action add role authp/user
      }

      transform user {
        match origin facebook
        match sub 1015891985
        action add role authp/admin
      }
```

**Comment by benroy73** [comment]
Thanks Paul! The diff looks great and I appreciate your config tips. This is a great project you've created and continue to maintain.
