### ISSUE TITLE
Auth redirect on assets

### ISSUE THREAD

**Issue by mikenholt** [greenpau/caddy-auth-portal#185]
**Describe the issue**

I am not able to successfully `reverse_proxy` a service to my domain because it seems the ui assets are being redirected to the auth portal.

**Configuration**

```
{
  debug
}

example.com {
  tls email@address.com {
    dns cloudflare xxx
  }

  route /auth* {
    authp {
      crypto default token lifetime 3600
      crypto key sign-verify some_key
      backends {
        local_backend {
          method local
          path /etc/caddy/auth/local/users_db.json
          realm local
        }
      }
      ui {
        links {
          "Nomad" /nomad
        }
      }
    }
  }

  route /nomad* {
    authorize {
      primary yes
      crypto key verify some_key
      set auth url /auth
      allow roles authp/admin
    }
    uri strip_prefix /nomad
    rewrite * /ui/
    reverse_proxy 127.0.0.1:4646
  }

  route {
    redir https://{hostport}/auth 302
  }
}
```

**Version Information**

```
http.authentication.hashes.bcrypt v2.4.5
http.authentication.hashes.scrypt v2.4.5
http.authentication.providers.http_basic v2.4.5
http.handlers.authentication v2.4.5
http.authentication.providers.authorize v1.3.17
http.handlers.authp v1.4.25
```

**Expected behavior**

Expect the webpage to render.

**Additional context**

I basically took the Prometheus example and added `rewrite * /ui/` since this service serves everything with `ui/` as the base. 

With this config I can login successfully but when I click the link in the ui it renders a blank screen. Looking at the network traffic I see the the html file at `127.0.0.1:4646/ui` is successfully served, but all referenced assets within the file are redirected: 

![image](https://user-images.githubusercontent.com/22593495/138252654-f463810f-07e2-455c-888b-d588bed8c617.png)

The path for these assets is `127.0.0.1:4646/ui/assets/{file_name}`. 

I would just like everything at `127.0.0.1:4646/ui/*` to be proxied. I'm new to caddy so I am sure this is something simple.

**Comment by greenpau** [comment]
Remove the below and retry

cookie path /
  cookie samesite lax
  cookie lifetime 3600

**Comment by mikenholt** [comment]
@greenpau 

Okay tried that and same behavior.
