### ISSUE TITLE
feature: caddy-auth-portal as a simple OpenID Connect (OIDC) provider

### ISSUE THREAD

**Issue by CaringCat** [greenpau/caddy-auth-portal#188]
Just an idea.

Many self-hosted service already have OIDC integrations built-in, if caddy-auth-portal can also provide OIDC authentication to other service, it can eliminated the need to find other OIDC backends.

**Comment by greenpau** [comment]
@CaringCat , please reopen in [github.com/greenpau/caddy-security](https://github.com/greenpau/caddy-security/issues/new/choose) if this is still relevant for you. Please consider sponsoring the work on the project! 👍
