### ISSUE TITLE
question: Is there a tool for adding more users to the local backend?

### ISSUE THREAD

**Issue by andoks** [greenpau/caddy-auth-portal#191]
**Describe the issue**

As an administrator I wish to add more users in the local_backend users.json database.

My question is: Is there is a tool or web-page to do this (as an admin)?

I know of the `/auth/register` endpoint, but this seems to primarily be meant for users to register themselves, and then the administrator has to acknowledge the registration by moving the entries from the registration json file to the users json file manually using a text-editor, then restarting caddy for the changes to take effect. Is this correct?

The way to add new users I have found is to simply copy-paste the existing entry and change it.

https://authp.github.io/docs/authenticate/local/identity-store

**Configuration**

N/A

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
/app # caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.4.5
http.authentication.hashes.scrypt v2.4.5
http.authentication.providers.http_basic v2.4.5
http.handlers.authentication v2.4.5
http.authentication.providers.authorize v1.3.19
http.handlers.authp v1.4.27
/app # 

```

**Expected behavior**

N/A

**Additional context**

Building caddy manually with auth-portal and authorize plugins, inspired by the Dockerfile in caddy-auth-portal repo

**Comment by greenpau** [comment]
> My question is: Is there is a tool or web-page to do this (as an admin)?

@andoks , I am working on it. It should come in the next couple weeks.

**Comment by andoks** [comment]
@greenpau thank you, that will be great! And thank you for your work so far too, auth-portal+authorize was a huge improvement over caddy's built-in basic auth.

**Comment by greenpau** [comment]
@andoks , please reopen in [github.com/greenpau/caddy-security](https://github.com/greenpau/caddy-security/issues/new/choose) if this is still relevant for you. Please consider sponsoring the work on the project! 👍 

With the migration to `caddy-security`, we are now much closer to achieve this.
