### ISSUE TITLE
ldap: ignore_cert_errors does not work or doc is unclear

### ISSUE THREAD

**Issue by resmo** [greenpau/caddy-auth-portal#192]
First, thanks for auth portal!

**Describe the issue**

LDAP backend docs says:

> The plugin DOES NOT ignore certificate errors when connecting to the servers. However, one may ignore the errors by setting `ignore_cert_errors` to `true`.

But it is unclear where to add it and everywhere I added it, caddy failed to start.

```
2021/11/05 09:55:10.117 INFO    using provided configuration    {"config_file": "/etc/caddy/Caddyfile", "config_adapter": ""}
run: adapting config using caddyfile: parsing caddyfile tokens for 'route': /etc/caddy/Caddyfile:37 - Error during parsing: parsing caddyfile tokens for 'authp': /etc/caddy/Caddyfile:12 - Error during parsing: auth backend ldap_backend subdirective ignore_cert_errors is unsupported
```

**Configuration**

Paste full `Caddyfile` below:

```
:8080 {
  route /auth* {
    authp {
      crypto key sign-verify ...
      crypto default token lifetime 3600
      cookie domain example.com
      cookie samesite lax
      backends {
        ldap_backend {
          method ldap
          realm example.com
          ignore_cert_errors true
          servers {
            ldaps://ad1.example.com
          }
          
          attributes {
            name givenName
            surname sn
            username sAMAccountName
            member_of memberOf
            email mail
          }
          username "CN=admin,OU=users,OU=_example,DC=example,DC=com,"
          password "secret"
          # password "file:/etc/caddy/auth/ldap.secret"
          search_base_dn "OU=_example,DC=example,DC=com"
          search_filter "(&(|(sAMAccountName=%s)(mail=%s))(objectclass=user))"
          groups {
            "OU=_example,DC=example,DC=com" viewer
          }
        }
      }
    }
  }

  route {
    authorize {
      primary yes
      crypto key verify ...
      set auth url /auth
      allow roles viewer
    }

    file_server browse {
      root /mnt/
    }
  }
}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.4.5
http.authentication.hashes.scrypt v2.4.5
http.authentication.providers.http_basic v2.4.5
http.handlers.authentication v2.4.5
http.authentication.providers.authorize v1.3.19
http.authentication.providers.jwt v0.5.0
http.handlers.authp v1.4.27
```

**Expected behavior**

docs would be clearer where to add it

**Comment by greenpau** [comment]
@resmo , thank you for the issue! I will fix the docs today and also provide some additional advice on the config

Here is what you need:

servers {
  ldaps//foo.bar.com ignore_cert_errors
}

**Comment by greenpau** [comment]
@resmo , updated [LDAP Configuration](https://authp.github.io/docs/authenticate/ldap/ldap) section of the docs. Note the `openssl s_client -showcerts` script. You might want to consider using `trusted_authority` after you confirmed everything is working with `ignore_cert_errors`.

Please see inline comments to your configuration.

Remove the `ignore_cert_errors`.

```
          # ignore_cert_errors true
```

It is best adding the `trusted_authority ` directive:

```
          servers {
            ldaps://ad1.example.com
            trusted_authority path/to/pem/file
          }
```          
Here, the attributes map you specified is the default attribute mapping.

https://github.com/greenpau/caddy-auth-portal/blob/e58ef214cbf3808d991fde5cc184a927609f381f/pkg/backends/ldap/authenticator.go#L181-L195

Therefore, you could remove the `attributes` directive completely.

```
          attributes {
            name givenName
            surname sn
            username sAMAccountName
            member_of memberOf
            email mail
          }
```

The `search_filter` is the default. It is being set here. Thus, you could remove it from your configuration.

https://github.com/greenpau/caddy-auth-portal/blob/e58ef214cbf3808d991fde5cc184a927609f381f/pkg/backends/ldap/authenticator.go#L179

```
          search_filter "(&(|(sAMAccountName=%s)(mail=%s))(objectclass=user))"
```

**Comment by greenpau** [comment]
@resmo , also, please let me know if you run into any other issue! Please blog and tweet about your design! 😃
