### ISSUE TITLE
question: setting default redirect_url in authorize context

### ISSUE THREAD

**Issue by drkstr101** [greenpau/caddy-auth-portal#193]
Hello, again my friend, cheers on the documentation upgrade! 

**Describe the issue**

I would like to integrate with client-side auth using the same OAuth2 provider, google in this case. Client-side auth is done using `@supabase-js/auth`, which I believe I can achieve by sending auth token to https://[DATABASE_NAME].supabase.co/auth/v1/callback before forwarding to the desired redirect_url from query params. Both systems happen to accept the same auth_token query param, so I lucked out there.

A clear and concise description of what the issue is.

There is no issue, for the time being, I can work around the issue by disabling caddy auth on client "app" routes.

I was just hoping for your thoughts on the best way to shoehorn in a 3rd party with as little disruption as possible.

Cheers, and thank you for your time!

**Configuration**

Paste full `Caddyfile` below:

```
{
  # Uncomment to remove rate limit
  # acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
  email admin@watheia.org
  http_port 80
  https_port 443
}

2604:a880:4:1d0::19:4000, 143.110.235.219, microbase.dev {
  # Serve static assets
  root * /var/www/assets
  file_server

  # Serve the auth portal frontend
  route /auth* {
    authp {
      ui {
        theme basic
        template login "/etc/gatekeeper/assets/templates/basic/login.template"
        template portal "/etc/gatekeeper/assets/templates/basic/portal.template"
        logo url "https://cdn.watheia.org/assets/icon.png"
        logo description "Gatekeeper"
        links {
          "Whoami" /auth/whoami icon "las la-star"
          "Account" /auth/settings icon "las la-cog"
          "Workspace" "/#/workspace/watheia"
        }
      }

      backends {
        google_oauth2_backend {
          method oauth2
          realm google
          provider google
          client_id [semi-secret]
          client_secret [secret]
          scopes openid email profile
        }
      }

      transform user {
        match origin google
        action add role authp/user
      }
    }
  }

  route * {
    authorize {
      primary yes
      set auth url /auth/login
      allow roles authp/admin authp/user
      allow roles superadmin
       enable js redirect
      # I tried adding a redir_url here...
    }
    
    @websockets {
      header Connection *Upgrade*
      header Upgrade    websocket
    }
    reverse_proxy @websockets http://localhost:9229
    reverse_proxy * http://localhost:4200
  }
}

# redirect to app
www.microbase.dev {
  redir https://microbase.dev/ 307
}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.4.5
http.authentication.hashes.scrypt v2.4.5
http.authentication.providers.http_basic v2.4.5
http.handlers.authentication v2.4.5
http.authentication.providers.authorize v1.3.18
http.handlers.authp v1.4.26
```

**Comment by greenpau** [comment]
> Hello, again my friend, cheers on the documentation upgrade!

@drkstr101, thank you! I think when I moved the docs to a single website without search, people started asking questions :-) which is a good thing! Will try to respond as fast as I can and improve the docs too.

> Both systems happen to accept the same auth_token query param, so I lucked out there.

Need more clarity here. What I describe below may not be the right answer here.

Generally, the query parameters come into play with `caddy-authorize` plugin in 2 cases:

* [Token discovery](https://authp.github.io/docs/authorize/token-discovery):  the `set token sources`  directive defines where to look for tokens. If you want to disable query parameter lookup, then you set to rely on cookies and header only: `set token sources header cookie`.
* Redirect to something that would authenticate a user. Please read [here](https://authp.github.io/docs/authorize/auto-redirect-url) about `set redirect query parameter`, which allows you to change from `redirect_url` to something else

Note: I noticed in the `#` in `/#/workspace/watheia`. There is a special use case, where you can redirect with Javascript. See [Javascript Redirect](https://authp.github.io/docs/authorize/auto-redirect-url#javascript-redirect) and review this [code](https://github.com/greenpau/caddy-authorize/blob/main/pkg/handlers/js_redirect.go#L22-L42).

---

Now, some feedback on your config. It is mostly readability.

### Use Shortcuts

Shortcuts: https://authp.github.io/docs/authenticate/misc#shortcuts

You can replace this:

```
      backends {
        google_oauth2_backend {
          method oauth2
          realm google
          provider google
          client_id [semi-secret]
          client_secret [secret]
          scopes openid email profile
        }
      }
```

With (no need to encapsulate in `backends`):

```
      backend google <client_id> <client_secret>
```

### Use Transforms for Some Links

User Transforms: https://authp.github.io/docs/authenticate/user-transforms

```
  route /auth* {
    authp {
      ui {
...
        links {
          "Whoami" /auth/whoami icon "las la-star"
          "Account" /auth/settings icon "las la-cog"
        }
      }
      transform user {
        match origin google
        action add role authp/user
        ui link "Workspace" "/#/workspace/watheia" icon "las la-code-branch"
      }
```

**Comment by greenpau** [comment]
@drkstr101 , you can also disable redirect with `disable auth redirect` and handle it with client-side app.

**Comment by greenpau** [comment]
@drkstr101 please reopen in [github.com/greenpau/caddy-security](https://github.com/greenpau/caddy-security/issues/new/choose) if this is still relevant for you. Please consider sponsoring the work on the project! 👍
