### ISSUE TITLE
question: Installation method

### ISSUE THREAD

**Issue by ClemontX** [greenpau/caddy-auth-portal#194]
> A clear and concise description of what you want to accomplish.

Hello there, is there a installation procedure documented somewhere?
If not, can someone give me a hint, how to install the plugin?

KR
Carl

**Comment by greenpau** [comment]
@ClemontX , I will update docs later.

1. Download windows or linux binary from README.md page link
2. Follow manual build procedure at https://github.com/greenpau/caddy-auth-portal/blob/main/CONTRIBUTING.md#development-environment

**Comment by greenpau** [comment]
@ClemontX , you could also use Caddy download pagecand select relevant plugins. https://caddyserver.com/download

The links at README.md page are simply shortcuts to Caddy downloads.

**Comment by ClemontX** [comment]
Thank you @greenpau .
And sorry for the maybe dumb question.
I'm new to Caddy :D 

KR

**Comment by greenpau** [comment]
@ClemontX , i recommend visiting https://caddy.community where you can find help around generic caddy questions.
