### ISSUE TITLE
question: Auth and application on separate domains

### ISSUE THREAD

**Issue by TheSilkky** [greenpau/caddy-auth-portal#197]
> A clear and concise description of what you want to accomplish.

The application I'm trying to deploy doesn't support running on a sub directory (eg. `domain.com/portainer`). Is it possible to run the authentication and application on separate domains? I tried using this Caddyfile:
```
admin.silkky.cloud {
	import default

	route /auth* {
		authp {
			backends {
				github_oauth2_backend {
					method oauth2
					realm github
					provider github
					client_id {env.GITHUB_CLIENT_ID}
					client_secret {env.GITHUB_CLIENT_SECRET}
					scopes user
				}
			}
			transform user {
				exact match sub github.com/TheSilkky
				action add role superadmin
				ui link "Portainer" https://portainer.silkky.cloud
			}
		}
	}

	#route /portainer* {
	#	authorize {
	#		set auth url /auth
	#		allow roles superadmin
	#	}
	#
	#	uri strip_prefix /portainer
	#	reverse_proxy http://portainer:9000
	#}
}

portainer.silkky.cloud {
	import default

	authorize {
		set auth url admin.silkky.cloud/auth
		allow roles superadmin
	}

	reverse_proxy http://portainer:9000
}
```

When I deploy I get this error:
`directive 'authorize' is not ordered, so it cannot be used here`

**Comment by TheSilkky** [comment]
Fixed using `route`

**Comment by greenpau** [comment]
@TheSilkky , one other thing. Your setup has multiple hosts in a single domain. You need to use “cookie domain” directive. Without it, you would be able to authenticate, but will have errors going to portainer.silkky.cloud

Please see sample config file.

https://github.com/greenpau/caddy-auth-portal/blob/main/assets/conf/local/multihost/Caddyfile
