### ISSUE TITLE
various auth features in the golang package "authelia"

### ISSUE THREAD

**Issue by joe-getcouragenow** [greenpau/caddy-auth-portal#20]
Have you seen this ?

https://github.com/authelia/authelia

as it says on the box "The Single Sign-On Multi-Factor portal for web apps"

I have not had a chance to really dig into it but its supports hardware yubikeys and OTP

I figured you might be interested in this.

The first thing i thought iof was " Caddy is not on the list of proxies". Bummer.

**Comment by joe-getcouragenow** [comment]
Opps looks like your already thinking about it: https://github.com/authelia/authelia/issues/1248

**Comment by samyak-jain** [comment]
Hey @greenpau, I was reading your conversation at authelia/authelia#1248 and it is not clear to me how we can intergrate this plugin with authelia. Do you mind shedding some light into how that would exactly work?

**Comment by greenpau** [comment]
@samyak-jain , idk. I never installed `authelia`.
