### ISSUE TITLE
question: Disable Authorization header?

### ISSUE THREAD

**Issue by TheSilkky** [greenpau/caddy-auth-portal#200]
> A clear and concise description of what you want to accomplish.

The application I'm deploying uses the Authorization header for it's own internal auth, this conflicts with authp and causes 401 errors. Is it possible to completely disable authp from using the Authorization header?

I tried using `set token sources cookie` however this seems to only affect caddy-authorize.

Caddyfile:
```
admin.silkky.cloud {
	import secureheader

	route /auth* {
		authp {
			cookie domain silkky.cloud
			backend github {env.GITHUB_CLIENT_ID} {env.GITHUB_CLIENT_SECRET}
			transform user {
				exact match sub github.com/TheSilkky
				action add role authp/admin
				ui link "Portainer" https://portainer.silkky.cloud
				ui link "Grafana" /grafana
				ui link "Prometheus" /prometheus
			}
		}
	}

	route /grafana* {
		authorize {
			set auth url /auth
			allow roles authp/admin
			enable js redirect
		}

		reverse_proxy http://grafana:3000
	}

	route /prometheus* {
		authorize {
			set auth url /auth
			allow roles authp/admin
		}

		reverse_proxy http://prometheus:9090
	}

	route {
		redir https://admin.silkky.cloud/auth 302
	}
}

portainer.silkky.cloud {
	import secureheader

	route {
		authorize {
			primary yes
			set auth url https://admin.silkky.cloud/auth
			set token sources cookie
			allow roles authp/admin
			enable js redirect
		}

		reverse_proxy http://portainer:9000
	}
}

```

**Comment by greenpau** [comment]
> The application I'm deploying uses the Authorization header for it's own internal auth, this conflicts with authp and causes 401 errors. Is it possible to completely disable authp from using the Authorization header?

@TheSilkky , please help me understand the issue here. Is the issue with `authorize` plugin? How does the issue manifest itself (e.g. i browse to x, and see y)?

**Comment by TheSilkky** [comment]
Portainer uses the Authorization header for it's default accounts system, that conflicts with authp and causes errors to occur in Portainer, such as: `http error: Invalid JWT token (err=Invalid JWT token) (code=401)"`. When using Cloudflare it usually results in a timeout. (I've also seen issues with Grafana).

**Comment by greenpau** [comment]
> Portainer uses the Authorization header for it's default accounts system, that conflicts with authp and causes errors to occur in Portainer, such as: http error: Invalid JWT token (err=Invalid JWT token) (code=401)".

@TheSilkky , are the also using `access_token` as key identifier? 

Try setting `crypto default token name authtoken` in the following way:

```
admin.silkky.cloud {
	import secureheader

	route /auth* {
		authp {
			cookie domain silkky.cloud
			crypto default token name authtoken
			backend github {env.GITHUB_CLIENT_ID} {env.GITHUB_CLIENT_SECRET}
			transform user {
				exact match sub github.com/TheSilkky
				action add role authp/admin
				ui link "Portainer" https://portainer.silkky.cloud
				ui link "Grafana" /grafana
				ui link "Prometheus" /prometheus
			}
		}
	}

	route /grafana* {
		authorize {
			set auth url /auth
			allow roles authp/admin
			enable js redirect
		}

		reverse_proxy http://grafana:3000
	}

	route /prometheus* {
		authorize {
			set auth url /auth
			allow roles authp/admin
		}

		reverse_proxy http://prometheus:9090
	}

	route {
		redir https://admin.silkky.cloud/auth 302
	}
}

portainer.silkky.cloud {
	import secureheader

	route {
		authorize {
			primary yes
                        crypto default token name authtoken
			set auth url https://admin.silkky.cloud/auth
			set token sources cookie
			allow roles authp/admin
			enable js redirect
		}

		reverse_proxy http://portainer:9000
	}
}
```

Try it and let me know what you see.

**Comment by TheSilkky** [comment]
Seems like that completely broke things, now I'm getting 502 errors with trying to load anything. 

I've done some digging and I'm starting to think this not related to authp at all, it looks like `http error: Invalid JWT token (err=Invalid JWT token) (code=401)"` is a normal startup warning with Portainer. I think there is something wrong with my Portainer configuration.

**Comment by TheSilkky** [comment]
Sorry for any confusion, I think this is configuration problem for me.

**Comment by greenpau** [comment]
@TheSilkky , please help with promoting this project!

* Blog about your Caddy setup with auth plugins at https://github.com/authp/authp.github.io/tree/main/blog
* Promoting the plugins on Twitter by referencing the above repos and mentioning @caddyserver and @GreenbergTech
