### ISSUE TITLE
question: LDAP anonymous bind & custom group matching

### ISSUE THREAD

**Issue by hoefling** [greenpau/caddy-auth-portal#202]
Hi, I'm trying out the LDAP backend and have two questions:

1. Is anonymous binding supported? It should be just a simple auth with empty ("zero-length") username and password, but neither omitting `username`/`password` fields nor setting them to empty strings doesn't do, resulting in an `failed configuring user credentials for LDAP binding	{"error": "no username found"}`:
   ```
   backends {
       ldap_backend {
           method ldap
           ...
           username ""
           password ""
      }
   }
   ```
2. The `memberOf` attribute requires the `memberOf` overlay, but the server I'm authenticating against uses POSIX groups (so `uid`/`memberUid` attributes are used instead of `memberOf`/`member`). Can I customize group search for roles assignment?

**Comment by greenpau** [comment]
@hoefling , thank you for the issue! Did you see attributes mapping that you can reconfigure?

https://github.com/greenpau/caddy-auth-portal/blob/1ade689edd5b6ead24517ad6b8226d5a7dde9ed2/assets/conf/ldap/Caddyfile#L23

**Comment by greenpau** [comment]
@hoefling , in https://github.com/greenpau/caddy-auth-portal/issues/125 @terefang mentioned this insecure LDAP server for testing purposes. I think it uses POSIX. I will create a demo config for that server. Perhaps, you could benefit from it too.

**Comment by hoefling** [comment]
@greenpau no worries, let me add some more details. For the anonymous bind: as stated e.g. [here](https://ldapwiki.com/wiki/Simple%20Authentication#section-Simple+Authentication-AnonymousAuthenticationMechanismOfSimpleBind):

> An LDAP client may use the anonymous authentication mechanism of the simple Bind method to explicitly establish an anonymous authorization state by sending a Bind request with a name value of zero length and specifying the simple authentication choice containing a password value of zero length.

This is not supported as of now, correct?

**Comment by hoefling** [comment]
Regarding the POSIX groups. If I read the code correctly, the only use case that is supported right now for group search is the `memberOf` overlay. So the database looks roughly like this:
```ldif
# user
dn: uid=aadams,ou=users,dc=example,dc=com
objectClass: top
objectClass: inetOrgPerson
uid: aadams
givenName: Alice
sn: Adams
cn: Alice Adams
mail: aadams@example.com
memberOf: cn=admins,ou=groups,dc=example,dc=com

# group
dn: cn=admins,ou=groups,dc=example,dc=com
objectClass: top
objectClass: groupOfNames
cn: admins
member: uid=aadams,ou=users,dc=example,dc=com
```
We have a user `aadams` that belongs to the group `admins`.

There are other configurations possible though. For example, using POSIX groups you'd have a database

```ldif
# user
dn: uid=aadams,ou=users,dc=example,dc=com
objectClass: top
objectClass: inetOrgPerson
objectClass: posixAccount
uid: aadams
uidNumber: 1001
givenName: Alice
sn: Adams
cn: Alice Adams
mail: aadams@example.com

# group
dn: cn=admins,ou=groups,dc=example,dc=com
objectClass: top
objectClass: posixGroup
cn: admins
memberUid: aadams
```
so there's no way to to do the group search just by assigning `member_of` to `uid` or whatever.

**Comment by greenpau** [comment]
> This is not supported as of now, correct?

@hoefling, let me read through it and I will try figuring it out. I have lots of experience with Microsoft AD, and need to get on top of what we have here.

Currently, I will try making the https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/ work. This requests some amendments to the current code to allow insecure LDAP, i.e. non-TLS.

**Comment by greenpau** [comment]
@hoefling, I get the issue now.

> Regarding the POSIX groups. If I read the code correctly, the only use case that is supported right now for group search is the memberOf overlay. So the database looks roughly like this:

This is correct.

> There are other configurations possible though. For example, using POSIX groups you'd have a database

Let me implement a shim for this. The LDAP server in #125 also uses POSIX group, but identifies users by `uniqueMember` instead of `memberUid` (see [here](https://github.com/greenpau/caddy-auth-portal/issues/125#issuecomment-973131567))

**Comment by greenpau** [comment]
@hoefling , I think with the release of [v1.4.29](https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.4.29). You should be good to go here.

* added a section to docs: https://authp.github.io/docs/authenticate/ldap/ldap#posix-groups-integration
* sample configuration file: https://github.com/greenpau/caddy-auth-portal/blob/main/assets/conf/ldap/posix/Caddyfile
  It is actually a working server 😄 

You could add your own `search_group_filter`.
