### ISSUE TITLE
question: Authenticating across domains

### ISSUE THREAD

**Issue by sbrl** [greenpau/caddy-auth-portal#204]
> It's been asked before about authenticating across subdomains in #57. But can it be done across different domains?

So I have a great setup working authenticating against a local backend with multiple different subdomains being secured.

Now, I want to secure a different domain. For example, if my portal / auth domain is `auth.example.com`, and it is already securing say `wiki.example.com`, I now want to secure `something.another.co.uk`. Is this possible at all?

<details>
<summary>Existing caddy config</summary>
<pre><code>
auth.mooncarrot.space {
	route {
		# Ref https://github.com/greenpau/caddy-auth-portal/issues/175#issuecomment-927305564
		authp {
			backend local /srv/caddy/data/users_db.json local
			cookie domain mooncarrot.space
			ui {
				links {
					"User Settings" "/settings" icon "las la-cog"
					"Identity (debug)" "/whoami" icon "las la-bug"
				}
			}
			transform user {
				match origin local
				action add role authp/user
			}
		}
	}
}

*.mooncarrot.space {
	# Ref https://github.com/caddyserver/format-encoder
	log {
		format formatted
	}
	
	tls /etc/letsencrypt-cluster/live/mooncarrot.space/fullchain.pem /etc/letsencrypt-cluster/live/mooncarrot.space/privkey.pem
	
	route {
		jwt {
			primary yes
			allow roles authp/admin authp/user
			set auth url https://auth.mooncarrot.space
	    }
		
		reverse_proxy https://elsewhere.mooncarrot.space:443 {
			#header_down strict-transport-security	"max-age=31536000"
		}
	}
	
	header strict-transport-security	"max-age=31536000"
	header x-frame-options				"SAMEORIGIN"
	header x-xss-protection				"1; mode=block"
	header x-content-type-options		"nosniff"
}
</code></pre>
</details>

...if I just do something like this:

```caddy
sub.anotherdomain.co.uk {
	# Ref https://github.com/caddyserver/format-encoder
	log {
		format formatted
	}
	
	tls /path/to/fullchain.pem /path/to/privkey.pem
	
	route {
		jwt {
			primary yes
			allow roles authp/admin authp/user
			set auth url https://auth.mooncarrot.space
		}
		
		root * /srv/stuff
		file_server
	}
	
	header strict-transport-security	"max-age=31536000"
	header x-frame-options				"SAMEORIGIN"
	header x-xss-protection				"1; mode=block"
	header x-content-type-options		"nosniff"
}
```

....then it redirects in an infinite loop between `sub.anotherdomain.co.uk` and `auth.mooncarrot.space` once I have signed in.

**Comment by greenpau** [comment]
@sbrl , try researching the following and see how it can be useful to you:

Access-Control-Allow-Origin: http://foo.bar.com
Access-Control-Allow-Credentials: true

**Comment by greenpau** [comment]
@sbrl , after re-reading your question, i think it might not be possible.

**Comment by sbrl** [comment]
Hrm, ok. I've tried adding those headers with

```caddy
# ...

	route {
		header "access-control-allow-origin" "https://ci.starbeamrainbowlabs.com"
		header "access-control-allow-credentials" "true"
		
		jwt {
			primary yes
			allow roles authp/admin authp/user
			set auth url https://auth.mooncarrot.space
			#crypto key verify a138a4f3-830e-42f4-bb55-27fd3943c368
			
	    }
		
		reverse_proxy https://fabio.mooncarrot.space:443 {
			#header_down strict-transport-security	"max-age=31536000"
			
		}
		
		
	}

# ....
```

....but it doesn't seem to send the headers in question.

I guess to solve this problem I need to either:

1. Move `ci.starbeamrainbowlabs.com` to be `ci.mooncarrot.space`.
2. Setup a new caddy-auth-portal instance on `auth.starbeamrainbowlabs.com`
3. Use HTTP basic authentication on this domain instead

**Comment by greenpau** [comment]
@sbrl , i would say option 2 is in order.
