### ISSUE TITLE
feature: allow inserting user-specific values from database into custom claims

### ISSUE THREAD

**Issue by andoks** [greenpau/caddy-auth-portal#206]
#151 implements adding arbitrary claims to JWT, this request builds on that in that I would like to source the values for the custom (and standard) claims from the database entry for the specific user (in my case I use the local backend).

In concept this could be similar to how the authorize plugin handle injecting values from [jwt into header variables](https://authp.github.io/docs/authorize/headers#custom-headers), with the difference being that auth-portal injects claims into the JWT from the database.

This could help with usecases like using authp/authorize with Hasura, as it is common to want to use the users ID (independent of changes to email and username) in various user-specific queries ([hasura jwt spec](https://hasura.io/docs/latest/graphql/core/auth/authentication/jwt.html#the-spec))

**Comment by greenpau** [comment]
@andoks , imagine that the feature existed. What would be the caddyfile directives (hypothetically) that would instruct the plugin to do what you want?

The above would help me to develope the feature.

additionally, just to note, the Hasura example would require the injection of “nested” values (this map).

**Comment by andoks** [comment]
@greenpau Based on your example from #151, something like this perhaps? (note: I'm not familiar with quoting rules of arguments to Caddy directives)

```
:443 {
	route /auth* {
		authp {
                       # Elided backend config - uses local
			transform user {
				exact match role hasura-editor
                                action add https://hasura.io/jwt/claims.x-hasura-user-id from id as string
                                action add https://hasura.io/jwt/claims.x-hasura-allowed-roles  ["editor", "user", "mod"] as string list
                                action add https://hasura.io/jwt/claims.x-hasura-default-role user as string
                                action add https://hasura.io/jwt/claims.x-hasura-org-id from org as string
                                action add https://hasura.io/jwt/claims.x-hasura-custom custom as string
                            }
			}
			crypto key sign-verify whatever
		}
	}

	route /* {
		handle /api/ {
			uri strip_prefix /api
			reverse_proxy http://hasura-server:8080
		}
	}
}
```

An alternative could perhaps be to specify custom claims directly in the local backend DB. Maybe this feature only makes sense when using that backend anyway?

**Comment by greenpau** [comment]
> something like this perhaps? (note: I'm not familiar with quoting rules of arguments to Caddy directives)

@andoks , you got it right 👍 You can quote in caddy, e.g. "System Admin".

```
# action add https://hasura.io/jwt/claims.x-hasura-user-id from id as string
action add https://hasura.io/jwt/claims.x-hasura-user-id from jti

# action add https://hasura.io/jwt/claims.x-hasura-allowed-roles  ["editor", "user", "mod"] as string list
action add https://hasura.io/jwt/claims.x-hasura-allowed-roles editor user mod as list

# action add https://hasura.io/jwt/claims.x-hasura-default-role user as string
action add https://hasura.io/jwt/claims.x-hasura-default-role user

# action add https://hasura.io/jwt/claims.x-hasura-org-id from org as string
action add https://hasura.io/jwt/claims.x-hasura-default-role from org

# action add https://hasura.io/jwt/claims.x-hasura-custom custom as string
action add https://hasura.io/jwt/claims.x-hasura-custom custom
```

1. I think "as string" should be the default option when it comes to adding claims.
2. Instead of "as string list", you could also do "as list". I still need to document this [here](https://github.com/authp/authp.github.io/issues/5)
3. Regarding `from id`, it will likely be `jti`.

Additionally, how to instruct the plugin to created "nested entry from `https://hasura.io/jwt/claims.x-FOO`. As you can see there is a number of dots in that string. Thus, having dots as a separator does not work. I am thinking of using "pipe".

```
https://hasura.io/jwt/claims.x-FOO
https://hasura.io/jwt/claims|x-FOO
```

> An alternative could perhaps be to specify custom claims directly in the local backend DB. Maybe this feature only makes sense when using that backend anyway?

It makes sense for all the backends! 👍 Really cool use case you've found.

**Comment by andoks** [comment]
@greenpau, 

> I think "as string" should be the default option when it comes to adding claims.
Reasonable, I have no qualms about being explicit though (unless of course, the only types that will be supported are strings and lists of strings), for documentation purposes. I still find the Caddy directive syntax to be slightly obtuse myself, but maybe this will be alleviated with more experience :sweat_smile: 

> Instead of "as string list", you could also do "as list". I still need to document this here
I agree if the only supported types are to be strings and lists of strings, but if other types are to be supported, being explicit could be preferred IMO

> Regarding from id, it will likely be jti.
As far as I understand it, JTI is the JWT ID (the unique ID of the token  itself), not the ID of the user. What I need is the UUID of the user in question.

**Comment by greenpau** [comment]
@andoks , please reopen in [github.com/greenpau/caddy-security](https://github.com/greenpau/caddy-security/issues/new/choose) if this is still relevant for you.
