### ISSUE TITLE
feature: API for accessing user data by ID (local backend)

### ISSUE THREAD

**Issue by andoks** [greenpau/caddy-auth-portal#210]
In the future I would like to be able to query auth-portal for user information (from the local backend) by providing the users' UUID (similar to this [auth0](https://auth0.com/docs/users/user-search/retrieve-users-with-get-users-by-id-endpoint) API). I want to do this because when/if #206 is implemented, I want to put the users' ID into the token, and store it in the database on certain CRUD operations, and be able to query auth-portal for the username & e-mail for display-purposes, even though these user-properties may have changed since the operation itself happened.

Nice properties of such an API would be:
- being able to put the API in a separate caddy listener block (to be able to block external access entirely, only exposing it internally in a docker network for example)
- having a management secret token that must be passed as a header or similar, to be allowed access

I realize there is the [whoami API](https://authp.github.io/docs/authenticate/misc#user-identity), but if I understand it correctly, this decodes and presents the information in the token being passed only.

Possibly related issue: https://github.com/greenpau/caddy-auth-portal/issues/109#issuecomment-807853755

**Comment by greenpau** [comment]
> I want to do this because when/if #206 is implemented

@andoks , you can now inject custom claims. It happened in #151. The #206 is about injecting custom "nested" claims.

> I realize there is the whoami API, but if I understand it correctly, this decodes and presents the information in the token being passed only.

Yes, including what you may have injected.

> Nice properties of such an API would be:

This would be a separate API service from auth portal. I am working on it in my spare time.

**Comment by greenpau** [comment]
@andoks , please reopen in [github.com/greenpau/caddy-security](https://github.com/greenpau/caddy-security/issues/new/choose) if this is still relevant for you. Please consider sponsoring the work on the project! 👍
