### ISSUE TITLE
question: How to handle Mobile Apps that can't do MFA

### ISSUE THREAD

**Issue by samcro1967** [greenpau/caddy-auth-portal#211]
Curious as to how you would recommend handling mobile apps as an example that are not capable of performing MFA.  Google and Amazon have a way for a user to create a password for this use case that are associated to your user account.  I guess I could create a second user without MFA and only use that for apps that cannot perform MFA.  When I use the WebUI, it will be protected by MFA with the primary account.  The secondary account for mobile apps would then just have a very long and complex password.

For apps that have a separate path for the mobile app, I bypass the URI prefix.  Not all aps have that though.  Looking for your thoughts on the best way to handle.

**Comment by greenpau** [comment]
> Curious as to how you would recommend handling mobile apps as an example that are not capable of performing MFA

@samcro1967 , what do you mean by "mobile apps"? Are you thinking about iOS app?

**Comment by samcro1967** [comment]
Yes, iOS and android apps.  A lot of them you specify a server URL, ID, and password.  There is no way to enter an MFA.  

**Currently my thought on how to handle it is one of these three ways:**
1. Create a single account with a complex password and restrict it to the specific mobile apps only.  Share the account with everyone.  If a user needs to be removed, the password need to be changed and all users have to reconfigure their apps.
2. Create an account per mobile app with a complex password and restrict it to one specific app.  Share the account with everyone who uses that app.  Users then need to user different accounts for different apps.  If a user needs to be removed, all passwords need to be changed and all users need to reconfigure their apps.
3. Create 2 accounts for every user, one with MFA and one with a complex password.  Restrict their mobile account to only the apps that need it.  Probably the best balance between security and user experience.  Just have to remove 2 accounts to remove a user and not disrupt other users.

My only thought for a way to make this a little more straight forward would be to allow a way to create an app password (with mandatory complexity requirements) for existing user accounts.

A user then only has one account.  But then how to handle it on the proxy side?  Maybe create two URL's for a service?  One for web access only and grant privs via MFA and a second URL to grant privs to the app password?   This would not prevent them from using the mobile URL though in a browser and using the app password, but that is probably an acceptable sacrifice unless it could be restricted by OS type.  That is probably a rabbit hole though...

**Comment by greenpau** [comment]
> Yes, iOS and android apps. A lot of them you specify a server URL, ID, and password. There is no way to enter an MFA.

@samcro1967 , I think the best way to handle is ...

1. User opens iOS app and the user is not authenticated
2. iOS app generates a random code (100+ characters long)
3. iOS app opens a browser to `http://auth.contoso.com/mobile/login?code=<random-code>` (that's auth portal address)
4. The user authenticates in the browser. When authenticated, the browser opens a link to iOS app
5. iOS app makes a call to `http://auth.contoso.com/mobile/authorize?code=<random-code>` and received JWT token from the portal. The portal destroy the <random-code> from its cache. It is akin to OTP.

Also, if interested, please see my comments on how to implement API keys. https://github.com/greenpau/caddy-auth-portal/issues/213#issuecomment-1006353208

**Comment by greenpau** [comment]
@PedroDBFlores , @lennartschoch , see if you are interested in the above feature: https://github.com/greenpau/caddy-auth-portal/issues/211#issuecomment-1008049256.
