### ISSUE TITLE
feature: Steam (OpenID 2.0) backend

### ISSUE THREAD

**Issue by deluxghost** [greenpau/caddy-auth-portal#212]
Steam uses old OpenID 2.0, not OIDC, but apparently we can't let a big company upgrade their tech stack 😐 

Document: https://partner.steamgames.com/doc/features/auth

**Comment by greenpau** [comment]
@deluxghost , I think it is possible. It may require some modification in “pkg/backends/oauth”.

**Comment by greenpau** [comment]
The relevant doc is here: https://partner.steamgames.com/doc/webapi_overview/oauth

**Comment by greenpau** [comment]
Please reopen in [github.com/greenpau/caddy-security](https://github.com/greenpau/caddy-security/issues/new/choose) if this is still relevant for you. Please consider sponsoring the work on the project! 👍
