### ISSUE TITLE
question: Local Backend Access Logs

### ISSUE THREAD

**Issue by kirsch33** [greenpau/caddy-auth-portal#220]
I run fail2ban alongside auth-portal and got a notification this morning that fail2ban kicked in for the first time in 15 months, which is good, but still puts me on guard. I have fail2ban and Caddy setup to write logs to the same file, and these are some of the entries I can see for the IP address that was banned:

```
XXX.XXX.XX.XXX - - [07/Jan/2022:12:28:10 +0000] "GET /auth?redirect_url=https://myservice.mywebsite.net/prod/.env HTTP/2.0" 302 0

XXX.XXX.XX.XXX - - [07/Jan/2022:12:28:11 +0000] "GET /auth/login HTTP/2.0" 200 942

XXX.XXX.XX.XXX - - [07/Jan/2022:12:28:11 +0000] "GET /auth/login HTTP/2.0" 200 942

XXX.XXX.XX.XXX - - [07/Jan/2022:12:28:11 +0000] "GET /auth/login HTTP/2.0" 200 942
```

It looks like they first tried accessing a service, and auth-portal redirected them to the login page. They then reloaded the login page multiple times. My question is this: Is there anywhere within caddy-auth-portal to view login attempts as admin? I'd like to know if they were actually attempting to input credentials or just found the portal login page. 

I only have 1 user, and MFA is enabled as a user-transform, so I'm not terribly concerned but also want to be reassured in these instances of what exactly the attempts were trying to achieve so I can adjust my response appropriately. I am using caddy-auth-portal 1.4.36 currently.

**Comment by greenpau** [comment]
> XXX.XXX.XX.XXX - - [07/Jan/2022:12:28:11 +0000] "GET /auth/login HTTP/2.0" 200 942

The login should happen in `/auth/sandbox/<uuid>`. This just tells you that they landed on the login page. Recently, I removed password input from the login page. A user provides a password in the "sandbox". In sum, no authentication happened if you don't see "sandbox" in your logs.

> Is there anywhere within caddy-auth-portal to view login attempts as admin? I'd like to know if they were actually attempting to input credentials or just found the portal login page.

Yes, you would see the following entry.

```
2022/01/07 15:51:52.686 WARN    http.handlers.authp     user authorization checkpoint failed    {"session_id": "7ImdrBbVeCfdinwAaYGUnBBATYtpkFhBLYQCjdkvL4a", "request_id": "c27b2e5d-64d0-4b1a-b580-4eed2be5f674", "error": "Password authentication failed. Please retry"}
```

A user provides a bad password:

![image](https://user-images.githubusercontent.com/3826416/148569705-47c9a098-cceb-4838-9cca-88992dd39cbc.png)

Then, the user gets to attempt (retry) it 4 more time. After that, the sandbox gets closed and the user is back at the login.

![image](https://user-images.githubusercontent.com/3826416/148569625-f946da2f-540a-4776-9d45-5ea147e05ca0.png)

**Comment by greenpau** [comment]
When max attempts gets reached:

![image](https://user-images.githubusercontent.com/3826416/148570009-01a70592-58b9-4822-8aa4-fdb01e2c3877.png)

**Comment by greenpau** [comment]
@kirsch33 , another aspect of it is username. I probably should add user identifier associated with the provided username when logging failed attempts. Don't want to provide username in the logs, because that's not a good practice. Will think how to do it when implementing https://github.com/greenpau/caddy-auth-portal/issues/207
