### ISSUE TITLE
question: Subdomains with GitHub oAuth

### ISSUE THREAD

**Issue by animosity22** [greenpau/caddy-auth-portal#221]
I've got a working setup based on the other documentation for a single site that connects me to GitHub oAuth and works like a charm. 

I'm trying to setup a few sub domains and I've went through too many iterations without much luck.

I was trying to adapt your docs from here:

https://github.com/greenpau/caddy-auth-portal/blob/main/assets/conf/local/multihost/Caddyfile

To work with a github oauth flow and authorization.

My attempt where I thought I was on the right track looked something like:

```
auth.domain.com {
        route /auth* {
                authp {
                        crypto default token lifetime 172800
                        cookie domain domain.com
                        cookie lifetime 172800
                        backend github blah secret
                        transform user {
                                match origin github
                                action add role authp/user
                                ui link "My Website" / icon "las la-star"
                                ui link "My Identity" "/auth/whoami" icon "las la-star"
                        }
                        transform user {
                                match origin github
                                match email some.user@gmail.com
                                action add role authp/admin
                        }
                }
}

apps.domain.com {
 reverse_proxy localhost:8581
                 route /auth* {
                        authorize {
                                primary yes
                                allow roles authp/admin authp/user
                                validate bearer header
                                set auth url /auth/oauth2/github
                                inject headers with claims
                        }
                        respond * "my app" 200
                }
        route /someotherapp* {
                authorize
                reverse_proxy localhost:8181
        }
}

```

I am sure I have a typo in typing it back up with a {} or something but I did have it validated in Caddy.

My end state:
- have auth.domain.com setup for handling all the auth part
- have app1.domain.com app2.domain.com which may contain 0 to many routes in them to serve apps
- tie it all back into auth.domain.com

If you could share a sample config or adjust what I have to get me there, it would be greatly appreciated.

**Comment by greenpau** [comment]
@animosity22 , see if the following config makes sense. Note the `context` keyword.  Please ask follow up questions.


```
auth.domain.com {
        route /auth* {
                authp {
                        crypto default token lifetime 172800
                        cookie domain domain.com
                        cookie lifetime 172800
                        backend github blah secret
                        transform user {
                                match origin github
                                action add role authp/user
                                ui link "My Website" / icon "las la-star"
                                ui link "My Identity" "/auth/whoami" icon "las la-star"
                        }
                        transform user {
                                match origin github
                                match email some.user@gmail.com
                                action add role authp/admin
                        }
                }
}

app1.domain.com {
        route /someotherapp* {
                authorize {
                   context app1
                   primary yes
                   allow roles authp/admin authp/user
                   validate bearer header
                   set auth url https://auth.domain.com/auth/oauth2/github
                   inject headers with claims
                }
                reverse_proxy localhost:8181
        }
        route /anotherapp* {
                authorize {
                   context app1
                }
                reverse_proxy localhost:8182
        }
}

app2.domain.com {
        route /someotherapp* {
                authorize {
                   context app2
                   primary yes
                   allow roles authp/admin authp/user
                   validate bearer header
                   set auth url https://auth.domain.com/auth/oauth2/github
                   inject headers with claims
                }
                reverse_proxy localhost:8181
        }
        route /anotherapp* {
                authorize {
                   context app2
                }
                reverse_proxy localhost:8182
        }
}
```

**Comment by animosity22** [comment]
Thanks! I think I'm super close now as I think I just need to adjust the call back URL as I'm getting a mismatch since it's as subdomain. 

I found this:

https://github.com/pennersr/django-allauth/issues/1483#issuecomment-245859326

Which talks about removing the redirect URI and I'll play around and see if I can figure out what's it passing.

I'm almost over the finish line!

**Comment by greenpau** [comment]
@animosity22 , see https://authp.github.io/docs/authenticate/oauth/backend-oauth2-0007-github

callback url: https://auth.domain.com/auth/oauth2/github/authorization-code-callback

**Comment by animosity22** [comment]
I did use that already as I had a working single domain setup as it is that:

![image](https://user-images.githubusercontent.com/5088712/148624531-27ace252-36a5-4743-9f36-7b117502a0fc.png)

I'll need to go through a bit more careful and see if I typo'ed something along the way.

**Comment by animosity22** [comment]
Simple enough.

I have 2 app registrations and when I updated to use the new config you had proposed, I never switched the ID/client secret to the new app registration so it was properly complaining about the redirect being wrong.

Config works and I've added in my subdomains.

Much appreciated!

**Comment by greenpau** [comment]
@animosity22 , glad it is working 👍

**Comment by greenpau** [comment]
@animosity22 , thank you for the gift 👏 ❤️
