### ISSUE TITLE
question: Custom UI per Role

### ISSUE THREAD

**Issue by samcro1967** [greenpau/caddy-auth-portal#222]
I see there is a way with transform user to add a custom link to the UI based on a role.  Is there a way to set a custom UI for a role or restrict the links the role sees in the UI?

I see that I can setup a custom ACL and deny access to a link based on a role, but the link is still in the UI and the user gets a forbidden message if they click on it.

If I have 50 links in the UI, I would want the superadmin role to see them all, but say guest for only to see 10 of them.  Is there a way to do that currently?

**Comment by greenpau** [comment]
> I see there is a way with transform user to add a custom link to the UI based on a role. Is there a way to set a custom UI for a role or restrict the links the role sees in the UI?

@samcro1967 , there is a way to add custom link. For example, in the following config everyone gets `My Website` and `My Identity` links, but only users with `authp/user` role get `Portal Settings`. You can match on email, name, etc.

https://gist.github.com/greenpau/dbfadd3c9fee21dbb0a0d3902a8d0ec0#file-localauth_caddyfile-L10-L30

Now, you can completely redesign the look and feel of the `Portal` page by using 

```
    authp {
      ui {
        ...
        template login "/path/to/copy/of/portal.template"
        ...
      }
```

The original template is `assets/templates/basic/portal.template`.

Will create a Youtube video to show how to "mod" the portal template. Name: "Caddy Auth Portal: Customizing/Theming Portal UI". Subscribe to https://www.youtube.com/channel/UCNdBS4UnrknBm2SPENBHWUQ

> I see that I can setup a custom ACL and deny access to a link based on a role, but the link is still in the UI and the user gets a forbidden message if they click on it.

The Portal presents links. You can deny access to an endpoint with `caddy-authorize` based on role, name, email, etc.

See [Granting Access with Access Lists​](https://authp.github.io/docs/authorize/acl-rbac#granting-access-with-access-lists)

> If I have 50 links in the UI, I would want the superadmin role to see them all, but say guest for only to see 10 of them. Is there a way to do that currently?


```
        route /auth* {
                authp {
                        ...
                        ui {
                                links {
                                        # Seen by everyone
                                        "My Identity" "/auth/whoami" icon "las la-user"
                                }
                        }
                        transform user {
                                match roles authp/admin
                                ui link "Link 1" "/link1" icon "las la-cog"
                                ui link "Link 2" "/link2" icon "las la-cog"
                                # the other 48 links
                                ui link "Link N" "/linkN" icon "las la-cog"
                        }
                        transform user {
                                match roles authp/user
                                ui link "Link 1" "/link1" icon "las la-cog"
                                ui link "Link 2" "/link2" icon "las la-cog"
                                # the other 8 links
                                ui link "Link N" "/linkN" icon "las la-cog"
                        }
                }
        }
```

**Comment by samcro1967** [comment]
Thank you.  Was exactly what I was looking for.
