### ISSUE TITLE
feature: Password Recovery via Email

### ISSUE THREAD

**Issue by tetricky** [greenpau/caddy-auth-portal#226]
I cannot see any way to configure password recovery. Yet tantalisingly it seems to be an option in the Portal (I've tried it).

## Password Recovery Failed
Password recovery failed. Please retry.

I can't see any documentation on this...does it only work with some other type of backend, or not at all?

**Comment by greenpau** [comment]
> I can't see any documentation on this...does it only work with some other type of backend, or not at all?

@tetricky, thank you for the question! 👍 

The "Password Recovery" as a link exists, but the functionality does not. Why not? Initially I thought that resetting password or MFA is insecure to do via email. Now, as this project matures I think it might be the time to add it as a feature. (side note, the password reset via email is related to email as MFA #96 and iOS app auth #223; all of them have a form of one-time password)

## Option 1: Redirect to instructions

In the meantime, you could do the following. Say you are running the form the root of the path, i.e. the login page is `https://auth.myfiosgateway.com/login`. 

```
auth.myfiosgateway.com {
    ...
  route {
    authp {
      ...
      password_recovery_enabled yes
      ...
```

The "Forgot Password" link points to https://auth.myfiosgateway.com/forgot

![image](https://user-images.githubusercontent.com/3826416/149626931-5085d81e-f567-4a3c-a236-7dc7816c4c32.png)

Next, create a route that would handle the `/forgot` and redirect users to the instructions on how to reset a password, e.g. call or open helpdesk tickets, etc.

```
auth.myfiosgateway.com {
  ...
  route /forgot* {
    # respond "password recovery procedure"
    redir https://auth.myfiosgateway.com/docs/howto
  }
  route {
    authp {
      ...
      password_recovery_enabled yes
      ...
```

## Option 2: Reset password manually

Locate the local database file, e.g. `users.json`:

```
backend local /home/greenpau/.local/caddy/users.json local
```

In the file, locate the user you want to reset a password for, e.g. `webadmin`.

The password you are looking for is whether `disabled` is NOT set to `true`.

![image](https://user-images.githubusercontent.com/3826416/149627269-af636f06-aef4-453e-87a1-16a931446700.png)

Next, use `bcrypt` to generate a new hash manually. See [here](https://authp.github.io/docs/authenticate/local/password-management#manually)

Finally, modify `hash` field to the newly generated password hash.

**Comment by tetricky** [comment]
Brilliant. That points me in the right direction. I'll use a redirect to frame a workflow for triggering a password reset (even if it's just me manually doing something).

Thanks for that.

**Comment by greenpau** [comment]
> Similarly when a user is registering I'm sure I saw something about receiving an email...which doesn't happen, and will never happen without some setup. Is this in the same category?

@tetricky , you would need to modify the `register` template. See https://youtu.be/20XOn-RBIX0 for the instructions on how to customize UI. In the video, the instructions are about `login.template`. You would need to do the same for `register.template`.

**Comment by greenpau** [comment]
>  Is this in the same category? It would perhaps be better to not have a stub that promises something, but doesn't deliver....alternatively I'd be curious about how to make it happen!

@tetricky , it is a feature, i.e. SMTP to complete registration. I will try finding type to work on it.

In the meantime 😄 ... You can copy the user from `registration.json` to `user.json`.

**Comment by tetricky** [comment]
....there's a lot of good stuff here. for my needs it integrates lovely with caddy, and negates the need for me to run keycloak or some such...which saves me a lot of resource.

I think my  personal 'would like to have' is password recovery based on email, and I get the requests for registration transfer to users...but if I'm going to have to manually intervene, the form of that isn't critical to me (although easier better - subject to security).

**Comment by greenpau** [comment]
> 'would like to have' is password recovery based on email, and I get the requests for registration transfer to users

let’s keep it open as a feature request.

**Comment by tetricky** [comment]
Appreciated....though obviously if there's a password recovery by email, I'm going to need a change email (like change password). It's a can of worms...

**Comment by greenpau** [comment]
>It's a can of worms...

@tetricky, I am glad you appreciate the challenges I have 😄 🤣

**Comment by greenpau** [comment]
@tetricky , please reopen in [github.com/greenpau/caddy-security](https://github.com/greenpau/caddy-security/issues/new/choose) if this is still relevant for you. Please consider sponsoring the work on the project! 👍
