### ISSUE TITLE
question: Integrating with Nextcloud?

### ISSUE THREAD

**Issue by lumbo7332** [greenpau/caddy-auth-portal#227]
I'm trying to find a way to integrate `caddy-authorize` with Nextcloud, but I'm not really sure how to go about it. Should I be using OAuth? SAML? I'm using a local backend currently.

**Comment by greenpau** [comment]
> Should I be using OAuth? SAML? I'm using a local backend currently.

@lumbo7332 , I never worked with Nextcloud, but I think you could use [OAuth](https://authp.github.io/docs/authenticate/oauth/backend-oauth2-0000-generic).

This [link](https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-oauth-nextcloud) provides general info that leads me to believe that it is possible. 

However, you (or someone else) needs to modify some code. If you need help with this, connect with me on LinkedIn/Slack and we could do it outside this issue. I would need access to "dev/test" Nextcloud environment.

**Comment by lumbo7332** [comment]
Thanks! Where can I contact you on Slack?

**Comment by greenpau** [comment]
@lumbo7332 , there is a way to reach out via email: `greenpau@outlook.com`.

**Comment by lumbo7332** [comment]
Cool, I'll email you.

**Comment by greenpau** [comment]
@lumbo7332 , added `nextcloud` provider to OAuth with [v1.4.39](https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.4.39). Currently, the config should look like this:

```
            backends {
                nextcloud_oauth2_backend {
                    method oauth2
                    realm nextcloud
                    provider nextcloud
                    base_auth_url https://nextcloud.mydomain.com
                    client_id XXXXX
                    client_secret YYYY
                }
            }
```

**Comment by xpufx** [comment]
Nextcloud has a SAML app (It's available up to v22 - unless it updated very recently to 23) which works.  Check out https://goauthentik.io/integrations/services/nextcloud/ for the necessary settings for nextcloud. You have to adapt the authentik config to caddy-auth .

**Comment by greenpau** [comment]
@lumbo7332 , please reopen in [github.com/greenpau/caddy-security](https://github.com/greenpau/caddy-security/issues/new/choose) if this is still relevant for you.
