### ISSUE TITLE
question: Sending verification emails?

### ISSUE THREAD

**Issue by lumbo7332** [greenpau/caddy-auth-portal#228]
I'm trying to figure out how I'm supposed to send registration confirmation emails. I can't seem to find anything about SMTP configuration.

**Comment by greenpau** [comment]
Please see https://github.com/greenpau/caddy-auth-portal/issues/226

**Comment by lumbo7332** [comment]
Thanks. I didn't know if that was related, because it was about recovery passwords, but now I can see it is related.
