### ISSUE TITLE
Is caddy-authorize supposed to work with other idp products?

### ISSUE THREAD

**Issue by xpufx** [greenpau/caddy-auth-portal#229]
As it's a separate module, I assumed that I could use caddy-authorize without using authp/portal and have it talk to my own idp server already set up. (I am using authentik).  I think it's possible to chain with SAML/oauth and have the 3rd party idp provide the authentication information but it seems a bit weird to have to have two full idp servers just to give caddy a way to authenticate. Am I missing something?

Another question is reagarding the various name with which this project is known and the caddy documentation refers to it.

There's authp and portal. There's, http.handlers.auth_portal and http.handlers.authp whose documentation looks almost identical in content if not names. There's http.authentication.providers.saml with a blank documentation page and a total of 3 hits on google 2 of which are to said blank documentation page. It looks like some restructring went on at some point but what is still available to use? What is not recommended anymore? Which does what? If there's some documentation regarding this, can you please provide the link to it?

Thank you.

**Comment by greenpau** [comment]
@xpufx , thank you very much for the questions! 👍 

> As it's a separate module, I assumed that I could use caddy-authorize without using authp/portal and have it talk to my own idp server already set up. (I am using authentik). I think it's possible to chain with SAML/oauth and have the 3rd party idp provide the authentication information but it seems a bit weird to have to have two full idp servers just to give caddy a way to authenticate. Am I missing something?

Yes, you can use `caddy-authorize` without `caddy-auth-portal`. It knows to redirect to OAuth "client" (the portal is the client, i.e. has client id and secret configured), but would not act as OAuth client itself. The future plan is to make it a client ... it will happen when I introduce `caddy-security` (see below) next month.

By the way, you could have a "portal" for the purpose of redirecting to "authentik". All of it happens such that a user never sees the portal. A portal has special `oauth2/<name>` endpoints that do not serve UI at all.

> Another question is reagarding the various name with which this project is known and the caddy documentation refers to it.

At the moment, I store all docs at https://authp.github.io/ (backed by https://github.com/authp/authp.github.io)

> There's authp and portal. There's, http.handlers.auth_portal and http.handlers.authp whose documentation looks almost identical in content if not names. There's http.authentication.providers.saml with a blank documentation page and a total of 3 hits on google 2 of which are to said blank documentation page. It looks like some restructring went on at some point but what is still available to use? What is not recommended anymore? Which does what? If there's some documentation regarding this, can you please provide the link to it?

Please understand that a lot of my work on caddy plugins is my own professional development. I write code to learn how to do it better.

My first attempt and writing a plugin was https://github.com/greenpau/caddy-auth-saml. Now it is obsolete.

Then, I realized that I want to authenticate with a local username/password. I took that features of `caddy-auth-saml` and created `caddy-auth-portal`, which did SAML and local auth (with [`go-identity`](https://github.com/greenpau/go-identity)). Subsequently, I needed OAuth and I added it to the portal.

Well, I wanted to do the verification of the tokens issues by the portal. So, I created `caddy-auth-jwt` (it used `jwt` Caddyfile keyword) to verify JWT tokens. Subsequently, the feature set of this plugin grew and I decided to rename it to `caddy-authorize` and use `authorize` keyword in Caddyfile configurations. I wanted to verify both PASETO and JWT tokens, and API keys, and Authorization headers. It became more than `-jwt`.

**Future**

I started working on consolidating all of the above under a single Caddy plugin - `caddy-security`.

* [`caddy-security`](https://github.com/greenpau/caddy-security): implements Caddy app and plugins only.
* [`aaasf`](https://github.com/greenpau/aaasf): combines the features of `caddy-auth-portal` ,`caddy-authorize`, and `go-identity`.
   It does not contain any Caddy-specific code and can be used with any go web framework. 

Note: The will be no development in `caddy-auth-portal` ,`caddy-authorize`, and `go-identity` going forward.

**Comment by xpufx** [comment]
@greenpau Thanks for the quick and detailed explanation. I allowed a bit of my frustration to come through in my tone. Hope it wasn't too much. The whole project seems to be pretty full featured complete solution and I understand it will only get better. Keep up the good work. I will read this a few more times and try to figure out how to proceed. I don't have a super urgent need for it. I thought maybe if I could get it working I could at least put together a short document to help people who want to interoperate with the two projects - and others.  Thanks again.

**Comment by greenpau** [comment]
>  I thought maybe if I could get it working I could at least put together a short document to help people who want to interoperate with the two projects - and others.

@xpufx , if you need help, just ask a specific question in an issue. If this involves having integration with another product, please set up a "dev/test" instance for me to test with, e.g. dev nextcloud server.

**Comment by greenpau** [comment]
@xpufx , i think a good starter to understand how things work is https://youtu.be/k8tbbffMGZk

**Comment by greenpau** [comment]
@xpufx , then, you can take and disable auth portal and only allowing OAuth proxy.

**Comment by xpufx** [comment]
@greenpau I watched this video yesterday. Thanks. I will watch it again. I don't have the portal plugin embedded into the caddy binary. Do I need it? What did you mean by disable auth portal?

**Comment by greenpau** [comment]
> I don't have the portal plugin embedded into the caddy binary. Do I need it? 

@xpufx , you would need to compile with `caddy-auth-portal`.

> What did you mean by disable auth portal?

Please provide your current `Caddyfile` and I will show you want you would need to do.

**Comment by greenpau** [comment]
@xpufx , please reopen in [github.com/greenpau/caddy-security](https://github.com/greenpau/caddy-security/issues/new/choose) if this is still relevant for you. Please consider sponsoring the work on the project! 👍
