### ISSUE TITLE
Github backend requests both read and write access

### ISSUE THREAD

**Issue by ziyaointl** [greenpau/caddy-auth-portal#230]
When using the github backend, the scope requested is `user`, which includes both read and write permissions to user data: https://github.com/greenpau/caddy-auth-portal/blob/0f64ae51b30682557cfa1ffb9dedcc92dc689aaf/caddyfile.go#L270
This is not ideal, since caddy shouldn't be changing user data. Instead, we could use the scope `read:user` which requests only read access.

Github documentation: https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps

**Comment by greenpau** [comment]
@ziyaointl , thank you for the question! Please use `generic` provider instead of `github`. This way you can have Github integration with the more restrictive scope.

**Comment by greenpau** [comment]
@ziyaointl , this sounds like a better default. Please see https://github.com/greenpau/caddy-auth-portal/issues/231#issue-1106200478 and re-open the issue in `caddy-security`.

**Comment by ziyaointl** [comment]
@greenpau Thanks for such a swift reply!

I attempted to use the `generic` provider but unfortuantely was stuck on an error "authorization server response has no id_token field". Digging a bit deeper, I see that `id_token` seems to be required by the factory function that creates a `backend`, with no option to customize it in a Caddyfile.
https://github.com/greenpau/caddy-auth-portal/blob/f56ad05f79e9cb4a35495bf730444afa8e72b45b/pkg/backends/oauth2/backend.go#L76-L79

Here's my configuration for the generic oauth provider that generates the error:
```
backends {
      generic_oauth2_backend {
          method oauth2
          realm generic
          provider generic
          client_id <redacted>
          client_secret <redacted>
          base_auth_url https://github.com/login/oauth/
          authorization_url https://github.com/login/oauth/authorize
          token_url https://github.com/login/oauth/access_token
          identity_token_name access_token
          disable key_verification
          enable accept_header
          scopes openid email profile
      }
}
```

As I was typing this I see your new reply now :) Apologies for opening this in the wrong place! I'll open a new issue in `caddy-security`.

**Comment by greenpau** [comment]
> I see that id_token seems to be required by the factory function that creates a backend, with no option to customize it in a Caddyfile.

👍 will add it via the new issue 😄 Alternatively, once I finalize the migration, you could open a PR yourself. It should be pretty straight-forward.
