### ISSUE TITLE
feature: JumpCloud provider for SAML2

### ISSUE THREAD

**Issue by edolnx** [greenpau/caddy-auth-portal#232]
Greetings - I would love to help get JumpCloud support to the SAML providers in Caddy Auth Portal. The docs say to reach out if another provider should be supported, and I hope this is the correct way to do this. I will be able to sponsor this work through my employer, but wanted to reach out to see if that was appropriate. An added bonus of JumpCloud is that accounts are free for up to 10 users, so setting up a dev/test environment is very easy and their docs are public. What can I do to help support this?

CHANGE_ME

**Comment by greenpau** [comment]
@edolnx , thank you for reaching out 👍  Let me try seeing what it takes.

**Comment by greenpau** [comment]
@edolnx , meanwhile, please set up your own tenant.

**Comment by edolnx** [comment]
I already have a tenant setup, and have done some work with JumpCloud before so if we need help from them I can facilitate that. Thanks and let me know how I can help.

**Comment by greenpau** [comment]
> I already have a tenant setup, and have done some work with JumpCloud before so if we need help from them I can facilitate that. Thanks and let me know how I can help.

@edolnx , please provide me all the details about the test tenant via `greenpau@outlook.com`. Please create a user for me and share the details.

P.S. Created free JumpCloud tenant, but it did not finish the setup.

**Comment by edolnx** [comment]
Created and sent from carl@tormem.com

**Comment by greenpau** [comment]
@edolnx , the feature is now part of `caddy-security`. The sample configuration is in https://github.com/greenpau/caddy-security/blob/main/assets/config/jumpcloud/Caddyfile
