### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS between login portal

### ISSUE THREAD

**Issue by enefry** [greenpau/caddy-auth-portal#233]
**Describe the issue**

I'm trying to configure a auth domain(Single sign-on) to manage multiple domain authentication, 
but I got "ERR_TOO_MANY_REDIRECTS" error when my second domain site is authenticated. 
The browser keeps jumping at the /login /portal and cannot return to the second domain site
https://auth.mydomain.com/login <--> https://auth.mydomain.com/portal

**Configuration**
--------------------------------------------------------------------------------------------------------------
auth server (machine 1)
--------------------------------------------------------------------------------------------------------------
```
https://auth.mydomain.com:443 {
    tls {
        dns cloudflare awQAMXgrGrIzgr7ub5B1o5WisjwPhe3JT8FJP8Q1 # (example id)
    }
    log {
        output file /var/log/caddy2/auth.log
    }

    # custom login template resources begin
    route /login_assets/fonts/* {
        uri strip_prefix /login_assets/fonts/
        file_server {
            root /etc/caddy2/authp/fonts
        }
    }

    route /login_assets/css/* {
        uri strip_prefix /login_assets/css/
        file_server {
            root /etc/caddy2/authp/css
        }
    }
    route /login_assets/js/* {
        uri strip_prefix /login_assets/js/
        file_server {
            root /etc/caddy2/authp/js
        }
    }
    # custom login template resources end

    route {
            authp {
                    crypto default token lifetime 43200
                    crypto key sign-verify e9KiL45qXEkJi6w7mypQVcBHBB1lDRpx # (example id)
                    backend local /etc/caddy2/users.json local
                    cookie domain mydomain.com
                    ui {
                        links {
                            "main" "https://mydomain.com" icon "las la-search"
                            "private人" "https://priv.mydomain.com" icon "las la-user"
                            "infos" "./whoami" icon "las la-user"
                        }
                    	template login "/etc/caddy2/authp/login.template"
                        template sandbox "/etc/caddy2/authp/sandbox.template"
                    }
                    transform user {
                        match origin local
                        match roles authp/admin
                        ui link "settings" "./settings" icon "las la-cog"
                    }
            }
    }
}
```

--------------------------------------------------------------------------------------------------------------
main server (machine 1) work fine
--------------------------------------------------------------------------------------------------------------
```
https://mydomain.com:443 {
    tls {
        dns cloudflare awQAMXgrGrIzgr7ub5B1o5WisjwPhe3JT8FJP8Q1
    }
    log {
        output file /var/log/caddy2/www.log
    }

    route {
        authorize {
            primary yes
            allow roles authp/admin authp/user
            validate bearer header
            inject headers with claims
            crypto key verify e9KiL45qXEkJi6w7mypQVcBHBB1lDRpx
            set auth url https://auth.mydomain.com:443
        }
        reverse_proxy https://mydomain.com:9443 {
            header_up Host {upstream_hostport}
            header_up X-Forwarded-Host {host}
            transport http {
              tls_insecure_skip_verify
            }
        }
    }
}
```
--------------------------------------------------------------------------------------------------------------
second server (machine 1) 
--------------------------------------------------------------------------------------------------------------
```
https://private.mydomain.com {
    tls {
        dns cloudflare awQAMXgrGrIzgr7ub5B1o5WisjwPhe3JT8FJP8Q1
    }
    log {
        output file /var/log/caddy2/priv.log
    }
    route {
        authorize
        reverse_proxy https://private.mydomain.com:8443 { # to another machine
            header_up Host {upstream_hostport}
            header_up X-Forwarded-Host {host}
            transport http {
              tls_trusted_ca_certs /etc/caddy2/ssl/cf.cert
            }
        }
    }
}

```
--------------------------------------------------------------------------------------------------------------
third server (machine 1)
--------------------------------------------------------------------------------------------------------------
```
https://public.mydomain.com {
    tls {
        dns cloudflare awQAMXgrGrIzgr7ub5B1o5WisjwPhe3JT8FJP8Q1
    }
    log {
        output file /var/log/caddy2/public.log
    }
    route {
        authorize
        reverse_proxy https://public.mydomain.com:8443 { # to another machine
            header_up Host {upstream_hostport}
            header_up X-Forwarded-Host {host}
            transport http {
              tls_trusted_ca_certs /etc/caddy2/ssl/cf.cert
            }
        }
    }
}

```
**Version Information**
```
caddy2 version
v2.4.6

go_version: go1.17.5
go_os:      linux
go_arch:    amd64
path:       caddy
main:       caddy (devel) 
http.authentication.hashes.bcrypt v2.4.6
http.authentication.hashes.scrypt v2.4.6
http.authentication.providers.http_basic v2.4.6
http.handlers.authentication v2.4.6
http.authentication.providers.authorize v1.3.24
http.handlers.authp v1.4.38
```
--------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/2153953/149893201-4d9d85e4-63dd-44be-a499-8cefb810c644.png)

**Comment by greenpau** [comment]
@enefry , does your login page render fine?

**Comment by enefry** [comment]
> 
first login is ok
after login , will rediect to portal, and begin loop

**Comment by greenpau** [comment]
> after login , will rediect to portal, and begin loop

@enefry , do you ever get to the portal with links?

First, comment out your custom templates:

>                    	# template login "/etc/caddy2/authp/login.template"
>                      # template sandbox "/etc/caddy2/authp/sandbox.template"

Then browse to `https://mydomain.com/logout` to clear cookie.

Retry and report.

**Comment by enefry** [comment]
> > after login , will rediect to portal, and begin loop
> 
> @enefry , do you ever get to the portal with links?
> 
> First, comment out your custom templates:
> 
> > ```
> >                	# template login "/etc/caddy2/authp/login.template"
> >                  # template sandbox "/etc/caddy2/authp/sandbox.template"
> > ```
> 
> Then browse to `https://mydomain.com/logout` to clear cookie.
> 
> Retry and report.

comment out your custom templates:
everything work fine in my new browser (other browser) , 
but on old browser (error before) also loop rediect
I try "https://mydomain.com/logout", but seen not work , 
I  clean my browser data  and it work .

thank you very much
