### ISSUE TITLE
question: Is it possible to get the AzureID passed through OAUTH?

### ISSUE THREAD

**Issue by calebcoverdale** [greenpau/caddy-auth-portal#234]
Hello! 

I was wondering if it was possible to get the AzureID of a user passed through OAUTH? I was taking a look through and there is tons of progress on custom claims, was wondering what the steps would need to be in order to pass the AzureID of a user through as an item in the token? 

Thanks so much for your work on this, it's incredible.

**Comment by greenpau** [comment]
> I was wondering if it was possible to get the AzureID of a user passed through OAUTH? I was taking a look through and there is tons of progress on custom claims, was wondering what the steps would need to be in order to pass the AzureID of a user through as an item in the token?

@calebcoverdale , thank you for the question! In short, this could be done. Please share your Caddyfile.

**Comment by calebcoverdale** [comment]
`{
	debug true
	http_port 80
	https_port 443
	order authorize before reverse_proxy
	order authp before authorize
	admin 0.0.0.0:2019
	log {
		output file /logs/access.log {
			level warn
			format json
			roll_size 1gb
			roll_keep 5
			roll_keep_for 720h
		}
	}
}

(root) {
	authorize {
		# makes this block referencable later with a bare authorize directive
		primary yes
		# must match the crypto key password in the authp block above.
		crypto key e5ZaB46bF27d verify from directory LOCATIONOFKEYHERE
		# must point to the authp host above
		set auth url AUTHURLHERE
		# role "viewer" is allowed everywhere.
		allow roles admin contractor operator q9

	}
}

(admin) {
	authorize {
		set auth url AUTHURLHERE
		allow roles authp/user admin
	}
}

dev-caleb.opstunnel.com {
	tls {
		dns cloudflare CLOUDFLARETOKENHERE
	}
	route /auth/* {
		trace tag="marvel" response_debug=yes
		authp {
			crypto key e5ZaB46bF27d sign-verify from directory AUTHKEYLOCATIONHERE
			# All hosts using this auth must be in cookie_domain.
			cookie domain opstunnel.com
			# optional settings so auth lasts longer
			crypto default token lifetime 3600
			cookie lifetime 3600
			ui {
				links {
					"My Identity" "/auth/whoami" icon "las la-star"
				}
			}
			# backend google <client_id> <client_secret>
			backends {
				azure_oauth2_backend {
					method oauth2
					realm azure
					provider azure
					client_id CLIENTIDHERE
					client_secret CLIENTSECRETHERE
					tenant_id TENANTIDHERE
					scopes openid email profile
				}
			}


		}
	}
	import root
	route {
		# This respond is just a placeholder for whatever real content
		# you want to serve on the rest of the auth host, i.e. local
		# files or a reverse_proxy, or a redirect to /auth.
		authorize
		reverse_proxy ROUTETOFRONTEND
	}
	route /api* {
		# This authorize block extends the authorize with `primary yes` and
		# overrides the `allow` directive to allow different roles.
		# In this case, viewer isn't sufficient, admin role is required.
		authorize
		reverse_proxy ROUTETOBACKEND
	}
}
`

If you would like me to move this question over to Caddy Security I can do that as well.  

I probably should have asked the question if I can passthrough additional claims such as family_name, or other attributes I set in Azure...  

If you need the AzureAD App manifest I can post that as well.

**Comment by greenpau** [comment]
> I probably should have asked the question if I can passthrough additional claims such as family_name, or other attributes I set in Azure...

@calebcoverdale , I see. Unfortunately, I do not have Azure tenant. So ... let's troubleshoot together.

In your configs, you have enabled debug. In the logs, when authenticating, look for the reference to OAuth, specifically "OAuth 2.0 access token response decoded".

https://github.com/greenpau/caddy-auth-portal/blob/4f0d5954fc4c709e4e32c1f77377af0240cd0027/pkg/backends/oauth2/authenticate.go#L327-L330

Paste it here (modify security relevant parts). The goal is to figure out whether the "AzureID of a user" is in the access token.

If it is not, then we need to implement `fetchClaims` function specific to Azure.

https://github.com/greenpau/caddy-auth-portal/blob/4f0d5954fc4c709e4e32c1f77377af0240cd0027/pkg/backends/oauth2/authenticate.go#L119-L123

How is your Go?

**Comment by calebcoverdale** [comment]
This is the access token response I get back from the logs (in JWT format):

```
{
  "aud": "",
  "iss": "",
  "iat": 1642521327,
  "nbf": 1642521327,
  "exp": 1642526598,
  "acct": 0,
  "acr": "1",
  "aio": "",
  "amr": [
    "pwd",
    "mfa"
  ],
  "app_displayname": "Caddy",
  "appid": "",
  "appidacr": "1",
  "family_name": "",
  "given_name": "",
  "idtyp": "user",
  "ipaddr": "184.67.80.74",
  "name": "FIRSTNAME LASTNAME",
  "oid": "THISISWHATIWANT",
  "onprem_sid": "",
  "platf": "5",
  "puid": "",
  "rh": "",
  "scp": "email openid profile User.Read User.Read.All",
  "signin_state": [
    "kmsi"
  ],
  "sub": "",
  "tenant_region_scope": "NA",
  "tid": "",
  "unique_name": "email",
  "upn": "email",
  "uti": "",
  "ver": "1.0",
  "wids": [

  ],
  "xms_st": {
    "sub": ""
  },
  "xms_tcdt": 
}
```

```
{
  "aud": "",
  "iss": "https://login.microsoftonline.com/TENANTID/v2.0",
  "iat": 1642521327,
  "nbf": 1642521327,
  "exp": 1642525227,
  "email": "EMAIL",
  "family_name": "LASTNAME",
  "name": "FIRSTNAME LASTNAME",
  "nonce": "",
  "oid": "THISISWHATIWANTHERE",
  "preferred_username": "EMAILADDRESS",
  "rh": "",
  "roles": [
    "admin",
    "user",
    "guest"
  ],
  "sub": "",
  "tid": "",
  "upn": "",
  "uti": "",
  "ver": "2.0"
}
```

Log line containing AccessToken and ID TOKEN:
```
{"level":"debug","ts":1642521627.4824917,"logger":"http.handlers.authp","msg":"received OAuth 2.0 authorization server access token","request_id":"30b02156-b7dc-430a-ac96-f23d7903dc23","token":{"access_token":"SEEACCESSTOKENCLAIMABOVE","expires_in":4970,"ext_expires_in":4970,"id_token":"SEEIDTOKENABOVE","scope":"email openid profile User.Read User.Read.All","token_type":"Bearer"}}
```
Log line containing decoded claims: 

```
{"level":"debug","ts":1642521627.483103,"logger":"http.handlers.authp","msg":"decoded claims from OAuth 2.0 authorization server access token","request_id":"30b02156-b7dc-430a-ac96-f23d7903dc23","claims":{"email":"EMAIL","exp":1642525227,"iat":1642521327,"iss":"https://login.microsoftonline.com/TENANTID/v2.0","name":"FIRSTNAME LASTNAME","roles":["admin","user", "guest"],"sub":""}}
```

**Comment by greenpau** [comment]
> Go is a bit rough, but I can read through it...

@calebcoverdale , that's great! 👍

Do you see the "the AzureID of a user" in the output?

**Comment by calebcoverdale** [comment]
> 

The OID is the ObjectID of the user - so that is what I was looking for.  

There are a few other fields in there that I saw that might be nice to eventually passthrough (once I read the code on how to add this one in, I should be able to modify it for others) - because in Azure you are able to customize the claim scopes to add extras for the claims...

**Comment by greenpau** [comment]
> The OID is the ObjectID of the user - so that is what I was looking for.

@calebcoverdale , we established that this is doable. Please re-open this issue in `caddy-security`. Will handle this after migration is complete.

> There are a few other fields in there that I saw that might be nice to eventually passthrough (once I read the code on how to add this one in, I should be able to modify it for others) - because in Azure you are able to customize the claim scopes to add extras for the claims...

same.
