### ISSUE TITLE
docs: example

### ISSUE THREAD

**Issue by rayjlinden** [greenpau/caddy-auth-portal#27]
I just read the docs I found here - and I finished being very confused as to where to start.

Like what do I put into my Caddyfile to turn this own?  I did not even see Caddyfile mentioned - so I'm rather confused...

An example or two, would certainly help.

**Comment by greenpau** [comment]
> Like what do I put into my Caddyfile to turn this own? I did not even see Caddyfile mentioned - so I'm rather confused...

@rayjlinden , the plugin works with JSON config. I am working on Caddyfile PR as  we speak: https://github.com/greenpau/caddy-auth-portal/pull/26

Once finished the Caddyfile would look something like this: https://github.com/greenpau/caddy-auth-portal/blob/a9879542bcf6e13ce69f996f3cf48836d9c3bb05/assets/conf/local/Caddyfile

The JSON config is here: https://github.com/greenpau/caddy-auth-portal/blob/main/assets/conf/local/config.json

I started the plugin development with JSON config (not Caddyfile). Currently, making Caddyfile for this plugin and https://github.com/greenpau/caddy-auth-jwt

Also, take a look at https://github.com/greenpau/gatekeeper. It has JSON config and step by step what to do.

**Comment by greenpau** [comment]
@rayjlinden , also, here is the readme file for local auth https://github.com/greenpau/caddy-auth-portal/blob/main/pkg/backends/local/README.md

**Comment by rayjlinden** [comment]
Well - my timing is close.  I took a look at your PR and with that things seem much more clear.  The example you have in there is very helpful!  Indeed, I've written up my Caddyfile in anticipation of it getting released.  I say ship it!  👍 

Only question I had was around validating the jwt and redirecting if not authenticated.  Again, I have not messed with the jwt directive before - so it is not obvious to a newbie what to put there...

**Comment by greenpau** [comment]
> Only question I had was around validating the jwt and redirecting if not authenticated. 

@rayjlinden , baking Caddyfile support for jwt too. I will release portal and jwt together. Hopefully this week. JWT plugin has the redirect to authentication portal feature.

**Comment by greenpau** [comment]
@rayjlinden , Caddyfile functionality is ready for you. https://github.com/greenpau/caddy-auth-portal#secure-prometheus
