### ISSUE TITLE
feature: jwt > auth_url should allow different host

### ISSUE THREAD

**Issue by MexHigh** [greenpau/caddy-auth-portal#29]
If I try to set the `jwt > auth_url` directive to something like `https://auth.example.com`, I get the following error: 

` Error during parsing: path directive must begin with '/'`

It should be possible to have the auth portal on another host so that hosts (e.g. `chat.example.com` and `videos.example.com`) use the same auth portal.

**Comment by greenpau** [comment]
@MexHigh , fair point! This issues belongs to greenpau/caddy-auth-jwt. Please port this issue to that repo and I will fix it right away.
