### ISSUE TITLE
feature: add options to change cookie parameters

### ISSUE THREAD

**Issue by greenpau** [greenpau/caddy-auth-portal#30]
Add options to change cookie parameters.

Provided the following configuration, the cookie with token is not being passed to `https://chat.example.com`. See this issue about intra domain cookie handling: https://stackoverflow.com/questions/18492576/share-cookie-between-subdomain-and-domain

```
{
    order jwt first
}


https://auth.example.com {

    route /jwt-auth-test {
        jwt {
              primary yes
              auth_url "https://auth.example.com"
              trusted_tokens {
                  static_secret {
                      token_name access_token
                      token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
                      token_issuer e1008f2d-ccfa-4e62-bbe6-c202ec2988cc
                  }
              }
              allow roles admin
        }
        respond "Login flow is working. You are authorized :)" 200
    }

    route {
        auth_portal {
            path /
            backends {
                local_backend {
                    type local
                    path /etc/caddy-auth/users.json
                    realm local
                }
            }
            jwt {
                token_name access_token
                token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
                token_issuer e1008f2d-ccfa-4e62-bbe6-c202ec2988cc
            }
            ui {
                login_template "/etc/caddy-auth/login.template"
                portal_template "/etc/caddy-auth/portal.template"
                logo_url "<removed>"
                logo_description "<removed>"
                links {
                    "Testpage" /jwt-auth-test
                    "Chat" "https://chat.example.com"
                }
            }
        }
    }

}


https://chat.example.com {

    route {
        jwt {
            auth_url "https://auth.example.com"
            trusted_tokens {
                static_secret {
                    token_name access_token
                    token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
                    token_issuer e1008f2d-ccfa-4e62-bbe6-c202ec2988cc
                }
            }
            allow roles admin
        }
        reverse_proxy http://[::1]:8050 {
            header_down -Server
        }
    }

}
```

**Comment by greenpau** [comment]
cc: @MexHigh

**Comment by MexHigh** [comment]
> @MexHigh , could you please post screenshot from https://jwt.io/ of the token you get. Just want to see roles, etc.
> 
> The authentication works, correct?
> 
> The access to `/jwt-auth-test` works too?
> 
> The access to `https://chat.example.com` does not work?

![Screenshot 2020-09-12 222415](https://user-images.githubusercontent.com/50419884/93004387-bd42aa00-f546-11ea-9753-eafaa1a8cee1.png)

`sub` and `email` are both correct. Roles are too, i think (`guest` and `anonymous` are added).

### from users.json
```
  "roles": [
    {
      "name": "admin"
    }
  ]
```

Access to `/jwt-auth-test` works perfectly after logging in but as I said, the cookie is not send to `https://chat.example.com` so it redirects me back to `https://auth.example.com`.

**Comment by greenpau** [comment]
> the cookie is not send to https://chat.example.com

@MexHigh , exactly! That's the issue that needs to be fixed here. Will work on it today.

**Comment by greenpau** [comment]
@MexHigh , I will create Caddyfile option for Cookies parameters ...

* `cookie_domain`: adds the Domain attribute to Cookies. It determines which hosts are allowed to receive the cookie.
* `cookie_path`: adds the Path attribute to Cookies. It determines the URL path that must exist in the requested
  URL in order to send the Cookie header.

![image](https://user-images.githubusercontent.com/3826416/93006372-5f539980-f529-11ea-8622-dc0e34a3dfba.png)

**Comment by greenpau** [comment]
@MexHigh , also, I will be changing the `type local` to `method local` in the next release, the one that addresses your issue.

Now, in order for your scenario to work, you would need to add:

```
cookie_domain example.com
```

**Comment by greenpau** [comment]
@MexHigh , release https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.0.14. Please test.

**Comment by MexHigh** [comment]
@greenpau It does work now, thanks for your help :)
