### ISSUE TITLE
How to redirect to the originally requested url?

### ISSUE THREAD

**Issue by rayjlinden** [greenpau/caddy-auth-portal#33]
Looking at the redirect example:
    auth_url https://auth.example.com/auth?redirect_url=https://chat.example.com

So after auth they would get redirected to https://chat.example.com

However, in my case I just want them to go back to the link they were originally trying to get to - not a hard coded location.  How do I do that?

**Comment by greenpau** [comment]
> However, in my case I just want them to go back to the link they were originally trying to get to - not a hard coded location. How do I do that?

@rayjlinden , this would be a feature request in caddy-auth-jwt repo.

Something like:

auth_url https://auth.example.com/auth?redirect_url=auto

**Comment by greenpau** [comment]
Resolved by: https://github.com/greenpau/caddy-auth-jwt#auto-redirect-url
