### ISSUE TITLE
bug: redirect loop after token expiry

### ISSUE THREAD

**Issue by MexHigh** [greenpau/caddy-auth-portal#38]
Assuming we are running the `auth_portal` on `https://auth.example.com/auth`, a `jwt` secured ressource on `https://something.example.com` and already have a working access token and access to the ressouce.

After the token expires (defaults to 15 minutes i think) and accessing `https://something.example.com`, I'm getting redirected to `https://auth.example.com/auth?redirect_url=/auth?redirect_url=/auth?redirect_url=/auth?redirect_url=/auth[...]?redirect_url=/auth?redirect_url=https://something.example.com/` (pay attention to the last `?redirect_url` query!) with a "too many redirects" error.

Based on the path in all but the last `?redirect_url` query, I'm assuming this is an issue with portal.

**Comment by greenpau** [comment]
> Based on the path in all but the last ?redirect_url query, I'm assuming this is an issue with portal.

@MexHigh , This is the subdomain cookie issue ... The redirect_url is created by `jwt` plugin. Do you specify `?redirect_url` in your config? If yes, you should not. If not, I am curious about your cookies jar content.

**Comment by MexHigh** [comment]
No I' didn't specified the `?redirect_url`.

These are the cookies when accessing the `auth_portal` directly (after the mentioned 15 Minutes):
![access_auth](https://user-images.githubusercontent.com/50419884/93985253-17ccd900-fd85-11ea-863e-e6d645840978.png)

and when accessing a `jwt` secured ressouce (before getting redirected to the `auth_portal`):
![access_ressouce](https://user-images.githubusercontent.com/50419884/93985292-24e9c800-fd85-11ea-825d-4b407e3af140.png)

**Comment by greenpau** [comment]
@MexHigh , I I just pushed bugfix release.

If it does not help, please post the expanded url list.

![image](https://user-images.githubusercontent.com/3826416/94026061-359b3d80-fd87-11ea-9d2e-ed5b97c07571.png)

Also, the release contains support for `token_lifetime`. For example, this one is 1 hour.

```
    auth_portal {
      path /auth
      backends {
        local_backend {
          method local
          path /etc/gatekeeper/auth/local/users_db.json
          realm local
        }
      }
      jwt {
        token_name access_token
        token_secret ...
        token_issuer ...
        token_lifetime 3600
      }

```

**Comment by greenpau** [comment]
@MexHigh, please let me know if it worked.

**Comment by greenpau** [comment]
Release ref: https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.1.2

**Comment by MexHigh** [comment]
Works with and without the `token_lifetime` set. Thank you.
