### ISSUE TITLE
feature: add Google group membership claim

### ISSUE THREAD

**Issue by rayjlinden** [greenpau/caddy-auth-portal#41]
Maybe this is more of a question for the jwt repo?

My site is configured with google auth backend.  Working great!

However, I have a specific route I would locked down to specific users.  How do I do that when using google auth?

**Comment by greenpau** [comment]
> My site is configured with google auth backend. Working great!

Great news!!!!!

> However, I have a specific route I would locked down to specific users. How do I do that when using google auth?

@rayjlinden , by default, the scope you pass to Google is: `openid email profile`

```
        google_oauth2_backend {
          method oauth2
          realm google
          provider google
          client_id XXXXXX
          client_secret YYYYYYYY
          scopes openid email profile
        }
```

You need to change it to `openid email profile groups`, i.e. add `groups`, `roles`, etc.

Please read https://github.com/greenpau/caddy-auth-portal#okta. Specifically "By default, the default Authorization Server has no groups scope."

https://raw.githubusercontent.com/greenpau/caddy-auth-portal/main/assets/docs/images/okta_configure_scope_04.png

There is probably something similar in Google Identity Platform. However, I don't have an enterprise account so I don't know that configuration there.

If you are able to configure Google with groups claim, please post screenshots here. It will help others.

**Comment by rayjlinden** [comment]
Google does not return group information via oauth at all.  You would have
to call some other apis.  The Apache mod is doing that to give you an idea
of what is involved:
https://github.com/RTBHOUSE/google_groups_auth

However, we do not use google groups at all.  So I’d rather not go down
that path.

Is it possible to just set permissions based on email instead of group?
For our simplistic use cases that would be preferable.

Ray

**Comment by greenpau** [comment]
> Google does not return group information via oauth at all.  You would have to call some other apis.

@rayjlinden , this is easy to implement. Will ask you to test.

**Comment by greenpau** [comment]
@rayjlinden , please test and provide feedback.

Released https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.1.12

The instructions are here: https://github.com/greenpau/caddy-auth-portal#adding-role-claims

**Comment by rayjlinden** [comment]
Well I tried it - I get this error:
```
caddy_1     | run: adapting config using caddyfile: parsing caddyfile tokens for 'route': /Caddyfile:43 - Error during parsing: parsing caddyfile tokens for 'auth_portal': /Caddyfile:25 - Error during parsing: unsupported root directive: user
```

It is unclear from the docs where I need to add the user directive.  I must have it in the wrong place... but where?

**Comment by greenpau** [comment]
@rayjlinden , inside google backend config.

**Comment by greenpau** [comment]
@rayjlinden , to clarify:

```
myapp.localdomain.local, localhost, 127.0.0.1 {
  route /auth* {
    auth_portal {
      path /auth
      backends {
        google_oauth2_backend {
          method oauth2
          realm google
          provider google
          client_id XXXXXXXXXXXXXX.apps.googleusercontent.com
          client_secret YYYYYYYYYYYYYYYYY
          scopes openid email profile
          user "^greenpau" regex add role superuser
        }
```

**Comment by greenpau** [comment]
@rayjlinden , updated docs https://github.com/greenpau/caddy-auth-portal#adding-role-claims

**Comment by rayjlinden** [comment]
The docs make it very clear now.  I got it all working.  Very easy once you know where to put it!

I have a little issue in the case of "permission denied".  I get a 403 back as I would expect.

Then I have this:
```
        handle_errors {
                rewrite * /{http.error.status_code}
                reverse_proxy https://http.cat
        }
```

Which should have shown a little kitty picture on the 403.  Instead, it did a download.  This is more than likely a problem in this snippet?  I don't know...  I'm assuming the Content-Type is wrong.- but I'm not sure, how, why that would be happening...

**Comment by greenpau** [comment]
> Which should have shown a little kitty picture on the 403. Instead, it did a download. This is more than likely a problem in this snippet? I don't know... I'm assuming the Content-Type is wrong.- but I'm not sure, how, why that would be happening...

@rayjlinden, I don't know about this one. It is better suited for `caddyserver` issues.

The `jwt` plugin is what sends the 403. The `jwt` plugin is authenticator, not middleware ... try commenting the lines and see what happens.

```
        if err.Error() == "user role is valid, but not allowed by access list" {
            //w.WriteHeader(403)
            //w.Write([]byte(`Forbidden`))
            return caddyauth.User{}, false, err
        }
```

**Comment by greenpau** [comment]
> @rayjlinden, I don't know about this one. It is better suited for caddyserver issues.

@rayjlinden , this is a bug in `jwt` plugin. I will fix it this weekend and let you know to re-tests. Basically, I need to comment out these two lines.

**Comment by greenpau** [comment]
@rayjlinden , the 403 is a tricky one ... I am opening an issue in `jwt` repo for this one.

https://github.com/greenpau/caddy-auth-jwt/issues/32

**Comment by greenpau** [comment]
@rayjlinden , see https://github.com/greenpau/caddy-auth-jwt/issues/32 

The redirect is the only viable option at the moment.
