### ISSUE TITLE
github oauth2 error 401 - jwt: no primaryInstance auth provider found in default context

### ISSUE THREAD

**Issue by sbamin** [greenpau/caddy-auth-portal#42]
I have followed github OAuth2 config as per README file. My caddyfile (caddy v2) looks like this.

```
{
	http_port 4050
	https_port 4051
	# auto_https off
}

https://beta.example.com:4051 {
  	root * /var/srv

	## https
	tls /etc/ssl/mycert.pem /etc/ssl/mycert.key

	basicauth /* bcrypt "Restricted" {
		user1 <hashed pwd1>
		user2 <hashed pwd2>
	}

	file_server browse {
		hide *.conf *.txt
		index index.html index.htm
	}

	encode zstd gzip

	handle_errors {
		rewrite * /{http.error.status_code}.html
		file_server
	}

	header {

		# Replace http with https
		Location http:// https://

		# enable HSTS
		Strict-Transport-Security max-age=31536000;

		# disable clients from sniffing the media type
		X-Content-Type-Options nosniff

		# clickjacking protection
		X-Frame-Options DENY

		# keep referrer data off of HTTP connections
		Referrer-Policy no-referrer-when-downgrade
	}

	log {
		output file /var/logs/caddy2/access.log {
			roll_size 200mb
			roll_keep 5
			roll_keep_for 720h
		}

		format console

		level ERROR
	}

	## reverse proxy servers
	route /proxy1/* {
		uri strip_prefix /proxy1
		reverse_proxy localhost:6000
	}

	route /proxy2/* {
		uri strip_prefix /proxy2
		reverse_proxy localhost:7000
	}

	## webdav
	route {
		rewrite /dav /dav/

		@intranet {
			protocol https
			method GET
			remote_ip <ALLOWED_IP_RANGE>

			## disallow any of following
			not {
				method PUT DELETE
				remote_ip <ALLOWED_IP_RANGE>
				remote_ip <ALLOWED_IP1>
				remote_ip <ALLOWED_IP2>
			}
		}

		webdav @intranet {
			root /scratch/dav
			prefix /dav
		}

		file_server @intranet browse {
			hide *.txt *.md
			index index.html index.htm
		}
	}

	## OAuth2
	route /auth* {
		auth_portal {
			backends {
				github_oauth2_backend {
		          method oauth2
		          realm github
		          provider github
		          client_id Iv1.XXXXXXXXXXXXX
		          client_secret dummysdfo8sdfncs9usffsdfjfsd8yfsdufnsd87fgsdb
		          scopes user
		          user github.com/foo add role superuser
        		}
			}
		}
	}

	## Secure /vault using OAuth2 while serve rest of website using basicAuth
	route /vault* {
		jwt {
			auth_url /auth/oauth2/github
			allow roles superuser
		}
		respond * "github oauth2 sso" 200
	}
}
```

I have also setup github app per instructions with a callback URL: `https://beta.example.com:4051/auth/oauth2/github/authorization-code-callback`

When visiting `https://beta.example.com:4051/vault/`, I get 401 error after entering valid basic auth credentials. However, it does not redirect me to OAuth2 login. Also, I can visit `https://beta.example.com:4051/auth` and can successfully login via github OAuth2 but still I get an error 401  visiting `https://beta.example.com:4051/vault/`

While I have successfully used caddy v1 with https://github.com/tarent/loginsrv for github oauth2 login flow, I am new to caddy2 schema.

Caddy2 error log shows following:

```
2020/10/07 15:36:17.364 ERROR   http.authentication.providers.jwt       authorization provider provisioning error {"instance_name": "jwt-1", "error": "no primaryInstance authorization provider found in default context when configuring jwt-1"}
2020/10/07 11:36:17 [ERROR] Authenticating with jwt: no primaryInstance authorization provider found in default context when configuring jwt-1
```

And detailed access.log showing following:

```
# XXXXXXXXXXX	error	http.log.access.log0	handled request	{"request": {"remote_addr": "XXXXXXXXXXX", "proto": "HTTP/2.0", "method": "GET", "host": "beta.example.com:4051", "uri": "/vault", "headers": {"Accept-Language": ["en-US,en;q=0.9,hi;q=0.8,gu;q=0.7"], "Cookie": ["access_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; backTo=https://beta.example.com:4051/vault"], "Upgrade-Insecure-Requests": ["1"], "User-Agent": ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.XXXX Safari/537.36"], "Sec-Fetch-Site": ["none"], "Sec-Fetch-Mode": ["navigate"], "Accept-Encoding": ["gzip, deflate, br"], "Authorization": ["Basic XXXXXXXXXXXX=="], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"], "Sec-Fetch-User": ["?1"], "Sec-Fetch-Dest": ["document"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "h2", "proto_mutual": true, "server_name": "beta.example.com"}}, "common_log": "<REMOTE_IP> - user1 [07/Oct/2020:11:19:20 -0400] \"GET /igv HTTP/2.0\" 500 4315", "duration": 0.000333441, "size": 4315, "status": 500, "resp_headers": {"Referrer-Policy": ["no-referrer-when-downgrade"], "Strict-Transport-Security": ["max-age=31XXXXX;"], "X-Content-Type-Options": ["nosniff"], "X-Frame-Options": ["DENY"], "Etag": ["\"XXXXXX\""], "Content-Type": ["text/html; charset=utf-8"], "Server": ["Caddy"]}}
```

**Comment by greenpau** [comment]
@sbamin , the issue is that your `portal` and `jwt` plugins are misconfigured.

**Comment by greenpau** [comment]
@sbamin , posting details ...

**Comment by greenpau** [comment]
@sbamin , please take a look at [this](https://github.com/greenpau/caddy-auth-portal/blob/main/assets/conf/local/Caddyfile#L8-L92) and [this](https://github.com/greenpau/caddy-auth-portal/blob/68b619e41bdb7f40cf6316d19fd4c347dd8636be/assets/conf/local/Caddyfile#L95-L110).

**Comment by greenpau** [comment]
@sbamin , you need something along these:

```
	## OAuth2
	route /auth* {
		auth_portal {
			backends {
				github_oauth2_backend {
		          method oauth2
		          realm github
		          provider github
		          client_id Iv1.XXXXXXXXXXXXX
		          client_secret dummysdfo8sdfncs9usffsdfjfsd8yfsdufnsd87fgsdb
		          scopes user
		          user github.com/foo add role superuser
        		}
			}
      jwt {
  token_name access_token
  token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
  token_issuer e1008f2d-ccfa-4e62-bbe6-c202ec2988cc
  token_lifetime 3600
}
		}
	}

	## Secure /vault using OAuth2 while serve rest of website using basicAuth
	route /vault* {
		jwt {
      primary yes
      trusted_tokens {
        static_secret {
          token_name access_token
          token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
          token_issuer e1008f2d-ccfa-4e62-bbe6-c202ec2988cc
        }
      }
			auth_url /auth/oauth2/github
			allow roles superuser
		}
		respond * "github oauth2 sso" 200
	}
```

**Comment by greenpau** [comment]
@sbamin , the important this is that `token_secret` matches between `jwt` and `portal`. Please keep me posted on your progress.

**Comment by sbamin** [comment]
Thanks @greenpau 

I am now able to get past err 401 but visiting /vault/ now gives me `github oauth2 sso` while HTTP status showing 200. Log was showing `invalid jwt signature` but I double checked `token_secret` in both `jwt` and `auth_portal`, and they are identical.

**Comment by greenpau** [comment]
> I am now able to get past err 401 but visiting /vault/ now gives me github oauth2 sso while HTTP status showing 200. Log was showing invalid jwt signature but I double checked token_secret in both jwt and auth_portal, and they are identical.

@sbamin , once authenticated, please go to `/auth/whoami` and post what you see. It should be the content of you token.

**Comment by greenpau** [comment]
@sbamin . also, are you using the latest version of `portal`?

**Comment by sbamin** [comment]
I build caddy2 from its website on Oct 5. 

```
{
  "authenticated": true,
  "exp": 1602098043,
  "iat": 1602094443,
  "iss": "https://beta.example.com:4051/auth/oauth2/github/authorization-code-callback",
  "nbf": 1602093843,
  "origin": "https://api.github.com/user",
  "roles": [
    "anonymous",
    "guest",
    "everyone",
    "labusers"
  ],
  "sub": "github.com/sbamin"
}
```

**Comment by greenpau** [comment]
@sbamin , please rebuild with the latest.

Also, I think the issue is with. You should remove it ... It is what causes the 401.

```
	basicauth /* bcrypt "Restricted" {
		user1 <hashed pwd1>
		user2 <hashed pwd2>
	}
```

Then, reconfigure other endpoint to use `jwt`.

**Comment by sbamin** [comment]
got cha and just noticed that in access.log as basicauth and not jwt secret was being passed in header. Let me reconfigure and check how it goes. Thanks for helping out here.

**Comment by greenpau** [comment]
@sbamin , see https://github.com/greenpau/caddy-auth-jwt#caddyfile for reference. First `jwt` mention should be primary. The rest are non-primary.

**Comment by sbamin** [comment]
I removed basicauth and followed same schema as https://github.com/greenpau/caddy-auth-jwt#caddyfile but getting a plain text message (HTTP 200 OK) with `github oauth2 sso` with invalid jwt signature. I removed cookies, and started a new session incognito mode but no luck. I will debug more after reading your docs and let you know how it goes. 

```
2020/10/07 15:39:26.387 INFO    watcher config file changed; reloading  {"config_file": "Caddyfile"}
2020/10/07 15:39:26.388 INFO    using provided configuration    {"config_file": "Caddyfile", "config_adapter": ""} Authenticating with jwt: [signature is invalid]
```

**Comment by greenpau** [comment]
> Authenticating with jwt: [signature is invalid]

@sbamin , is it possible you have another JWT token in your cookies?

**Comment by greenpau** [comment]
@sbamin , just a suggestion. First, enable debugging:

```
{
	http_port 4050
	https_port 4051
	# auto_https off
        debug
}
```

Next, use trace plugin to get better output: https://github.com/greenpau/caddy-trace#getting-started

**Comment by sbamin** [comment]
Enabled debug and trace plugin. Following is after I get `github oauth2 sso` when visiting `beta.example.com:4051/vault/`. If I fall back to caddy v1 with OAuth2 based on https://github.com/tarent/loginsrv, same /vault path works.

```
2020/10/07 20:11:05.288	INFO	http.log.access.log0	handled request	{"request": {"remote_addr": "XXXXX:49945", "proto": "HTTP/2.0", "method": "GET", "host": "beta.example.com:4051", "uri": "/vault", "headers": {"Accept-Language": ["en-US,en;q=0.5"], "Accept-Encoding": ["gzip, deflate, br"], "Dnt": ["1"], "Cookie": ["access_token=XYZXYZXYZ......"], "Upgrade-Insecure-Requests": ["1"], "Te": ["trailers"], "User-Agent": ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:78.0) Gecko/20100101 Firefox/78.0"], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "h2", "proto_mutual": true, "server_name": "beta.example.com:4051"}}, "common_log": "XXXXXX - - [07/Oct/2020:16:11:05 -0400] \"GET /vault HTTP/2.0\" 200 17", "duration": 0.000529221, "size": 17, "status": 200, "resp_headers": {"Server": ["Caddy"], "Referrer-Policy": ["no-referrer-when-downgrade"], "Strict-Transport-Security": ["max-age=31536000;"], "X-Content-Type-Options": ["nosniff"], "X-Frame-Options": ["DENY"], "Content-Type": []}}
```

**Comment by greenpau** [comment]
> Following is after I get github oauth2 sso when visiting beta.example.com:4051/vault/.

@sbamin , do you see all of the JWT instances successfully initialize?

**Comment by greenpau** [comment]
> 2020/10/07 20:11:05.288	INFO	http.log.access.log0	handled request	...

@sbamin , this is not the log from `trace` plugin. That's native caddy v2 logging.

**Comment by greenpau** [comment]
@sbamin . side note.

No need to do this ...

```
https://beta.example.com:4051 {
```

Rather,

```
beta.example.com {
```

**Comment by sbamin** [comment]
opps! Looks like I don't have it in caddy2 binary. I will rebuilt and update tomorrow. 

and can update with full log. AFAIK, jet directives were initialized w/o any error.

**Comment by sbamin** [comment]
Is it ok to send you logs via email?

**Comment by greenpau** [comment]
@sbamin , yes, email is fine. Please send the logs and config.

**Comment by sbamin** [comment]
Thanks and just sent.

**Comment by greenpau** [comment]
This now closed. @sbamin , when you get a chance please post your working config.

**Comment by sbamin** [comment]
Thanks @greenpau 

Here is  a working Caddyfile for caddy v2, https://gist.github.com/sbamin/1450d11044c4fc750268c2e7772940c9 It enables OAuth2 for static files under /vault* and a webDAV server under `/mango*` while keep rest of the contents without any authentication. You may set caddy2 directive, `basicauth` to protect rest of contents.

Main issue with my original Caddyfile was a wrong directive: `respond * "github oauth2 sso" 200`.

```
	route /vault* {
		jwt {
			auth_url /auth/oauth2/github
			allow roles superuser
		}
		respond * "github oauth2 sso" 200
	}
```

The correct directive to browse static files was `file_server`, e.g., 

```
		jwt {
			auth_url /auth/oauth2/github
			allow roles superuser
                        ## additional configs
		}
		file_server browse {
			index index.html index.htm
		}
```

Also, OAuth2 configurations should precede rest of configurations, and the default route  with`/*` path must be written at the last.
