### ISSUE TITLE
Token used before issued with google provider

### ISSUE THREAD

**Issue by Inlustra** [greenpau/caddy-auth-portal#43]
I can't seem to get the google backend to work correctly, I'm navigated to the /auth error page within the portal

`failed validating OAuth 2.0 access token: failed to parse id_token: Token used before issued`

Logs:
```
{"level":"debug","ts":1602347125.5113904,"logger":"http.handlers.auth_portal","msg":"received OAuth 2.0 authorization server access token","request_id":"95660a15-66f0-4e77-abfb-475a320df1b7","token":{"access_token":"_REDACTED_","scope":"openid","token_type":"Bearer"}}
caddy            
```
```
{
   "level":"warn",
   "ts":1602347125.511588,
   "logger":"http.handlers.auth_portal",
   "msg":"Authentication failed",
   "request_id":"95660a15-66f0-4e77-abfb-475a320df1b7",
   "auth_method":"oauth2",
   "auth_realm":"google",
   "error":"failed validating OAuth 2.0 access token: failed to parse id_token: Token used before issued"
}
```

CaddyFile:
```
 auth.mydomain.com {
    route /auth* {
        auth_portal { 
            path /auth
            backends {
                google_oauth2_backend {
                    method oauth2
                    realm google
                    provider google
                    client_id _redacted_.apps.googleusercontent.com
                    client_secret _redacted_
                    
                    scopes openid email profile
                    user thomas@mydomain.com add role superuser
                }
            }
            jwt {
                token_name access_token
                token_secret bad09f0a-5533-4013-bb40-49463d6feefa
                token_issuer 65074400-9288-4d9b-b04d-66053cc5e169
            }
        }
    }
 }

 sso.mydomain.com {
        
    jwt {
        primary yes
        trusted_tokens {
            static_secret {
                token_name access_token
                token_secret bad09f0a-5533-4013-bb40-49463d6feefa
                token_issuer 65074400-9288-4d9b-b04d-66053cc5e169
            }
        }
        auth_url "https://auth.mydomain.com/auth/oauth2/google?redirect_url=https://sso.mydomain.com"
        allow roles superuser
    }
    reverse_proxy sso:9091
}
```

I'm unsure whether this is something I'm doing wrong (Most likely) or not... happy to dig into this issue as best I can.

**Comment by greenpau** [comment]
@Inlustra , first ensure you have the latest versions of `portal` and `jwt` plugins.

Next issue is that you need to have domain level cookies.

See here: https://github.com/greenpau/caddy-auth-portal#authorization-cookie

Add:

```
        auth_portal { 
           cookie_domain mydomain.com
           ...
```

That would fix it.

Next, do not add "redirect_url". it will be added automatically.

```
 sso.mydomain.com {
        
    jwt {
    ...
        auth_url "https://auth.mydomain.com/auth/oauth2/google"
    ...
```

**Comment by greenpau** [comment]
@Inlustra , also, note the error: "Token used before issued".

I think you have time sync issues too.... 

Run `date` command and see whether your clock is in sync.

**Comment by greenpau** [comment]
@Inlustra , it is an educated guess ... Google issues token that contain "nbf" (not before) field. If the timestamp in the token is in the future, then you cannot use the token. It is usually because of clock sync issues.

**Comment by greenpau** [comment]
@Inlustra , make sure you have `scopes openid email profile`. In the email I got initially, it said "scopes openid".

**Comment by Inlustra** [comment]
Thank you for your quick response! 
I actually just fixed the cookie_domain one as I implemented the github_oauth2_backend which is working brilliantly!

I'll have a dig to see if it's the time issue thanks for the advice! 


I realise this is a super side note... and I should raise another issue for this, but if I use the root domain instead of with the auth prefix. The portal oauth2 links are broken and instead navigate to: `https://oauth/google` for instance! (I'll dig into this one separately)
```
 auth.mydomain.com {
    route  {
        auth_portal { 
            path /
            backends {
                google_oauth2_backend {
                    method oauth2
                    realm google
                    provider google
                    client_id _redacted_.apps.googleusercontent.com
                    client_secret _redacted_
                    
                    scopes openid email profile
                    user thomas@mydomain.com add role superuser
                }
            }
            jwt {
                token_name access_token
                token_secret bad09f0a-5533-4013-bb40-49463d6feefa
                token_issuer 65074400-9288-4d9b-b04d-66053cc5e169
            }
        }
    }
 }
```

**Comment by Inlustra** [comment]
@greenpau the date does seem to be correct on the server and in the docker container at least 
`Sat Oct 10 17:02:39 UTC 2020`

**Comment by greenpau** [comment]
> I realise this is a super side note... and I should raise another issue for this, but if I use the root domain instead of with the auth prefix. The portal oauth2 links are broken and instead navigate to: https://oauth/google for instance! (I'll dig into this one separately)

@Inlustra , yes, that probably needs another issue :-)

**Comment by greenpau** [comment]
@Inlustra , addd default route redirect to see everything to `/auth`. That would do the trick for you.

```
  route {
    # trace tag="default"
    redir https://{hostport}/auth 302
  }
```

**Comment by greenpau** [comment]
@Inlustra , that default route should be placed at the end of `auth.mydomain.com`:

```
auth.mydomain.com {
...
  route {
    # trace tag="default"
    redir https://{hostport}/auth 302
  }
}
```

**Comment by Inlustra** [comment]
Figured I'd update here just in case anyone sees the same thing...
It was definitely a time issue as greenpau mentioned, forcibly updating ntp seemed to fix the issue - in my case it returned again within a couple of hours 🤷 - server time drift... yay!
