### ISSUE TITLE
question: GitHub OAuth support org/team membership restrictions

### ISSUE THREAD

**Issue by schu** [greenpau/caddy-auth-portal#46]
Hi. It took me a bit to puzzle together a working config for GitHub OAuth, so I thought I would paste a full example here (albeit basic):

<details>

```
example.com {
        route /auth* {
                auth_portal {
                        backends {
                                github_oauth2_backend {
                                        method oauth2
                                        realm github
                                        provider github
                                        client_id CCC
                                        client_secret DDD
                                        scopes user
                                        user github.com/schu add role test
                                }
                        }
                        jwt {
                                token_name access_token
                                token_secret AAA
                                token_issuer BBB
                                token_lifetime 300
                        }
                }
        }

        route /test* {
                jwt {
                        primary yes
                        trusted_tokens {
                                static_secret {
                                        token_name access_token
                                        token_secret AAA
                                        token_issuer BBB
                                }
                        }
                        auth_url /auth/oauth2/github
                        allow roles test
                }
                respond * "Successfully authenticated via GitHub OAuth!" 200
        }
}
```

</details>

I have a few questions/comments about https://github.com/greenpau/caddy-auth-portal#github

* The docs ask the user to generate a private key, but it doesn't seem to be used - what is it for?
* The docs don't ask the user to enable any permissions, for example read-only access to the email addresses or organization members and teams. At the same the docs say "The github provider does not have mail claim" - would retrieving email addresses work with access for the GitHub app enabled? But...
* Why a GitHub App and not GitHub OAuth? ([Differences](https://docs.github.com/en/free-pro-team@latest/developers/apps/differences-between-github-apps-and-oauth-apps)) As far as I understand, an OAuth app would be the more appropriate choice here (and it allows to request [scopes](https://docs.github.com/en/free-pro-team@latest/developers/apps/scopes-for-oauth-apps#available-scopes), e.g. `user:email` and `read:org`).
* It would be great if you could add a few examples for (I imagine) common use cases like giving access to all members of an organization or team within an organization.
* With the current version (`1.2.1`), is it possible to say "all members of GitHub org github.com/example" have access?

In general, I think the documentation would be clearer with separate files per provider and with both complete and simpler configuration snippets.

**Comment by greenpau** [comment]
@schu , thank you for posting this!

> The docs ask the user to generate a private key, but it doesn't seem to be used - what is it for?

It is a standard Github process. It is not used.

> The docs don't ask the user to enable any permissions, for example read-only access to the email addresses or organization members and teams. At the same the docs say "The github provider does not have mail claim" - would retrieving email addresses work with access for the GitHub app enabled? But...

The only constant that would be associated with a user is the user's Github handle. Pulling emails out adds confusion :-) at times, users have more than one email, e.g. 2 or 3 email is a norm. Deciding which one to pick as a primary is a headache.

> Why a GitHub App and not GitHub OAuth? (Differences) As far as I understand, an OAuth app would be the more appropriate choice here (and it allows to request scopes, e.g. user:email and read:org).

I think Github's direction is Github Apps ... However, I am open to suggestions and PRs.

> It would be great if you could add a few examples for (I imagine) common use cases like giving access to all members of an organization or team within an organization.

This would be a new feature.

> With the current version (1.2.1), is it possible to say "all members of GitHub org github.com/example" have access?

No. See above.

> In general, I think the documentation would be clearer with separate files per provider and with both complete and simpler configuration snippets.

I tried that, but then people were not reading docs. I actually have separate doc pages here: https://github.com/greenpau/caddy-auth-portal/tree/main/assets/docs/pages

**Comment by schu** [comment]
>> The docs ask the user to generate a private key, but it doesn't seem to be used - what is it for?

> It is a standard Github process.

The key is [not generated by default](https://docs.github.com/en/free-pro-team@latest/developers/apps/authenticating-with-github-apps#generating-a-private-key) and needed for signing JWT tokens to authenticate as GitHub App in a particular context, if I understand correctly. So it seems to be unnecessary here.

>> Why a GitHub App and not GitHub OAuth? (Differences) As far as I understand, an OAuth app would be the more appropriate choice here (and it allows to request scopes, e.g. user:email and read:org).

> I think Github's direction is Github Apps ... However, I am open to suggestions and PRs.

As far as I understand, they serve different purposes (authenticating as a user vs. the app with its own identity). One of the mentioned use cases for GitHub OAuth in the documentation is explicitly "GitHub as identity provider": https://docs.github.com/en/free-pro-team@latest/developers/apps/about-apps#about-oauth-apps

For example, Grafana implements authentication via GitHub with GitHub OAuth: https://grafana.com/docs/grafana/latest/auth/github/ And they support `allowed_organizations` and `team_ids`.

>> It would be great if you could add a few examples for (I imagine) common use cases like giving access to all members of an organization or team within an organization.

> This would be a new feature.

I think this is needed to make GitHub OAuth useful. Otherwise folks would still have to maintain configuration for each user on Caddy's side, while the expectation is being able to manage access through the identity provider.

Unfortunately I don't have much time currently, so I'm not sure if I can help in the short term.

**Comment by greenpau** [comment]
> The key is not generated by default and needed for signing JWT tokens to authenticate as GitHub App in a particular context, if I understand correctly. So it seems to be unnecessary here.

@schu , with Github apps, there is a warning message that say you must generate that key prior to using GitHub Apps.

> As far as I understand, they serve different purposes (authenticating as a user vs. the app with its own identity). One of the mentioned use cases for GitHub OAuth in the documentation is explicitly "GitHub as identity provider": https://docs.github.com/en/free-pro-team@latest/developers/apps/about-apps#about-oauth-apps

@schu , I was reading [this](https://docs.github.com/en/free-pro-team@latest/developers/apps/migrating-oauth-apps-to-github-apps#reasons-for-switching-to-github-apps) and assumed it is the way to go.

  > GitHub Apps are the officially recommended way to integrate with GitHub because they offer many advantages over a pure OAuth-based integration:

I don't have a preference.

> I think this is needed to make GitHub OAuth useful. Otherwise folks would still have to maintain configuration for each user on Caddy's side, while the expectation is being able to manage access through the identity provider.

Agreed! 

> Unfortunately I don't have much time currently, so I'm not sure if I can help in the short term.

Same here. Will get back to it next month. Great link from Grafana! Will implement that approach.

**Comment by schu** [comment]
> GitHub Apps are the officially recommended way to integrate with GitHub because they offer many advantages over a pure OAuth-based integration:

(from https://docs.github.com/en/free-pro-team@latest/developers/apps/migrating-oauth-apps-to-github-apps#reasons-for-switching-to-github-apps)

That indeed reads like GitHub apps should be preferred.

And I remembered that Nebraska uses a GitHub app to implement org/team restrictions; the code can be found here: https://github.com/kinvolk/nebraska/blob/master/cmd/nebraska/auth/githubauth.go
