### ISSUE TITLE
mismatch fmt-string and params

### ISSUE THREAD

**Issue by deluxghost** [greenpau/caddy-auth-portal#47]
https://github.com/greenpau/caddy-auth-portal/blob/850db4b064e4181cfe39ec1366d7f6fb680a5929/pkg/backends/oauth2/backend.go#L217

here we have `%s` but no args for it. I'm away from my pc so i cant create a PR for this.

there might be other mistakes like this one, consider adding linter to CI workflow might help.

**Comment by greenpau** [comment]
@deluxghost , thank you for reporting this. No need PR on this one because I will be adding a separate “errors” package in the project. I want to convert all fmt.Errorf to ErrFooBar types.
