### ISSUE TITLE
OAuth 2.0 authorization state not found

### ISSUE THREAD

**Issue by xmflsct** [greenpau/caddy-auth-portal#48]
I am not really sure how to debug this. I get below error
`{"level":"warn","ts":1603370360.55736,"logger":"http.handlers.auth_portal","msg":"Authentication failed","request_id":"---","auth_method":"oauth2","auth_realm":"google","error":"OAuth 2.0 authorization state not found"}`

This happens when I am using previously logged in browsers. When I try incognito mode, everything is fine. Any suggestions? Thanks!

**Comment by greenpau** [comment]
> This happens when I am using previously logged in browsers.

@xmflsct , let's start with your Caddyfile configuration. Please post it here.

**Comment by greenpau** [comment]
@xmflsct , also, please your modules:

```
caddy list-modules -versions | grep auth
```

**Comment by xmflsct** [comment]
The modules
```
http.authentication.hashes.bcrypt v2.2.1
http.authentication.hashes.scrypt v2.2.1
http.authentication.providers.http_basic v2.2.1
http.authentication.providers.jwt v1.1.3
http.handlers.auth_portal v1.2.4
http.handlers.authentication v2.2.1
```

My Caddyfile concerning auth
```
(auth) {
        jwt {
                primary yes
                auth_url https://auth.test.example.com/oauth2/google
                allow roles admin
                trusted_tokens {
                        static_secret {
                                token_name access_token
                                token_secret {$JWT_SECRET}
                        }
                }
        }
}
auth.test.example.com {
        route {
                auth_portal {
                        path /
                        cookie_domain test.example.com
                        backends {
                                google_oauth2_backend {
                                        method oauth2
                                        realm google
                                        provider google
                                        client_id {$GOOGLE_OAUTH_CLIENT_ID}
                                        client_secret {$GOOGLE_OAUTH_CLIENT_SECRET}
                                        scopes openid email profile
                                        user my-user-name@gmail.com add role admin
                                }
                        }
                        jwt {
                                token_name access_token
                                token_secret {$JWT_SECRET}
                        }
                }
        }
}
needauth.test.example.com {
        route {
                jwt
                reverse_proxy localhost:8000
                encode zstd gzip
        }
}
```

**Comment by greenpau** [comment]
@xmflsct , upgrade to `v1.2.5` and let me know if you see the same issue. OK?

**Comment by greenpau** [comment]
there was a bug related to serving from `path /`

**Comment by greenpau** [comment]
@xmflsct , Also, just to confirm, are you using HTTPS? ... I expect the answer to be yes (99%) ...

**Comment by xmflsct** [comment]
> @xmflsct , Also, just to confirm, are you using HTTPS? ... I expect the answer to be yes (99%) ...

Yes I am within the 99%. :) Will update soon and let you know!

**Comment by greenpau** [comment]
@xmflsct, also please paste the entire log of the server start up. I just want to make sure that all parts of the `portal` are loading fine.

**Comment by greenpau** [comment]
@xmflsct , preliminary thoughts ...

The error stems from here:

https://github.com/greenpau/caddy-auth-portal/blob/63c8e7339d2b2d021b53309b1508f6aebd6c3f25/pkg/backends/oauth2/backend.go#L217-L221

When the plugin redirects a user to Google, it includes a `state`. The `state` is being recorded in a `stateManager` (cache). That cache is local to the instance which executed the redirect.

Thus ... are you running multiple instances of Caddy or it is a single node setup?

**Comment by xmflsct** [comment]
After updating, it works like a charm! Thank you for your quick support and this plugin, that finally I can upgrade to Caddy2!

**Comment by greenpau** [comment]
> After updating, it works like a charm! Thank you for your quick support and this plugin, that finally I can upgrade to Caddy2!

@xmflsct , excellent! Feel free to give it a star and promote the plugins (`portal`, `jwt`) on the social platforms you use!
