### ISSUE TITLE
Complete your license file - its still in template form

### ISSUE THREAD

**Issue by tgelite** [greenpau/caddy-auth-portal#49]
1) awesome plugin, we are starting testing and love what's seen so far.
2) are you excepting financial contributions?
3) your LICENSE file is still in template form and not completed...  we'd like to be compliant in our use and possible distribution alongside our product...

**Comment by greenpau** [comment]
@tgelite , thank you! I am accepting financial contributions (feel free to email me at greenpau@outlook.com). Per the license file, will update that shortly.
