### ISSUE TITLE
issue with redirect caching and ephemeral state

### ISSUE THREAD

**Issue by vrischmann** [greenpau/caddy-auth-portal#53]
Hello,

first of all, thanks for this project, really helpful :)

I setup my auth portal using the google oauth2 backend but I'm having some problems which I believe are due to the 308 Permanent Redirect and the fact that both Firefox and Chrome are caching the response.

The steps to reproduce are:
* Go on the auth portal, click on the Google button
* You're presented with the Google "choose an account" form, don't choose an account yet, instead restart caddy
* Now choose an account, you should be presend with "Authentication failed" as in the screenshot below
* Go back to the auth portal, retry and it should still fail

![Screenshot from 2020-10-26 21-40-30](https://user-images.githubusercontent.com/1916079/97226222-fc198000-17d3-11eb-9312-b45b6ee86b3a.png)

In fact at this point the only thing which makes it work correctly again is clearing the cache. 

With debug enabled in the logs I'm getting this:
```
{
  "level": "debug",
  "ts": 1603744821.461704,
  "logger": "http.handlers.auth_portal",
  "msg": "received OAuth 2.0 response",
  "request_id": "0fe789d2-cd2d-4349-a5fd-93cc53f8261e",
  "params": {
    "authuser": [
      "1"
    ],
    "code": [
      "<redacted>"
    ],
    "prompt": [
      "none"
    ],
    "scope": [
      "email profile https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email openid"
    ],
    "state": [
      "9c2cef77-950d-4e52-a695-c29e25e00067"
    ]
  }
}
{
  "level": "warn",
  "ts": 1603744821.4623556,
  "logger": "http.handlers.auth_portal",
  "msg": "Authentication failed",
  "request_id": "0fe789d2-cd2d-4349-a5fd-93cc53f8261e",
  "auth_method": "oauth2",
  "auth_realm": "google",
  "error": "OAuth 2.0 authorization state not found"
}
```

As said above I believe the issue is because the 308 Redirect is cached and its contents is this (I removed some of the query string):
```
<a href="https://accounts.google.com/o/oauth2/v2/auth?client_id=redacted&amp;state=9c2cef77-950d-4e52-a695-c29e25e00067">Permanent Redirect</a>.
``` 
Since the state is stored in a map, after a restart it won't exist and therefore the state cached by the browser will no longer be valid, and the redirect will never work again until the cache is cleared in some way.

I don't know if 308 Redirect caching is intended behavior by the browser but I sucessuflly solved this problem by replacing the 308 [here](https://github.com/greenpau/caddy-auth-portal/blob/main/pkg/core/portal.go#L244) with a 302 which don't get cached.

Let me know if you need more information. Thanks !

**Comment by greenpau** [comment]
@vrischmann , please compile using the latest version. See releases. Also, please paste your configuration.

**Comment by vrischmann** [comment]
I'm using 7caf09b28a17c4aa40f895aacd2bc4ab36bf8ff1

My configuration is basically this:
```
example.com {
    route /auth* {
        auth_portal {
            path /auth
            backends {
                google_oauth2_backend {
                    method oauth2
                    realm google
                    provider google
                    client_id {$GOOGLE_CLIENT_ID}
                    client_secret {$GOOGLE_CLIENT_SECRET}
                    scopes openid email profile

                    user foobar@gmail.com add role verified
                }
            }
            jwt {
                token_name access_token
                token_secret {$JWT_SECRET}
                token_issuer {$JWT_ISSUER}
                token_lifetime 604800
            }
            ui {
                links {
                    "Grafana" /grafana
                }
            }
        }
    }

    # Grafana
    route /grafana* {
        jwt {
            primary yes
            trusted_tokens {
                static_secret {
                    token_name access_token
                    token_secret {$JWT_SECRET}
                    token_issuer {$JWT_ISSUER}
                }
            }
            allow roles verified
        }

        rewrite /grafana{path} {path}
        reverse_proxy /grafana* localhost:3000
    }
}
```

**Comment by greenpau** [comment]
> You're presented with the Google "choose an account" form, don't choose an account yet, instead restart caddy

@vrischmann, are you saying Caddy restart was in mid authentication flow?

**Comment by greenpau** [comment]
@vrischmann , I see the issue. I will create a bugfix and create a new release.

**Comment by vrischmann** [comment]
Yes that's right, mid flow. 

Good to know that you reproduce it, and thanks !

**Comment by greenpau** [comment]
@vrischmann , please use https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.2.8 and retest.

**Comment by greenpau** [comment]
@vrischmann , side note, I suggest you switch to using `token_rsa_file` instead of `token_secret`. See [here](https://github.com/greenpau/caddy-auth-portal#jwt-tokens)

**Comment by vrischmann** [comment]
The new version works fine now, thank you. Thanks for the tip also !

**Comment by greenpau** [comment]
@vrischmann , I am glad things worked out for you. Feel free to promote the project on the social media platforms you use! 😄
