### ISSUE TITLE
bug: local_backend Caddyfile directive - backend name is required but missing

### ISSUE THREAD

**Issue by xombiemp** [greenpau/caddy-auth-portal#55]
Thanks for creating this plugin for Caddy2!

I have a simple configuration working with this in my Caddyfile
```
  route /auth* {
    auth_portal {
      backends {
        local_backend {
          method local
          path /etc/caddy/auth/local/users.json
          realm local
        }
      }
      # local_backend /etc/caddy/auth/local/users.json
      jwt {
        token_name access_token
        token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
        token_issuer e1008f2d-ccfa-4e62-bbe6-c202ec2988cc
        token_lifetime 3600
      }
    }
  }

  @protected not path /favicon.ico /public* /tautulli/api*
  route @protected {
    jwt {
      primary yes
      trusted_tokens {
        static_secret {
          token_name access_token
          token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
          token_issuer e1008f2d-ccfa-4e62-bbe6-c202ec2988cc
        }
      }
    }
  }
```

If I remove the backends property from the auth_portal and just have the local_backend property like the commented out line then I get this error:
`backend name is required but missing`

Should I be able to use this shortened Caddyfile directive?  I'm I doing something wrong?

**Comment by greenpau** [comment]
> Thanks for creating this plugin for Caddy2!

@xombiemp, thank you! I have been putting a lot of work into this plugin. Would appreciate a star and a mention on the social media platforms you use. It is hard to promote a project, so I can use your help there :-)

Per you specific question ...

> Should I be able to use this shortened Caddyfile directive? I'm I doing something wrong?

There is a bug in the code. Right now. Will fix it in a moment ...

**Comment by greenpau** [comment]
@xombiemp , really like this trick 👍 

```
  @protected not path /favicon.ico /public* /tautulli/api*
  route @protected {
```

**Comment by greenpau** [comment]
@xombiemp ,

**Comment by greenpau** [comment]
@xombiemp , released https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.2.10 with the bugfix. Please retest.

**Comment by xombiemp** [comment]
Absolutely, I starred it!
I just tested again with the fix and it is working great now. Thanks!
