### ISSUE TITLE
Use random tokens if undefined

### ISSUE THREAD

**Issue by xombiemp** [greenpau/caddy-auth-portal#56]
My config looks like:
```
  route /auth* {
    auth_portal {
      local_backend /etc/caddy/auth/local/users.json
      jwt {
        token_name access_token
        token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
        token_issuer e1008f2d-ccfa-4e62-bbe6-c202ec2988cc
        token_lifetime 3600
      }
    }
  }

  @protected not path /favicon.ico /public* /tautulli/api*
  route @protected {
    jwt {
      primary yes
      trusted_tokens {
        static_secret {
          token_name access_token
          token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
          token_issuer e1008f2d-ccfa-4e62-bbe6-c202ec2988cc
        }
      }
    }
  }
```

What I'm wondering about is if there might be a way to eliminate the token settings from the config.  If they aren't defined then the plugins would use random values and somehow coordinate that between the jwt and portal plugins.  I believe the Caddy 1 plugins jwt and login did something like this, because I did not have to define tokens like this.

Do you think it's possible? Am I way off?

**Comment by greenpau** [comment]
@xombiemp , let’s start with that you can safely remove token_issuer and token_name from the config. Next, by default token_lifetime is 15 minutes. You can remove this directive too if you are ok with this limit.

Token secret is the only thing that need to be present. Now, I suggest you don’t use static password, rather you could add

token_rsa_file Hz789bc303f0db /etc/gatekeeper/auth/jwt/sign_key.pem

See https://github.com/greenpau/caddy-auth-portal#jwt-tokens

If you don’t want specify any secrets and let the server auto-generate it, it is not an option an at the moment. Long story short ... portal and jwt are two separate plugins. Further each declaration/mention of a plugin in Caddyfile is a separate instance. Sharing data between the instances is something I was working to solve. There is no easy way to communicate between the instance. I would consider adding it as a feature.

Did I answer you question?

**Comment by greenpau** [comment]
Also, I can probably create a few shortcuts related to “jwt”. Will add it tomorrow. Now, I going to 🛌 !

**Comment by xombiemp** [comment]
@greenpau I would definitely be interested in the plugins being able to communicate a generated secret as a feature request.

Thanks for the other tips given!
My config now looks like:
```
  route /auth* {
    auth_portal {
      local_backend /etc/caddy/auth/local/users.json
      jwt {
        token_rsa_file 1 /etc/caddy/auth/jwt/jwt_privatekey.pem
      }
    }
  }

  @protected not path /favicon.ico /public* /tautulli/api*
  route @protected {
    jwt {
      primary yes
      trusted_tokens {
        public_key {
          token_rsa_file 1 /etc/caddy/auth/jwt/jwt_publickey.pem
        }
      }
    }
  }
```
I am also very interested in any shortcuts you can create tomorrow. 😄

**Comment by greenpau** [comment]
After my future release, the following snippet in `jwt` Caddyfile:

```
trusted_public_key 1 /etc/caddy/auth/jwt/jwt_publickey.pem
```

replaces the following:

```
      trusted_tokens {
        public_key {
          token_rsa_file 1 /etc/caddy/auth/jwt/jwt_publickey.pem
        }
      }
```

**Comment by greenpau** [comment]
After my future release, the following snippet in `portal` Caddyfile:

```
    auth_portal {
      jwt_token_file 1 /etc/caddy/auth/jwt/jwt_privatekey.pem
      ...
    }
```

Replaces:

```
    auth_portal {
      jwt {
        token_rsa_file 1 /etc/caddy/auth/jwt/jwt_privatekey.pem
      }
      ...
    }
```

**Comment by greenpau** [comment]
@xombiemp , please review https://github.com/greenpau/caddy-auth-portal#caddyfile-shortcuts. These changes are in https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.2.11.

Please test.

**Comment by xombiemp** [comment]
@greenpau This is great! I just tested this config and it is working as expected:
```
  route /auth* {
    auth_portal {
      local_backend /etc/caddy/auth/local/users.json
      jwt_token_file 1 /etc/caddy/auth/jwt/jwt_privatekey.pem
    }
  }

  @protected not path /favicon.ico /public* /tautulli/api*
  route @protected {
    jwt {
      primary yes
      trusted_public_key 1 /etc/caddy/auth/jwt/jwt_publickey.pem
    }
  }
```

This looks about as compact as possible without the plugins being able to share a random secret. Thanks so much!

**Comment by greenpau** [comment]
This is as good as it gets at the moment! :-)
