### ISSUE TITLE
Authenticating across subdomains

### ISSUE THREAD

**Issue by vsoze** [greenpau/caddy-auth-portal#57]
First off I just wanted to say thank you for your work on this plugin, it's been a life saver for migrating to v2 and protecting services while avoiding resorting to basic auth.

Authentication doesn't seem to work for me across subdomains; here's an example config:

```
auth.example.com {
  route /auth* {
    auth_portal {
      path /auth
      backends {
        local_backend {
          method local
          path /etc/caddy/auth/users.json
          realm local
        }
      }
      jwt {
        token_name access_token
        token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
        token_issuer e1008f2d-ccfa-4e62-bbe6-c202ec2988cc
      }
    }
  }
}

service.example.com {
  jwt {
    primary yes
    trusted_tokens {
      static_secret {
        token_name access_token
        token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
        token_issuer e1008f2d-ccfa-4e62-bbe6-c202ec2988cc
      }
    }
    auth_url https://auth.example.com/auth
  }
}
```

The redirect to authentication happens just fine, as does the redirect back after inputting login information, but I'm not actually authenticated and just end up in redirect loops. I've also tried:
```auth-url https://auth.example.com/auth?redirect_url=https://service.example.com```
with no luck.

I tried creating separate auth portals for each subdomain, but it seems only one can be defined based on this error:
```found more than one primary instance of the plugin for default context```
I wasn't able to figure out a way to set default or not as with the jwt directive.

I'm reaching out in hopes that I'm missing something with regards to authenticating across subdomains. Any help is much appreciated, thanks!

**Comment by greenpau** [comment]
@vsoze , add context in the second definition.

service.example.com {
  jwt {
    context service1

**Comment by greenpau** [comment]
@vsoze , alternatively, remove the following from service config. It is not necessary here.

    primary yes
    trusted_tokens {
      static_secret {
        token_name access_token
        token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
        token_issuer e1008f2d-ccfa-4e62-bbe6-c202ec2988cc
      }
    }

**Comment by greenpau** [comment]
@vsoze , you also need to add in auth portal

cookie_domain example.com

Please review docs

**Comment by greenpau** [comment]
No need adding “context service1”

**Comment by vsoze** [comment]
@greenpau , adding cookie_domain in auth_portal worked, I knew I had to have been missing something simple, thanks!
