### ISSUE TITLE
Local user DB identity property

### ISSUE THREAD

**Issue by xombiemp** [greenpau/caddy-auth-portal#58]
I'm trying to wrap my head around the local db. I have a php app behind the portal that relies on the following variable to identify logged in users:
$_SERVER['REMOTE_USER']

It appears that this variable is set based on the "address" property and not the "username" property.  Is this on purpose?  Would it be useful to be able to control that?
I can change the "address" property so that it passes what I want, but is that address property used for anything else?  What is the "domain" property used for?

```
{
  "revision": 1,
  "users": [
    {
      "id": "eb5319ec-17ef-4af2-b726-6ce2d1f10a5d",
      "username": "andrew",
      "email_addresses": [
        {
          "address": "andrew@mydomain.com",
          "domain": "mydomain.com"
        }
      ],
      "passwords": [
        {
          "purpose": "generic",
          "type": "bcrypt",
          "hash": "$2a$10$v8QhEzH1rflvsKJYCZxHNeGQmxOBHYhOmtlUjUS1CGn19sfEfZji.",
          "cost": 10,
          "expired_at": "0001-01-01T00:00:00Z",
          "created_at": "2020-10-29T06:40:06.481974054Z",
          "disabled_at": "0001-01-01T00:00:00Z"
        },
        {
          "purpose": "generic",
          "type": "bcrypt",
          "hash": "$2a$10$Bxd2xGn1gCcNZieaCxKPvOMegUtRmlreGtDuhF7NWlDPCoUZ2/0.O",
          "cost": 10,
          "expired": true,
          "expired_at": "2020-10-29T06:40:06.551599456Z",
          "created_at": "2020-10-29T06:34:46.218066678Z",
          "disabled": true,
          "disabled_at": "2020-10-29T06:40:06.551599533Z"
        }
      ],
      "created": "2020-10-29T06:34:46.218066056Z",
      "last_modified": "2020-10-29T06:34:46.218066168Z",
      "roles": [
        {
          "name": "superadmin"
        }
      ]
    }
  ]
}
```

I'm curious about the structure of the user db.  Is this based on a defined standard I can read about?  Or did you design the structure?

**Comment by greenpau** [comment]
> It appears that this variable is set based on the "address" property and not the "username" property. 

@xombiemp , I don't understand the question. Please elaborate.

> I'm curious about the structure of the user db. Is this based on a defined standard I can read about? Or did you design the structure?

The structure of the user database is based on the library I've created https://github.com/greenpau/go-identity

See here https://pkg.go.dev/github.com/greenpau/go-identity#Database

The user object is: https://pkg.go.dev/github.com/greenpau/go-identity#User

> $_SERVER['REMOTE_USER']

Regarding the passing of the username, please read [this](https://github.com/greenpau/caddy-auth-jwt#pass-token-claims-in-http-headers) and let me know what you think.

Please ask follow up questions!

**Comment by xombiemp** [comment]
Ok, so REMOTE_USER is an environment variable.  It looks like this is what is setting it in the fastcgi module:
https://github.com/caddyserver/caddy/pull/3577/files

And that http.auth.user.id place holder looks like it is set here:
https://github.com/caddyserver/caddy/blob/c9fdff9976da38c650a51cd3fb4f2667853ff627/modules/caddyhttp/caddyauth/caddyauth.go#L82

I don't really know how this correlates to the auth-portal plugin, but I can tell you that this value is being set to what ever the value of the "address" property is in the user database file.  I can't find where that is happening in the code.

**Comment by greenpau** [comment]
@xombiemp , this is outside of the portal. I think you need to look into reading JWT token in PHP. The token is being passed to your PHP app.

**Comment by xombiemp** [comment]
@greenpau I think I found it.
https://github.com/greenpau/caddy-auth-jwt/blob/a34b002bb49e82dfc51aa311aadd6d246a464be7/plugin.go#L195

The ID is being set with userClaims.Email.  That caddyauth.User.ID is what's used to set the http.auth.user.id placeholder, which is what is used to set the REMOTE_USER environment variable.

So I guess the question is, what would be the ramifications of setting the ID using userClaims.Subject rather than userClaims.Email?

**Comment by greenpau** [comment]
@xombiemp , you want it to be an email? If so, I can provide Caddyfile option in jwt plugin to allow you setting it to email. Works forks for you?

**Comment by greenpau** [comment]
@xombiemp , i mean the other way ...

**Comment by xombiemp** [comment]
@greenpau, yeah! that would be great

**Comment by greenpau** [comment]
@xombiemp , the requested changes are in https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.2.12
Please read https://github.com/greenpau/caddy-auth-jwt#user-identity

**Comment by xombiemp** [comment]
@greenpau I think there is an issue with this.  I have tried user_identity subject and user_identity email and the REMOTE_USER always looks like an id now:
REMOTE_USER = cf33bef0-2373-42c9-a774-e5a22976fe11

I've looked at the code and I can't spot where the issue is.

**Comment by greenpau** [comment]
@xombiemp , When you go to “auth/whoami”, what do you see?

**Comment by xombiemp** [comment]
I see
```
{
  "authenticated": true,
  "exp": 1604024717,
  "expires_at_utc": "Thu Oct 29 20:25:17 MDT 2020",
  "iat": 1604023817,
  "iss": "https://mydomain.com/auth",
  "issued_at_utc": "Thu Oct 29 20:10:17 MDT 2020",
  "jti": "bdda81e3-f768-4094-be09-e985955882fe",
  "mail": "myemail@gmail.com",
  "origin": "localhost",
  "roles": [
    "superadmin",
    "guest",
    "anonymous"
  ],
  "sub": "andrew"
}
```

I also have a test php page that is printing the server variables and it has:
REMOTE_USER = bdda81e3-f768-4094-be09-e985955882fe
HTTP_X_TOKEN_SUBJECT = andrew
HTTP_X_TOKEN_USER_EMAIL = myemail@gmail.com
HTTP_X_TOKEN_USER_ROLES = superadmin guest anonymous

You can see the REMOTE_USER matches the jti value, whatever that is.
Something must be wrong with how the userIdentity.ID is being set.

**Comment by greenpau** [comment]
@xombiemp , please run

Caddy list-modules -versions

**Comment by xombiemp** [comment]
admin.api.load v2.2.1
admin.api.metrics v2.2.1
caddy.adapters.caddyfile v2.2.1
caddy.listeners.tls v2.2.1
caddy.logging.encoders.console v2.2.1
caddy.logging.encoders.filter v2.2.1
caddy.logging.encoders.filter.delete v2.2.1
caddy.logging.encoders.filter.ip_mask v2.2.1
caddy.logging.encoders.json v2.2.1
caddy.logging.encoders.logfmt v2.2.1
caddy.logging.encoders.single_field v2.2.1
caddy.logging.writers.discard v2.2.1
caddy.logging.writers.file v2.2.1
caddy.logging.writers.net v2.2.1
caddy.logging.writers.stderr v2.2.1
caddy.logging.writers.stdout v2.2.1
caddy.storage.file_system v2.2.1
exec v0.0.0-20200905052237-8d34c546e3f0
http v2.2.1
http.authentication.hashes.bcrypt v2.2.1
http.authentication.hashes.scrypt v2.2.1
http.authentication.providers.http_basic v2.2.1
http.authentication.providers.jwt v1.1.5
http.encoders.gzip v2.2.1
http.encoders.zstd v2.2.1
http.handlers.acme_server v2.2.1
http.handlers.auth_portal v1.2.12
http.handlers.authentication v2.2.1
http.handlers.encode v2.2.1
http.handlers.error v2.2.1
http.handlers.exec v0.0.0-20200905052237-8d34c546e3f0
http.handlers.file_server v2.2.1
http.handlers.headers v2.2.1
http.handlers.map v2.2.1
http.handlers.metrics v2.2.1
http.handlers.push v2.2.1
http.handlers.request_body v2.2.1
http.handlers.reverse_proxy v2.2.1
http.handlers.rewrite v2.2.1
http.handlers.static_response v2.2.1
http.handlers.subroute v2.2.1
http.handlers.templates v2.2.1
http.handlers.vars v2.2.1
http.matchers.exec_noop v0.0.0-20200905052237-8d34c546e3f0
http.matchers.expression v2.2.1
http.matchers.file v2.2.1
http.matchers.header v2.2.1
http.matchers.header_regexp v2.2.1
http.matchers.host v2.2.1
http.matchers.method v2.2.1
http.matchers.not v2.2.1
http.matchers.path v2.2.1
http.matchers.path_regexp v2.2.1
http.matchers.protocol v2.2.1
http.matchers.query v2.2.1
http.matchers.remote_ip v2.2.1
http.matchers.vars v2.2.1
http.matchers.vars_regexp v2.2.1
http.reverse_proxy.selection_policies.first v2.2.1
http.reverse_proxy.selection_policies.header v2.2.1
http.reverse_proxy.selection_policies.ip_hash v2.2.1
http.reverse_proxy.selection_policies.least_conn v2.2.1
http.reverse_proxy.selection_policies.random v2.2.1
http.reverse_proxy.selection_policies.random_choose v2.2.1
http.reverse_proxy.selection_policies.round_robin v2.2.1
http.reverse_proxy.selection_policies.uri_hash v2.2.1
http.reverse_proxy.transport.fastcgi v2.2.1
http.reverse_proxy.transport.http v2.2.1
pki v2.2.1
tls v2.2.1
tls.certificates.automate v2.2.1
tls.certificates.load_files v2.2.1
tls.certificates.load_folders v2.2.1
tls.certificates.load_pem v2.2.1
tls.handshake_match.sni v2.2.1
tls.issuance.acme v2.2.1
tls.issuance.internal v2.2.1
tls.issuance.zerossl v2.2.1
tls.stek.distributed v2.2.1
tls.stek.standard v2.2.1

**Comment by greenpau** [comment]
@xombiemp , I added a log entry to see what is being returned to Caddy.

```diff
diff --git a/plugin.go b/plugin.go
index 6ef5cff..08bddfa 100644
--- a/plugin.go
+++ b/plugin.go
@@ -243,6 +243,11 @@ func (m AuthProvider) Authenticate(w http.ResponseWriter, r *http.Request) (cadd
                }
        }

+       m.logger.Info(
+               "foobar",
+               zap.Any("identity", userIdentity),
+       )
+
        return userIdentity, true, nil
 }


```

As you can see the "ID" is being set to email.

```json
{
  "level": "info",
  "ts": 1604065969.2071426,
  "logger": "http.authentication.providers.jwt",
  "msg": "foobar",
  "identity": {
    "ID": "webadmin@localdomain.local",
    "Metadata": {
      "email": "webadmin@localdomain.local",
      "id": "fad88eb2-b33d-4d57-8552-b2cec517e09d",
      "roles": "superadmin guest anonymous",
      "sub": "webadmin"
    }
  }
}
```

Unfortunately, your issue is outside the scope of this plugin.

Try relying on `HTTP_X_TOKEN_USER_EMAIL`.

**Comment by xombiemp** [comment]
@greenpau 
Sorry, I'm pulling my hair out trying to figure out what is going on.
I went back to jwt v1.1.4 and auth_portal v1.2.11 and removed the new user_identity directive from my Caddyfile.
I confirmed that REMOTE_USER is the email value.

Then I updated back to the latest jwt v1.1.5 and auth_portal v1.2.13 and did not change my Caddyfile at all. REMOTE_USER is now an id.

I'm very confused and frustrated. Everything looks like it should work, but I promise, something with the change made it so that it's not even passing the email back like it did before.

I don't control the PHP app in question and it relies on $_SERVER['REMOTE_USER'], so unfortunately I can't just start using HTTP_X_TOKEN_USER_EMAIL.

I'll continue digging. Might try to figure out how to add some more logging in the other two places that are linked to above.

**Comment by greenpau** [comment]
@xombiemp , the change is that caddy version is different probably. Please check go.mod. If that is so, then you need to reach out to github.com/caddyserver/caddy

**Comment by greenpau** [comment]
@xombiemp , for logging, I suggest trying “caddy-trace” plugin.

Also, I will take a look at the differences between the two version.

**Comment by greenpau** [comment]
@xombiemp , also whatever digging you do ... it should be in "jwt" plugin.

**Comment by greenpau** [comment]
@xombiemp , additionally, try building on a different system.

**Comment by greenpau** [comment]
@xombiemp ... thinking out loud ... what is the reverse proxy injects that header?

What is your config for reverse proxy?

**Comment by greenpau** [comment]
There could be something in here:

```
 modules/caddyhttp/reverseproxy/caddyfile.go                       |  11 +++
 modules/caddyhttp/reverseproxy/healthchecks.go                    |  20 +++++-
 modules/caddyhttp/reverseproxy/hosts.go                           |   5 +-
 modules/caddyhttp/reverseproxy/reverseproxy.go                    |  24 ++++++-
 modules/caddyhttp/reverseproxy/streaming.go                       |   6 +-
```

**Comment by greenpau** [comment]
The `REMOTE_USER` is being set in `github.com/caddyserver/caddy/modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go`

**Comment by greenpau** [comment]
More specifically:

```
    authUser := ""
    if val, ok := repl.Get("http.auth.user.id"); ok {
        authUser = val.(string)
    }
```

**Comment by greenpau** [comment]
@xombiemp , good news! Spoke with caddyserver developers and they are saying it is related to this https://github.com/caddyserver/caddy/pull/3577

Will need to update this plugin to get it working properly.

**Comment by greenpau** [comment]
@xombiemp , you get your solution in 5 minutes! 😄

**Comment by andoks** [comment]
@greenpau sorry for necroing this issue, but may I suggest adding a list to the [docs](https://authp.github.io/docs/authorize/) of variables that auth-portal/[authorize](https://github.com/greenpau/caddy-authorize) will make available? From this issue I interpret that the http.auth.user.id variable will work in my Caddyfile (and indeed, it seems like it does!), but I was unable to find anything about it in the [docs](https://authp.github.io/docs/authorize/)

**Comment by greenpau** [comment]
> @greenpau sorry for necroing this issue, but may I suggest adding a list to the docs of variables that auth-portal/authorize will make available? 

@andoks , it is OK 👍 My work isn't perfect and I want to improve it 😺 

> From this issue I interpret that the http.auth.user.id variable will work in my Caddyfile (and indeed, it seems like it does!), but I was unable to find anything about it in the docs

Do any of the following links help?

* https://authp.github.io/docs/authorize/headers
* https://authp.github.io/docs/authorize/identity

You can ask me to fix the docs, or you could make PR to https://github.com/authp/authp.github.io

**Comment by andoks** [comment]
@greenpau that list would have covered my needs nicely, thanks!

What I ended up looking for in the docs instead however was a list of ["placeholders"](https://caddyserver.com/docs/conventions#placeholders), of which `http.auth.user.id` is one of (and is exposed by the Caddy [basic-auth module](https://caddyserver.com/docs/caddyfile/directives/basicauth#basicauth)).

It seems like this placeholder is exported by caddy-authorize too from how my Caddyfile works.

> You can ask me to fix the docs, or you could make PR to https://github.com/authp/authp.github.io

I will consider making a PR, but unfortunately I do not have the time right at this moment, as I would have to search through the source-code of the auth-portal/authorize project, and investigate how Caddy plugins work too.
