### ISSUE TITLE
feature: Using own css file, without including all templates

### ISSUE THREAD

**Issue by MexHigh** [greenpau/caddy-auth-portal#61]
Is there an option to change the `{{ pathjoin .ActionEndpoint "/assets/css/styles.css" }}` file? It would be perfect if you could just include an extra css file that overwrites the defaults in the one provided (in my case, I would only change the background to match my homepage).

Something like
```
auth_protal {
    ui {
        css_overwrite "/etc/gatekeeper/ui/style.css"
    }
    ...
}
```
would be nice.

Thanks in advance :)

**Comment by greenpau** [comment]
@MexHigh , it is easy, see https://github.com/greenpau/caddy-auth-portal#theming

In a nutshell, you can make a copy of templates in here https://github.com/greenpau/caddy-auth-portal/tree/main/assets/templates/basic

Then, in each copy, you could change whatever you want.

Then, you could reference it in your config:

```
      ...
      ui {
        #logo_url "https://caddyserver.com/resources/images/caddy-circle-lock.svg"
        logo_description "AuthP"
        login_template "/etc/gatekeeper/ui/forms_login.template"
        # portal_template "/etc/gatekeeper/ui/forms_portal.template"
        # whoami_template "/etc/gatekeeper/ui/forms_whoami.template"
        # register_template "/etc/gatekeeper/ui/forms_register.template"
        # generic_template "/etc/gatekeeper/ui/forms_generic.template"
        #settings_template "/etc/gatekeeper/ui/forms_settings.template"
        ...
```

Does this help?

**Comment by MexHigh** [comment]
Yes I've read this, but this is just too much config going on for the simple usecase of changing the background color. This also causes problems when I update the portal and you changed the templates.

**Comment by greenpau** [comment]
@MexHigh , I will see what I can do. It is likely doable. You just need the ability to add custom css on login or everywhere?

**Comment by MexHigh** [comment]
It would be nice if the css would affect all pages. Thanks for your great work.

**Comment by greenpau** [comment]
@MexHigh , the feature is in [v1.2.17](https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.2.17).

See [Custom CSS Styles](https://github.com/greenpau/caddy-auth-portal#custom-css-styles) for docs.

Please test and report back 😃

**Comment by MexHigh** [comment]
I'm using this directive
```
ui {
    ...
    custom_css_path "/etc/caddy-auth/styles-overwrite.css"
    ...
}
```
(ne other templates set)

___

![image](https://user-images.githubusercontent.com/50419884/98391838-7b6e4580-2057-11eb-94bc-3292b3cb1703.png)

## Issues
- The path set in the Caddyfile is just attached to the request.
- When setting the path absolute (starting with `/`), it will be referenced from the domains root. This is a problem when serving the auth portal under a subpath (`/auth/`) like I do.
- Existence of the file is not checked on startup / reload.

I think you need to create a symlink in `/auth/assets/css/style-overwrite.css` referencing the file configured in the Caddyfile.

**Comment by greenpau** [comment]
@MexHigh , the directive is not reading that file. Rather, it is actual URL path. The plugin does not read it at all.

**Comment by greenpau** [comment]
@MexHigh , I think I misunderstood what you wanted 😞 Let me implement the reading of the file and loading it to "auth/assets/...". Will probably happen next week.

**Comment by MexHigh** [comment]
That's no problem. Take your time 👍

**Comment by greenpau** [comment]
Will add custom js too

**Comment by greenpau** [comment]
@MexHigh , I was thinking about JS. This way one could load external analytics code.

**Comment by greenpau** [comment]
@MexHigh , here is what you can do:

```
        custom_css_path /etc/gatekeeper/ui/assets/styles.css
        #custom_js_path /etc/gatekeeper/ui/assets/script.js
```

**Comment by greenpau** [comment]
@MexHigh , this is now in https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.2.19. 

Please test and report back 😃

**Comment by MexHigh** [comment]
Works both perfectly. Thank you very much :)
