### ISSUE TITLE
Ensure plugin works on Windows

### ISSUE THREAD

**Issue by greenpau** [greenpau/caddy-auth-portal#63]

**Comment by greenpau** [comment]
@rismoney, does the plugin work on Windows? :-)

**Comment by rismoney** [comment]
I may have a use case for it, so I may be able to provide an answer to this soon.

**Comment by greenpau** [comment]
Thank you, @rismoney! I think local auth may fail because of file path processing, it is tailored towards linux.

**Comment by fdarveau** [comment]
I have been using this plugin on Windows for a few months now without any issue using local path for the auth file on C:/ drive.

The only issue I have encountered so far is the redirection back to the original link after authentication, though it is probably due to my config.

**Comment by greenpau** [comment]
> I have been using this plugin on Windows for a few months now without any issue using local path for the auth file on C:/ drive.

@fdarveau , thank you for the feedback! 👍 I would appreciate you starring `portal` and `jwt` repos 😉 

> The only issue I have encountered so far is the redirection back to the original link after authentication, though it is probably due to my config.

@fdarveau , when you experience it again, please open an issue about it. Also, I removed `token_issuer` as of [v1.3.6](https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.3.6). Please upgrade the plugin and remove the references to `token_issuer`, if any.

**Comment by greenpau** [comment]
> The only issue I have encountered so far is the redirection back to the original link after authentication, though it is probably due to my config.

@fdarveau , there was a bug related to that, but the fix is in `v1.3.6`.

**Comment by fdarveau** [comment]
After updating, the issue is fixed. Thanks!

**Comment by greenpau** [comment]
I am closing this one, because @fdarveau had success with windows deployment.
