### ISSUE TITLE
Microsoft OAuth2 backend

### ISSUE THREAD

**Issue by cnschn** [greenpau/caddy-auth-portal#64]
In the Readme file the Microsoft OAuth2 backend is currently listed as "TBD", is there any work for this done already?

I started to hack something together to support a Microsoft OAuth2 application, I could try to clean it up over the next few days and prepare a PR if you're interested?

**Comment by greenpau** [comment]
@cnschn , yes. PR are welcome! Please see https://github.com/greenpau/caddy-auth-portal/blob/main/CONTRIBUTING.md#contributing-guidelines

You need to start from here:

https://github.com/greenpau/caddy-auth-portal/blob/1b08b04f5b75796b2d6733caec862d84586e2b5f/pkg/backends/oauth2/backend.go#L118-L172

Please add another provider called `azure`. That would be your Microsoft OAuth2.

The docs should go in `assets/docs/pages/80-backend-oauth2.md`

**Comment by cnschn** [comment]
Thanks @greenpau, I got it to work both with a multitenant, "All Microsoft account users" application registration, and a tenant-specific one provided by my organization.

There is still one issue I'd like some input on: The JWKs returned by Microsoft's endpoint do not have an `"alg"` key, which throws an error in `Validate()`. According to [the spec](https://tools.ietf.org/html/rfc7517#section-4.4) it's optional. I might miss something in the code, but it looks like when the access token is validated it gets the information about the signing algorithm from the `"alg"` key of the token's header, not the JWK, right? Where is the `"alg"` information of the JWK actually used?

**Comment by greenpau** [comment]
> he JWKs returned by Microsoft's endpoint do not have an "alg" key, which throws an error in Validate(). 

@cnschn , please post permalink for this.

> Where is the "alg" information of the JWK actually used?

I think it is used here.  The purpose is validation that the key is RSA key and that the `kid` of the key is a "trusted" kid.

https://github.com/greenpau/caddy-auth-portal/blob/9d13c319525b9e2a728fbf6493d0b6ab9f75e973/pkg/backends/oauth2/validator.go#L36-L38

Whether the `kid` is trusted or not gets determined by the keys loaded by the below function:

https://github.com/greenpau/caddy-auth-portal/blob/85389dc996c3f60a033304a018385a88976f26c5/pkg/backends/oauth2/backend.go#L416

**Comment by cnschn** [comment]
> > he JWKs returned by Microsoft's endpoint do not have an "alg" key, which throws an error in Validate().
> 
> @cnschn , please post permalink for this.

The point where the error happens, you mean? It's here:

https://github.com/greenpau/caddy-auth-portal/blob/85389dc996c3f60a033304a018385a88976f26c5/pkg/backends/oauth2/jwks.go#L45-L48


> I think it is used here. The purpose is validation that the key is RSA key and that the `kid` of the key is a "trusted" kid.
> 
> https://github.com/greenpau/caddy-auth-portal/blob/9d13c319525b9e2a728fbf6493d0b6ab9f75e973/pkg/backends/oauth2/validator.go#L36-L38
> 
> Whether the `kid` is trusted or not gets determined by the keys loaded by the below function:
> 
> https://github.com/greenpau/caddy-auth-portal/blob/85389dc996c3f60a033304a018385a88976f26c5/pkg/backends/oauth2/backend.go#L416

If I read the first snippet correctly, it takes the `"alg"` from `token`, not from the JWK that is stored in `b.publicKeys`, right? These lines also do not give any error, it's in the `fetchKeysUrl` function where the call to `Validate()` errors out in line 48 of the link I posted at the top. In fact, I just commented out the `return fmt.Errorf()` and everything works fine.

**Comment by greenpau** [comment]
@cnschn  , the error is happening when the plugin tries to load trusted keys.

https://github.com/greenpau/caddy-auth-portal/blob/85389dc996c3f60a033304a018385a88976f26c5/pkg/backends/oauth2/backend.go#L459-L464

At a high level, when provider sends you a token you need to have some way to check the validity. For that you need to load trusted keys from somewhere. 

Not all providers have that functionality. That's why there are various flavors of providers.

For example, Facebook does not have that functionality. Please see below.

https://github.com/greenpau/caddy-auth-portal/blob/85389dc996c3f60a033304a018385a88976f26c5/pkg/backends/oauth2/backend.go#L152-L158

https://github.com/greenpau/caddy-auth-portal/blob/85389dc996c3f60a033304a018385a88976f26c5/pkg/backends/oauth2/backend.go#L184-L187

You need to figure out the way Azure behaves in respect to OAuth2.

**Comment by cnschn** [comment]
> @cnschn , the error is happening when the plugin tries to load trusted keys.
> 
> https://github.com/greenpau/caddy-auth-portal/blob/85389dc996c3f60a033304a018385a88976f26c5/pkg/backends/oauth2/backend.go#L459-L464
> 
> At a high level, when provider sends you a token you need to have some way to check the validity. For that you need to load trusted keys from somewhere.

Understood, but fetching the keys and using them to validate the token is working fine, that's still happening. It's just that the JWKs provided by microsoft don't include the algorithm inside the JWK (which they are allowed to, according to the spec), but only in the actual issued token. All needed information is still there, the token comes both with the information about which algorithm it was signed with, and the `"kid"` which connects it to the JWK it was signed with. In that sense, storing the `"alg"` inside the JWK as well could be considered redundant.

I think all other checks that are performed to see if the JWK are valid are perfectly fine, it's just that checking if they have an "`alg`" key in the header should not be one of them. Not the least because "the spec says so" ;-)

**Comment by greenpau** [comment]
> It's just that the JWKs provided by microsoft don't include the algorithm inside the JWK (which they are allowed to, according to the spec), but only in the actual issued token.

ok! then add some properties to the provider that you would then know assume the algorithm.

> Not the least because "the spec says so" ;-)

🤣

**Comment by greenpau** [comment]
@cnschn , let's connect on LinkedIn! Great work! 👍
