### ISSUE TITLE
Add feature to configure favicon (or probably just correct my lack of understanding)

### ISSUE THREAD

**Issue by drkstr101** [greenpau/caddy-auth-portal#65]
Hello,

I wanted to configure the favicon that displayed in the portal and the only way I could think of to do this was to copy in the templates [and inject a bit of HTML](https://github.com/watheia/theia-server/blob/7c0ae6fbc68efaf5da0b0e52c47f425e11b8526f/gatekeeper/etc/gatekeeper/templates/basic/generic.template#L9) into the header.

Is there something I could do on my end to make this less hacky? Perhaps just reroute the asset paths in Caddy? Just use injected javascript to write the tags?

Or if this is something you would like to support natively and feel like giving me a few pointers on how to go about this, I can attempt a PR for this feature. I think I've learned enough golang for basic templating at this point, so I wouldn't mind giving it a try.

Cheers, and thank you for your time!

**Comment by greenpau** [comment]
@drkstr101 , I think I would need to add “custom header” Caddyfile directive.

Additionally, I need to make it such that css/js/header could be selectively applied to portal’s pages.

Next, I need to add a directive to add files to static assets, e.g.

addon asset <uri_path> <content_type> <filesystem_path> 

This way you can inject your favicons via the plugin.

**Comment by greenpau** [comment]
@drkstr101 , I will find time next week to address this issue.

**Comment by greenpau** [comment]
@drkstr101 , would having `custom_html_head_path` help? (similar to https://github.com/greenpau/caddy-auth-portal#custom-css-styles). This would inject that the code in `path/to/head.html` into an existing HTML page.

```
custom_html_head_path path/to/head.html
```

**Comment by greenpau** [comment]
@drkstr101 , this is not available in [v1.3.2](https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.3.2). Please see [here](https://github.com/greenpau/caddy-auth-portal#custom-header).
