### ISSUE TITLE
"user enumeration" on login

### ISSUE THREAD

**Issue by jaysonsantos** [greenpau/caddy-auth-portal#66]
Hey there, right now If you use login with a local backend, a possible attacker could do some sort of user enumeration by trying random usernames because when the user does not exist, it will not try and calculate a bcrypt password then returning an error immediately.
If you want, you could point me to the best place to implement a dummy bcrypt calculation based on the smaller cost on the users.json file, I thought of using a defer on AuthenticateUser based on a flag success, when the deferred function runs it checks if it was a success or not, and if it wasn't, just calculate the dummy bcrypt.
What do you think about it?

**Comment by greenpau** [comment]
> Hey there, right now If you use login with a local backend, a possible attacker could do some sort of user enumeration by trying random usernames because when the user does not exist, it will not try and calculate a bcrypt password then returning an error immediately.

@jaysonsantos, it is a possibility.

>  If you want, you could point me to the best place to implement a dummy bcrypt calculation based on the smaller cost on the users.json file, I thought of using a defer on AuthenticateUser based on a flag success, when the deferred function runs it checks if it was a success or not, and if it wasn't, just calculate the dummy bcrypt.

>  What do you think about it?

@jaysonsantos , thank you for asking this question! Awesome questions! I actually thought of that same scenario but did not have a chance to address it yet.

In a nutshell, I want to keep a mapping between a pair of "username and source IP address for a request" and the number of login attempt. When a number of login failures is reached, block for X time, or CAPTCHA, or something else.

The same type of mapping will exists for max logins per address.

Now, back to bcrypt calculation. The enumeration with bcrypt results in extra processing on compute side. This could lead to DDoS exposure.

If you want to implement that calculation you would need to do it somewhere here:

https://github.com/greenpau/caddy-auth-portal/blob/85389dc996c3f60a033304a018385a88976f26c5/pkg/backends/local/backend.go#L148-L174

More specifically, I would do bcrypt calculation prior to locking local database.

https://github.com/greenpau/caddy-auth-portal/blob/85389dc996c3f60a033304a018385a88976f26c5/pkg/backends/local/backend.go#L150

Does this help?

---

@jaysonsantos , I have been putting a lot of work into this plugin. Would appreciate a star and a mention on the social media platforms you use. It is hard to promote a project, so I can use your help there :-)

**Comment by greenpau** [comment]
@jaysonsantos . I added the issue and added the `AuthenticateDummyUser` function:

https://github.com/greenpau/caddy-auth-portal/blob/21109658e62d134531bd069d4a7723934d8ee6e1/pkg/backends/local/backend.go#L152-L171

It is resolved.
