### ISSUE TITLE
how to make links open in new window (ui, links directive)

### ISSUE THREAD

**Issue by rajaseg** [greenpau/caddy-auth-portal#69]
@greenpau Here is the new issue for opening links in new window. Please find the code below. I want Jekyll to open in new window when I click on the it in the portal.

```
auth.example.com {
    route /auth* {
        auth_portal {
            path /auth
            cookie_domain example.com
            backends {
                google_oauth2_backend {
                    method oauth2
                    realm google
                    provider google
                    client_id {google_client_id}
                    client_secret {google_client_secret}
                    scopes openid email profile
                }
            }
            jwt {
                token_name access_token
                token_secret {token_secret}
                token_issuer {token_iisuer}
            }
            ui {
                links {
                  "Jekyll" jekyll.example.com
                  "Blog" blog.example.com
                }
            }
        }
    }
}
```
Please find the screen cap below for reference.
![image](https://user-images.githubusercontent.com/633479/100631661-f9212a80-3351-11eb-9bae-6c55b1cbd906.png)

**Comment by greenpau** [comment]
@rajaseg , I will treat this as a feature request and provide the solution to this shortly.

**Comment by rajaseg** [comment]
> @rajaseg , I will treat this as a feature request and provide the solution to this shortly.

Thanks you very much.

**Comment by greenpau** [comment]
@rajaseg

**Comment by greenpau** [comment]
@rajaseg , please read [here](https://github.com/greenpau/caddy-auth-portal#portal-links).

The directive that you need:

```
"Jekyll" jekyll.example.com target_blank
```

You need to be at v1.2.22.

Please test and close if it works for you.

**Comment by rajaseg** [comment]
> @rajaseg , please read [here](https://github.com/greenpau/caddy-auth-portal#portal-links).
> 
> The directive that you need:
> 
> ```
> "Jekyll" jekyll.example.com target_blank
> ```
> 
> You need to be at v1.2.22.
> 
> Please test and close if it works for you.

Do you mean the caddy-auth-portal@v1.2.22?

--with github.com/greenpau/caddy-auth-portal@1.2.22

**Comment by greenpau** [comment]
> --with github.com/greenpau/caddy-auth-portal@v1.2.22

@rajaseg , I mean this:

```
--with github.com/greenpau/caddy-auth-portal@latest \
--with github.com/greenpau/caddy-auth-jwt@latest
```

**Comment by rajaseg** [comment]
> > --with github.com/greenpau/caddy-auth-portal@v1.2.22
> 
> @rajaseg , I mean this:
> 
> ```
> --with github.com/greenpau/caddy-auth-portal@latest \
> --with github.com/greenpau/caddy-auth-jwt@latest
> ```

@greenpau I have tested the functionality (link in new window) and associated icon as well. Everything looks good.
Please find image for reference. Thank you very much for the feature.

![image](https://user-images.githubusercontent.com/633479/100781334-e6315780-3430-11eb-93e0-7819da90e043.png)
