### ISSUE TITLE
feature: add user registration page

### ISSUE THREAD

**Issue by greenpau** [greenpau/caddy-auth-portal#7]
Create a configuration parameter allowing users to register. 

The registration get approved by users with "admin" and "superadmin" roles.

**Comment by greenpau** [comment]
Completed.

**Comment by cilex-ft** [comment]
@greenpau How can the admin approve users ? Thanks!

**Comment by greenpau** [comment]
> How can the admin approve users ? Thanks!

@cilex-ft , please subscribe to the issue https://github.com/greenpau/caddy-auth-portal/issues/4

The user and approval management requires feature development.
