### ISSUE TITLE
Plex Single Sign On

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [greenpau/caddy-auth-portal#70]
Would it be possible to add Plex as an authorization server? Ombi, Tautulli, and Organizr all have implementations for reference.

**Comment by greenpau** [comment]
> Would it be possible to add Plex as an authorization server? Ombi, Tautulli, and Organizr all have implementations for reference.

@Adrian-at-CrimsonAuzre , thank you for opening the issue! Plex - sure! What are the links to the implementations?

**Comment by Adrian-at-CrimsonAuzre** [comment]
[Ombi](https://github.com/tidusjar/Ombi/blob/b7571ed191bdb20b7839b08c3d36229a0a45caf6/src/Ombi.Api.Plex/PlexApi.cs#L71)
[Tautulli](https://github.com/Tautulli/Tautulli/blob/9184ae4608367bf601077690a7f9d059c720b452/lib/plexapi/myplex.py)
[Organizr](https://github.com/causefx/Organizr/blob/6bbdb47d44bd1fd13d350c46d6eefe9743c9fac0/api/functions/auth-functions.php#L168)
I don't know if it's possible, but it would be nice to have a setting to restrict sign on to Admin Only, Home Only, or Anyone.

**Comment by greenpau** [comment]
@Adrian-at-CrimsonAuzre , please create a workflow diagram for the design. I do not use Plex, so you need to help me understand the flow.

**Comment by Adrian-at-CrimsonAuzre** [comment]
Tautuli just uses a little bit of JS ([see attached](https://github.com/greenpau/caddy-auth-portal/files/5618332/Tautulli.OAuth.txt)) to spawn a window for signing into plex.tv. Then passes the token to the back end which checks to see if the user can sign into the given server by using the magic key, `X-Plex-Token`, which returns a token that can be used to access a given server with `https://plex.mydomain.com/?X-Plex-Token=LxZgnXXXXXXXXXXjMYu1` which will return a 200 code and some info if the user can access the server. If MediaContainer.readOnlyLibraries == 0, then the token is valid for the administrator of the server. Otherwise, it's just a regular user.

**Comment by greenpau** [comment]
> Then passes the token to the back end which checks to see if the user can sign into the given server by using the magic key, X-Plex-Token, which returns a token that can be used to access a given server with https://plex.mydomain.com/?X-Plex-Token=LxZgnXXXXXXXXXXjMYu1 which will return a 200 code and some info if the user can access the serv

@Adrian-at-CrimsonAuzre , I think this warrants a custom `plex` authentication backend. What is the easiest way to create a Plex instance that can return a token on Linux? Is [this](https://support.plex.tv/articles/200288586-installation/) it?

**Comment by Adrian-at-CrimsonAuzre** [comment]
Yes, either install bare that way or spin up a [Docker image](https://hub.docker.com/r/linuxserver/plex).

**Comment by greenpau** [comment]
@Adrian-at-CrimsonAuzre , is this what you are looking for?

![image](https://user-images.githubusercontent.com/3826416/100668865-910b1e00-332a-11eb-9754-704cb989b7b7.png)

**Comment by greenpau** [comment]
@Adrian-at-CrimsonAuzre , I re-read your initial question. You want provide username and password that exist on Plex Media server and have RBAC based on Owner Only, Home Only, or Anyone?

**Comment by Adrian-at-CrimsonAuzre** [comment]
Yes, that is what I want. I'd like to use this Caddy plugin to give SSO capabilities to applications that I host that don't have single sign-on capabilities (Radarr, Sonarr, Lidarr, etc)

**Comment by greenpau** [comment]
> Yes, that is what I want. I'd like to use this Caddy plugin to give SSO capabilities to applications that I host that don't have single sign-on capabilities (Radarr, Sonarr, Lidarr, etc)

@Adrian-at-CrimsonAuzre , I installed Plex media server. Where do you configure users? How do you assign a user to a group, i.e. Owner Only, Home Only, or Anyone?

**Comment by Adrian-at-CrimsonAuzre** [comment]
In the webui in the upper right under users and sharing. Add a friend will add a user to the server (they need a Plex account though, I just used a spare email for testing).  

Plex doesn't 100% have groups, but the account that's associated with the server is always _the_ owner account. After digging around I'm not sure that Home accounts are differentiated in any way from regular accounts, but a regular account is just someone you invite to the server.

**Comment by greenpau** [comment]
@Adrian-at-CrimsonAuzre , I researched it and I don't think Plex backend integration would work. The plex server does not maintain identity store (think usernames and passwords). Therefore, it could not be used to authenticate users.

**Comment by Adrian-at-CrimsonAuzre** [comment]
The Plex server itself doesn't, but Plex.tv does and the server will only validate users who are authorized on the server.

**Comment by greenpau** [comment]
@Adrian-at-CrimsonAuzre , Plex.tv does not have authorization endpoint, e.g. OAuth. See https://forums.plex.tv/t/feature-request-for-oauth2-endpoint/159232 where there is no resolution on the topic.

**Comment by greenpau** [comment]
There is a good thread on it here: https://forums.plex.tv/t/how-to-get-a-transient-token-from-the-server/135430/9

@Adrian-at-CrimsonAuzre , feel free to provide a detailed diagram of how it is supposed to work. Unfortunately, I cannot help you without functional requirements.
