### ISSUE TITLE
Nextcloud single sign on

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [greenpau/caddy-auth-portal#71]
Since Plex isn't going to work out, how about [Nextcloud](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/oauth2.html)?
It seems to support OAuth2 out of the box, so does this even need its own implementation?

**Comment by greenpau** [comment]
@Adrian-at-CrimsonAuzre , OAuth implementation differ. This particular one are not following openID subspec of OAuth2.0. The plugin needs to be tailored for Nextcloud.
