### ISSUE TITLE
Presenting Authenticated User Name through Header in Reverse Proxy Scenario ( Grafana Proxy Pass Config)

### ISSUE THREAD

**Issue by tgelite** [greenpau/caddy-auth-portal#72]
**Describe the issue**

As I work my way through the available documentation and discussion/examples for the auth proxy and jwt, is that the authenticated user information is within the jwt and not presented as header information.  The question being; "Is it possible to dynamically pass authenticated user and group information (such as X-WEBAUTH-USER and X-WEBAUTH-GROUPS) that we can not extend with jwt authorization.

In the configuration we are attempting to build, grafana in a auth proxy configuration (  https://grafana.com/docs/grafana/latest/auth/auth-proxy/ )

**Configuration**
Using caddy as a authenticating reverse proxy over 3 web applications on the same host as the caddy server. 
 
Our configuration is nascent right now as myself and a development team member have been searching around for reference or discussion around exposing authenticated user in a way that would be compatible.  

Right now dev work is over caddy on windows in dev and caddy on raspbian lite os in integrated testing.  

The custom web app indicated in a node.js we app that we want to pass authenticated user detail to, and we want to convey authenticated user in the headers for the route.  The equivalent for nginx would be expressed as ` proxy_set_header X-WEBAUTH-USER $user;`   can caddy expand $user as a value (if so what is the sytax?).

In addition there is node red and grafana that we would like to have caddy proxy auth handle authentication and convey username to when routing requests through reverse proxy mode.

Paste full `Caddyfile` below:

```
{
storage file_system {
                root    F:\caddy\storage
        }
        local_certs
        http_port     80
        https_port    443
        debug
}

https://test.example.com, https://10.1.1.20 {
       # custom node.js web application with its own authentication we want to replace with caddu proxy auth 
       # on port 1080 route  
       route /* {
                # jwt
                reverse_proxy http://localhost:1080
       }
       # node red dahsboard running on port 1880 route that we will need to work out authentication and passing user
       route /ui/* {
               # jwt 
               reverse_proxy http://localhost:1880
       }
       # grafana with modified base URL configuration for /gr running on port 3000 route - needs to use auth proxy
       route /gr/* {
# as a hack right now its pre generated key with long life, this needs to be replaced with the auth proxy config in grafana
# and authenticated user being passed via headers from caddy auth portal upon sucessful authentication & route to grafana.
# for "request_header Authorization hack" see https://grafana.com/docs/grafana/latest/http_api/auth/
# for config goal see https://grafana.com/docs/grafana/latest/auth/auth-proxy/
# jwt
               request_header Authorization: "Bearer eyJrIjoid1VBS1QwZjFYTmJ2MXROSnQ0VDUwbWFtRENGZjNjV1MiLCJuIjoiZW0iLCJpZCI6MX0="
               reverse_proxy http://localhost:3000
       }
       #strike header providing auth to log out out (example) not yet implemented
       route /logoff {
               request_header - Authorization:
               reverse_proxy http://localhost:1080
       }

  route /version* {
    respond * "1.1.0" 200
       }

        log {
                level INFO
                format console
                output file f:\caddy\caddy.log
        }
}
```

**Expected behavior**

Once a user is authenticated by the caddy auth portal, to be able to dynamically set X-WEBAUTH-USER and X-WEBAUTH-GROUPS or any other custom defined headers, based on authenticated user information, when routing to web applications behind caddy in a reverse proxy configuration. 

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.2.1
http.authentication.hashes.scrypt v2.2.1
http.authentication.providers.http_basic v2.2.1
http.authentication.providers.jwt v1.1.10
http.handlers.auth_portal v1.2.20
http.handlers.authentication v2.2.1
http.handlers.trace v1.1.4
```

**Additional context**

There is no bug or issue here, more just ignorance on our part based on what we can identify to date and where best forum for discussion is for how to type of things...

**Comment by greenpau** [comment]
@tgelite , please upgrade to the latest versions of portal and jwt. After that, amend your issue ^

**Comment by tgelite** [comment]
Ok updated!

http.authentication.hashes.bcrypt v2.2.1
http.authentication.hashes.scrypt v2.2.1
http.authentication.providers.http_basic v2.2.1
http.authentication.providers.jwt v1.2.1
http.handlers.auth_portal v1.3.2
http.handlers.authentication v2.2.1
http.handlers.trace v1.1.4

**Comment by greenpau** [comment]
> Once a user is authenticated by the caddy auth portal, to be able to dynamically set X-WEBAUTH-USER and X-WEBAUTH-GROUPS or any other custom defined headers, based on authenticated user information, when routing to web applications behind caddy in a reverse proxy configuration.

@tgelite , there are a number of things here:

1. `portal` plugin does not set headers. Rather, it injects JWT token into a cookie.
2. prior to reaching `reverse_proxy` plugin, a request must pass through `jwt` plugin. The `jwt` plugin reads the token issued by `portal` and if the token is valid, the request reaches the `reverse_proxy` plugin

Please see [docs](https://github.com/greenpau/caddy-auth-jwt#pass-token-claims-in-http-headers) for enabling the passing of headers.

Now, the header would not match `X-WEBAUTH-USER` and `X-WEBAUTH-GROUPS`. This would require a feature request.

I could implement something like this:

```
inject header X-WEBAUTH-USER email
inject header X-WEBAUTH-GROUPS roles
```

Is that what you need here?

**Comment by greenpau** [comment]
@tgelite , the [url](https://grafana.com/docs/grafana/latest/auth/auth-proxy/) has the reference to the following.

```
header_name = X-WEBAUTH-USER
header_property = username
headers = Name:X-WEBAUTH-NAME Email:X-WEBAUTH-EMAIL Groups:X-WEBAUTH-GROUPS
```

The JWT token has the fields necessary to populate this. It should be straight forward.

Are you planning to use `local` backend?

**Comment by tgelite** [comment]
Thank you very much for the specific documentation links, I'm reading through now. 

Yes, exactly.  As far as proxy auth and similar, that set of field X-WEBAUTH values covers a wide number of proxy AuthN/AuthZ use cases (including ours).

Yes, initially using local backend.  The team who is having the app stack built anticipates installations where LDAP will be used by next year.   I anticipate that the caddy-auth-portal flexibility on auth types will be useful for integration projects landing in different authentication service scenarios.

Beyond our specific requirements, It would seem to me that longer term that the caddy_auth_portal being able to convey SAML assertions or resolve and present OATH token detail in a visible way via headers to the applications that are proxy authentication aware behind caddy in a reverse proxy AuthN/AuthZscenario would be valuable, too.

Thanks!

**Comment by greenpau** [comment]
@tgelite , I think what you need is already here. You just need to reconfigure Grafana.

Compare:

```
header_name = X-WEBAUTH-USER
header_property = username
headers = Name:X-WEBAUTH-NAME Email:X-WEBAUTH-EMAIL Groups:X-WEBAUTH-GROUPS
```

with:

```
header_name = X-Token-Subject
header_property = username
headers = Name:X-Token-User-Name Email:X-Token-User-Email Groups:X-Token-User-Roles
```

As described [here](https://github.com/greenpau/caddy-auth-jwt#pass-token-claims-in-http-headers), upon `enable claim headers`, you will get the following headers:

```
    "X-Token-Subject": "webadmin"
    "X-Token-User-Name": "Web Administrator"
    "X-Token-User-Email": "webadmin@localdomain.local"
    "X-Token-User-Roles": "superadmin guest anonymous"
```

**Comment by tgelite** [comment]
Perfect, we will test with this.  Sorry to pull you into the grafana side of interpreting things, this is a huge help.  Thanks!

**Comment by greenpau** [comment]
@tgelite , also, the header may reach Grafana as `X_Token_Subject` or `X-TOKEN-SUBJECT`, etc. 

use `caddy-trace` to determine the headers. Please `trace` one line above `reverse_proxy`.

**Comment by tgelite** [comment]
I will share redacted example of what is presented and what the working config was here, once we are set up based on all the info provided.

**Comment by greenpau** [comment]
> Yes, initially using local backend. The team who is having the app stack built anticipates installations where LDAP will be used by next year. 

@tgelite, LDAP will work out of the box too.

**Comment by Manoj321** [comment]
> I will share redacted example of what is presented and what the working config was here

Were you able to get this to work? Can you share the config?
