### ISSUE TITLE
feature: WebAuthn support

### ISSUE THREAD

**Issue by craigfrancis** [greenpau/caddy-auth-portal#78]
Following on from:

https://github.com/w3c/webauthn/issues/1362#issuecomment-746624274

https://github.com/greenpau/caddy-auth-portal/blob/cb90d8656989a35ede780bdedcb21e555aea08ad/assets/templates/basic/settings.template#L607-L635

I don't have the time to debug the code at the moment, but have a look at how I implemented the getPublicKey() polyfill.

In particular, the bit where I use the `result.response.attestationObject`:

https://github.com/craigfrancis/webauthn-tidy/blob/main/new/js/polyfill.js?ts=4#L552

I, like you, use `CBOR.decode()` to get to `authData`.

Then I use my [`authenticator_buffer_parse`](https://github.com/craigfrancis/webauthn-tidy/blob/main/new/js/polyfill.js?ts=4#L429) function to get the flags, and the `der_content`.

Now that's DER format, I don't know enough about Go to know if it can support that... but if not, and it's like PHP which uses PEM (via openssl), then it's fairly easy to convert (`$user_key_value` is the DER value base64 encoded):

https://github.com/craigfrancis/webauthn-tidy/blob/main/new/check.php?ts=4#L126

**Comment by greenpau** [comment]
@craigfrancis , once again, thank you for much! I will review and follow up with questions.

**Comment by greenpau** [comment]
@craigfrancis , Happy New Year! 🎉 

I am getting back to it! I use CBOR from [github.com/paroga/cbor-js](https://github.com/paroga/cbor-js).

https://github.com/craigfrancis/webauthn-tidy/blob/85b8f53648a628e0a8f1866d450960008b18a75c/new/js/polyfill.js#L472-L474

It looks like you are using slightly different CBOR implementation. In the implementation I use, there is no `length` to `publicKeyObject`. My guess is that you needed an offset and you included it in your CBOR implementation. Is that right?

**Comment by greenpau** [comment]
@craigfrancis, the CBOR code I am referring to starts [here](https://github.com/craigfrancis/webauthn-tidy/blob/85b8f53648a628e0a8f1866d450960008b18a75c/new/js/polyfill.js#L46) and returns length over [here](https://github.com/craigfrancis/webauthn-tidy/blob/85b8f53648a628e0a8f1866d450960008b18a75c/new/js/polyfill.js#L416-L419).

**Comment by craigfrancis** [comment]
I’ll check it over again when I get back to my computer, but if memory serves, I had to modify the CBOR decoder a bit to return the length, and stop itself when it’s at the end.

Again, I’m relying on my memory here, but I think WebAuthN uses a feature of CBOR, where it encodes the length in itself (as in, this field is X bits long, next, this field is Y bits long, etc, now we get to the end, and we have processed Z bits)... I’m sure it made someone think they were very clever, to save a bit of data, but personally I think it just adds complexity.

**Comment by greenpau** [comment]
Added this image for my notes.

![](https://www.w3.org/TR/webauthn-1/images/fido-attestation-structures.svg)

**Comment by craigfrancis** [comment]
Yep, that's the image I was using, from the [Attestation](https://www.w3.org/TR/webauthn-2/#sctn-attestation) section of the WebAuthN spec.

As to what I did, well, you've already identified the key points...

I'm also using [github.com/paroga/cbor-js](https://github.com/paroga/cbor-js/blob/master/cbor.js), which I hope I've credited them correctly on [line 41](https://github.com/craigfrancis/webauthn-tidy/blob/85b8f53648a628e0a8f1866d450960008b18a75c/new/js/polyfill.js?ts=4#L41).

First, and not really relevant to this issue, on [line 46](https://github.com/craigfrancis/webauthn-tidy/blob/85b8f53648a628e0a8f1866d450960008b18a75c/new/js/polyfill.js?ts=4#L46), I tweaked how the library is included (I'm putting it into a local `CBOR` variable, so I can do `CBOR.decode()`, without using a module, or the global scope).

And the key part, which you have already highlighted on lines [416-419](https://github.com/craigfrancis/webauthn-tidy/blob/85b8f53648a628e0a8f1866d450960008b18a75c/new/js/polyfill.js?ts=4#L416-L419), is where I've replaced the original code (commented out, just above), which complained about "Remaining bytes", and instead I'm returning the decoded data, and the offset it got to (and intentionally ignoring the remaining data).

Just to confirm the changes, I just did:

    diff -w cbor.js polyfill.js
    [...]
    > 
    >         var CBOR = (function(undefined) {
    > 
    389a412,533
    >                     // var ret = decodeItem();
    >                     // if (offset !== data.byteLength)
    >                     //     throw "Remaining bytes";
    >                     // return ret;
    >                     return {
    >                             'data': decodeItem(),
    >                             'length': offset,
    >                         };
    >                 }
    > 
    >                 return {'encode': encode, 'decode': decode};
    > 
    >             })();
    [...]

(this does ignore some of the wrapper code, but it's not important here).

**Comment by greenpau** [comment]
> And the key part, which you have already highlighted on lines 416-419, is where I've replaced the original code (commented out, just above), which complained about "Remaining bytes", and instead I'm returning the decoded data, and the offset it got to (and intentionally ignoring the remaining data).

@craigfrancis , thank you looking at it 👍 

Interesting observation ... not on topic, but still relevant.

```js
      if ('x5c' in attStmt) {
        // Handle non-ECDAA attestation type
        var certChain = [];
        // The elements of this array contain attestnCert and its
        // certificate chain, each encoded in X.509 format. The attestation
        // certificate attestnCert MUST be the first element in the array.
        response["x5c"] = []
        attStmt.x5c.forEach(item => response.x5c.push(uint8array_to_base64(item)));
      } else {
        if ('ecdaaKeyId' in attStmt) {
          // Handle ECDAA attestation type
        } else {
          throw "ecdaaKeyId not found in attestation statement";
        }
      }
```

Apparently, if I take the first element of `x5c` array, base64 decode it and run the following SSL command, I get a valid cert.

```
echo -n "x5c 1st element value" | base64 -d > key.crt
openssl x509 -in key.crt -inform der -text
```

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 902058766 (0x35c4530e)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = Yubico U2F Root CA Serial 457200631
        Validity
            Not Before: Aug  1 00:00:00 2014 GMT
            Not After : Sep  4 00:00:00 2050 GMT
        Subject: C = SE, O = Yubico AB, OU = Authenticator Attestation, CN = Yubico U2F EE Serial 902058766
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:66:ae:cd:ae:25:18:8e:4a:23:97:00:58:41:84:
                    7f:65:ad:f1:f0:8b:04:23:fa:85:63:4a:bb:a9:86:
                    2e:14:2d:f7:b9:f4:09:df:2e:4e:5e:9e:06:af:7a:
                    17:39:e1:51:d5:77:90:30:b5:8a:d7:71:b5:5f:6c:
                    75:62:7e:2b:07
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            1.3.6.1.4.1.41482.2:
                1.3.6.1.4.1.41482.1.7
            1.3.6.1.4.1.45724.2.1.1:
                ...
            1.3.6.1.4.1.45724.1.1.4:
                ....(yr.I..u=....*
            X509v3 Basic Constraints: critical
                CA:FALSE
```

**Comment by craigfrancis** [comment]
I think that's the certificate for the authentication device, when doing a full attestation check.

When calling `navigator.credentials.create(options)`, the `options['publicKey']['attestation']` will normally be set to 'none', to avoid the "Allow this site to see the make and model of your security key" permission check.

I doubt many sites will use this, unless you're going to be checking the full certificate chain, and checking that against your own list of hardware providers you trust (a bank might do this, but I doubt a typical website will care).

**Comment by greenpau** [comment]
> When calling navigator.credentials.create(options), the options['publicKey']['attestation'] will normally be set to 'none', to avoid the "Allow this site to see the make and model of your security key" permission check.

@craigfrancis , good to know! 👍 

> I doubt many sites will use this, unless you're going to be checking the full certificate chain, and checking that against your own list of hardware providers you trust (a bank might do this, but I doubt a typical website will care).

I think this could be handy.

**Comment by craigfrancis** [comment]
If you're a bank, and you're providing the devices to customers; or a company providing them to employees; you know the manufacturer, and that *might* be a useful feature.

But for most websites, who cares where the device came from?

This check also adds an extra step during the enrolment process (where some people, typically the ones who know more about this stuff, might wonder why you want to know).

It's also a step that might go wrong (in the future, more hardware manufacturers will hopefully exist, and it's possible that some might not get the attestation process quite right, as it's not used that often).

I also like how Apple suddenly started supporting this in Safari 14 via FaceID or TouchID, and I didn't have to add them to the list of my "approved" manufacturers (it just started working).

**Comment by greenpau** [comment]
just in case someone find it ...

The `sig` field in the attestation object:

```
  "attestationObject": {
    "attStmt": {
      "alg": -7,
      "sig": "MEQCIBRQMm1GlRgK+7UQXYcuc0IWEsM9nWejSi0cyaQQUvDyAiBHw9BgPdt9tC7w5Itr29xFpodZgm8DvXFJnLOoys6GZw==",
...
```

gets decoded as follows. Big thanks to @francislavoie for the pointer to [ASN.1 JavaScript decoder](https://lapo.it/asn1js/).

![image](https://user-images.githubusercontent.com/3826416/103675969-89a0eb00-4f4e-11eb-952a-f4a449699a05.png)


```
echo "MEQCIBRQMm1GlRgK+7UQXYcuc0IWEsM9nWejSi0cyaQQUvDyAiBHw9BgPdt9tC7w5Itr29xFpodZgm8DvXFJnLOoys6GZw==" | base64 -d > sig.bin
od -A x -t x1z -v sig.bin
```

The result follows.. The first 2 bytes (`30 44`) indicates it is a sequence (`30` is sequence, see also [SEQUENCE encoding
](https://letsencrypt.org/docs/a-warm-welcome-to-asn1-and-der/#sequence-encoding)) of 68 bytes in length (`44` hex is 68 decimal).

Then, there are 2 objects, each is 34 bytes in length. The first 2 bytes (`02 20`) indicates it is an integer (`02`) of 32 bytes length (`20` in hex, or 32 in decimal).

```
000000 30 44 02 20 14 50 32 6d 46 95 18 0a fb b5 10 5d  >0D. .P2mF......]<
000010 87 2e 73 42 16 12 c3 3d 9d 67 a3 4a 2d 1c c9 a4  >..sB...=.g.J-...<
000020 10 52 f0 f2 02 20 47 c3 d0 60 3d db 7d b4 2e f0  >.R... G..`=.}...<
000030 e4 8b 6b db dc 45 a6 87 59 82 6f 03 bd 71 49 9c  >..k..E..Y.o..qI.<
000040 b3 a8 ca ce 86 67                                >.....g<
000046
```

![image](https://user-images.githubusercontent.com/3826416/103678307-5f9cf800-4f51-11eb-9188-14be80755328.png)

**Comment by craigfrancis** [comment]
Oh, that's interesting... that's similar to the (erm, cheats way) I created the DER encoding of the public key:

https://github.com/craigfrancis/webauthn-tidy/blob/85b8f53648a628e0a8f1866d450960008b18a75c/new/js/polyfill.js?ts=4#L483

Where my prefix is used to say it's DER encoded, `ecPublicKey`, using `prime256v1`, followed by the key value, marked `ECC uncompressed`.

With your signature, with its two 32 byte integers, what are they? values `r` and `s`?

https://tools.ietf.org/html/rfc3279#page-21

https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm#Signature_generation_algorithm

It's as this point I struggle to follow the calculations, assume it's all correct, and store the base64 encoded value :-)

**Comment by greenpau** [comment]
> With your signature, with its two 32 byte integers, what are they? values r and s?

@craigfrancis , that's the question I am asking myself right this moment 😃 That's why it is fun to explore :-)

**Comment by greenpau** [comment]
Closing. Need to find time to get back to webauthn.
