### ISSUE TITLE
can I configure multiple ldap_backends?

### ISSUE THREAD

**Issue by SvenDowideit** [greenpau/caddy-auth-portal#83]
We have different LDAP servers, but I'd like to create this site allowing login for users from either.

I tried by having 2 ldap_backend's in the single backend section, but the caddyfile parser didn't like that
Then I tried using 2 separate routes, one for each, but that results in a run time error:

```
021/01/07 06:08:13.574	ERROR	admin.api	request error	{"error": "loading config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 2: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'auth_portal': provision http.handlers.auth_portal: authentication provider registration error, instance portal-16, error: found more than one primary instance of the plugin for default context: map[default:0xc00019e600], 2", "status_code": 400}

```

I don't know what the expected result it - is caddy-auth coded to permit only one ldap_backend, or is this a parse issue, or just me not trying the right config?

**Comment by greenpau** [comment]
@SvenDowideit , short answer is yes. Please post your config.

**Comment by greenpau** [comment]
@SvenDowideit , you dont need multiple routes. Just call them ldap_backend1 and ldap_backend2. The realm names should be different. I will provide more feedback once I see you Caddyfile.

**Comment by SvenDowideit** [comment]
bingo - I'd totally forgotten the caddyfile `1`, `2` thing :/

that gets me 2 almost working ldap_backends, with one interesting issue - both backends are using the second backend's configured username and password, which therefore means it fails to be able to use the first backend

(at least, that's what the `ERROR	http.handlers.auth_portal	LDAP connection binding failed` line shows)

digging deeper, the config json created from the caddyfile doesn't do this - both ldap_backends have their correct info, so I guess its happening somewhere deeper?

**Comment by greenpau** [comment]
> that gets me 2 almost working ldap_backends, with one interesting issue - both backends are using the second backend's configured username and password, which therefore means it fails to be able to use the first backend

@SvenDowideit , each backend is independent of each other. Each backend handled unique domain. If you want to have a fallback, then you have multiple servers, e.g. 

```
         servers {
            ldaps://ldaps1.contoso.com ignore_cert_errors
            ldaps://ldaps2.contoso.com ignore_cert_errors
          }
```

Also, each `realm` creates an entry in a dropdown on a login page.

> digging deeper, the config json created from the caddyfile doesn't do this - both ldap_backends have their correct info, so I guess its happening somewhere deeper?

@SvenDowideit , please post your Caddyfile. Do you have different `realm` for each `ldap_backendX` in your config?

https://github.com/greenpau/caddy-auth-portal/blob/f98ac1422c3b82f9b23c7f5d58a50206b8eb1ca5/assets/conf/ldap/Caddyfile#L17-L39

**Comment by greenpau** [comment]
> digging deeper, the config json created from the caddyfile doesn't do this - both ldap_backends have their correct info, so I guess its happening somewhere deeper?

@SvenDowideit , I switched the plugin to work with Caddyfile.

**Comment by SvenDowideit** [comment]
i'm refering to the json that caddy uses after the caddyfile has been parsed.

yes, the backends have different realms.

so, I've hopefully removed all the internal secrets from this - and for the latest test, I switched the order of ldap_backend1 and ldap_backend2 - which results in ldap_backend2 (now earlier in the list of backends in the caddy json that is used internally) failing to authenticate due to it using the user&pass from ldap_backend1

```
2021/01/07 22:49:26.162	ERROR	http.handlers.auth_portal	LDAP connection binding failed	{"server": "ldaps://10.10.10.10", "username": "CN=ldap2user", "error": "LDAP Result Code 49 \"Invalid Credentials\": 80090308: LdapErr: DSID-0C09044E, comment: AcceptSecurityContext error, data 52e, v2580\u0000"}

```

```
    route /auth* {
        auth_portal {
            path /auth
            backends {
                ldap_backend2 {
                    method ldap
                    realm first
                    servers {
                        ldaps://10.10.10.10 ignore_cert_errors
                    }
                    attributes {
                        name displayName
                        description title
                        fisrtname givenName
                        surname sn
                        username mail
                        member_of memberOf
                        email mail
                        dn dn
                    }
                    username "CN=user1"
                    password "nope"
                    search_base_dn "OU=ldapone,DC=asdf,DC=sdf,DC=fd"
                    search_filter "(&(|(sAMAccountName=%s)(mail=%s))(objectclass=user))"
                    groups {
                        "CN=something" ldap1
                    }
                }
                ldap_backend1 {
                    method ldap
                    realm ldap2
                    servers {
                        ldaps://192.168.12.12 ignore_cert_errors
                    }
                    attributes {
                        name displayName
                        description title
                        firstname givenName
                        surname sn
                        username mail
                        member_of memberOf
                        email mail
                        dn dn
                    }
                    username "CN=ldap2user"
                    password "someother"
                    search_base_dn "DC=ewew,DC=fddf,DC=asd"
                    search_filter "(&(|(sAMAccountName=%s)(mail=%s))(objectclass=user))"
                    groups {
                        "CN=elided" ldap2
                    }
                }
                local_backend {
                    method local
                    path /etc/users.json
                    realm local
                }
            }
            jwt {
                token_name access_token
                token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
            }
            ui {
                links {
                "My App" /myapp
                "User info" /auth/whoami
                }
            }
        }
    }
```

**Comment by greenpau** [comment]
@SvenDowideit , have you tried using fqdn and trusted_authority? Please see https://github.com/greenpau/caddy-auth-portal#ldap-authentication-backend

**Comment by SvenDowideit** [comment]
fqdn ? if you mean for the ldaps://server - yes, I am, that's elided for reasons.
and i don't see what trusted authority has to do with it - the wrong username is being sent to the first ldap_backend, and the error message above shows this.

**Comment by greenpau** [comment]
@SvenDowideit , just two clarify. You have two different domains. The authentication to one of the domains does not work. The other works fine. Correct?

**Comment by greenpau** [comment]
realm = domain

**Comment by SvenDowideit** [comment]
correct, and when I swap the order in the caddyfile (with no changes in text), the one that works switches to the one that is last in the file

**Comment by greenpau** [comment]
@SvenDowideit , it supposed to be that each backend definition is a separate instance.

**Comment by SvenDowideit** [comment]
I don't think I understand - are you saying that ldap_backend1 and ldap_backend2 in the one backends section isn't supported?

**Comment by greenpau** [comment]
@SvenDowideit , please see https://github.com/freescout-helpdesk/freescout/issues/869#issuecomment-728258632

perhaps you are having the same issue with how binding username is set up.

**Comment by greenpau** [comment]
> I don't think I understand - are you saying that ldap_backend1 and ldap_backend2 in the one backends section isn't supported?

@SvenDowideit in your config the two backends are separate. You are good there.

**Comment by SvenDowideit** [comment]
I think the error I put in the message above shows somewhat clearly that the first ldap_backend is being sent the username that is in the second ldap_backend's configuration

```
2021/01/07 22:49:26.162	ERROR	http.handlers.auth_portal	LDAP connection binding failed	{
"server": "ldaps://10.10.10.10", 
"username": "CN=ldap2user",
 "error": "LDAP Result Code 49 \"Invalid Credentials\": 80090308: LdapErr: DSID-0C09044E, comment: AcceptSecurityContext error, data 52e, v2580\u0000"
}
```

**Comment by SvenDowideit** [comment]
both the server and username values have been shortened and faked to avoid sending out internal info - they're both fully qualified.

**Comment by greenpau** [comment]
@SvenDowideit , please paste html for the dropdown on the login page

**Comment by greenpau** [comment]
@SvenDowideit , it does not make sense that a backend sends username associated with another backend.

**Comment by SvenDowideit** [comment]
<!doctype html>
<html lang="en">
  <head>
    <title>Sign In</title>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Authentication Portal">
    <meta name="author" content="Paul Greenberg github.com/greenpau">
    <link rel="shortcut icon" href="/auth/assets/images/favicon.png" type="image/png">
    <link rel="icon" href="/auth/assets/images/favicon.png" type="image/png">

    
    <link rel="stylesheet" href="/auth/assets/materialize-css/css/materialize.css" />
    <link rel="stylesheet" href="/auth/assets/google-webfonts/roboto.css" />
    <link rel="stylesheet" href="/auth/assets/line-awesome/line-awesome.css" />
    <link rel="stylesheet" href="/auth/assets/css/styles.css" />
    
  </head>
  <body class="app-body">
    <div class="container">
      <div class="row">
        <div class="col s12 m8 offset-m2 l6 offset-l3 xl4 offset-xl4 app-card-container">
          <div class="row app-header center">
            
            <div class="col s4">
              <img class="d-block mx-auto mb-2" src="/auth/assets/images/logo.svg" alt="Authentication Portal" width="72" height="72">
            </div>
            <div class="col s8">
              <h4>Sign In</h4>
            </div>
            
          </div>
          
          <form action="/auth" method="POST">
            <div class="row app-form">
              
              <div class="row app-input-row valign-wrapper">
                <div class="col s4">
                  <p class="app-input-text">Username</p>
                </div>
                <div class="col s8">
                  <div class="input-field app-input-field">
                    <input id="username" name="username" type="text" class="validate">
                  </div>
                </div>
              </div>
              
              
              <div class="row app-input-row valign-wrapper">
                <div class="col s4">
                  <p class="app-input-text">Password</p>
                </div>
                <div class="col s8">
                  <div class="input-field app-input-field">
                    <input id="password" name="password" type="password" class="validate">
                  </div>
                </div>
              </div>
              
              
              <div class="row app-input-row valign-wrapper">
                <div class="col s4">
                  <p class="app-input-text">Domain</p>
                </div>
                <div class="col s8">
                  <div class="input-field app-input-field">
                    <select id="realm" name="realm" class="browser-default">
                    
                      
                      <option value="first">FIRST</option>
                      
                    
                      
                      <option value="ldap2">LDAP2</option>
                      
                    
                      
                      <option value="local" selected>LOCAL</option>
                      
                    
                    </select>
                  </div>
	              </div>
	            </div>
              
            </div>
            <div class="row app-control valign-wrapper">
              <div class="col s6">
                
                
              </div>
              <div class="col s6 right-align">
                <button type="submit" name="submit" class="waves-effect waves-light btn app-btn">
                  <i class="las la-sign-in-alt left app-btn-icon"></i>
                  <span class="app-btn-text">Login</span>
                </button>
              </div>
            </div>
          </form>
          
          
        </div>
      </div>
    </div>
    
    <script src="/auth/assets/materialize-css/js/materialize.js"></script>
    
    
  </body>
</html>

**Comment by greenpau** [comment]
@SvenDowideit , I need to look at it a bit more. Perhaps, there is a bug.

**Comment by greenpau** [comment]
@SvenDowideit , what happens when you have only 1 LDAP backend at a time? Do they both work?

**Comment by SvenDowideit** [comment]
yes, each ldap_backend works in isolation, and when there are 2, the last one works, and the first one fails with an error that contains the username of the second.

**Comment by greenpau** [comment]
@SvenDowideit , I submitted https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.3.10. Please compile with that version and let me know the results.

**Comment by greenpau** [comment]
@SvenDowideit , if it works, then I will promote it to `latest`.

**Comment by greenpau** [comment]
@SvenDowideit , I confirmed, this was a bug.

**Comment by SvenDowideit** [comment]
@greenpau yes, confirmed! all 2 ldap backends and the local one work with v1.3.10

**Comment by greenpau** [comment]
> yes, confirmed! all 2 ldap backends and the local one work with v1.3.10

@SvenDowideit , thank you for reporting this! This is resolved now? Also, please promote the plugin via your blog and the social media platforms.

**Comment by SvenDowideit** [comment]
yup, fully resolved - thanks for your help!
