### ISSUE TITLE
Complete MFA workflow

### ISSUE THREAD

**Issue by clems71** [greenpau/caddy-auth-portal#86]
**Describe the issue**

Looked at the code base. Seems like everything is setup to store and set MFA tokens. Been able to test it on my setup and works fine.

Seems like the workflow is not complete yet though. I looked at login.go/ServeLogin. Would love to contribute back in implementing that, with some guidance from you @greenpau . I guess it is quite backend specific, because Google OIDC, or Okta for instance already has 2FA, so we should ask for the 2nd factor only on a per backend basis.

Let me know what you have in mind for the MFA workflow!

**Comment by greenpau** [comment]
@clems71 , I am working on the MFA in #14 . Please subscribe to it. Closing this one. Let’s keep all the discussion there.

You asked good question about the backends. short answer - i want MFA for local auth primarily.

**Comment by greenpau** [comment]
It is #13.
