### ISSUE TITLE
[Question] Local authentication mixed with user registration?

### ISSUE THREAD

**Issue by tgelite** [greenpau/caddy-auth-portal#87]
**Describe the issue**

These questions have to do with local user registration from caddy auth portal.

1) can I use the existing "user_db.json" as the starting file for the "registration_db.json" so that we keep the superuser and registered users for authentication in the same file?  **UPDATE: YES**

2) I'm assuming we would edit the javascript and template to allow for a "role" to be defined in the user registration screen as well.

3) has anyone worked out a "change password on first login" flow for the local auth...

**Update** - cleaned up the configuration file and included what we are attempting to use for registration, below
**Configuration**

```
{
        storage file_system {
                root /opt/caddy/storage
        }
        local_certs
        http_port 80
        https_port 443
}
https://example.com, https://10.252.252.21 {
        log {
                level INFO
                format console
                output file /var/log/caddy/caddy.log
        }
        route /auth* {
                auth_portal {
                        path /auth
                        backends {
                                local_backend {
                                        method local
                                        path /opt/caddy/assets/conf/local/auth/user_db.json
                                        realm local
                                }
                        }
                        jwt {
                                token_name access_token
                                token_secret AnExampleSecretString123
                        }
                        ui {
                                theme basic
                                links {
                                        "Elite Manager" /
                                        "Auth Portal Settings" /auth/settings
                                        "who am i check" /auth/whoami
                                        "Add MFA Authentication App" /auth/settings/mfa/add/app
                                }
                        }
                        registration {
                                dropbox /opt/caddy/assets/conf/local/auth/user_db.json
                                title "User Registration"
                        }
                }
        }
        route /gr/* {
                jwt {
                        enable claim headers
                }
                reverse_proxy http://localhost:3000
        }
        route /version* {
                respond * "2.0.0-a" 200
        }
        route /ui/* {
                jwt {
                        enable claim headers
                }
                reverse_proxy http://localhost:1880
        }
        route /* {
                jwt {
                        primary yes
                        trusted_tokens {
                                static_secret {
                                        token_name access_token
                                        token_secret AnExampleSecretString123
                                }
                        }
                        enable claim headers
                }
                reverse_proxy http://localhost:1081
        }
}

```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.2.2
http.authentication.hashes.scrypt v2.2.2
http.authentication.providers.http_basic v2.2.2
http.authentication.providers.jwt v1.2.1
http.handlers.auth_portal v1.3.3
http.handlers.authentication v2.2.2
```

**Expected behavior**

I would expect that the user_db.json and registration_db.json are interchangeable?  

**Additional context**

I'm just checking if anyone has extended the local user authentication in a "register users by a admin" and "users change password on first login" kind of use case.

**Comment by tgelite** [comment]
Also - updated to latest caddy & auth portal last night too: 

```
./linux_arm7_custom version
v2.3.0 h1:fnrqJLa3G5vfxcxmOH/+kJOcunPLhSBnjgIvjXV/QTA=

./caddy_linux_arm7_custom list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.3.0
http.authentication.hashes.scrypt v2.3.0
http.authentication.providers.http_basic v2.3.0
http.authentication.providers.jwt v1.2.3
http.handlers.auth_portal v1.3.10
http.handlers.authentication v2.3.0
```

**Comment by tgelite** [comment]
One thing I'm not clear on is what URI to use to hit the registration page in the auth portal?  /auth/reg or /auth/register does not work...

**Comment by tgelite** [comment]
Ok so the base URI is /auth/register.  It appeared to properly register my user over the common user_db.json.  It sets the user's role to "registration pending" in that file. 

I'm wondering if I can make the /auth/register path a protected path by JWT so that only our "admin" and "superuser" roles can access the registration page.

I'll continue to research the path to customizing this.

**Comment by greenpau** [comment]
@tgelite , my original idea was to have a way to promote registered user to user db. However, I did not get to it yet.

**Comment by greenpau** [comment]
The two files are not interchangeable. They just use the same format.

**Comment by tgelite** [comment]
Ah ok, that makes sense, I was wondering if there was some kind of "planned" portion of this to pull from registration and update user db. 

I'll take a look at that with our devs as a process we could build for user registration "approval".  We're working in node.js not go unfortunately but if we work something out we'll post to public github. 

I think we'll modify from admin register and use the user register with code so password management is user self maintained, and then set the role as we update user_db.json from the registration_db.json.

Thanks for the confirmation and additional detail.

**Comment by AlbertoGP** [comment]
> The two files are not interchangeable. They just use the same format.

Hi, just started using your plugins today, they are working very well so far.
What happens if an external program loads these files and does the transfer?
Would `caddy-auth-portal` pick up the updated file on the next authentication call, or would I need to reload `caddy`?
Would `caddy-auth-portal` overwrite `user_db.json` when restarting `caddy`?

I ask (instead of just trying it out) because maybe `caddy-auth-portal` assumes that nobody else is touching those files, and in that case I will go in a different direction.
