### ISSUE TITLE
[Question] Do we need to compile Caddy_auth_portal from source to introduce new templates?

### ISSUE THREAD

**Issue by tgelite** [greenpau/caddy-auth-portal#88]
**Describe the issue**

Reading through the templates, and attempting to introduce a new "set" of templates, it appears that they must be present at time of caddy compilation to be referenceable with the template definition?

At some point we will need to in earnest produce a unique set of templates that we invoke, and I'm checking if my working assumption is correct that we will need to create the set at time of compilation like so

```
assets/templates/custom/generic.template
assets/templates/custom/login.template
assets/templates/custom/portal.template
assets/templates/custom/register.template
assets/templates/custom/whoami.template
assets/templates/custom/settings.template
```

And then we could reference that set within the compiled caddy server with the configuration notation of:
localhost {
  route /auth* {
    auth_portal {
      ui {
        theme custom
      }

That approach would be used rather than having to configure the per template static mappings as shown in the "Theming" section of the docs?  - https://github.com/greenpau/caddy-auth-portal#theming

Or am I assuming too much as far as what is exposed for us to mess with and I should back away with a custom template set...

**Configuration**
N/A

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.2.2
http.authentication.hashes.scrypt v2.2.2
http.authentication.providers.http_basic v2.2.2
http.authentication.providers.jwt v1.2.1
http.handlers.auth_portal v1.3.3
http.handlers.authentication v2.2.2
eeuser@elite-pidev:/opt/caddy/assets/conf/loca
```

**Expected behavior**

Compiling with templates present in the proper path within assets will properly introduce the templates as a set to caddy auth portal's "theme" configuration assertion. 

**Additional context**

Wondering what folks have done with custom template sets...

**Comment by greenpau** [comment]
@tgelite , you are correct. You can reference your templates as described here: https://github.com/greenpau/caddy-auth-portal#theming

```
    auth_portal {
      ui {
        generic_template "/path/to/template"
        login_template "/path/to/template"
        portal_template "/path/to/template"
        register_template "/path/to/template"
        whoami_template "/path/to/template"
        settings_template "/path/to/template"
      }
```

Does this answer your question?

**Comment by tgelite** [comment]
That provides all the mappings, yes, thank you very much.

**Comment by tgelite** [comment]
Yes, thank you, the detail on the set of static mapping helps as well.  Thanks.

**Comment by starcoder204** [comment]
![image](https://user-images.githubusercontent.com/56172389/106081468-3d923200-6119-11eb-8183-3f8722607b60.png)

I think this describes we don't need to compile caddy_auth_portal from source to use different templates.
Am I wrong?

**Comment by greenpau** [comment]
@starcoder204 , no need to compile. Just reference templates on disk.

**Comment by starcoder204** [comment]
Yes. Thanks for your confirmation :) @greenpau
