### ISSUE TITLE
feature: increase cookie life time

### ISSUE THREAD

**Issue by jloh** [greenpau/caddy-auth-portal#90]
**Describe the issue**

At the moment the cookies that get specified by the portal only live for the users session and get deleted/expire after that. It'd be great to be able to control this or alternatively sync it up with the JWT token life time.

The cookie set the the portal currently has an Expires / Max-Age of "Session". I couldn't find where this comes in the code base so maybe its the default FF sets if the cookie doesn't have a Max-Age?

Apologies if this is in the docs somewhere, I can only find information on increasing the JWT token life time, not the cookie itself.

**Configuration**

Paste full `Caddyfile` below:

```
auth.example.com {
  tls {
    dns cloudflare {env.CLOUDFLARE_API_TOKEN}
  }
  route /auth* {
    auth_portal {
      path /auth
      backends {
        github_oauth2_backend {
          method oauth2
          realm github
          provider github
          client_id {$GITHUB_CLIENT_ID}
          client_secret {$GITHUB_CLIENT_SECRET}
          scopes user
          user github.com/jloh add role superuser
        }
      }
      ui {
        links {
          "Git Server" https://git.example.com
        }
      }
      jwt {
        token_name {$JWT_TOKEN_NAME}
        token_secret {$JWT_TOKEN_SECRET}
        token_lifetime 2592000
      }
      cookie_domain example.com
    }
  }
  route / {
    redir https://{hostport}/auth/oauth2/github 302
  }
}

git.example.com {
  route {
    jwt {
      primary yes
      trusted_tokens {
        static_secret {
          token_name {$JWT_TOKEN_NAME}
          token_secret {$JWT_TOKEN_SECRET}
        }
      }
      allow roles superuser
      auth_url https://auth.example.com/auth/oauth2/github
    }
    reverse_proxy 127.0.0.1:8080
  }
  encode zstd gzip
  tls {
    dns cloudflare {env.CLOUDFLARE_API_TOKEN}
  }
}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.3.0
http.authentication.hashes.scrypt v2.3.0
http.authentication.providers.http_basic v2.3.0
http.authentication.providers.jwt v1.2.3
http.handlers.auth_portal v1.3.10
http.handlers.authentication v2.3.0
```

**Expected behavior**

I guess extending the JWT token life time also extended the cookie life time.

**Additional context**

No context, but once again thanks for the plugin!

**Comment by greenpau** [comment]
@jloh , thank you for the issue! The thought process around it is not in docs. I will provide answer inline and provide context to other readers, if any. Perhaps, at some point, will bring it to docs.

> At the moment the cookies that get specified by the portal only live for the users session and get deleted/expire after that. It'd be great to be able to control this or alternatively sync it up with the JWT token life time.

This is correct. The cookie attributes are being set here.

https://github.com/greenpau/caddy-auth-portal/blob/a56fc4f223b28e543d7a4c99c7edf7cc423dce3b/pkg/cookies/cookie.go#L29-L41

This function is also being called from here. That is where the JWT token gets inserted into a cookie.

https://github.com/greenpau/caddy-auth-portal/blob/a56fc4f223b28e543d7a4c99c7edf7cc423dce3b/pkg/handlers/login.go#L109-L113

> The cookie set the the portal currently has an Expires / Max-Age of "Session". I couldn't find where this comes in the code base so maybe its the default FF sets if the cookie doesn't have a Max-Age?

The reason the expiration is `Session` is rooted in the following (see [Set-Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie))

* Max-Age=<number> Optional: Number of seconds until the cookie expires. A zero or negative number will expire the cookie immediately. If both Expires and Max-Age are set, Max-Age has precedence.
* Expires=<date> Optional: The maximum lifetime of the cookie as an HTTP-date timestamp. See Date for the required formatting.

If unspecified, the cookie becomes a **session cookie**. A session finishes when the client shuts down, and session cookies will be removed.

> Apologies if this is in the docs somewhere, I can only find information on increasing the JWT token life time, not the cookie itself.

These are great questions! Personally, it makes me looked critically at how the thing works right now 😃 👍 

Now, in terms of your feature request.

First, what you are asking will change the current behavior of the plugin and introduces a new configuration option related to cookies. Currently, the plugin has the `cookie_domain`  and `cookie_path` as Caddyfile configuration directives.

How would you call the new directive? What are the parameters to the directive?

Second, the introduction of the new directive would also require the change in how `GetAttributes()` works.

What would it be?

**Comment by jloh** [comment]
> First, what you are asking will change the current behaviour of the plugin and introduces a new configuration option related to cookies.
> How would you call the new directive? What are the parameters to the directive?

Maybe my understanding of how JWT age/lifetime works is wrong, but shouldn't Cookie lifetime be equal to JWT token lifetime? No point having the Cookie expire before the token, or the other way around. As such, shouldn't these match? It would mean there isn't a requirement to introduce a new config option, could just be based off the `token_lifetime` param with some docs updates.

Assuming this is wrong and a new value does need to be set, I would expect the new param to just be something like `cookie_maxage` since its the only one that makes sense (to me!) as `Expires` requires a timestamp which wouldn't work very well in a config file.

I would expect `cookie_maxage` to just be in seconds much like `token_lifetime`.

> Second, the introduction of the new directive would also require the change in how `GetAttributes()` works.

I'm in the process of learning Go right now, so this likely isn't right but I _think_ something like this?

```diff
diff --git a/caddyfile.go b/caddyfile.go
index 9a392ae..d3a0c33 100644
--- a/caddyfile.go
+++ b/caddyfile.go
@@ -392,6 +392,7 @@ func parseCaddyfileAuthPortal(h httpcaddyfile.Helper) ([]httpcaddyfile.ConfigVal
 					return nil, h.Errf("%s argument value conversion failed: %s", rootDirective, err)
 				}
 				portal.TokenProvider.TokenLifetime = lifetime
+				portal.Cookies.Lifetime = lifetime
 			case "jwt":
 				if portal.TokenProvider == nil {
 					portal.TokenProvider = jwtconfig.NewCommonTokenConfig()
diff --git a/pkg/cookies/cookie.go b/pkg/cookies/cookie.go
index 9a7dc91..2ca9021 100644
--- a/pkg/cookies/cookie.go
+++ b/pkg/cookies/cookie.go
@@ -15,14 +15,16 @@
 package cookies
 
 import (
+	"fmt"
 	"strings"
 )
 
 // Cookies represent a common set of configuration settings
 // applicable to the cookies issued by the plugin.
 type Cookies struct {
-	Domain string `json:"domain,omitempty"`
-	Path   string `json:"path,omitempty"`
+	Domain   string `json:"domain,omitempty"`
+	Path     string `json:"path,omitempty"`
+	Lifetime int    `json:"lifetime,omitempty"`
 }
 
 // GetAttributes returns cookie attributes.
@@ -36,6 +38,9 @@ func (c *Cookies) GetAttributes() string {
 	} else {
 		sb.WriteString(" Path=/;")
 	}
+	if c.Lifetime != 0 {
+		sb.WriteString("Max-Age=" + fmt.Sprint(c.Lifetime) + ";")
+	}
 	sb.WriteString(" Secure; HttpOnly;")
 	return sb.String()
 }
```

This works of the assumption that it can be coupled with the token lifetime, otherwise maybe something like this instead:

```diff
diff --git a/caddyfile.go b/caddyfile.go
index 9a392ae..f85f6d3 100644
--- a/caddyfile.go
+++ b/caddyfile.go
@@ -111,6 +111,12 @@ func parseCaddyfileAuthPortal(h httpcaddyfile.Helper) ([]httpcaddyfile.ConfigVal
 			case "cookie_path":
 				args := h.RemainingArgs()
 				portal.Cookies.Path = args[0]
+			case "cookie_lifetime":
+				lifetime, err := strconv.Atoi(h.Val()) // Not 100% certain this is right, unsure whether it should be args[0] instead of h.Val()
+				if err != nil {
+					return nil, h.Errf("%s argument value conversion failed: %s", rootDirective, err)
+				}
+				portal.Cookies.Lifetime = lifetime
 			case "path":
 				args := h.RemainingArgs()
 				portal.AuthURLPath = args[0]
diff --git a/pkg/cookies/cookie.go b/pkg/cookies/cookie.go
index 9a7dc91..2ca9021 100644
--- a/pkg/cookies/cookie.go
+++ b/pkg/cookies/cookie.go
@@ -15,14 +15,16 @@
 package cookies
 
 import (
+	"fmt"
 	"strings"
 )
 
 // Cookies represent a common set of configuration settings
 // applicable to the cookies issued by the plugin.
 type Cookies struct {
-	Domain string `json:"domain,omitempty"`
-	Path   string `json:"path,omitempty"`
+	Domain   string `json:"domain,omitempty"`
+	Path     string `json:"path,omitempty"`
+	Lifetime int    `json:"lifetime,omitempty"`
 }
 
 // GetAttributes returns cookie attributes.
@@ -36,6 +38,9 @@ func (c *Cookies) GetAttributes() string {
 	} else {
 		sb.WriteString(" Path=/;")
 	}
+	if c.Lifetime != 0 {
+		sb.WriteString("Max-Age=" + fmt.Sprint(c.Lifetime) + ";")
+	}
 	sb.WriteString(" Secure; HttpOnly;")
 	return sb.String()
 }
```

Thanks for your fast response!

**Comment by greenpau** [comment]
@jloh , what you said makes sense. We could create a directive for max age. Also, please see if you can find this useful https://github.com/greenpau/caddy-auth-portal/blob/main/CONTRIBUTING.md#development-environment.

This could be one way to get better at Go.

**Comment by greenpau** [comment]
@jloh , waiting for you PR 👍

**Comment by greenpau** [comment]
@jloh , I am working through this and here is what I am discovering during similar testing you did.

I will share my code in a new commit for you to see later. By the way, this was a good exercise for me because I created a few useful test functions! 👍 

This is all happens inside `TestCookieLifetime` unit test. 

Step 1: my authentication request, see traceable `02701cc2-4e7f-4efa-829e-d7d7ba652ac5`:

```json
{
  "level": "debug",
  "time": "2021-02-13T20:35:51.146-0500",
  "msg": "debugging request",
  "request_id": "02701cc2-4e7f-4efa-829e-d7d7ba652ac5",
  "direction": "incoming",
  "tag": "testing",
  "method": "POST",
  "proto": "HTTP/2.0",
  "host": "127.0.0.1:8443",
  "uri": "/auth",
  "remote_addr_port": "127.0.0.1:33708",
  "remote_addr": "127.0.0.1",
  "remote_port": 33708,
  "content_length": 50,
  "cookie_count": 0,
  "user_agent": "Go-http-client/2.0",
  "referer": "",
  "cookies": [],
  "query_params": {},
  "headers": {
    "Accept-Encoding": "gzip",
    "Content-Length": "50",
    "Content-Type": "application/x-www-form-urlencoded",
    "User-Agent": "Go-http-client/2.0"
  },
  "form": {
    "password": [
      "password123"
    ],
    "realm": [
      "local"
    ],
    "username": [
      "webadmin"
    ]
  }
}
```

The response with 302 redirect on success:

```json
{
  "level": "debug",
  "time": "2021-02-13T20:35:51.205-0500",
  "msg": "debugging response",
  "request_id": "02701cc2-4e7f-4efa-829e-d7d7ba652ac5",
  "direction": "outgoing",
  "tag": "testing",
  "status_code": 302,
  "response_size": 0,
  "buffer_size": 0
}
```

⚠️ Looks like I need to parse headers when using `caddy-trace`.

Additional log entry about the acquired identity:

```json
{
  "level": "debug",
  "ts": 1613266551.205507,
  "logger": "http.handlers.auth_portal",
  "msg": "Authentication succeeded",
  "request_id": "02701cc2-4e7f-4efa-829e-d7d7ba652ac5",
  "user": {
    "exp": 1613270151,
    "jti": "02701cc2-4e7f-4efa-829e-d7d7ba652ac5",
    "iss": "https://127.0.0.1:8443/auth",
    "sub": "webadmin",
    "email": "webadmin@localdomain.local",
    "roles": [
      "superadmin",
      "guest",
      "anonymous"
    ],
    "origin": "localhost"
  }
}
```

Step 2: Arrival at the portal. Here, I can see the value is being passed, but `Secure` and `HttpOnly` both set to false. That should not be. The Max-Age is not being passed.

```json
{
  "level": "debug",
  "time": "2021-02-13T20:35:51.205-0500",
  "msg": "debugging request",
  "request_id": "bb29d701-5243-430c-9476-859f7ed0c204",
  "direction": "incoming",
  "tag": "testing",
  "method": "GET",
  "proto": "HTTP/2.0",
  "host": "127.0.0.1:8443",
  "uri": "/auth/portal",
  "remote_addr_port": "127.0.0.1:33708",
  "remote_addr": "127.0.0.1",
  "remote_port": 33708,
  "content_length": 0,
  "cookie_count": 1,
  "user_agent": "Go-http-client/2.0",
  "referer": "https://127.0.0.1:8443/auth",
  "cookies": [
    {
      "Name": "access_token",
      "Value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTMyNzAxNTEsImp0aSI6IjAyNzAxY2MyLTRlN2YtNGVmYS04MjllLWQ3ZDdiYTY1MmFjNSIsImlhdCI6MTYxMzI2NjU1MSwiaXNzIjoiaHR0cHM6Ly8xMjcuMC4wLjE6ODQ0My9hdXRoIiwic3ViIjoid2ViYWRtaW4iLCJlbWFpbCI6IndlYmFkbWluQGxvY2FsZG9tYWluLmxvY2FsIiwicm9sZXMiOlsic3VwZXJhZG1pbiIsImd1ZXN0IiwiYW5vbnltb3VzIl0sIm9yaWdpbiI6ImxvY2FsaG9zdCJ9.mIFc31GHLdGObuAR76neBt_zMrrU_gUYL0X8rOQZ1ps",
      "Path": "",
      "Domain": "",
      "Expires": "0001-01-01T00:00:00Z",
      "RawExpires": "",
      "MaxAge": 0,
      "Secure": false,
      "HttpOnly": false,
      "SameSite": 0,
      "Raw": "",
      "Unparsed": null
    }
  ],
  "query_params": {},
  "headers": {
    "Accept-Encoding": "gzip",
    "Content-Type": "application/x-www-form-urlencoded",
    "Referer": "https://127.0.0.1:8443/auth",
    "User-Agent": "Go-http-client/2.0"
  },
  "form": {}
}
```

The response is 200. Clearly, it works:

```json
{
  "level": "debug",
  "time": "2021-02-13T20:35:51.206-0500",
  "msg": "debugging response",
  "request_id": "bb29d701-5243-430c-9476-859f7ed0c204",
  "direction": "outgoing",
  "tag": "testing",
  "status_code": 200,
  "response_size": 3001,
  "buffer_size": 3001
}
```

It could be something related to Caddy itself or its testing harness.

**Comment by greenpau** [comment]
After updateding to caddy-trace v1.1.5, I can see the cookies in the response.

Next place to check is the `caddytest.Tester` code, i.e. https://github.com/caddyserver/caddy/blob/master/caddytest/caddytest.go

```json
{
  "level": "debug",
  "time": "2021-02-13T22:23:47.768-0500",
  "msg": "debugging response",
  "request_id": "5fdafc0b-4b64-459f-951a-3d7ca44a459f",
  "direction": "outgoing",
  "tag": "testing",
  "status_code": 302,
  "response_size": 0,
  "buffer_size": 0,
  "response_headers": {
    "Authorization": [
      "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTMyNzY2MjcsImp0aSI6IjVmZGFmYzBiLTRiNjQtNDU5Zi05NTFhLTNkN2NhNDRhNDU5ZiIsImlhdCI6MTYxMzI3MzAyNywiaXNzIjoiaHR0cHM6Ly8xMjcuMC4wLjE6ODQ0My9hdXRoIiwic3ViIjoid2ViYWRtaW4iLCJlbWFpbCI6IndlYmFkbWluQGxvY2FsZG9tYWluLmxvY2FsIiwicm9sZXMiOlsic3VwZXJhZG1pbiIsImd1ZXN0IiwiYW5vbnltb3VzIl0sIm9yaWdpbiI6ImxvY2FsaG9zdCJ9.dvctftbJh4fWprWUpNGj_ZOjiI_viuSvtbOr73Y70lw"
    ],
    "Cache-Control": [
      "no-store"
    ],
    "Location": [
      "/auth/portal"
    ],
    "Pragma": [
      "no-cache"
    ],
    "Server": [
      "Caddy"
    ],
    "Set-Cookie": [
      "access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTMyNzY2MjcsImp0aSI6IjVmZGFmYzBiLTRiNjQtNDU5Zi05NTFhLTNkN2NhNDRhNDU5ZiIsImlhdCI6MTYxMzI3MzAyNywiaXNzIjoiaHR0cHM6Ly8xMjcuMC4wLjE6ODQ0My9hdXRoIiwic3ViIjoid2ViYWRtaW4iLCJlbWFpbCI6IndlYmFkbWluQGxvY2FsZG9tYWluLmxvY2FsIiwicm9sZXMiOlsic3VwZXJhZG1pbiIsImd1ZXN0IiwiYW5vbnltb3VzIl0sIm9yaWdpbiI6ImxvY2FsaG9zdCJ9.dvctftbJh4fWprWUpNGj_ZOjiI_viuSvtbOr73Y70lw; Path=/; Max-Age=900; Secure; HttpOnly;"
    ]
  }
}
```

For now I am just going to pass the cookie lifetime test and add "TODO" for later.

**Comment by greenpau** [comment]
@jloh , fyi, this is a common pattern for testing. It is worth knowing it.

https://github.com/greenpau/caddy-auth-portal/blob/7665ed8de6d6f3a2d934e96c56e088da62653c76/pkg/cookies/cookie_test.go#L15-L71
