### ISSUE TITLE
o365 MFA only Authentication (via Microsoft Authenticator) or OAuth2 validation for multiple caddy sites

### ISSUE THREAD

**Issue by bigbydesign** [greenpau/caddy-auth-portal#93]
I am wondering if it is possible to just setup your plugin to do just MFA. The setup constraint would be that I want to have users use the Microsoft o365 authenticator code for their account to allow the proxies requests to complete. I am intending on using this for exposing Intranet sites to the internet that don't support MFA. factor authentication.

 If this is not possible, can one authentication allow the JWT token for multiple sites? i.e. I authenticate to the portal and now I have access to 5 sites on caddy? Forgive me for my ignorance.

**Comment by greenpau** [comment]
> If this is not possible, can one authentication allow the JWT token for multiple sites? i.e. I authenticate to the portal and now I have access to 5 sites on caddy?

@bigbydesign , if all 5 sites are in the same domain, then you can authenticate only once and the token you get will be valid of all sites. The “cookie_domain” directive allows specifying a domain name.

> the Microsoft o365 authenticator code 

what is the authentication backend you will be using? Loca, ldap, oauth, etc...

**Comment by greenpau** [comment]
Stale issue. Closing.
