### ISSUE TITLE
Microsoft Azure user w/o email license

### ISSUE THREAD

**Issue by sixtus** [greenpau/caddy-auth-portal#95]
**Access for contractors**

As a caddy-auth-portal admin, I want to give access to remote contractors. The easiest way is to add them as a user, but don't give them any license.

However `scopes openid email profile` implies the user needs an email and my choices are limited to paying for the account or not getting access.

**Configuration**

`scopes openid email profile`

**Expected behavior**

I would like to have a configuration, where a missing email will default to the userid. This way, I can use AD to manage the contractors w/o paying a Microsoft tax

**Comment by greenpau** [comment]
@sixtus , what if you pass “role”/“group” as part of Azure Oauth attributes?

**Comment by sixtus** [comment]
@greenpau I am not sure I understand. Is that something to put in `scopes`?

**Comment by greenpau** [comment]
@sixtus , yes. Please look towards the end of Okta section. There is an example of how to add a “group” scope. It is probably very similar with Azure.

**Comment by sixtus** [comment]
```
  "scopes_supported": [
    "openid",
    "profile",
    "email",
    "offline_access"
  ]
```

**Comment by sixtus** [comment]
not sure what I should put in given these supported scopes. From what I understand, caddy-auth-profile has an implict dependency on email and profile. And I need to replace email with something in the profile

**Comment by greenpau** [comment]
@sixtus , when you send `scopes` with the value of  `openid email profile` to Azure, Azure will look up rules for `email` and `profile` scopes in its "database" and will return attributes associated with its scope. Say you sent a scope called "groups". Azure will not have it in its database, and therefore it will not return it. 

You need to configure that scope. This article explains how to do it: [Azure - How to: Provide optional claims to your app - Configuring groups optional claims](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#configuring-groups-optional-claims)

**Comment by greenpau** [comment]
@sixtus , another good article: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#configuring-groups-optional-claims

**Comment by greenpau** [comment]
@sixtus , please post your complete Caddyfile + screenshots from Azure configuration.

**Comment by greenpau** [comment]
No action.
