### ISSUE TITLE
feature: Adding Email Two Factor Code

### ISSUE THREAD

**Issue by bigbydesign** [greenpau/caddy-auth-portal#96]
Paul,

How difficult would it be to query AD or separate db. for the email address field and use it as an optional multifactor to validate identity?

User logins in with AD and then receives an email with the 6 digit key to provide second factor. This is for my users that don't have access to cell phone to validate identity via authenticator app.

Thanks,

Andy

**Comment by kirsch33** [comment]
I 2nd this request!

**Comment by greenpau** [comment]
I think there are facilities allowing to implement something like that. Recently I created a concept of a sandbox. The verification by email could be a thing there.

**Comment by greenpau** [comment]
@bigbydesign , @bigbydesign , please reopen in [github.com/greenpau/caddy-security](https://github.com/greenpau/caddy-security/issues/new/choose) if this is still relevant for you. Please consider sponsoring the work on the project! 👍
