### ISSUE TITLE
feature: Okta OIDC provider not working with Okta Workforce

### ISSUE THREAD

**Issue by kaeltis** [greenpau/caddy-auth-portal#98]
**Describe the issue**

The default `okta` provider currently only supports Okta Developer accounts or Okta Workforce accounts with an additional "API Access Management" license, since those come with support for multiple authentications servers and therefore have a a different OAuth API URL.

Okta Developer / Workforce **with** API Access Management:
```
Metadata: https://MYORG.okta.com/oauth2/AUTHSERVER/.well-known/openid-configuration?client_id=XXXXXXXXXXXXXXXXXXXXXX
Authorization Endpoint: https://MYORG.okta.com/oauth2/AUTHSERVER/v1/authorize
```

Workforce **without** API Access Management:
```
Metadata: https://MYORG.okta.com/.well-known/openid-configuration?client_id=XXXXXXXXXXXXXXXXXXXXXX
Authorization Endpoint: https://MYORG.okta.com/oauth2/v1/authorize
```

This is also explained at https://developer.okta.com/docs/reference/api/oidc/#composing-your-base-url and https://support.okta.com/help/s/article/400-error-on-authentication-to-Okta-using-OIDC

To currently use this with our Okta Workforce Tenant, we have to use the generic provider as shown in the config below.

It would be nice if there was a flag for the okta provider that could switch between those two URL formats.

**Configuration**

```
localhost {
  route /auth* {
    auth_portal {
      backends {
        generic_oauth2_backend {
          method oauth2
          realm generic
          provider generic
          base_auth_url https://MYORG.okta.com/
          metadata_url https://MYORG.okta.com/.well-known/openid-configuration?client_id=XXXXXXXXXXXXXXXXXXXXXX
          client_id XXXXXXXXXXXXXXXXXXXXXX
          client_secret YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
          scopes openid email profile
        }
      }
    }
  }

  route /sso/oauth2/generic* {
    jwt {
      auth_url /auth/oauth2/generic
    }
    respond * "generic oauth2 sso" 200
  }

}
```

**Version Information**

```
http.authentication.hashes.bcrypt v2.3.0
http.authentication.hashes.scrypt v2.3.0
http.authentication.providers.http_basic v2.3.0
http.authentication.providers.jwt v1.2.7
http.handlers.auth_portal v1.4.6
http.handlers.authentication v2.3.0
```

**Comment by greenpau** [comment]
@kaeltis , thank you for raising the issue! Will add it.

**Comment by greenpau** [comment]
@kaeltis, please reopen in [github.com/greenpau/caddy-security](https://github.com/greenpau/caddy-security/issues/new/choose) if this is still relevant for you. Please consider sponsoring the work on the project! 👍
