### ISSUE TITLE
After logging in I'm redirected to the "logged in" page instead of going directly to the target website

### ISSUE THREAD

**Issue by richardpowellus** [greenpau/caddy-auth-portal#99]
**Describe the issue**

I'm using caddu-auth-portal with Azure OAuth2 and everything's working great except for the fact that after I login successfully I get redirected to the "logged in" screen. At that point I can click the link for the website I was trying to access and I can access it just fine. So, for now, I'm not blocked but I do have to do a lot more clicking than I'd like to be doing.

Ideally I'd like it if I browse to https://radarr.myhome.net, OAuth2 authantication happens, I land on https://radarr.myhome.net.

**Configuration**

```
{
  https_port 443
}

(tls-dns-azure) {
  tls {
    dns azure {
      tenant_id [REDACTED]
      client_id [REDACTED]
      client_secret [REDACTED]
      subscription_id [REDACTED]
      resource_group_name [REDACTED]
    }
  }
}

(auth-trusted-tokens) {
  token_name access_token
  token_secret [REDACTED]
}

(auth) {
  jwt {
    primary yes
    auth_url https://auth.myhome.net/auth/oauth2/azure
    allow roles anonymous guest
    allow roles admin
    allow roles everyone Everyone
    trusted_tokens {
      static_secret {
        import auth-trusted-tokens
      }
    }
  }
}

(auth-admin-required) {
  jwt {
    primary no
    auth_url https://auth.myhome.net/auth/oauth2/azure
    allow roles admin
    trusted_tokens {
      static_secret {
        import auth-trusted-tokens
      }
    }
  }
}

auth.myhome.net {
  route /* {
    import auth
    redir https://auth.myhome.net/auth/oauth2/azure 302
  }

  route /auth* {
    auth_portal {
      path /auth
      cookie_domain myhome.net
      backends {
        azure_oauth2_backend {
          method oauth2
          realm azure
          provider azure
          client_id [REDACTED]
          client_secret [REDACTED]
          scopes openid email profile
          user [REDACTED] add role admin
        }
      }
      jwt {
        import auth-trusted-tokens
      }
      ui {
        links {
          "Radarr" https://radarr.myhome.net
        }
      }
    }
  }

  import tls-dns-azure

}

radarr.myhome.net {

  route {
    import auth-admin-required

    reverse_proxy radarr:7878
  }

  import tls-dns-azure

}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
/srv # caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.3.0
http.authentication.hashes.scrypt v2.3.0
http.authentication.providers.http_basic v2.3.0
http.authentication.providers.jwt v1.2.7
http.handlers.auth_portal v1.4.6
http.handlers.authentication v2.3.0
```

**Expected behavior**

If I browse to https://radarr.myhome.net I go through the OAuth2 authentication process and then I'm redirected back to https://radarr.myhome.net (which is a reverse proxy).

**Additional context**

**Comment by greenpau** [comment]
@richardpowellus , please post screenshots of your azure config. Want to see your callbacks.

**Comment by richardpowellus** [comment]
I only have the one callback set - I guess I'm supposed to have more?

<img width="1006" alt="screenshot" src="https://user-images.githubusercontent.com/1369873/111181044-cf8bb800-856a-11eb-8c85-f0f6a2c096a8.png">

**Comment by greenpau** [comment]
@richardpowellus , I am reading https://github.com/greenpau/caddy-auth-portal#microsoft and it has only 1 callback. Your screenshot matches.


One thing I noticed here:

```
auth.myhome.net {
  route /* {
    import auth
    redir https://auth.myhome.net/auth/oauth2/azure 302
  }

  route /auth* {
```

I think the default tour should come last. Please change the order, retry, and report back.

**Comment by richardpowellus** [comment]
Wow, that was it. So simple. Thanks for the help!

**Comment by greenpau** [comment]
@richardpowellus , please promote the plugin on social media platforms you use and :star:  it :-)
